### PR TITLE
Fix Organization chat channel Membership management 

### LINKED ISSUE #9249: Can't invite or remove user in the connect page.
**Describe the bug**
When I want to invite someone or delete the member from the group chat in https://dev.to/connect page, It will show an error  "User not authorized"

**To Reproduce**

**Screenshots**

image

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Google Chrome 
- Version:  83.0.4103.116 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by narender2031**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
- Added missing params in fastly params
- fix: Now org channel can send an invitation 
- fix: now org can remove user 
- fix: now org channel can update role 

## Related Tickets & Documents
close #9249
## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by narender2031** [comment]
@fdoxyz can you please restart the build.

**Comment by fdoxyz** [comment]
@narender2031 done. I'll take a closer look at the changes soon

**Comment by fdoxyz** [comment]
Sorry for taking a bit to get to this @narender2031, my comments regarding what is being updated in this PR:

> Added missing params in fastly params

I don't see this as necessary at the moment. The current features from the new membership management component aren't broken, is there a need to change the parameters here and adding them to `config/fastly/snippets/safe_params_list.vcl`? What process is this fix solving or how can I reproduce it?

> fix: Now org channel can send an invitation
> fix: now org can remove user
> fix: now org channel can update role

I think this relates directly with Organization management: When a new user is added/removed from an Organization, it should be added/removed to the Connect channel automatically. Currently only adding works, when a user is removed from an Organization it's not removed from the Organization chat channel. In the end it comes down to having no need to invite users.

The current problem I see is that Organization chat channel mods can see all the controls from the component including the invite link & remove user, but they don't work because of the policy.

My suggestion: Keep the logic that adds `is_org_channel` but instead use it to hide the "remove" button and also to hide the invitation link URL for Organization chat channels. This way the users won't click on a button that doesn't work, because the only way to join an Organization is by joining the Organization. This will give us a bit extra security that no one is added to the Organization private chat.

@benhalpern any thoughts on this suggestion? Do you see this flow differently?

**Comment by narender2031** [comment]
@benhalpern & @fdoxyz any updates on this PR?

**Comment by narender2031** [comment]
@fdoxyz  Agree with your point. we don't need to add params in Fastly. It works fine.

**Comment by narender2031** [comment]
@fdoxyz or @rhymes Please restart the build

**Comment by msarit** [comment]
Hey @narender2031, @benhalpern & @fdoxyz! 👋🏾 
Would you please take a look at this PR, and conclude on next steps? Looks like there were some unanswered questions from July last year. Thanks!

**Comment by fdoxyz** [comment]
Thanks for the bump @msarit!

I want to cc @forem/prod-eng-planning-team as they might be able to help with their input on this too. I feel a bit out of the loop on the Connect part of the codebase to know if we still want to pursue this. If yes, then it would be good to hear from them on how to proceed based on the conversation above.

**Comment by mstruve** [comment]
This seems more like a fix than a feature so I would be in favor of moving forward with it if @narender2031 can get the conflicts resolved and the branch up to date with master.

**Comment by narender2031** [comment]
> This seems more like a fix than a feature so I would be in favor of moving forward with it if @narender2031 can get the conflicts resolved and the branch up to date with master.

This is fix. Sure. I will fix the conflict and up the branch @mstruve

**Comment by narender2031** [comment]
@mstruve I don't have access to this branch. We can do one thing I will fix this issue in the new PR.

**Comment by citizen428** [comment]
@narender2031 Thanks! I'll close this PR then and wait for you to open a new one. 😃

**Pull request closed without merging**
