### PR TITLE
Fix Unable to Preview a Reply for a Comment Before Publishing it

### LINKED ISSUE #20389: Unable to Preview a Reply for a Comment Before Publishing it
**Describe the bug**

I can't preview a comment that I wrote before publishing it. There is nothing happen when I click the button.

**To Reproduce**

1. Go to a post.
2. Go to a comment and click reply.
3. Write a reply.
4. Click "preview" button.
5. Nothing happens.

**Expected behavior**

**Screenshots**

preview not working

**Desktop (please complete the following information):**

- OS, version: Windows 11
- Browser, version: Chrome, Version 119.0.6045.160 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

### PR DESCRIPTION
**Pull request by joaoGabriel55**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

I can't preview a comment that I wrote before publishing it. There is nothing happen when I click the button.

## Related Tickets & Documents

- Related Issue #20389
- Closes #20389

## QA Instructions, Screenshots, Recordings

1. Go to a post.
2. Go to a comment and click reply.
3. Write a reply.
4. Click "preview" button.

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [axe DevTools](https://www.deque.com/axe/) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

_For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by joaoGabriel55** [comment]
I do not know if this was the better approach because we lost a (simple) test

**Review by maestromac — CHANGES_REQUESTED** [review]
Thanks for this PR. I think what you got here is too drastic of a change. The problem is that when we migrated legacy JS (JS within assets) of to bundler JS (app/javascripts), we  lost the implied global function. What I'm suggesting as a solution instead is to add 

```
  window.handleCommentPreview = handleCommentPreview;
```

onto line 67 of `app/assets/javascripts/initializers/initializeCommentsPage.js.erb`
That will resolve this issue with mininal change. what do you think?

**Comment by ccoVeille** [comment]
> Thanks for this PR. I think what you got here is too drastic of a change. The problem is that when we migrated legacy JS (JS within assets) off to bundler JS (app/java scripts), we lost the implied global function assignment. What I'm suggesting as a solution instead is to add 
> 
> ```
>   window.handleCommentPreview = handleCommentPreview;
> ```
> 
> onto line 67 of `app/assets/javascripts/initializers/initializeCommentsPage.js.erb`
> That will resolve this issue with mininal change. what do you think?

I would say you @maestromac should open a PR with the simple change you request, mention this PR and see how things evolve. Asking someone who wrote things 6 months ago to change everything to only keep 1 line of code that is not his one sounds like strange to me.

Because then, if it doesn't work, reviewer may come after him to request changes, while it would be consequence of following your guidance.

My 2 cents, @joaoGabriel55 could do whatever he wants of course

**Comment by ccoVeille** [comment]
And yes, I would love this painful bug to be fixed!

**Pull request closed without merging**
