### PR TITLE
Update feed filter language & component (RFC#236)

### PR DESCRIPTION
**Pull request by aitchiss**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This PR addresses RFC: https://github.com/forem/rfcs/pull/236 (Update feed filter language & component).

The main strands are:

### 1. Feed filter option terminology has changed

The functionality in terms of how the filters work hasn't changed at all, but the words we apply to each have:

Feed -> Trending
Week -> This Week
Month -> This Month
Year -> This Year
Infinity -> All Time

The heading of the page now also changes when you select a filter e.g. instead of "Posts" you should see "Trending" by default.

### 2. Dropdown for feed filtering on larger screens

Where we previously showed the "navigation tabs" component, we now show a dropdown of the feed filter options. I've kept the breakpoints for this in line with the current implementation, with the result being that this dropdown is shown on all screens apart from portrait orientation mobile phones.

https://user-images.githubusercontent.com/20773163/129867217-385cb61e-f9da-416e-a67e-10a66290ee65.mp4

### 3. Modal drawer for feed filtering on smallest screens

As above, this should only be visible on portrait orientation mobile phone screen size. In this viewport, when you click the feed filter options button you should see a modal drawer slide in from the bottom with the navigation options.

https://user-images.githubusercontent.com/20773163/129867235-76bc5737-b2f3-4c3a-9e76-fdedd796e38d.mp4

### 4. Change to time filter / route names

The URLs and filters used to decide which articles to show has changed to match the new terminology

`/` -> No change
`/latest` -> `/top/most-recent`
`/week` -> `/top/this-week`
`/month` -> `top/this-month`
`/year` -> `/top/this-year`
`/infinity` -> `/top/all-time`

Redirects have been created to redirect the old routes to the new ones.

## Related Tickets & Documents

https://github.com/forem/rfcs/pull/236

## QA Instructions, Screenshots, Recordings

When testing this PR, we need to bear in mind:
- This applies to the home feed, but also the tag index (e.g. `/t/beginners`)
- The logged in and logged out feed are rendered differently, so we need to test both 🙂 
- We should test on real mobile devices to make sure we capture any UX nuance of the new drawer component

**We'll need to test:**
- Navigating between different feed filter options
- Navigating backwards and forwards from articles/other pages, to make sure the dropdowns/modal drawers continue to work as expected
- Viewing each version of the feed (filtered/unfiltered, logged in/logged out, home feed/tag index) to make sure we're getting the same results as before
- Checking that articles being paged in have the correct search params for each filter. We can check this in the devtools network tab, inspecting the request's "sort_by" and "published_at" parameters
- Visting the old URL routes and checking the browser shows them being redirected to the new ones

### UI accessibility concerns?

Most of the accessibility concerns have been addressed and tested as part of the previous PR introducing the new MobileDrawer component, but things to keep an eye on are:

- If you see the appropriate checkmark next to your currently selected navigation link, this means `aria-current="page"` is successfully set. If you don't see a checkmark next to the link for your current page, something's gone wrong!
- The dropdown on larger screens should conform to the [usual dropdown pattern documented in storybook](https://storybook.forem.com/?path=/story/components-dropdowns--default)
- The mobile navigation drawer uses the new `MobileDrawer` under the hood, and expected interaction pattern in terms of focus management is the same as with a "normal" Modal. [Details again in storybook](https://storybook.forem.com/?path=/story/components-mobiledrawer--default)

## Added/updated tests?

- [X] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://admin.forem.com/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [X] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by ludwiczakpawel** [comment]
First of all, I think @aitchiss did a tremendous and amazing job with implementing the requested changes. 

And I know I'm late to the party because I was gone so please treat my feedback very loosely. Also, it should be feedback to RFC and not PR but since RFC has been already merged&approved :)... Anyway, I think it's important to rise some concerns now even if it's almost done...

1. Discoverability – if we hide tabs in dropdown (for desktop) it'll be obviously cleaner view because we basically remove UI, but I'm afraid ppl will struggle using it. And I'm curious if there’s anything in particular we want to achieve with this change.
  - I believe it might be a result of changing names for filtering labels - they are now longer so we kinda need to collapse everything in the dropdown because otherwise it won't fit.. I'm not a copy expert here so I trust good judgement with picking label, but I'm not sure if it's worth it and if original ones really were confusing...
2. As long as I love the proposed UI for mobile breakpoint (that sliding drawer) it feels unnecessary for web browser. That custom drawer component could be really awesome for native apps, but doing any kind of custom modals/drawers/popups on mobile is always tricky and will almost always bite our butts at some point (due to weird mobile browsers behavior with fixed elements and scrollable elements but also with how browsers calculate viewports height. In other words - this will almost always cause some bugs and troubles.
3. Changing routes seems like unnecessary step here as well. I also suspect there’s a mistake in “most recent” route as these basically display posts in chronological order yet the route is `/top/most-recent` - **top** indicating it’s some sort of “relevance” order.

I think 1. & 2. could be solved with either horizontally scrollable navigation (see mobile web for google.com results) OR a combination of what we have today with a simple dropdown (like on desktop):
image

**Comment by aitchiss** [comment]
> I think 1. & 2. could be solved with either horizontally scrollable navigation (see mobile web for google.com results) OR a combination of what we have today with a simple dropdown (like on desktop)

I like both options, but I think option 1 has the added benefit of it always being really easy to see which time filter is selected. Option 2 makes sense to me too, as the Trending/Most Recent gives a clue to what the overflow menu contains, but if I've selected "This Week", once the dropdown is closed I don't have any UI visible to remind me that that's the filter I'm currently on.

I agree about the route name changes too, apart from we would have to rename the `/infinity` route I think as the correlation between "All Time" and "Infinity" isn't as obvious as e.g. "Most Recent" to "Latest"

I'm easy about whether we use the drawer navigation or not. Definitely true that we'd be adding another component to maintain that could be a source of bugs. I do have some vague UX concerns with the modal drawer, in that you click a button at the very top of the page, and the content you were looking for appears as far from that button as possible 😅

**Comment by citizen428** [comment]
@aitchiss @ludwiczakpawel Did we decide on how to move forward with this? Do we still need this PR or should we close it?

**Comment by aitchiss** [comment]
I think we are going in a different direction with the home feed, so I'll close this. @ludwiczakpawel - am I right in thinking we also don't want the mobile modal drawer component ([documented here in storybook](https://storybook.forem.com/?path=/story/components-mobiledrawer--default), including [navigation version](https://storybook.forem.com/?path=/story/app-components-mobiledrawernavigation--default))? If so, I'll get a PR up to remove the code 🧹

**Comment by ludwiczakpawel** [comment]
Yeap, lets close it.

@aitchiss is there a way to keep the drawer component "just in case"? even though we don't use it today I _think_ there's a potential in it, just don't exactly know where yet :)

**Comment by aitchiss** [comment]
Yup it's already there in storybook, so we can just leave the code for now and leave the sweeping up til we've had more time to think about it 👍

**Pull request closed without merging**
