### PR TITLE
Update webpack-dev-server to 4.0.0

### PR DESCRIPTION
**Pull request by citizen428**
## What type of PR is this? (check all applicable)

- [X] Tools update

## Description

In #14625 Dependabot tried to update webpack-dev-server to 4.0.0. However, this is a breaking update that required several changes so I opted for a separate PR instead. This PR:

* Updates `webpack-dev-server` to 4.0.0
* Updates `webpack-cli` to the new minimum version (4.7.0)
* Updates the `webpacker` gem to 6.0.0.rc.5 (this is the version that was released 6 days ago and adds support for webpack-dev-server 4.0.0`
* Made a minor change to `config/webpack/development.js`. Without this I got the following error:
    ```
    Cannot use [chunkhash] or [contenthash] for chunk in 'js/[name]-[contenthash].js' (use [hash] instead)
    ```
* Switch from `javascript_packs_with_chunks_tag` to `javascript_pack_tag` (the former was deprecated in rc1)

## Related Tickets & Documents

 #14625 

## QA Instructions, Screenshots, Recordings

Please test that the webpack dev server works as expected in local development.

### UI accessibility concerns?

None

## Added/updated tests?

- [X] No, and this is why: tests should not be affected by this

## [Forem core team only] How will this change be communicated?

- [X] I will share this change internally with the appropriate teams

### CODE REVIEW

**Comment by citizen428** [comment]
It seems there are some changes necessary due to the webpacker update, I'll look into these a bit later.

**Comment by citizen428** [comment]
It seems like Webpacker 6 requires Webpack 5, which is also the recommended version for webpack-dev-server 4.0.0. Is it worth going ahead with this @nickytonline?

**Comment by nickytonline** [comment]
> Apparently, Webpacker 6 requires adding loaders explicitly, maybe you can help with this @nickytonline (not sure if we need any/which ones we need).
> 
> It probably also makes sense to run `rails webpacker:install` and update all the config files, though again I may need help from someone who works more on the frontend.

In the main app we do not use any webpack loaders. We use some in the wepack configuration for Storybook.

**Comment by nickytonline** [comment]
> It seems like Webpacker 6 requires Webpack 5, which is also the recommended version for webpack-dev-server 4.0.0. Is it worth going ahead with this @nickytonline?

webpack 5 offers speed improvements via better caching and some other goodies. See https://webpack.js.org/blog/2020-10-10-webpack-5-release/#general-direction. It's worth upgrading most likely. I can take a peek at this.

**Comment by nickytonline** [comment]
Just investigating local development failures. Running `bin/webpack` though appears to work fine.

image

**Comment by nickytonline** [comment]
I stand corrected. We use one loader for ERB integration.

https://github.com/forem/forem/blob/0d8e8608d07f99305679cc8aa7c06ebacf9d83e9/config/webpack/environment.js#L39

**Comment by citizen428** [comment]
@nickytonline We can keep this branch open and plug away on the issues, similar to what we did in another branch for the Ruby 3 upgrade.

**Comment by citizen428** [comment]
@nickytonline The upgrade guide can be found here: https://github.com/rails/webpacker/blob/master/docs/v6_upgrade.md

I performed many of the steps already. What's still missing:

* Adding any loaders, etc we might need.
* Adding back custom config from `config/webpack_old` to `config/webpack`
* Adding back custom config from `config/webpacker_old.yml` to `config/webpacker.yml`

It would be great if you could help with the steps outlined above (and everything else you notice that I may have missed from the upgrade guide).

**Comment by citizen428** [comment]
@nickytonline I made some more changes here, e.g. installing missing plugins, etc. I also started moving over the config. I think we should leave `config/webpack/base.js` alone and use the custom config file that we merge into the base config as described in the docs. [This SO answer](https://stackoverflow.com/a/66932573/220147) has a good example but I think I'll leave the actual changing of this file to you, I'm not that familiar with webpack internals.

**Comment by nickytonline** [comment]
Just FYI @citizen428, none of the Storybook files should be touched in this PR. It uses webpack as well, but it's completely separate from webpacker.

**Comment by citizen428** [comment]
@nickytonline Should we close this and start over? There are a ton of merge conflicts now.

**Comment by nickytonline** [comment]
Yeah, let's close this for now. I haven't had anytime to look at this as well, as there are other priorities atm. Is this blocking anything like a Rails upgrade because if a webpacker 5 or is this just a nice to have for now?

**Comment by citizen428** [comment]
@nickytonline No, it's fine. I think we should pin the version though so we don't get any more Dependabot PRs for this.

**Pull request closed without merging**
