### PR TITLE
Bump ruby version 3.0.2 -> 3.0.3

### PR DESCRIPTION
**Pull request by dscottS3**
This version bump includes security fixes for ReDos, Buffer Overrun, and
cookie spoofing. More info here:
https://www.ruby-lang.org/en/news/2021/11/24/ruby-3-0-3-released/

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description
Small ruby version bump from `3.0.2` to `3.0.3`. Although it's a small bump, it does address some security concerns. More on that here: https://www.ruby-lang.org/en/news/2021/11/24/ruby-3-0-3-released/

## Related Tickets & Documents
n/a

## QA Instructions, Screenshots, Recordings
Testing should include allowing the test suite to run and pass.

### UI accessibility concerns?
n/a

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: Tests are not needed for ruby version bump.
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [x] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

### CODE REVIEW

**Comment by citizen428** [comment]
Ah, I had started a branch myself locally before seeing this. There are several more places we'll need to update:

* [ ] `Containerfile`
* [ ] `.travis.yml`
* [ ] `.gitpod.dockerfile`

Additionally, we need to wait for 3.0.3 to be available in Fedora and have a new image made.

**Comment by dscottS3** [comment]
ah, thanks @citizen428 -- great minds think alike (or something like that) 

I updated those files. I'm speculating the path in the `Containerfile` for `quay.io` will remain relatively the same. 

Totally makes sense to wait and I wasn't trying to jump the gun. But I did want to get the proverbial "ball rolling".

**Comment by citizen428** [comment]
@dscottS3 Thanks to @andygeorge we have a 3.0.3 testing container now `quay.io/forem/ruby:3.0.3-testing`. Can you update this PR so we can see if everything works as expected?

**Comment by dscottS3** [comment]
@citizen428 looks like the build failed :/
https://buildkite.com/forem/build-containers/builds/11519#2aaa8245-3e33-4455-8c66-42e50fd9bcc0

**Comment by citizen428** [comment]
Hmm, the container build fails when trying to build the `field_test` gem, we need to look into that.

**Comment by maestromac** [comment]
:wave: @dscottS3 , friendly OSS ping. Is this still blocked by fedora container?

**Pull request closed without merging**
