### PR TITLE
Crayons Toggle Update

### PR DESCRIPTION
**Pull request by ludwiczakpawel**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Optimization

## Description

This is a followup for our **just** merged [Toggle component](https://storybook.forem.com/?path=/story/components-form-elements-toggles--default). It's inspired by the [suggestion of one of our community members](https://dev.to/afif/comment/1nd2i) that we can technically create toggle like this without any extra markup. Which I think is a great simplification for our devs.

## Related Tickets & Documents

- https://dev.to/afif/comment/1nd2i

## QA Instructions, Screenshots, Recordings

1. Spin up `yarn storybook`
2. Go to our Toggle component `/?path=/story/components-form-elements-toggles--default` and if it looks ok then it's ok to merge :D

### CODE REVIEW

**Review by aitchiss — COMMENTED** [review]
This all looks good, but I noticed in Safari there's almost like a weird bouncing effect when you switch the button 🤔 

https://user-images.githubusercontent.com/20773163/162776465-ab7c9efd-d855-409a-9cbb-1a94d6ed6b01.mp4

Any clues?

**Comment by ludwiczakpawel** [comment]
@aitchiss interesting. i'll take a look.

**Comment by jeremyf** [comment]
Looks good to this guy…I mean, I prefer plain text so perhaps I'm not the best.  But the story book works

**Review by jeremyf — APPROVED** [review]

**Review by aitchiss — APPROVED** [review]
So I re-ran this to grab you a screenshot of the Safari issue, and I can't reproduce that weird bouncing issue anymore 🙃 I have no idea what was causing that before but seems like it was a local issue... so yay!

**Comment by jeremyf** [comment]
I believe this created an issue now identified in #17386

**Pull request merged**
