### PR TITLE
HTML error fix - better urlencode - share links

### PR DESCRIPTION
**Pull request by jmau111**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

The share links are partly urlencoded, but some parts remain in raw format, which does not pass the HTML validator

## Related Tickets & Documents

https://github.com/forem/forem/issues/13289

### CODE REVIEW

**Review by citizen428 — APPROVED** [review]

**Review by rhymes — APPROVED** [review]
Thank you @jmau111!

**Comment by jmau111** [comment]
@rhymes @citizen428 hello, do you think this PR can be merged?

**Comment by rhymes** [comment]
@jmau111 I merged main in, I'll keep an eye on the build

**Comment by jmau111** [comment]
@rhymes thanks a lot. It's ok from the validator's perspective, 3 or 5 HTML errors have been removed.

**Pull request merged**
