### PR TITLE
Fix non channel details visible

### LINKED ISSUE #9234: Non-chat channel users should not see chat channel details
**Describe the bug**

When a connect channel invitation did not get emailed to a member (#9233), I asked them to go to dev.to/connect to see if they could see their invite there. They could, but they could also see the details of the group -- such as their pending status.

**To Reproduce**
If a user has not accepted an invite yet, the chat channel details (such as who is in that channel) should stay hidden from them.

**Screenshots**

This is a screenshot from Gracie's experience.

### PR DESCRIPTION
**Pull request by narender2031**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Non-chat channel users should not see chat channel details. Pending memberships should only visible to chat-channel MOD user.

## Related Tickets & Documents
close #9234

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by fdoxyz** [comment]
Thank you for quickly sending in the PR @narender2031! I don't think this solves the problem entirely though. This is how I tested this:

1. Create channel "Test" with user A & user B
1. Accept the invitation as user A
1. Copy the channel URL
1. Log in as user B
1. Before accepting the invitation, load the channel URL and the member list is visible to user B

Maybe a solution for this could be check to see if the user is a member of the channel before displaying the sidecar entirely

**Comment by narender2031** [comment]
> Maybe a solution for this could be check to see if the user is a member of the channel before displaying the sidecar entirely

- As I asked @jessleenyc, I think she asked to hide pending requests. 

@fdoxyz I think it could be the best non-chat channel user can see channel name at least. What do you think?

**Comment by jessleenyc** [comment]
Hey, there might have been some miscommunication. I agree with @fdoxyz, I don't think the sidecar should be display any chat channel information if the user is not a member.

**Comment by narender2031** [comment]
@jessleenyc Do we need to show any message or empty sidebar should be fine?

**Comment by jessleenyc** [comment]
If they've already been invited to the workshop, I think giving them the option to accept the invitation there probably makes sense.

**Comment by narender2031** [comment]
> If they've already been invited to the workshop, I think giving them the option to accept the invitation there probably makes sense.

@jessleenyc 
Yes. Sounds perfect.
or In this case, If the user is not invited. it will show empty?

**Comment by narender2031** [comment]
@jessleenyc & @fdoxyz  when non-active membership users try to open the chat channel by using URL, it will redirect them to /connect. Now non-active users cannot saw the channel details and member list.  

>If they've already been invited to the workshop, I think giving them the option to accept the invitation there probably makes sense.

I didn't implement this because. We already created the PR to separate the request center.

**Comment by narender2031** [comment]
@rhymes can please restart this build also.

**Pull request merged**
