### PR TITLE
Automatically mark tag supported when adding mod

### LINKED ISSUE #11140: Adding a Mod to a Tag Should Automatically Mark the Tag as Supported
**Is your feature request related to a problem? Please describe.**

Yes, it's inefficient and opens the door for manual error to need to mark a tag as supported to a tag that is currently being modded.

**Describe the solution you'd like**

When you add a tag mod to a tag, it should automatically mark the tag as supported.

**Describe alternatives you've considered**

N/A

**Additional context**

We realized that some tags with tag mods are not marked as supported.

### PR DESCRIPTION
**Pull request by citizen428**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This PR automatcally marks tags as supported when a tag mod is added. This removes the burden from admins to manually mark the tag. 

## Related Tickets & Documents

Closes #11140 

## QA Instructions, Screenshots, Recordings

1. Create a tag: `tag = Tag.create(name: "admintest")`
2. Check that it isn't supported: `tag.supported? #=> false`
3. Assign a tag moderator: `AssignTagModerator.add_tag_moderators([User.last.id], [tag.id])`
4. Ensure the tag is now supported: `tag.reload.supported? #=> true`

## Added tests?

- [X] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## Added to documentation?

- [ ] Docs.forem.com
- [ ] README
- [X] No documentation needed

### CODE REVIEW

**Review by rhymes — APPROVED** [review]
Do we need to add some data update script for existing tags with mods but not marked as supported?

**Comment by citizen428** [comment]
> Do we need to add some data update script for existing tags with mods but not marked as supported?

Good question, cc @michael-tharrington

**Comment by michael-tharrington** [comment]
Great question @rhymes and thanks for the cc' @citizen428. 

It would be awesome if we have a data update script to turn any existing tag mods' unsupported tags to supported!

But if it's gonna be difficult to do, then don't worry about it!

**Review by mstruve — APPROVED** [review]
I think a DUS would be ideal here to get the data in a nice clean state but otherwise the code LGTM!

**Comment by citizen428** [comment]
Just did a check with Blazer, apparently, there are 71 tags who have assigned mods but are not supported:

```sql
select
	tags.name,
	supported,
	resource_id
from
	tags
	right outer join roles on (resource_id = tags.id)
where
	roles.name = 'tag_moderator'
	and supported = false
order by
	tags.name;
```

Screen Shot 2020-10-30 at 08 50 08

I'll add a DUS now and then rerequest reviews.

**Comment by citizen428** [comment]
Data update script added, please review again @rhymes and @mstruve, thanks!

**Review by rhymes — APPROVED** [review]
CTEs FTW! 🔥 🤣

**Review by mstruve — APPROVED** [review]
Tested the script locally as well and works great! 🚀

**Review by benhalpern — APPROVED** [review]

**Pull request merged**
