### PR TITLE
a11y-ize reaction drawer

### LINKED ISSUE #19139: Multi reaction drawer is not accessible via the Keyboard
Multi reaction drawer is not accessible via the Keyboard.
Feb-16-2023 12-14-54

### PR DESCRIPTION
**Pull request by rt4914**
## What type of PR is this? (check all applicable)

- [x] Bug Fix

## Related Tickets & Documents

- Closes #19139

## QA Instructions, Screenshots, Recordings

Output and different cases mentioned in this video: https://www.loom.com/share/a12279fbc7124f139f51aa402dcf19fe

### UI accessibility concerns?

Improves accessibility 

## Added/updated tests?

- [x] No

## [Forem core team only] How will this change be communicated?

- [x] This change does not need to be communicated

### CODE REVIEW

**Comment by rt4914** [comment]
@anujbhavsar96 I will need your help with the current design for the issues explained in this video https://www.loom.com/share/a6afe90238cf4a16b1ccb7623213d96a

**Comment by anujbhavsar96** [comment]
@RajaSK05 Can we have a browser default keyboard focus style instead of having customized ones? 

We have a few different styles for this across the platform right now, so it would be better to use browser default ones right now.

Keyboard focus

**Review by jaw6 — APPROVED** [review]

**Comment by anujbhavsar96** [comment]
Thanks for sharing that alternative @rt4914 

I think that alternative also looks fine to me. Whichever is easy implementation-wise. The drawer highlight looks perfect.

**Comment by rt4914** [comment]
> Thanks for sharing that alternative @rt4914
> 
> I think that alternative also looks fine to me. Whichever is easy implementation-wise. The drawer highlight looks perfect.

@anujbhavsar96 Thanks. Will keep this change.

**Review by maestromac — APPROVED** [review]
Nice! LGTM!

**Pull request merged**
