### PR TITLE
Fix broken contact link in email 

### LINKED ISSUE #19710: Fix broken `/contact` links in email
**Describe the bug**

Some emails incorrectly use translation files intended for main views in their emails to render links to support information which breaks when sent via email.

**To Reproduce**

1. Create an organization (which you can do on `/settings/organization`)
2. Delete an organization (which you can do on `/settings/organization/<org_id>`)
3. Try to click the "Contact us" button in the email
4. Load blank `http://contact`

**Expected behavior**

Instead of a link to a page on the platform, the link should `mailto:` the Forem's configured contact email, [as used in this email.](https://github.com/forem/forem/blob/cd9d5df963e7084a289915ae14c73d87c6770070/app/views/mailers/notify_mailer/account_deleted_email.text.erb#L3).

The full text should be something like:

`Contact us at <a href="mailto:<%= ForemInstance.contact_email %>><%= ForemInstance.contact_email %></a> if there is anything more we can help with.`

For example: "Contact us at [yo@dev.to](mailto:yo@dev.to) if there is anything more we can help with."

**Additional context**

- Email is sent [here](https://github.com/forem/forem/blob/5410f6f92c99d15584297ae56098260dcb8e3032/app/mailers/notify_mailer.rb#L100)
- Incorrect translations are defined [here](https://github.com/forem/forem/blob/5410f6f92c99d15584297ae56098260dcb8e3032/config/locales/en.yml#L3).
- You can find the offending list of emails that uses the incorrect translation file [here](https://github.com/search?q=repo%3Aforem%2Fforem+app%2Fviews%2Fmailers%2Fnotify_mailer%2F+contact_prompts&type=code).
- Ideally, the body text of the email would be kept in the translation files, but I'm unsure of the complexity of this approach re-calling Forem configuration, so this is not required for this issue.

### PR DESCRIPTION
**Pull request by jerinkc**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Use `mailto` links instead of pointing to /contact page.

## Related Tickets & Documents

- Related Issue #
- Closes #19710 

## QA Instructions, Screenshots, Recordings

Screenshot 2023-07-28 at 11 57 09 AM
Screenshot 2023-07-28 at 11 57 22 AM

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [axe DevTools](https://www.deque.com/axe/) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

_For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [ ] Yes
- [x] No
- [ ] I need help with writing tests

### CODE REVIEW

**Review by filleduchaos — COMMENTED** [review]
Thank you for your contribution! By the way, there is a spec in `spec/mailers/notify_mailer_spec.rb` that you could update to assert that the correct link is present in the emails; [here is an example](https://github.com/forem/forem/blob/22569b37c80b51009f0c423f9fdd076d6d95581d/spec/mailers/notify_mailer_spec.rb#L162-L199) of a test suite making assertions about an email's body

**Comment by jerinkc** [comment]
Thank you for your feedback, I have updated the spec file accordingly.

**Review by filleduchaos — APPROVED** [review]
Looks great to me 🎉

**Review by dukegreene — APPROVED** [review]
LGTM! Thanks for your contribution, and thanks for adding the requested spec as well!

**Pull request merged**
