### PR TITLE
CSS fix for : Tool tips are narrow and squished in multiple locations

### LINKED ISSUE #18814: Tool tips are narrow and squished in multiple locations
**Describe the bug**

The tooltips have a style bug where they are too narrow, with bizarre behavior as a result.

**To Reproduce**

- Go to `/notifications`.
- If you have reactions, hover over them.

**Expected behavior**

It would not be excessively narrow and make the appropriate word breaks depending on the context.

**Screenshots**

Screen Shot 2022-12-06 at 9 43 06 AM
Screen Shot 2022-12-06 at 9 43 09 AM

### PR DESCRIPTION
**Pull request by rt4914**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Tooltips are squished at various places.

This issue mention problems a 2 places:
- Notifications - **FIXED**
- Add a cover image tooltip (in Create Post) - **NOT FIXED**

The cover image tooltip has not been fixed because if we try to fix it it will end up re-creating this https://github.com/forem/forem/pull/18761 and therefore its fine if its squished as long as the text does not cut-off.

## Related Tickets & Documents

- Related Issue #18814
- Closes #18814

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

Screenshot 2022-12-13 at 10 16 27 PM
Screenshot 2022-12-13 at 10 16 37 PM
Screenshot 2022-12-13 at 10 16 46 PM
Screenshot 2022-12-13 at 10 33 55 PM

### UI accessibility concerns?

No

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [x] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

### CODE REVIEW

**Comment by rt4914** [comment]
@Ridhwana There is one more issue that I have found related to tooltips.

Have a look at https://github.com/forem/forem/blob/e5e36a2e2dc25481cbc6433c9ffde9bcbe20fe80/app/views/comments/_comment_header.html.erb#L17

In line 16, we are using `crayons-hover-tooltip` and `data-tooltip` to show the tooltip and also in line 17 we are using `title` which also shows the tooltip.

The result is two tooltips.
Screenshot 2022-12-13 at 10 19 13 PM


So this needs to be fixed at multiple places, I think removing `title` should be fine but do you know of any accessibility concern that it might bring?

**Comment by Ridhwana** [comment]
> So this needs to be fixed at multiple places, I think removing `title` should be fine (which shows the bottom tooltip in screenshot) but do you know of any accessibility concern that it might bring?

I'm not 100% sure of this answer - but I did do some digging and it seems that the hover tooltips are not accessible, especially since they are designed to not be triggered by keyboard navigation. Here's a previous [conversation](https://github.com/forem/forem/pull/14876#discussion_r724742794) that implies it was inaccessible.

Hence I _think_ removing title should be okay, but if theres anyone more experienced on the topic than me then I would default to their judgement.

**Review by Ridhwana — APPROVED** [review]

**Comment by rt4914** [comment]
> > So this needs to be fixed at multiple places, I think removing `title` should be fine (which shows the bottom tooltip in screenshot) but do you know of any accessibility concern that it might bring?
> 
> I'm not 100% sure of this answer - but I did do some digging and it seems that the hover tooltips are not accessible, especially since they are designed to not be triggered by keyboard navigation. Here's a previous [conversation](https://github.com/forem/forem/pull/14876#discussion_r724742794) that implies it was inaccessible.
> 
> Hence I _think_ removing title should be okay, but if theres anyone more experienced on the topic than me then I would default to their judgement.

@Ridhwana Based on your explanation, if we remove `title` then the tooltip will be inaccessible and also if we remove the `crayons-hover-tooltip` then the UI won't look good. So definitely this needs more thought. Maybe this can be a separate issue altogether also considering that it will be probably be fixed across the project.

**Comment by rt4914** [comment]
> @rt4914 apologies it seems we've missed each other a bit. I'm saying that the crayons-hover-tooltip is already inaccessible and was built that way. I'm not sure what the context is however if it is already inaccessible and we are unable to navigate to it via the keyboard then it should be okay to remove the title.

@Ridhwana Okay got it. It makes sense. (Because of crayons-hover-tooltip the item/view is inaccessible via the keyboard and therefore removing the `title` is fine.) Let me know if I have understood this incorrectly.


In any case, I will file a separate issue for this as we will need to remove it not just from comments but will have to sweep the entire code to find other similar instances and remove them too.

**Comment by Ridhwana** [comment]
> @Ridhwana Okay got it. It makes sense. (Because of crayons-hover-tooltip the item/view is inaccessible via the keyboard and therefore removing the `title` is fine.) Let me know if I have understood this incorrectly.
> 
> In any case, I will file a separate issue for this as we will need to remove it not just from comments but will have to sweep the entire code to find other similar instances and remove them too.

Correct, and sounds good!

**Pull request merged**
