### PR TITLE
Remove asset reconciliation

### LINKED ISSUE #12725: Remove "asset_reconciliation" hack
**Describe the bug**

`app/views/layouts/_asset_reconciliation.html.erb` was added to the code in order to fix mismatches between the shell and body code. It is designed to _only_ "reconcile" CSS when there is a mismatch between the body and the head, but for some reason it seems to be trying to resolve a mismatch too often.

Part of the implementation of this was to fix an issue which has otherwise been fixed with how we store assets (there had been a caching issue on Forem deploys where we were purging assets on deploy, but pages were still caching them).

After this behavior was changed to fix a _different_ CSS bug, this behavior started to happen. It is documented in a couple separate issues:

https://github.com/forem/forem/issues/12631
https://github.com/forem/forem/issues/12455

"Asset reconciliation" has been useful in helping us roll out changes without "caching mismatches" we used to sometimes see due to our aggressive edge caching. But the help we were getting from it is badly negated by this bug, and we should most likely go back to the drawing board on how to deal with this issue. "Asset reconciliation" was always somewhat of a hack.

**To Reproduce**

View above issues

**Additional context**

Removing these lines should solve the issue:

```html
    <% if user_signed_in? %>
      <%= render "layouts/asset_reconciliation" %>
    <% end %>
```

(You can also remove the file itself)

This might mean we re-encounter some old cache mismatch issues this had resolved, but removing this hack would allow us to address those specifically.

### PR DESCRIPTION
**Pull request by Zhao-Andy**
## What type of PR is this? (check all applicable)
- [x] Bug Fix

## Description
This removes the `_asset_reconciliation.html.erb` file and its related code since it introduced other bugs while fixing some other ones. We want to take an approach where we're fixing the specific bugs that appeared before the `asset_reconciliation` hack.

## Related Tickets & Documents
See #12725 for more details

Resolves #12725...
and maybe #12631, #12455

## QA Instructions, Screenshots, Recordings
1. Before pulling this branch, update your user's theme to something non-default (like night theme)
2. Go to the home page
3. See that it has a flash of going from night theme to the default theme (user set theme not persisted)
4. Pull this branch down
5. Refresh (not hard refresh) the page
6. See that your theme persists

### UI accessibility concerns?
Nope

## Added tests?
- [x] No, and this is why: removing a feature

## [Forem core team only] How will this change be communicated?
- [x] I will share this change internally with the appropriate teams

## [optional] Are there any post deployment tasks we need to perform?
Nope

## [optional] What gif best describes this PR or how it makes you feel?

Spongebob smiles with satisfaction, and brushes his hands like he's done.

### CODE REVIEW

**Comment by benhalpern** [comment]
I'm going to remove my review and replace it with a couple folks who should have the context here. IMO looks great, but I'll leave it to some other folks who have dealt with some of our dreaded service worker/asset issues to sanity check and ensure this doesn't so much run through me. 😄

**Review by atsmith813 — APPROVED** [review]
Tested this locally, well done 💯

**Comment by ludwiczakpawel** [comment]
I'm removing myself from reviewers - even though I've reported several issues likely caused by the bug that is being fixed in this PR, I have never experienced these issues locally and I don't feel like a right person to verify the code :P but if it fixes things, awesome! <3

**Review by juliannatetreault — APPROVED** [review]
Works like a charm locally!! 🌃

**Pull request merged**
