### PR TITLE
Switch from combobox to plaintextArea on click outside

### PR DESCRIPTION
**Pull request by aitchiss**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

There is a small bug in the autocomplete work - if I start a user mention, and then click outside of the dropdown to dismiss the options, we successfully close the dropdown and user can continue typing. However, if you then try to use the up/down arrow keys you will find they don't work. 

This was because we were still in the Reach UI combobox which suppresses the up/down arrow key events.

The fix is to treat the 'click outside dismiss' the same as the other cases where we exit the 'search mode', and flip back to a vanilla text area. This PR handles two types of 'click outside':

- Click outside of the dropdown of options but **inside** the text area
- Click outside of the textarea

## Related Tickets & Documents

Addresses part of #13323 

## QA Instructions, Screenshots, Recordings

**Test click outside dropdown, but within textarea:**
- Create a new post
- Add some text and start a user mention by typing `@sometext`
- When the dropdown appears, click outside elsewhere in the text area
- The cursor should appear where you have clicked, and you should be able to continue typing
- Try using the up/down arrow keys and check they are moving the cursor as you would expect
- Test in comments as well as posts

https://user-images.githubusercontent.com/20773163/114153056-d95ccd00-9916-11eb-9e7c-20322e168506.mp4

**Test click outside of textarea:**
- Create a new post
- Add multiple lines of text
- Somewhere in the middle of your text content, start an `@mention`
- While the dropdown is still open, click outside of the text area to blur it
- Click back into the text area and verify that the arrow keys move you up in down in your text content
- Test in comments as well as posts

https://user-images.githubusercontent.com/20773163/114559697-e99ce100-9c63-11eb-810a-6ba94aa67ee0.mp4

### UI accessibility concerns?

This has minimal impact on accessibility, but does improve it slightly. Previously the text area would remain in 'combobox' mode which suggests to screen reader users they may type to search and view suggestions (which wasn't true in the case they had clicked away from an `@mention`. The component now correctly updates back to a plain textarea, better reflecting its usage.

## Added tests?

- [ ] Yes
- [X] No, and this is why: This is really hard to test in Cypress, as it relies heavily on exact clicks and knowing where the cursor position is. I don't think we would be able to test this reliably other than manually.
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [X] This change does not need to be communicated, and this is why not: So far this bug has only been reported internally and is a minor change

## [optional] What gif best describes this PR or how it makes you feel?

Abed from Community saying cool cool cool

### CODE REVIEW

**Review by rhymes — COMMENTED** [review]
Works well, found a small bug but I'm unsure if it should be part of this PR or done separately:

1. activate the component
2. select an option
3. press the esc button
4. the component closes itself
5. can't use the arrow keys anymore, as I guess I'm still inside "combobox" mode

Great work!

**Comment by aitchiss** [comment]
> Works well, found a small bug but I'm unsure if it should be part of this PR or done separately:
> 
> 1. activate the component
> 2. select an option
> 3. press the esc button
> 4. the component closes itself
> 5. can't use the arrow keys anymore, as I guess I'm still inside "combobox" mode
> 
> Great work!

I think that Escape press is being handled by the Reach UI combobox, since 'Escape' usually results in a _temporary_ dismissal of the combobox dropdown as per the standard combobox practices. I'm sure we can override it if it feels like it could be a pain point though, but maybe a separate issue 👍

**Review by rhymes — APPROVED** [review]
LGTM!

**Review by nickytonline — COMMENTED** [review]
This LGTM. Going to test it on iOS. It would be good to add an E2E test for this.

1. Activate the combobox
2. Blur the combobox
3. Go back in the editor (should be plain textarea now)
4. type and use arrow keys. (See https://docs.cypress.io/api/commands/type#Arguments)

**Review by msarit — APPROVED** [review]
Worked well for me 🎉  
I'm approving but echo @nickytonline point for Cypress tests (maybe in a separate PR)

**Comment by nickytonline** [comment]
Given the editor has high visibility, I would include the E2E tests in this PR

**Review by nickytonline — CHANGES_REQUESTED** [review]
Given the editor has high visibility, I would include the E2E tests in this PR.

**Comment by nickytonline** [comment]
I'm going to take a peek at the E2E tests for now as @aitchiss is done for the week.

**Comment by aitchiss** [comment]
> This LGTM. Going to test it on iOS. It would be good to add an E2E test for this.
> 
> 1. Activate the combobox
> 2. Blur the combobox
> 3. Go back in the editor (should be plain textarea now)
> 4. type and use arrow keys. (See https://docs.cypress.io/api/commands/type#Arguments)
> 
> Actually if we validate it's the plain text area, the arrow key test might not be necessary.

The test needs to test specifically for click outside of the dropdown but within the text area, rather than a blur event - I didn't realise before that Cypress allows you to pass an option for _where_ in an element to click - I _think_ this makes it robust enough to test this, but I worry a little bit about the reliability of expecting 'right' (centre right) to always be outside of the dropdown ('top' and 'bottom' positions don't work for us because they're obscured by other elements).

**Comment by aitchiss** [comment]
@nickytonline Cypress test added for the click outside of the textarea - funnily enough it showed up it wasn't working correctly (Cypress FTW)! So I've added a blur handler as well to make sure we switch back to the plain textarea. I've also updated the PR description with manual test steps / screen recording for that area

**Review by nickytonline — APPROVED** [review]
Thanks for adding the tests @aitchiss! 🚢

**Pull request merged**
