### PR TITLE
Fixed Bug 21280 - Allow Complex Markdown Structure with 3+ Ticks

### LINKED ISSUE #21280: Markdown code in a code block breaks the UI
**Describe the bug**

I tried to write Markdown code in an article. This example Markdown code happens to include a code block as well.

In GitHub Markdown, you can use more than three backticks, so that this issue can be evaded. On dev.to, it just breaks the UI.

**To Reproduce**

Try to post the following article text (or just preview it):

``````
It is absolutely a use-case to include _Markdown code_ inside a _code block_. For example, I could say you need to write your `README.md` file with the following content:

`````markdown
# Hello

This is a tutorial on how to use markdown.

Code blocks

```js
export default {}
```

`````

And then the whole article is bugged.
``````

**Expected behavior**

The longer backticked code block's beginning and end is matched correctly, so we can have code block in a markdown code block.

**Screenshots**

forem-markdown-bug

**Desktop (please complete the following information):**

- OS, version: Windows 11
- Browser, version: Google Chrome, Version 128.0.6613.137 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by yousefmarey12**
## What type of PR is this? (check all applicable)

- [Yes ] Refactor
- [ ] Feature
- [ Yes] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Bug 21280 reported that more than 3 backticks or tildes can be used in markdown standard. The error occurred whilst escaping the markdown as it would only escape **exactly** 3 ticks or tildes. In standard markdown, the closing ticks have to be **equal to or greater** than the opening ticks, which is exactly what I did.

Now, only the highest level markdown is escaped. 

An example outcome of the new code:

{{% raw %}}
`````markdown

````markdown

```js
const pi = 3.14
```

````

`````
{{% endraw %}}

An example outcome of the existing code (resulted in an unexpected broken UI):
{{% raw %}}
`````markdown


```js
{{% endraw %}}

const pi = 3.14

{{% raw %}}
```

`````
{{% endraw %}}

This results in the `spec/services/markdown_processor/parser_spec.rb` test: "escapes codeblocks in numbered lists" to fail. This is expected as inner markdown ticks and tildes should be displayed. If this PR is accepted, I think we should remove this test. All other tests passed.

Any concerns regarding the code, let me know.

## Related Tickets & Documents

- Related Issue #
- Closes #21280

## QA Instructions, Screenshots, Recordings

Now:
image

Before:
image

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [axe DevTools](https://www.deque.com/axe/) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

_For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [ ] Yes
- [Yes ] No, and this is why: I've tested with tildes (more than 3) and I also feel this PR should encourage us to remove a the specified unit test.
- [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?
Nope

## [optional] What gif best describes this PR or how it makes you feel?
this-is-my-first-time-mitchell-moffit

My first ever PR.

alt_text

### CODE REVIEW

**Comment by yousefmarey12** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by benhalpern** [comment]
Hey @yousefmarey12 thanks for this.

Can you edit the `spec/services/markdown_processor/parser_spec.rb` to adjust and/or remove the test you're describing with behavior which should change _as well_ as add one or two additional test to thoroughly exercise any behavior you might be changing here or could be affected?

We'll want to change any tests _before_ it is merged, and since this is such a critical path with complex logic we should add additional tests to bolster as much as possible.

If you come across unrelated test failures in GitHub you can ignore — as we're experiencing some occasional false positives.

**Comment by yousefmarey12** [comment]
Hello @benhalpern , I am thankful that you mentioned that because I manually tried the specified test (by creating a post) and it gave me a syntax error. I took an initial look at it, and the problem could be with either the renderer itself or a bug from my side. The escaped liquid tags came out as expected, but I have to look into if I will customize the renderer or the function itself. 

I understand this is open-source, but I like working with deadlines. However, I will be busy until the 24th. Could I perhaps have until the 27th to finish this?

**Comment by yousefmarey12** [comment]
Hello @benhalpern ,

I was mistaken regarding deleting a particular test as the test was actually important. I altered my code so that all of the written tests pass. 

I also wrote 2 extra tests that both passed. If you have any concerns regarding my code, please do not hesitate to ask.

**Pull request merged**
