### PR TITLE
Clear asset and vendor caches on deploy

### PR DESCRIPTION
**Pull request by jgaskins**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

We don't need these files inside deployment artifacts. They're only there to make asset compilation and bundling faster. This should give us a lot more headroom between our Heroku slug sizes and the soft cap of 300MB.

## Related Tickets & Documents

#13563
[Forem Slack thread](https://forem-team.slack.com/archives/CPGJMAX5F/p1620050711348800?thread_ts=1620049708.343800&cid=CPGJMAX5F)

## QA Instructions, Screenshots, Recordings

Check [build logs](https://dashboard.heroku.com/apps/benhalpern-community/activity) for [BHC](https://community.benhalpern.com). They should show slug size much smaller — last one I deployed manually was 292MB.

The latest build for DEV as of this writing is 322MB, which is above the soft cap.

## Added tests?

- [ ] Yes
- [x] No, and this is why: No runtime code is affected
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [x] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

Max Headroom

### CODE REVIEW

**Review by djuber — APPROVED** [review]
Looks reasonable

**Review by maestromac — APPROVED** [review]
LGTM! I think it would be a good idea to see to push this to BHC first to see how much reduction we'll get

**Comment by jgaskins** [comment]
@maestromac Good idea. I'll try that and post the result here.

**Comment by jgaskins** [comment]
It did cut down heavily on the slug size:

```
remote: -----> Compressing...
remote:        Done: 212.9M
```

That's not as low as I was hoping for but it's way better than the close to 300MB we've been seeing. However, it looks like Bundler needs those files because that's what it uses to determine whether the gems are installed:

```
remote: Running release command...
remote:
remote: + [[ '' = \b\l\o\c\k\e\d ]]
remote: + STATEMENT_TIMEOUT=4500000
remote: + bundle exec rails app_initializer:setup
remote: bundler: failed to load command: rails (/app/vendor/bundle/ruby/2.7.0/bin/rails)
remote: /app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/source/git.rb:206:in `rescue in load_spec_files': https://github.com/forem/acts_as_follower.git (at master@06393d3) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
```

Going to leave `vendor/cache` in.

**Review by citizen428 — APPROVED** [review]
Approved for the gi-g-gif alone.

**Review by rhymes — APPROVED** [review]
LGTM!

**Comment by aitchiss** [comment]
@jgaskins - just looking at tidying up some PRs and wondering if this one can be merged now?

**Comment by jgaskins** [comment]
@aitchiss Yep! Thanks for the reminder!

**Comment by maestromac** [comment]
Slug dropped from 320MB to 279MB :clap:

**Pull request merged**
