### PR TITLE
Routes: more modern and consistent syntax

### PR DESCRIPTION
**Pull request by yshmarov**
## What type of PR is this? (check all applicable)

- [X] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

improved syntax of routes file

## Related Tickets & Documents

N/A

## QA Instructions, Screenshots, Recordings

This is a refactor, app should function as before

### UI accessibility concerns?

N/A

## Added tests?

- [ ] Yes
- [X] No, and this is why: refactor already tested by existing tests
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [X] This change does not need to be communicated, and this is why not: refactor to existing file, no change in behaviour

### CODE REVIEW

**Comment by citizen428** [comment]
Thanks for this PR @yshmarov! Running Rubocop against `routes.rb` in this branch gives me 7 offenses, maybe you want to fix those too? They can be automatically fixed with `rubocop -a config/routes.rb`, so the effort is minimal.

**Comment by rhymes** [comment]
@yshmarov don't forget to sign the CLA, thank you, excited about this optimization. I'm a fan of `to:` as well :)

**Comment by rhymes** [comment]
Hi @yshmarov, let us know if you're having trouble signing the CLA and if we can help somehow

**Comment by yshmarov** [comment]
@rhymes CLA signed! Thanks for the reminder :)

**Review by rhymes — APPROVED** [review]
Thanks @yshmarov!

If you don't mind I can take care of @citizen428's request here https://github.com/forem/forem/pull/12547#issuecomment-772247648 and commit to this PR - I'm asking because I see you've edited the file directly and you might not have the entire Rails environment setup locally. Let me know!

**Review by citizen428 — APPROVED** [review]

**Comment by aitchiss** [comment]
Thank you @yshmarov for these changes!

**Pull request merged**
