### PR TITLE
Switch references to Forem master branch to main

### PR DESCRIPTION
**Pull request by joshpuetz**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This PR renames references to the `master` branch in `forem/forem` to `main`. It should not be merged until after the branch rename is performed on the Forem repo. 

Downstream users may need to update their local copies (they'll receive a notification as such when they visit https://github.com/forem/forem

Cursor_and_Branches_·_forem_forem

## Related Tickets & Documents

closes https://github.com/forem/internalEngineering/issues/279

**blocked by** https://github.com/forem/infra/issues/173

## Added tests?

- [x] Yes - **changed Travis CI configuration**
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## Added to documentation?

- [x] [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/)
- [x] README
- [ ] No documentation needed

## [optional] Are there any post deployment tasks we need to perform?

This PR is blocked by https://github.com/forem/infra/issues/173: we should verify Forem.cloud deployments are still working after this change.

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Review by rhymes — APPROVED** [review]
Let's do this!

**Review by Zhao-Andy — APPROVED** [review]
Yes!!!

**Review by maestromac — APPROVED** [review]
LGTM! I believe this will require special attention from Systems team.

**Comment by jdoss** [comment]
This will effectively break forem.cloud deployments until we can get some changes made on our end.

**Comment by joshpuetz** [comment]
> This will effectively break forem.cloud deployments until we can get some changes made on our end.

Is there a issue for that work that I can link to @jdoss?

**Comment by jdoss** [comment]
https://github.com/forem/infra/issues/173

**Comment by joshpuetz** [comment]
Converted back to a draft PR pending https://github.com/forem/infra/issues/173 so this isn't accidentally merged.

**Review by mstruve — APPROVED** [review]
🔥

**Review by citizen428 — APPROVED** [review]

**Review by vaidehijoshi — APPROVED** [review]
😭

**Review by rhymes — APPROVED** [review]
Let's do this!

**Pull request merged**
