### PR TITLE
Temporary fix for text sometimes overflowing code blocks in posts

### LINKED ISSUE #20053: Blog Text Overflow
**Describe the bug**
Some text including coding part is overflowing on x axis
When the number of words on a single line increased the text started overflowing and created a horizontal scroll for the blog

**To Reproduce**

Go to Dashboard -> First blog -> scroll down a bit -> text overflowing on x axis creating a scroll

**Expected behavior**
The text should wrap as in other blogs

The text should not overflow no matter how many words in a single line, The scroll should be inside the coding square but it is showing on the blog itself

**Screenshots**
Screenshot_2023-09-06-21-14-12-878_com android chrome
Screenshot_2023-09-06-21-14-16-317_com android chrome
Screenshot_2023-09-06-13-31-45-615_com android chrome

**Desktop (please complete the following information):**

- MacBook 13 pro
- Chrome

**Smartphone (please complete the following information):**

- Redmi note 8 pro:
- Android 11
- Chrome

### PR DESCRIPTION
**Pull request by filleduchaos**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

I thought this one was going to be a simple thing/missing bit of CSS, but it turned out more complicated than that

Basically, normally we parse markdown code snippets (delineated by backticks) into a code-highlighted `pre` element that's wrapped in a div that adds the expand/fullscreen control. Inspecting the article in question showed that the overflowing blocks _weren't_ getting wrapped in this div and were thus being excluded from the styling they should be getting. I still don't understand why; there are other code blocks in the article that are wrapped correctly/don't overflow, and when I pulled the article's markdown from the API there was nothing that seemed to distinguish the blocks that got wrapped and the blocks that didn't.

I wasn't making much progress untangling that knot, so for this PR I decided to stick to fixing the unwrapped code blocks to _look_ okay. We should revisit this at some point and figure out what's up with the parser because the blocks in question still don't have the fullscreen control like they're supposed to.

## Related Tickets & Documents

- Related Issue #20053 
- Closes #20053 (I will open a separate ticket for the article parser)

## QA Instructions, Screenshots, Recordings

<details>
<summary>Here is the markdown for the article in question:</summary>

~~~text
Hello Everyone, today i will show, how we can create a simple Image gallary in react using tailwind CSS and make it reusable.

Let's get started...

## Updating Tailwind config file
```js
 safelist: [
    'justify-center',
    'justify-self-center',
      ...[...[1,2,3,4,5,6,7,8,9,10,11,12,14,16,20].values()].flatMap(i => [`gap-x-${i}`, `gap-y-${i}`]),
      ...[...Array(12).keys()].flatMap(i => [`grid-cols-${i+1}`]),
  ]
```
* Add this safelist property inside tailwind config, it is used to safelist tailwind classes that we want to use dynamically in our project, basically tailwind remove those classes which are not used in the project, so if you try to dynamically add a class, it won't apply the stylings as the class is not there in the stylesheet.
* So, we are safelisting "justify-center" and "justify-self-center", which we will apply dynamically, then using array and flatMap, we are safelisting gap-x and gap-y value upto 20, so we can use classes with value upto 20 only like, gap-x-20 and gap-y-20, we can't use gap-x/y-22 or above. Same we applied to the grid-cols classes which contains value from 1 to 12.

## Gallary Props
```js
const Gallary = ({
    images = [],
    position = "left",
    gridLayout = "flex",
    gridCols = 2,
    colGap = "2",
    rowGap = "2",
    hoverFilter = false,
    gallaryClassName = "",
    imageClassName = ""
}) => {
```
This code defines a functional React component named Gallary. The component takes several props as an object destructure, which allows you to customize its behavior. Here's what each prop does:

* images: An array of objects representing images to be displayed in the gallery.
* position: The positioning of the gallery (e.g., "left").
* gridLayout: The layout style for the gallery (either "flex" or a CSS grid layout).
* gridCols: The number of columns in the grid layout.
* colGap: The gap between columns in the grid.
* rowGap: The gap between rows in the grid.
* hoverFilter: A boolean flag to determine whether a hover filter effect should be applied to the images.
* gallaryClassName: Additional CSS classes for the gallery container.
* imageClassName: Additional CSS classes for the individual images.

## Creating container - 
```js
return (
  <div 
    className={`${gallaryClassName} 
      ${gridLayout === "flex" ? "flex flex-wrap" : `grid grid-cols-${gridCols}`} 
     justify-${position} gap-y-${rowGap} gap-x-${colGap}`}>
```
This part of the code returns the JSX (JavaScript XML) that represents the gallery component. It uses template literals to dynamically generate the CSS classes based on the props provided. The classes determine the layout, positioning, and styling of the gallery.

## Rendering images using map
```js
    {
        images?.map(({ imgName, imgUrl, imgWidth, imgHeight, className }, index) => {
            return (
                <div className={`relative ${gridLayout !== "flex" ? `justify-self-${position}` : ""}`} key={index}>
                    <img 
                        name={imgName} 
                        src={imgUrl} 
                        width={imgWidth} 
                        height={imgHeight} 
                        alt={imgName} 
                        className={`text-center ${imageClassName} ${hoverFilter ?  "md:grayscale md:hover:grayscale-0" : ""} ${className}`} 
                        style={{ width: imgWidth, height: imgHeight }} />
                    {
                        imgName && imgName !== "" && 
                        <p className='absolute bottom-2 right-1/2 translate-x-1/2 bg-slate-100 px-4 py-2 rounded-xl'>{imgName}</p>
                    }
                </div>
            )
        })
    }
```
This section maps through the images array and renders each image within a <div>. The properties of each image are extracted from the array and used to set the image attributes and CSS classes. Additionally, if the hoverFilter prop is true, a grayscale filter is applied to the image when hovered.

## Full Code with usage - 
```js
{/* 

PROPS -
images = [
    {
        imgName:"Image 1",
        imgUrl:"imageurl",
        imgWidth: "300px",
        imgHeight: "300px",
        className: "border-4 !rounded-full !border-red-600"
    }
    .
    .
]
position = left/center
gridLayout = flex/grid
gridCols = 1 -> 12
colGap = 1,2,3,4,5,6,7,8,9,10,11,12,14,16,20
rowGap = 1,2,3,4,5,6,7,8,9,10,11,12,14,16,20
hoverFilter = true/false
gallaryClassName = CSS/ Tailwind classes
imageClassName = CSS/ Tailwind classes


USAGE - 
<Gallary 
    images={images} 
    position="center" 
    gridLayout="grid" 
    rowGap="4" 
    colGap="6" 
    gridCols={columns} 
    gallaryClassName="p-10 bg-slate-900 pt-20" 
    imageClassName="rounded-xl border border-white" 
    hoverFilter={true} />

*/}

import React from 'react'

const Gallary = ({
    images=[],
    position="left",
    gridLayout="flex",
    gridCols=2,
    colGap="2",
    rowGap="2",
    hoverFilter=false, 
    gallaryClassName="", 
    imageClassName=""
}) => {

  return (
    <div 
       className={`${gallaryClassName} 
       ${gridLayout === "flex" ? "flex flex-wrap" : `grid grid-cols-${gridCols}`} 
      justify-${position} gap-y-${rowGap} gap-x-${colGap}`}>
        {
            images?.map(({imgName,imgUrl,imgWidth,imgHeight,className},index) => {
                return (
                    <div className={`relative ${gridLayout !== "flex" ? `justify-self-${position}` : ""}`} key={index}>
                        <img 
                            name={imgName} 
                            src={imgUrl} 
                            width={imgWidth} 
                            height={imgHeight} 
                            alt={imgName} 
                            className={`text-center ${imageClassName} ${hoverFilter ?  "md:grayscale md:hover:grayscale-0" : ""} ${className}`} 
                            style={{width:imgWidth,height:imgHeight}} />
                        {
                            imgName && imgName !== "" && 
                            <p className='absolute bottom-2 right-1/2 translate-x-1/2 bg-slate-100 px-4 py-2 rounded-xl'>{imgName}</p>
                        }
                    </div>
                )
            })
        }
    </div>
  )
}

export default Gallary
```

## Changing columns dynamically
```js
// App.js
"use client"

import { useState } from "react"
import Gallary from "./components/Gallary"
import { images } from "@/app/data"

export default function Home() {

  const [columns, setColumns] = useState(4)

  return (
    <main className='min-h-screen grid place-items-center'>
      <select className="fixed top-4 right-4 px-4 py-2 rounded-xl z-10" value={columns} onChange={(e) => setColumns(e.target.value)}>
        {
          [...Array(12).keys()].flatMap(i => [`${i + 1}`]).map(value => {
            return (
              <option value={value} key={value}>
                {value} Column
              </option>
            )
          })
        }
      </select>
      <Gallary images={images} position="center" gridLayout="grid" rowGap="4" colGap="6" gridCols={columns} gallaryClassName="p-10 bg-slate-900 pt-20" imageClassName="rounded-xl border border-white" hoverFilter={true} />
    </main>
  )
}
```
* We are using a select element and map it with an array of value from 1-12, it will set the columns state which in turn change the columns in the Gallary component as the gridCols props is dependent on columns state value

#### It's not an advance gallary component, still you can apply more things like tailwind placeholders to give values in px or percentage, apply different filters other than grayscale or destructure it in way where we can pass other elements instead of just images only. 
Feel free to give suggestions in comments to improve the component and make it more reusable and efficient.
THANK YOU FOR CHECKING THIS POST
~~~

</details>

- Create a new post with that as the content
- Publish the post
- None of the code blocks should overflow

Video demonstration:
https://www.loom.com/share/4f34bf9ab16e492c9ff16b0a548b371b

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: just some CSS selector additions
- [ ] I need help with writing tests

### CODE REVIEW

**Review by jaw6 — APPROVED** [review]

**Review by rt4914 — CHANGES_REQUESTED** [review]
@filleduchaos 
This issue is more because of the content and less because of the code.


https://www.loom.com/share/dfe770921e314734a26725edb7638142?sid=45160a1c-120a-4100-a00f-fb61491af130


The previous similar issue: https://github.com/forem/forem/issues/18284#issuecomment-1271282864

(cc @mirie )

**Comment by mirie** [comment]
WOW great eyes @rt4914 ! I totally missed that markup error when looking at this before. 

We do get these issues passed over to us on a regular basis (I've manually fixed some myself), the fix you've put forth (I only looked at the Loom so didn't QA on Uffizzi instance yet) would reduce these support requests EVEN with user error in marksup, right? @rt4914 what are your thoughts this?

**Comment by rt4914** [comment]
> WOW great eyes @rt4914 ! I totally missed that markup error when looking at this before.
> 
> We do get these issues passed over to us on a regular basis (I've manually fixed some myself), the fix @filleduchaos put forth (I only looked at the Loom so didn't QA on Uffizzi instance yet) would reduce these support requests EVEN with user error in markup, right? @rt4914 what are your thoughts this?

@mirie There is definitely a pattern in both the issues. the tags (<td>, <div>) were not part of `single-line code` or `multi-line code` but even after that it did affect both of these. So in some way we to exclude these tags which are not part of `single-line code` or `multi-line code` while rendering the code.

I do agree that it would be great if we can solve this via code.

The solution mentioned in this PR creates one issue i.e. the code-full-screen feature does not work for the problematic code.

**Comment by mirie** [comment]
> The solution mentioned in this PR creates one issue i.e. the code-full-screen feature does not work for the problematic code.

Hmm, that's fair -- checking back on the linked post, it looks like full screen feature is broken without this fix too. Are you wondering if there's a way to handle this case such that full screen mode would continue to work too?

**Comment by rt4914** [comment]
> > @filleduchaos
> > This issue is more because of the content and less because of the code.
> > https://www.loom.com/share/dfe770921e314734a26725edb7638142?sid=45160a1c-120a-4100-a00f-fb61491af130
> > The previous similar issue: [#18284 (comment)](https://github.com/forem/forem/issues/18284#issuecomment-1271282864)
> > (cc @mirie )
> 
> I COMPLETELY missed this because I was looking at the code blocks themselves so much that I didn't pay enough attention to the rest of the article. Now that I know what it is, there are a couple of solutions I can think of:
> 
> * Validate the html to ensure that all opened html tags are closed (to catch unintentional instances like this). There might be a Nokogiri (or Nokogiri + library) option to do this, but I am not sure. If there is, we could then surface this to the user as an error when attempting to publish
> * Let the user input be and fix the issue post processing (i.e. find any `pre.highlight` elements that aren't wrapped in the correct `div`s with fullscreen controls as they should be and wrap them). We could do this in JS so it would automatically apply to previously published articles without the need to re-process their markdown
> 
> Let me know what you think 🙏

@filleduchaos Great suggested solutions. I agree that we can place checks in place to track the open-close tags.

**Review by benhalpern — APPROVED** [review]

**Pull request merged**
