### PR TITLE
[WIP] Add scroll to Anchor

### PR DESCRIPTION
**Pull request by Link2Twenty**
##  What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Anchors are not currently caught by the router

## Related Tickets & Documents
#10234

## QA Instructions, Screenshots, Recordings
- Go to [this post](https://dev.to/eduherminio/waiting-in-arduino-ii-millis-function-to-the-rescue-33k6#going-back-to-our-case-study)
- Click on `case study` link
- See anchor be picked up

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

## [optional] Are there any post deployment tasks we need to perform?
N/A

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by citizen428** [comment]
> Anchors are not currently caught by the router

This is where I end up on the current live site if I click the link you provided, so it seems like anchors get picked up just fine. Am I missing something

Screen Shot 2020-09-08 at 08 48 52

**Review by citizen428 — APPROVED** [review]

**Comment by fdoxyz** [comment]
I tried it out locally and the solution works great. Could you please get the branch up to date with master so it can pass the CI check?

**Comment by Link2Twenty** [comment]
I don't think the fail is being caused by a conflict, is it?

**Comment by fdoxyz** [comment]
I'm pretty sure it's not caused by a conflict or the changes in the PR.

I'm not certain if it's Travis or GitHub/Git itself, but when CI runs the test suite it hasn't pulled the latest master (maybe the merge is pointing to an older commit from master). 

This causes the build to fail because the code is outdated (fixes to these errors were merged but

**Comment by Link2Twenty** [comment]
I'm gonna say I did something wrong 😁

**Comment by rhymes** [comment]
I think something odd happened with this PR. It lists 397 files changed

**Comment by Link2Twenty** [comment]
Let's try again

**Pull request closed without merging**
