### PR TITLE
Fix social media settings to enable mastodon

### LINKED ISSUE #18978: Verify our identity on Mastodon using `rel=me` attribute
### Discussed in https://github.com/forem/forem/discussions/18822

<div type='discussions-op-text'>

<sup>Originally posted by **erinb223** December  7, 2022</sup>
Hey team! Got a Mastodon-related quick win for ya today: profile verification.

The most effective way to verify our identity on Mastodon is to add a link with a `rel=me` attribute to both our site homepage (dev.to) and our GitHub repo (github.com/forem/forem). [Mastodon has documentation on how to do it and how it works](https://docs.joinmastodon.org/user/profile/#verification).

This is what our profile looks like currently:
A screenshot of our Mastodon profile, with all our links boxed in standard gray.

Once we have verified our ownership of our domain and our repo using the above method, they will look like these:
A screenshot of Scott Hanselman's Mastodon profile, which shows three of his links boxed in green with a checkmark.

One way to incorporate this on the dev.to homepage, while also encouraging Mastodon users to engage with us on their social media platform of choice, could be to add a Mastodon icon to our social media icon selection here:
A screenshot of our homepage with the social media icons circled in red

Verification on Mastodon is key for the following reasons:
- It proves that we are the real dev.to, not a mirror
- It makes our audience more likely to trust us on the platform
- Users can safely, confidently follow verified links off the platform and onto our sites

Thanks for your consideration! I think this could be something of a quick win and I appreciate your work on it.</div>

### PR DESCRIPTION
**Pull request by jaw6**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

#19015 added support for mastodon and the `rel="me"` attribute, _however_, our `Settings::General` model is _super weird_ and does not work the way one might expect. In this case, #19015 changed the `defaults` hash, but that's only used when there's _no_ value saved for this setting — any forem that had already adjusted its `social_media_handles` setting wouldn't see the updated `mastodon` key.

This PR updates the Admin form to use a fixed list of social media services, instead of relying on what's in the saved settings.

## Related Tickets & Documents

- Closes #18978

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: settings are weirdly under-tested
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [x] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Review by rt4914 — APPROVED** [review]

**Comment by mirie** [comment]
@lboogie04 can you take a look at this PR today?

**Comment by mirie** [comment]
@jaw6 can this be merged/deployed to see if this fixes the issue so that @erinb223 can use it on DEV?

**Comment by jaw6** [comment]
@mirie It has now merged.

**Comment by erinb223** [comment]
Thanks all! I can now see the input field in `admin/customization/config > social media`.

Unfortunately the `rel=me` link doesn't work in this input. Is there another way we're thinking we can incorporate a `rel=me` link into the homepage? [Here is the original issue, for reference.](https://github.com/forem/forem/issues/18978)

I did also attempt to input the plain Fosstodon profile URL and after selecting "update settings," it didn't seem to "take." When I refresh the homepage the new icon does not appear, and upon navigating back to settings the URL is not saved to the field where I placed it.

**Pull request merged**
