### PR TITLE
BUGFIX: Allow image upload even if no existing image

### PR DESCRIPTION
**Pull request by philipqnguyen**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Presently, if a user does not have a profile image associated, the user would not be able to upload a new profile image.
This should fix that.

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

### UI accessibility concerns?
n/a

## Added tests?

- [x] Yes
- [ ] No, and this is why: Minor UI bug?
- [ ] I need help with writing tests

### CODE REVIEW

**Comment by philipqnguyen** [comment]
TravisCI is failing with this error:
```
       ActiveRecord::RecordInvalid:
         Validation failed: undefined method `parse' for #<Liquid::BlockBody:0x00000000149fa290>, Title can't be blank
       # ./spec/models/notification_spec.rb:10:in `block (2 levels) in <top (required)>'
       # ./spec/models/notification_spec.rb:247:in `block (3 levels) in <top (required)>'
       # ./spec/rails_helper.rb:141:in `block (3 levels) in <top (required)>'
       # ./spec/rails_helper.rb:141:in `block (2 levels) in <top (required)>'
```
Doesn't seem like it's related and looks like some other PRs are failing with the same error? Any ideas why this is happening?

**Comment by citizen428** [comment]
@philipqnguyen The spec issues should get fixed by #12313, we are working on it.

**Review by citizen428 — APPROVED** [review]

**Comment by rhymes** [comment]
@philipqnguyen I merged #12313, if you'd like go to ahead and merge master in your branch, the issues should be fixed.

Should we add a regression test as well? Currently if your fix gets rearranged for whatever reason there's nothing automatically that fails if the uploader disappears from users without an image. I'm thinking we'd prefer to have something fail if that happens.

A possible way to approach that is to add a test entry to https://github.com/forem/forem/blob/master/spec/requests/user/user_profile_spec.rb to test the two scenario:

1. a request on a user's profile without an image sees the `user[profile_image]` element in its HTML response
2. same thing for a user with a profile image

Thank you!

**Comment by philipqnguyen** [comment]
@rhymes I added the tests in 7c98c58, let me know if you need other changes.

**Review by rhymes — APPROVED** [review]
LGTM!

Thanks @philipqnguyen!

**Pull request merged**
