### PR TITLE
Update admin welcome checklist

### PR DESCRIPTION
**Pull request by Zhao-Andy**
## What type of PR is this? (check all applicable)
- [x] Documentation Update

## Description
This updates the admin welcome checklist according to specifications laid out in https://github.com/forem/internalCommunity/issues/153

image

## QA Instructions, Screenshots, Recordings
1. Go to localhost:3000/admin
2. Check that all the links work

### UI accessibility concerns?
Nope, just basic text and links

## Added/updated tests?
- [x] No, and this is why: change in copy

## [Forem core team only] How will this change be communicated?
- [x] communicated to admins through /admin

### CODE REVIEW

**Review by citizen428 — APPROVED** [review]
Tested locally, all links work. 🎉

**Review by Ridhwana — APPROVED** [review]
Looks good to me 🚀

**Comment by ellativity** [comment]
@Zhao-Andy am I correct in thinking that this is just a Travis CI issue at this point, and the checklist is otherwise good to go?

**Comment by Zhao-Andy** [comment]
Ah thanks for the ping @ellativity, let me fix this test.

**Pull request merged**
