### PR TITLE
Only show user count for large userbases clean up

### PR DESCRIPTION
**Pull request by leewynne**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This applies PR 'Only show user count for large userbases #11021' to app/views/shared/_auth_widget.html.erb

## Related Tickets & Documents

#11021 & #11914

## QA Instructions, Screenshots, Recordings

1. Ensure you are logged out.
2. Refresh and view the auth widget displayed above the navigation links on the left sidebar, it shouldn't have the user count in there, instead, it is only displayed when the large db threshold is met from this method in application_helper.rb

'
def display_estimated_user_count?
    estimated_user_count > LARGE_USERBASE_THRESHOLD
end
'

## Added tests?

- [ ] Yes
- [x] No, as they are used not the original #11021 and this is just a cleanup.
- [ ] I need help with writing tests

## Added to documentation?

- [ ] [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/)
- [ ] README
- [x] No documentation needed

## [optional] Are there any post deployment tasks we need to perform?

No

## [optional] What gif best describes this PR or how it makes you feel?

counting

### CODE REVIEW

**Comment by leewynne** [comment]
I have no idea how the file 'Membership.test.jsx' got in there 🙈

**Review by jacobherrington — CHANGES_REQUESTED** [review]
Let's add that JSX file back in, then this should be good to go! Thanks for catching this Lee :+1:

**Comment by leewynne** [comment]
Hey Jacob! I think it has already been deleted from the master branch, I can't find it.

**Comment by leewynne** [comment]
> Let's add that JSX file back in, then this should be good to go! Thanks for catching this Lee :+1: 

Hey @jacobherrington - I think that jsx file has actually already been deleted from the Forem master branch

**Pull request closed without merging**
