### PR TITLE
✂️  Remove myself from core contributors

### PR DESCRIPTION
**Pull request by citizen428**
## What type of PR is this?

- [X] Documentation Update

## Description

👋 

## How will this change be communicated?

- [X] I will share this change internally with the appropriate teams

## What gif best describes this PR or how it makes you feel?

my work here is done

### CODE REVIEW

**Comment by jeremyf** [comment]
Builds broke, guess you're stuck with us!

**Comment by jeremyf** [comment]
Drat, it's fixed.  I suppose we should merge this.  It has been an absolute privilege working with @citizen428.  Best wishes

**Review by jeremyf — APPROVED** [review]

**Review by msarit — APPROVED** [review]
😭😭😭😭😭😭😭

**Comment by jgaskins** [comment]
And now his watch has ended

**Pull request merged**
