### PR TITLE
Automatically run DataUpdateScripts in development

### PR DESCRIPTION
**Pull request by jgaskins**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

How many times have you pulled down the latest code only to be told "Nope! Run `rails data_updates:run` first"? What if the robots could do that for us?

Honestly I can't believe it took me this long to get fed up with this error :joy: 

## QA Instructions, Screenshots, Recordings

- Delete the record of a random DUS having been executed so that it will be required to run again `psql Forem_development -c 'delete from data_update_scripts where id in (select id from data_update_scripts order by random() limit 1);'`
- Open up a rails console with `rails c`
  - Note the "Running data updates..."
- Exit and `rails c` again
  - No "Running data updates" message because none were pending

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: Even if we wrote tests for it, this code runs before tests execute so we'd have no control case
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [x] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

### CODE REVIEW

**Comment by djuber** [comment]
https://github.com/forem/forem/pull/6068 I don't see any rationale on why we weren't automatically running these in the initial commit (the other commit since then added logging, but the development env check has raised this error since it was added).

**Comment by jgaskins** [comment]
> QA instructions might not actually produce any effect if a DUS had been run (and is present in the db) and removed (I think that's happened at least once). The odds of that are pretty low, and nil if you've reset your db recently.

Yeah, we probably shouldn't be relying on `size` alone, tbh, but instead get the distinct filenames that haven't been run. This is probably another one of those things that sounded "good enough" at the time and we just never changed it.

**Comment by djuber** [comment]
while this does happen for me when I load the server (`bundle exec rails server`) I'm not getting the warning/error successfully when starting pry `bundle exec rails console`.

```ruby
djuber@forem:~/src/forem$ bundle exec rails console
DEBUGGER[-e#2537661]: Attaching after process 2536582 fork to child process 2537661
Running via Spring preloader in process 2537661
Loading development environment (Rails 6.1.4.1)
[1] pry(main)> Rails.const_defined?(Console)
NameError: uninitialized constant Console   
Did you mean?  WebConsole
from (pry):1:in `__pry__'

[2] pry(main)> DataUpdateScript.scripts_to_run?
   (0.6ms)  SELECT "data_update_scripts"."file_name", "data_update_scripts"."status" FROM "data_update_scripts"      
=> true
```

As a side effect, when I checkout your branch and start the console the data updates don't run. They _do_ run when I start a server (and I was getting the error when I started the server as well).


```
djuber@forem:~/src/forem$ gh pr checkout 15489
Branch 'automate-dus-in-development' set up to track remote branch 'automate-dus-in-development' from 'origin'.
Switched to a new branch 'automate-dus-in-development'
djuber@forem:~/src/forem$ bundle exec rails console
DEBUGGER: Attaching after process 2537839 fork to child process 2537890
Running via Spring preloader in process 2537890
Loading development environment (Rails 6.1.4.1)
[1] pry(main)> DataUpdateScript.scripts_to_run?   (0.6ms)  SELECT "data_update_scripts"."file_name", "data_update_scripts"."status" FROM "data_update_scripts"      
=> true
```

Server is good - runs once, not the second time:

```

djuber@forem:~/src/forem$ bundle exec rails s
=> Booting Puma
=> Rails 6.1.4.1 application starting in development 
=> Run `bin/rails server --help` for more startup options
Running data updates...
[2537910] Puma starting in cluster mode...

^C[2537910] - Gracefully shutting down workers...
[2537910] === puma shutdown: 2021-11-24 11:05:17 -0600 ===
[2537910] - Goodbye!
Exiting
djuber@forem:~/src/forem$ bundle exec rails s
=> Booting Puma
=> Rails 6.1.4.1 application starting in development 
=> Run `bin/rails server --help` for more startup options
[2537976] Puma starting in cluster mode...
```

**Comment by jgaskins** [comment]
> `Running via Spring preloader in process 2537661`

@djuber Could this be why it's not happening for you in the console? I have `DISABLE_SPRING=true` in my shell config because of weird inconsistencies like this on app load. Spring is a lot faster, but I lose all that time and more during the existential crisis that comes from not understanding why my changes don't show up sometimes.

**Comment by djuber** [comment]
@jgaskins  - sure enough, disabling spring made it work as described.

**Review by djuber — APPROVED** [review]

**Comment by jgaskins** [comment]
@djuber I wonder if there's a way to make it work _with_ spring since that's the default. 🤔 Unfortunately, I don't know enough about it and this check was never blocking app load if Spring had the environment preloaded anyway, so I'm not sure it needs to be solved in this PR specifically.

**Review by jeremyf — APPROVED** [review]

**Pull request merged**
