### PR TITLE
Add constraints that are in the production DB

### PR DESCRIPTION
**Pull request by jgaskins**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Several PRs have come in with unnecessary changes to `db/schema.rb` due to the fact that the state of that file and the state of the database have diverged and git optimizes for committing files wholesale — you have to explicitly tell it _not_ to do that every time.

I pulled down the schema from DEV's production DB and ran `rails db:migrate` to find out what changes need to be made and whether the state of development and production DBs have diverged. Surprisingly, most folks' development DBs and DEV's production DB are more aligned than this file is with either one, so this PR fixes that. Hopefully, with this change, we can stop asking people to remove their changes to `db/schema.rb`, at least for a while.

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: Simple DB schema alignment
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://admin.forem.com/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [x] This change does not need to be communicated, and this is why not: After this is merged, it will be as everyone already expects it to be

## [optional] What gif best describes this PR or how it makes you feel?

Alignment

### CODE REVIEW

**Comment by msarit** [comment]
Looks good to me @jgaskins but question: would we need to cut PRs like this each time this divergence happens?

**Comment by jgaskins** [comment]
@msarit Indeed. Ideally it shouldn't happen and the fact that it seems to have only happened with these two lines seems to indicate that we've done pretty well with the upkeep and haven't diverged much. This was likely just a fluke that snuck in past code review.

**Comment by jgaskins** [comment]
Also I'm not sure how `pg_stat_statements` wasn't added because I use it pretty much all the time. 😄 Maybe it was added by Heroku when the DB was created originally back in like 2016, but honestly it's a good thing to have in general to be able to look at running queries and index history, and if we ever add any sort of introspection for running queries at the DB layer (to terminate runaway queries, for example), we'll want to ensure that extension is installed.

**Review by msarit — APPROVED** [review]

**Review by citizen428 — APPROVED** [review]
Thanks for doing this @jgaskins 👏

**Review by rhymes — APPROVED** [review]
Awesome!!

**Pull request merged**
