### PR TITLE
Add auto-remove .o native extension rake task

### PR DESCRIPTION
**Pull request by maestromac**
## What type of PR is this? (check all applicable)
- [x] Bug Fix

## Description
Our Heroku Slug size is currently 348.2 MiB of 500 MiB. It's good but could better.  One of our gem `sassc-ruby` currently includes 160MB of binary that we don't need. This PR removes it during the Heroku asset cleanup step.

Update: This changes drop our slug size to 278.3M

## Related Tickets & Documents
follow up to https://github.com/forem/forem/pull/12372
## QA Instructions, Screenshots, Recordings
n/a

### UI accessibility concerns?
n/a

## Added tests?
- [x] No, and this is why: this touches CD side

## [Forem core team only] How will this change be communicated?
- [x] I will share this change internally with the appropriate teams

## [optional] Are there any post-deployment tasks we need to perform?
I will closely monitor staging first

### CODE REVIEW

**Review by rhymes — APPROVED** [review]
Worth giving it a try, though I notice [this comment](https://github.com/sass/sassc-ruby/issues/200#issuecomment-821980839):

> The workaround didn't make the job for me, it doesn't run during the build. Even deleting everything manually didn't work to reduce de slug size during build.

**Comment by maestromac** [comment]
@rhymes I have tested this on BHC and verified it on Heroku that it does indeed work. see https://travis-ci.com/github/forem/forem/builds/224410232#L1491

**Review by djuber — APPROVED** [review]

**Comment by djuber** [comment]
https://buildkite.com/forem/build-containers/builds/4616#3cc563f7-faf8-4ef3-bd01-f2b0b75e23a9 last build failure looks like it was other people's problems, not yours.

**Comment by maestromac** [comment]
well gosh darn it, it doesn't seem to have an impact on DEV :(

**Comment by maestromac** [comment]
I manually check DEV's slug and I don't see `sassc` binary in there. Either this worked or it was removed by something else this whole time. Either way, I'm going to stop pursuing this for now.

**Pull request merged**
