### PR TITLE
Design fixes for badges

### LINKED ISSUE #18453: Bugs found in Profile Badges work on production
**Describe the bug**

There are multiple minor bugs found in profile badges work on production.

**To Reproduce**

### Issue 1

Visit https://dev.to/amyatforem and click on `1` badge and notice how its stretched.

Screenshot 2022-09-14 at 3 29 36 PM

### Issue 2

Visit https://dev.to/thepracticaldev and inspect the badges grid and notice that the width of each item is grid is not exactly same.

Screenshot 2022-09-14 at 3 30 06 PM  Screenshot 2022-09-14 at 3 30 13 PM

### Issue 3
This is hard to show here but locally I have reproduced it. If there are six or more badges, the `sixth` badge won't be visible.

### Issue 4
Stretched images in https://dev.to/badges and also when we click on any badge inside modal too.

Screenshot 2022-09-14 at 12 58 01 PM

**Expected behavior**

- The grid items should have same width.
- Images should not get stretched

### PR DESCRIPTION
**Pull request by rt4914**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

This PR focuses on covering all the edge cases identified in production for https://dev.to/badges page and user profiles.

### Issue 1

Visit https://dev.to/amyatforem and click on `1` badge and notice how its stretched.

Screenshot 2022-09-14 at 3 29 36 PM

### Issue 2

Visit https://dev.to/thepracticaldev and inspect the badges grid and notice that the width of each item is grid is not exactly same.

Screenshot 2022-09-14 at 3 30 06 PM  Screenshot 2022-09-14 at 3 30 13 PM

### Issue 3
This is hard to show here but locally I have reproduced it. If there are six or more badges, the `sixth` badge won't be visible.

### Issue 4
Stretched images in https://dev.to/badges and also when we click on any badge inside modal too.

Screenshot 2022-09-14 at 12 58 01 PM

### Solution 1

This has been solved by using `object-fit: contain` property on all images

Screenshot 2022-09-14 at 3 06 43 PM Screenshot 2022-09-14 at 3 06 50 PM

### Solution 2

This has also been solved making sure that all items in a grid on profile badge do have same width.

Screenshot 2022-09-14 at 3 39 21 PM
Screenshot 2022-09-14 at 3 39 30 PM

### Solution 3

All the images are now visible. This was an issue because of one CSS Style `media-card--all` which has been removed now.
Earlier it was showing only 6 images locally and after removing this class all seven badges are visible.

Screenshot 2022-09-14 at 3 41 03 PM

### Solution 4

This has been solved by using `object-fit: contain` property on all images

Screenshot 2022-09-14 at 3 42 05 PM

## Related Tickets & Documents

- Related Issue #18453
- Closes #18453

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

No

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: this PR is purely UI based
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [x] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

### CODE REVIEW

**Comment by rt4914** [comment]
Apart from these issues I have also notice issues on Safari Version 14 because it does not support aspect-ratio (Safari Version 15 works perfect) but for this I have filed it separately as it needs to be solved in other places too. #18452

**Review by jaw6 — APPROVED** [review]
Non-blocking question: Would it be valuable to move these style changes into a class?

**Review by Ridhwana — APPROVED** [review]
+1 on Joshuas comment: 
> Non-blocking question: Would it be valuable to move these style changes into a class?

**Comment by rt4914** [comment]
Changes mentioned by @jaw6 has been done. But blocking merge on clarification mentioned here. https://www.loom.com/share/1827429f9d844d46abdf9a9e218eca34

**Comment by rt4914** [comment]
> Changes mentioned by @jaw6 has been done. But blocking merge on clarification mentioned here. https://www.loom.com/share/1827429f9d844d46abdf9a9e218eca34

Conclusion: We have removed the `gray` shade for un-achieved labels completely and also filed an issue to track this in future https://github.com/forem/forem/issues/18495

**Pull request merged**
