### PR TITLE
Add --spec option for data_update generator

### PR DESCRIPTION
**Pull request by citizen428**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [X] Documentation Update

## Description

During my recent profile generalization work, I had to write quite a few data update scripts and got tired of adding the corresponding specs manually. I decided to add `--spec` / `--no-spec`options to the generator, with `--spec` being the deafault:

```
❯ rails generate data_update -h
Usage:
  rails generate data_update NAME [options]

Options:
  [--skip-namespace], [--no-skip-namespace]  # Skip namespace (affects only isolated applications)
  [--spec], [--no-spec]                      # Indicates when to generate spec
                                             # Default: true
[output snipped]
```

The generated specs are simple and follow our current conventions. The included message is borrowed from Rails' default generators:

```ruby
require "rails_helper"
require Rails.root.join(
  "20201103044008_do_the_thing.rb",
)

describe DataUpdateScripts::DoTheThing do
  pending "add some examples to (or delete) #{__FILE__}"
end
```

I also noticed that our generator doesn't play nicely with `rails destroy data_update`: since we prepend the timestamp to the filename during runtime it will yield a different value on `destroy` vs `generate` and the file won't actually get removed. It works for the newly added specs though, as those use stable filenames. I made a mental note of looking into this during the next downtime, the Rails migration generator should have clues on how to handle this case properly.

## Related Tickets & Documents

n/a

## QA Instructions, Screenshots, Recordings

1. Run `rails generate data_update DoSomething` and verify that the script and spec were created and have the right content.
2. Run `rails generate data_update DoSomethingElse --no-spec` and verify that the script gets created as expected but the spec doesn't.

## Added tests?

- [ ] Yes
- [X] No, and this is why: we didn't have any tests for this yet and I want to go back to writing the actual data update script that prompted this. I did make a mental note to add specs for the whole generator during the next cooldown period.
- [ ] I need help with writing tests

## Added to documentation?

- [X] Docs.forem.com
- [ ] README
- [ ] No documentation needed

### CODE REVIEW

**Review by rhymes — APPROVED** [review]
Works well, cool!

**Review by mstruve — APPROVED** [review]
SO AWESOME!!! Thanks @citizen428!

**Review by maestromac — APPROVED** [review]
Love it!

**Comment by vaidehijoshi** [comment]
This is rad! Thanks for taking the initiative and building this out for all of us to use, @citizen428! ❤️

**Pull request merged**
