### PR TITLE
Removing bootstrap from Config's collapsable sections

### PR DESCRIPTION
**Pull request by ludwiczakpawel**
## What type of PR is this? (check all applicable)

- [x] Refactor

## Description

This PR is another step towards removing Bootstrap dependency. This one focuses mainly on "Config" area - which contains lots of collapsable sections with forms. To drop that bootstrap dependency I decided to use `<details>` HTML element which basically provides the same collapsing possibilities. This may not be ideal from from design and accessibility point of view however Product/Design is actively working on updating this entire section so we will eventually remove `details` (and generally collapsible sections) entirely, and for now removing Bootstrap dependency just felt more important.

It may seem like a big PR because it updates a lot of files but that's because each section on that view is in a separate partial. But the main change is basically the same across all of them.

## QA Instructions, Screenshots, Recordings

Hopefully it all works as previously.

**Before:** 

image

**After:**

image

### UI accessibility concerns?

n/a

## Added/updated tests?

- [x] I need help.

### CODE REVIEW

**Review by nickytonline — COMMENTED** [review]
Yay for the `<details />` tag. 🥳

**Comment by nickytonline** [comment]
I'll take a peek at tests for this later today @ludwiczakpawel

**Comment by ludwiczakpawel** [comment]
@nickytonline isn't that what @aitchiss has done?

**Review by aitchiss — APPROVED** [review]

**Review by nickytonline — APPROVED** [review]
✂️🚀

**Pull request merged**
