### PR TITLE
Change "posted on" to "scheduled for" on the scheduled articles preview page

### PR DESCRIPTION
**Pull request by lightalloy**
## What type of PR is this? (check all applicable)

- [x] Feature
- [x] Bug Fix

## Description
Change "posted on" to "scheduled for" on the scheduled articles preview page

## Related Tickets & Documents
- Related Issue #17939 

## QA Instructions, Screenshots, Recordings
- enable the feature flag `FeatureFlag.enable(:schedule_articles)`
- create an article scheduled to the future
- the preview page should include "Scheduled for {published_at}" instead of "Posted on {published_at}"
- for articles, published in the past, the page should include "Posted on {published_at}" (as before the changes)

изображение

## Added/updated tests?
- [x] Yes

## [Forem core team only] How will this change be communicated?
- [x] I will share this change internally with the appropriate teams

### CODE REVIEW

**Review by Ridhwana — APPROVED** [review]

**Review by aitchiss — APPROVED** [review]
I do wonder if "Scheduled to .. " is the right phrase 🤔 I'm not totally sure but I feel like "Scheduled for .. " sounds more intuitive to me.

IDK, like I say I'm not sure either way 😆

**Comment by lightalloy** [comment]
@aitchiss I have read [this](https://english.stackexchange.com/questions/101640/scheduled-to-vs-scheduled-for) and vote for "Scheduled for" :D

**Comment by aitchiss** [comment]
Oh this is an interesting explanation @lightalloy! Thanks for sharing - I've learned something today 😄

**Comment by lightalloy** [comment]
@aitchiss Thanks for pointing this out :)

**Pull request merged**
