### PR TITLE
Adjusting conditional create post rendering

### PR DESCRIPTION
**Pull request by jeremyf**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Optimization?

## Description

This pull request does two things:
    
- Reverts the forem/forem#16606
- Replaces the conditional rendering with the approach from forem/forem#17076
    
What to consider:
    
- How does this impact Cumulative Layout Shift (CLS).  Prior to this
  commit, we didn't "flicker" the "Create Post" button into view if the
  site didn't have the conditional.
- In reverting forem/forem#16606 we remove a dependency on Turbo.
- We reduce one network call, relying instead on the async_info to carry
  the visible/hidden logic.
    
If the "flicker" is a problem we could add a conditional in the page for
if the site has enabled that feature.  However, that's a place holder as
we're looking at possible other reasons for allowing/disabling the
create a post.
    
This is a non-blocking PR, as in we can merge or not merge this and
proceed with what we have.  Instead the main goal is to "unify" our approach.

## Related Tickets & Documents

Related Issues:

- forem/forem#16606
- forem/forem#16490

## QA Instructions, Screenshots, Recordings

Following https://docs.google.com/document/d/1M_a6hJZM1KuBZ_--dqNQS5oLUqYvVGINas6o-gxZZEo/edit

### UI accessibility concerns?

See the "Flicker" concern above.

## Added/updated tests?

- [x] Yes

## [Forem core team only] How will this change be communicated?

- [x] I will share this change internally with the appropriate teams

### CODE REVIEW

**Review by aitchiss — COMMENTED** [review]
In this case, there's no CLS because the header "reserves" the same amount of height regardless of the link's existence. So although the 'Create Post' link pops into view a short time after the main header is rendered, the header height never changes 🙂  

Whether the dynamic appearance of the link is desirable or not is I guess a different question. For me, I don't see a problem, and there are other places we do vaguely similar things - e.g. comment 'subscribe' button on a post page dynamically turns into a richer 'manage subscription' button if the user is already subscribed. However, this is our "main" CTA throughout the app, so I wonder if others will have feelings about this. 

I definitely anticipate future challenges with this approach and CLS. For example, if we want to use this approach to hide "Posts", "Followers" etc on the dashboard, I think that is going to require a UI reshuffle. Those kinds of reshuffles will need design input and might be more work to achieve than the turbo-powered solution which toggles the visibility of items on the server side.

I guess I am wondering what we see as the future for "Spaces", and how granular these policies are going to be. The "worst case scenario" I'm thinking about is us having multiple policies active on a Forem, and having to anticipate layout shift for all the permutations of their hidden/visible states.

**Comment by jeremyf** [comment]
> I definitely anticipate future challenges with this approach and CLS. 

Yup.  And our upcoming AuthN/AuthZ work could have more impact.

> For example, if we want to use this approach to hide "Posts", "Followers" etc on the dashboard, I think that is going to require a UI reshuffle.

Good news on this front, that part is not cached, so the server sends the page without need for alteration.

> Those kinds of reshuffles will need design input and might be more work to achieve than the turbo-powered solution which toggles the visibility of items on the server side.

The turbo-powered solution still introduces the "flicker" but Dwight put a short-circuit in; namely if the flag is disabled, use the prior approach.  Toggling on the feature introduces the flicker.

https://github.com/forem/forem/blob/eef989cabf01b317bf00cbf1bb0787b49a66bfb1/app/views/layouts/_top_bar.html.erb#L32-L37

**Comment by jeremyf** [comment]
I'm going to close this PR for now, as I have another chunk of code to send forward that will improve the approach for this PR.

**Comment by jeremyf** [comment]
I re-opend this PR given another path proved to create notable resistance.

**Review by dscottS3 — APPROVED** [review]
It's been real, Turbo/Hotwire ✌️

**Comment by jeremyf** [comment]
I suspect we'll see Turbo once again some day soon.  It's super useful.

**Review by aitchiss — APPROVED** [review]
Looking good!

**Pull request merged**
