### PR TITLE
Add style to right side bar to allow for scrolling

### PR DESCRIPTION
**Pull request by lyqht**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

With this PR, a scrollbar will appear for the article right sidebar if the sidebar exceeds the height of the layout.
The scrollbar won't appear for sidebars that do not exceed the length.

## Related Tickets & Documents

Fixes issue #14806. 

## QA Instructions, Screenshots, Recordings

On Desktop
image

On mobile
Right side bar does not show up.

### UI accessibility concerns?

Don't think so, I tried not to change the original layout.

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: I don't know if the scroll behavior can be tested or not
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Review by ludwiczakpawel — CHANGES_REQUESTED** [review]
I can totally see where this is coming from and WHY it is done this way but I'm not 100% convinced this is the right solution for given problem. I believe, the ideal solution in our case would be replicating behavior of Twitter which you can preview in video below:

https://user-images.githubusercontent.com/108287/135900909-2cd11f62-352f-42ca-a71d-f17767f5c9ab.mov

(Ignore the sticky search bar) 
Whenever necessary (small viewport height), it basically scrolls WITH entire viewport for the initial part of scrolling event and then it just sticks - no matter which direction. Unfortunately I believe it's not just CSS but also JS however it's way better than providing a separate scroll for sidebar. 

(I'm adding this comment to the issue itself as well)

**Comment by lyqht** [comment]
@ludwiczakpawel ohh I see, alright I'll try to look around to see how to achieve this. 😊

**Comment by lyqht** [comment]
Spent quite long to come up with a way so that the side bar sticks to the bottom and still scroll up smoothly.
Here's what I manage to do so far.

scroll-down-fixed-but-scrollup-has-issue

- I made the sidebar to be fixed position whenever the last child element is present completely in the viewport
- I have tried to make the sidebar remain as "fixed" while moving up as you scroll up, however, I'm not sure why it moves up lesser than the scroll vertical distance detected -> so it is seen completely in the viewport before it aligns top with the article.
- I also thought to remove the "fixed" styling once the profile card comes back into view aligned with the article at the top,
so this lead to a weird situation where you see a part where the profile card just jumps up to the top once it shows completely in the viewport.
- While making this comment, I also realized that maybe I shouldn't remove the "fixed" styling, because if we follow the Twitter sidebar, on Forem the profile card will stay at the top even if we keep scrolling up before we reach the top of the article.

Need some guidance on whether I'm on the right path for implementing this or if I'm complicating the solution 🤣
Also, please let me know if I shouldn't call the utility function under `initializeDrawerSliders.js`, wasn't sure if I should make a new initializer file just use an existing one.

**Comment by ludwiczakpawel** [comment]
There's something off when I now test it:
- depending on how "fast" I scroll up or down it behaves differently and that happens even on resolutions that can easily fit the sidebar - it almost feels like the function is too "slow" to keep up the pace of scrolling. I think that's related to your question about 
- We should only call this function if sidebar content is taller than available space in viewport - that will prevent some randomness in behavior.
- I somehow managed to make the sidebar disappear. Don't ask me how - it was pretty random :)
- For smaller breakpoints we don't hide the sidebar - we drop it below the content so it's still there, therefore it behaves a bit weird in these breakpoints too (I can see its jumping) - so there should be another IF statement for that.
- One thing to keep in mind that will probably affect your function is that we let users customize whether the page header should be sticky or not - this affects padding on body and other calculations for sticky elements.

So to answer your question: I think the path (end goal) is probably correct but in regards to implementation it's still not bullet-proof enough and feels pretty complex :) (but hey, maybe it needs to be complex in order to be bullet-proof).

I'm not 100% sure how else I could guide you here, so please do let me know how can I help.

**Comment by lyqht** [comment]
@ludwiczakpawel , thanks for helping to test and giving many helpful hints! 

I have added if statements for addressing the points you mentioned:
- if sidebar content is taller than available space in viewport
- if is mobile

The point that you made about the scrolling can't keep up made me looked into improving performance scroll event listeners - and the common solution given is to use throttling, so I added a simple throttle function for that, it seems to help. 

> Ideally we use lodash.throttle package instead of this vanilla js, but when I tried importing the package with `import throttle from 'lodash.throttle`, the function `makeRightSidebarBottomSticky` function gets ignored. I don't really understand how the function is being used previously by just declaring it as a global function in an initializer file, without having to export it. Tried referring from `debounceAction.js` but I still didn't understand.

With some logic changes, I think the possibility of the sidebar "disappearing" has also been removed. 

But now, I'm facing troubles where the sidebar turns "unsticky" earlier than it reaches the top of the article, you can refer to the variable `reachedTopOfArticle` in the file. Not really sure how to ensure this.

**Comment by lyqht** [comment]
thank you @aitchiss for introducing this web api to me, it really does feel a lot more performant ✨ would love to collaborate with you to get this sidebar working as intended! would you like to merge into my current branch for your changes first?

**Comment by aitchiss** [comment]
Hey @lyqht - I've created a PR into your branch 🙂  The code is very "work in progress", but hopefully you'll be able to build on it. Have a look and let me know what you think / see how you get on with it.

**Comment by lyqht** [comment]
hi @aitchiss, following the web api approach, to replace the previous logic checks for 
```
  const isMobileDevice = screen.width <= 480;
  const sidebar = document.getElementById('sidebar-content');
  const sidebarShowsEntirelyInViewport = isCompletelyVisible(sidebar);

  if (sidebarShowsEntirelyInViewport || isMobileDevice) {
    return;
  }
```

i added the resize observer that only makes the intersection observer observe the sidebar only when the height of the sidebar exceeds the viewport. This behavior seems to work correctly on Google Chrome. 

However, I wanna raise a concern before we continue to implement the scrolling up logic. I was looking into the Web API observers and there are browser compatibility issues. I.E. will not work entirely, and it did not work on my usual development browser Firefox Developer Edition 94.0b9. I'm not sure if this will be a problem for other Firefox users of Forem.

**Comment by aitchiss** [comment]
> i added the resize observer that only makes the intersection observer observe the sidebar only when the height of the sidebar exceeds the viewport. This behavior seems to work correctly on Google Chrome.
> However, I wanna raise a concern before we continue to implement the scrolling up logic. I was looking into the Web API observers and there are browser compatibility issues. I.E. will not work entirely, and it did not work on my usual development browser Firefox Developer Edition 94.0b9. I'm not sure if this will be a problem for other Firefox users of Forem.

Thanks for raising this concern! I'm not sure if you need to use the ResizeObserver API - using IntersectionObserver should be fine, even if the viewport size changes, since the callback will only be triggered when the proportion of the sidebar which is visible changes - e.g. if it is always fully visible, the callback is never triggered.

Is there a bug/situation you were finding you needed ResizeObserver for?

We don't support IE, but Firefox should be compatible with both ResizeObserver and IntersectionObserver APIs, so that does sound strange that you had issues. Do you see errors in your console in Firefox?

**Comment by lyqht** [comment]
> > i added the resize observer that only makes the intersection observer observe the sidebar only when the height of the sidebar exceeds the viewport. This behavior seems to work correctly on Google Chrome.
> > However, I wanna raise a concern before we continue to implement the scrolling up logic. I was looking into the Web API observers and there are browser compatibility issues. I.E. will not work entirely, and it did not work on my usual development browser Firefox Developer Edition 94.0b9. I'm not sure if this will be a problem for other Firefox users of Forem.
> 
> Thanks for raising this concern! I'm not sure if you need to use the ResizeObserver API - using IntersectionObserver should be fine, even if the viewport size changes, since the callback will only be triggered when the proportion of the sidebar which is visible changes - e.g. if it is always fully visible, the callback is never triggered.
> 
> Is there a bug/situation you were finding you needed ResizeObserver for?
> 
> We don't support IE, but Firefox should be compatible with both ResizeObserver and IntersectionObserver APIs, so that does sound strange that you had issues. Do you see errors in your console in Firefox?

Oh I see! I think I confused myself when I was testing the intersectionobserver on firefox developer edition on mobile, and thought that it didn't work and then added up adding the resizeobserver. I don't see any errors on the Firefox Developer edition browser on either observers so I can't really add on much information beyond the browser version that I used.

And secondly - I would like to drop off this PR as I'm getting too busy with my other work commitments. Really appreciate the help that both of you have provided me, it's unfortunate that I couldn't see till the end for this bug fix.

**Comment by aitchiss** [comment]
> And secondly - I would like to drop off this PR as I'm getting too busy with my other work commitments. Really appreciate the help that both of you have provided me, it's unfortunate that I couldn't see till the end for this bug fix.

No worries @lyqht - I totally understand! Thank you for getting us as far along with this issue as you have - I'll close this PR for now, and make a note on the issue so that whoever picks this up next can continue to build on your solution.

Thanks again 🌟

**Pull request closed without merging**
