### PR TITLE
Polish tag UI

### LINKED ISSUE #20037: Collaborate with design on the c-btn for the tags UI
Related to [Hide tag weights and change negative weight tags to "Hidden tags" #19675
](https://github.com/forem/forem/issues/19675)

This issue is mainly to get some clarity and figure out how to best align the design to our current button component.

### PR DESCRIPTION
**Pull request by Ridhwana**
Build is failing on main as well.

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

@anujbhavsar96 this video is mainly to figure out from you how we can update the "Following" tag button
https://www.loom.com/share/d986b0a52d674ae7a950dcf02d8ac3a7?sid=3dd0a30a-395d-454a-85cd-c5009f32b15f.

In addition could you possibly look through /tags, dashboard/following_tags, dashboard/hidden_tags and let me know if we need any tweaks.

## Related Tickets & Documents

- Related Issue #https://github.com/forem/forem/issues/20037
- Closes #20037 

## QA Instructions, Screenshots, Recordings
Look through  /tags, dashboard/following_tags, dashboard/hidden_tags and ensure it aligns with design.

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [axe DevTools](https://www.deque.com/axe/) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

_For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [ ] Yes
- [x] No, UI changes
      have not been included_
- [ ] I need help with writing tests

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by anujbhavsar96** [comment]
Thanks for the Loom, @Ridhwana, I feel like we can keep using the `crayons-btn--outlined` for now, which is consistent with other following buttons on the platform. All other things look great.

We can make this `c-btn` change later when we clean up the design system components.

**Review by anujbhavsar96 — APPROVED** [review]
LGTM!!

**Review by dukegreene — APPROVED** [review]
It looks clean and crisp on my end! Very cool!

**Review by rt4914 — APPROVED** [review]
LGTM. 💯

**Pull request merged**
