### PR TITLE
i18n: Translate core Create and Manage

### PR DESCRIPTION
**Pull request by KrystalJean**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
I followed existing patterns of internationalization from my previous merged commits.  Please let me know if this should be under views instead of core, and I can change this.
## Related Tickets & Documents
This PR references issue "Internationalize Hardcoded Display Text #14888".

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility concerns?
None
_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why:Existing tests should suffice.
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by yheuhtozr** [comment]
The two strings are already covered by #15040.

**Comment by citizen428** [comment]
Ok, thanks for the heads-up @yheuhtozr! 

@KrystalJean Thanks a lot for your contribution, unfortunately, it seems like we'll have to close this PR since an earlier one already translated the same strings.

**Comment by citizen428** [comment]
@KrystalJean You can add them as suggestions in the other PR.

**Comment by yheuhtozr** [comment]
@KrystalJean Due to technical reasons (my GitHub repo is just a mirror), anything we add to my PR via GH won't be likely to last long. If you are planning to add something based on my contributions, I think opening a PR that overwrite my locale files (under `config/locales/views`) would be better.

**Comment by KrystalJean** [comment]
Ok @yheuhtozr thanks for letting me know. So, I will make my own pull request.  Should I reference your pull request in mine?

**Pull request closed without merging**
