### PR TITLE
Add comment to a few gems

### PR DESCRIPTION
**Pull request by heliocola**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation (comments in Gemfile) Update

## Description
Added comment to the following gems:
* "flipper-ui"
* "omniauth-google-oauth2"
* "yard-activerecord"
* "yard-activesupport-concern"

## Related Tickets & Documents
None

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings

None

### UI accessibility concerns?

None

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: the changes in this PR only add a comment to the gems listed above in the Gemfile, to adhere with its current standard.
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

No impact

## [optional] Are there any post deployment tasks we need to perform?

No

### CODE REVIEW

**Review by fdocr — APPROVED** [review]
Thank you for the contribution @heliocola. LGTM

**Review by Ridhwana — APPROVED** [review]
Thanks @heliocola!

**Comment by heliocola** [comment]
I noticed yesterday that there is a missing gem for dev group: `foreman`.
`bin/startup` uses it.
If it helps, I can add it to Gemfile and puth to this PR.
Or wait until this gets merged (to avoid possible conflict in Gemfile).

**Comment by Ridhwana** [comment]
> I noticed yesterday that there is a missing gem for dev group: `foreman`. `bin/startup` uses it. If it helps, I can add it to Gemfile and puth to this PR. Or wait until this gets merged (to avoid possible conflict in Gemfile).

Hi @heliocola 👋🏽 Thanks for this, I'll be merging it soon. Let's add foreman to a separate PR.

**Pull request merged**
