### PR TITLE
Make confirmation text a required field

### PR DESCRIPTION
**Pull request by jacobherrington**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Right now, you can submit the config form without including the required confirmation text. When you do this, it's a bit frustrating because it's such a large form and you can lose your inputs. 

~Also, this returns an unauthorized status which isn't really true because you can hit this error with all the necessary permissions, so I changed it to return a 422 (unprocessable entity) because most accurately (imo) you're missing a required parameter.~

This change now includes both frontend validation and more specific error messaging for the backend validation.

## Added tests?

- [x] yes
- [ ] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Review by Ridhwana — CHANGES_REQUESTED** [review]
@jacobherrington when I click Submit, it's showing me the json error as per my screenshot. Are you seeing different behaviour?

Screenshot 2020-08-26 at 15 02 48

**Comment by jacobherrington** [comment]
@Ridhwana Does this happen when you input the confirmation text correctly, or if you remove the required attribute and submit?

**Comment by Ridhwana** [comment]
> @Ridhwana Does this happen when you input the confirmation text correctly, or if you remove the required attribute and submit?

It happens when I enter the confirmation text incorrectly.

**Comment by jacobherrington** [comment]
@Ridhwana Yeah! It looks like there is a spec failure regarding the same issue. I'll look into it. thanks :smiley:

**Comment by jacobherrington** [comment]
@Ridhwana I just pushed a commit that will still fail CI, but I'm curious if you think this approach is better? It raises more specific errors that describe the missing or incorrect parameter.

**Comment by Ridhwana** [comment]
> @Ridhwana I just pushed a commit that will still fail CI, but I'm curious if you think this approach is better? It raises more specific errors that describe the missing (I used params.require() which should handle that case) or incorrect parameter (I used a BadRequest error, which may not be perfect, but it's pretty close without defining a custom error for this one case).

I think this is much better than what we had before this PR.

**Comment by Ridhwana** [comment]
A win in terms of user experience for me would be to make it more dynamic and treat it just like a field validation. i.e. when I enter the correct confirmation text I should be able to stay on the same page with all my info still entered (if possible) and a little red notice pop up to say that I entered the confirmation text incorrectly. But, that seems more complicated and I feel like this is good for now.

**Comment by jacobherrington** [comment]
@Ridhwana Updated to do exactly that!

It should now also pass specs and the improved error messages will help if frontend validation fails.

**Review by Ridhwana — APPROVED** [review]
@jacobherrington this solution looks and works great 😊, its so much more intuitive *and* the user doesn't lose their information or get navigated away from the page 🎉

The one point that I do want to mention is that previously they would have to provide their username, but now we're showing them their username by default, so they can essentially just copy and paste the sentence as is. I'm not sure if it was by design to not show their username in that prompt initially? but I don't see any real harm in this and I've approved.

**Pull request merged**
