### PR TITLE
Add im-in.space Mastodon instance

### PR DESCRIPTION
**Pull request by dar5hak**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix (I guess?)
- [ ] Optimization
- [ ] Documentation Update

## Description

I added https://im-in.space, a Mastodon instance, to the list of allowed instances.

## Related Tickets & Documents

#7981 

## QA Instructions, Screenshots, Recordings

NA

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by dar5hak** [comment]
Huh. I don't know how I managed to break the post editor by changing the Mastodon instance list, but this failed:

```
Failures:

  1) Creating an article with the editor with Runkit tag previews article with a Runkit tag and creates it

     Failure/Error: expect(page).to have_css(".runkit-element iframe", count: count)

       expected to find css ".runkit-element iframe" 1 time but there were no matches

     

     [Screenshot]: /home/travis/build/forem/forem/tmp/screenshots/failures_r_spec_example_groups_creating_an_article_with_the_editor_with_runkit_tag_previews_article_with_a_runkit_tag_and_creates_it_387.png
```

and so did this:

```
Failures:

  1) Editing with an editor user unpublishes their post

     Failure/Error: expect(page).to have_text("Unpublished Post.")

       expected to find text "Unpublished Post." in "Write a post\nSetup not completed yet, missing main social image, logo png, logo svg, and others. Please visit the configuration page.\nHeart\n0\nUnicorn\n0\nSaved\n0\nMore...\nSample Article\n#test\nSandy Williamson\nOct 12 ・1 min read\nEditManage\nSuspendisse ac lobortis velit, a feugiat sapien. Aenean condimentum, nulla at fermentum sagittis, tellus nisi suscipit velit, vel sollicitudin odio ligula a odio. Integer eget efficitur massa, in sodales velit. Nunc fermentum consequat scelerisque. Morbi elementum tristique faucibus. Nulla vel lectus non justo euismod varius. Vivamus id nisl sit amet odio tincidunt fringilla. Pellentesque odio odio, vulputate in risus eu, lacinia porttitor lorem. Nunc posuere tempus est, imperdiet suscipit odio maximus id. Nam eget feugiat magna.\ntitle: Sample Article\npublished: false\ndescription: this is a sample article\ntags: test\nSuspendisse ac lobortis velit, a feugiat sapien. Aenean condimentum, nulla at fermentum sagittis, tellus nisi suscipit velit, vel sollicitudin odio ligula a odio. Integer eget efficitur massa, in sodales velit. Nunc fermentum consequat scelerisque. Morbi elementum tristique faucibus. Nulla vel lectus non justo euismod varius. Vivamus id nisl sit amet odio tincidunt fringilla. Pellentesque odio odio, vulputate in risus eu, lacinia porttitor lorem. Nunc posuere tempus est, imperdiet suscipit odio maximus id. Nam eget feugiat magna.\nPosted on Oct 12 by:\nSandy Williamson\n@username2213\nNobis dicta eveniet. Sint reprehenderit nemo. Doloribus quia ea.\nEdit profile\nTwitter\nGitHub\nWebsite\nDiscussion\nSubscribe\nCode of Conduct • Report abuse\nRead next\nSome description\nDEV(local) Community copyright 2020\nBuilt on Forem — the open source software that powers DEV and other inclusive communities.\nMade with love and Ruby on Rails.\nHome\nReading list\nListings\nPodcasts\nVideos\nTags\nWrite a post\nCode of Conduct\nFAQ\nAbout\nPrivacy policy\nTerms of use\nContact\nSponsors"

     

     [Screenshot]: /home/travis/build/forem/forem/tmp/screenshots/failures_r_spec_example_groups_editing_with_an_editor_user_unpublishes_their_post_145.png
```

**Review by rhymes — APPROVED** [review]
Hi @dar5hak, thanks for the change!

Unfortunately that's a flakey spec, I'll restart the build

**Comment by dar5hak** [comment]
Thanks @rhymes! The second spec passed, but the first one failed again.

**Comment by rhymes** [comment]
@dar5hak I merged master in which contains #10806 that should fix the failing spec. Thank you for the patience :)

**Comment by dar5hak** [comment]
Thanks a lot @rhymes! 😃

**Review by mstruve — APPROVED** [review]

**Pull request merged**
