### PR TITLE
Remove IBM openapi-validator

### PR DESCRIPTION
**Pull request by rhymes**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

~Re-ran `yarn lint-openapi init` to fix newly emerged configuration errors~

Removed `ibm-openapi-validator`, see https://github.com/forem/forem/pull/13837#issuecomment-847155981 and ensuing conversation

One validator is better than two 🤣 

## Related Tickets & Documents

Closes https://github.com/forem/forem/issues/13829

~See https://github.com/IBM/openapi-validator/pull/286~

## QA Instructions, Screenshots, Recordings

Run `yarn api-docs:lint` and make sure the checks pass

### CODE REVIEW

**Review by joshpuetz — APPROVED** [review]

**Comment by juliannatetreault** [comment]
So, I just tested this out locally and ran into the following error when I ran `yarn api-docs:lint`:
```
yarn api-docs:lint

yarn run v1.22.5
$ spectral lint -F hint -v docs/api_v0.yml && lint-openapi -e docs/api_v0.yml
Found 83 rules (67 enabled)
Linting dev.to/docs/api_v0.yml
OpenAPI 3.x detected
No results with a severity of 'hint' or higher found!

Error: Cannot find module '@stoplight/spectral/rulesets/assets/assets.json'
```

When I run `yarn api-docs:lint` on `main` though, I do not run into this error, but do run into the error described in the bug report linked to this PR. 🤔

**Comment by rhymes** [comment]
OMG @juliannatetreault, thanks for checking! I had the same issue but I thought it was an issue with my own `node_modules` directory, as according to https://classic.yarnpkg.com/en/package/@stoplight/spectral?files the file is there :'(

I'll mull this over a bit more as I couldn't find an immediate solution other than removing the tool :D

**Comment by juliannatetreault** [comment]
> OMG @juliannatetreault, thanks for checking! I had the same issue but I thought it was an issue with my own `node_modules` directory, as according to https://classic.yarnpkg.com/en/package/@stoplight/spectral?files the file is there :'(
> 
> I'll mull this over a bit more as I couldn't find an immediate solution other than removing the tool :D

Oh my goodness, I thought the same thing and went down a tiny, weird rabbit hole trying to debug it. 😄  Sounds good to me -- feel free to ping me when you've decided on a solution, @rhymes!

**Comment by citizen428** [comment]
When you run the two commands specified in `api-docs:lint` it's only the second one that raises this error:

```
❯ node_modules/.bin/spectral lint -F hint -v docs/api_v0.yml
Found 83 rules (67 enabled)
Linting /home/michi/src/work/forem/docs/api_v0.yml
OpenAPI 3.x detected
No results with a severity of 'hint' or higher found!

❯ node_modules/.bin/lint-openapi -e docs/api_v0.yml
Error: Cannot find module '@stoplight/spectral/rulesets/assets/assets.json'
Require stack:
....
```

But I've been wondering for a while, what's the point in having two validators? Does the IBM validator really add that much given that it also relies on spectral for at least some of the checks? I've been working on adding support for the [Super-Linter](https://github.com/github/super-linter) action to our repository which only supports Spectral.

**Comment by rhymes** [comment]
@citizen428 yeah, I'm going to remove the ibm validator, I also noticed yesterday that it's essentially using the `spectral` validator internally. Let's make our lives easier :D

**Comment by rhymes** [comment]
Thanks @juliannatetreault, @citizen428 you can now re-review :D

**Review by citizen428 — APPROVED** [review]
Thanks @rhymes 🎉

**Comment by 747** [comment]
Hi, I think you still need to delete this line to pass.
https://github.com/forem/forem/blob/1bff6f9d830b965b0ff9cdcbaca4412c0a3ab912/package.json#L41

**Comment by rhymes** [comment]
@747 :-( sorry for the mishap! Would you like to send a PR?

**Pull request merged**
