### PR TITLE
Persist register field values if validation fails

### LINKED ISSUE #11099: Do not clear fields on account creation page if failed from invalid username
**Is your feature request related to a problem? Please describe.**
As a new user creating an account via `/users/sign_up?state=email_signup` (where a forem has enabled email/pass registration), I will lose all of the filled-out fields if I accidentally use an invalid username.

**Describe the solution you'd like**
Don't clear these fields.  I imagine that means validating the field in the browser before the form submits?

**Additional context**
[Here is a video in action.](https://p241.p3.n0.cdn.getcloudapp.com/items/WnurZYv6/Screen%20Recording%202020-10-26%20at%2003.44.58%20PM.mp4)

Raised by a community member of `the.community.club` [here](https://the.community.club/evanhamilton/comment/32).

### PR DESCRIPTION
**Pull request by bntzio**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This fixes the issue #11099 by keeping the controller user variable values in the form after submission if there are any errors.

This will improve the UX and allow users to quickly edit only the required fields to create an account.

## Related Tickets & Documents

References/Closes/Fixes/Resolves #11099 

## QA Instructions, Screenshots, Recordings

Enable email registration for your forem in `app/models/site_config.rb`:

```rb
field :allow_email_password_registration, type: :boolean, default: true
```

Then go to [/users/sign_up?state=email_signup](http://localhost:3000/users/sign_up?state=email_signup) in your local env and fill the register fields with an invalid username (spaces, existing username, etc) and submit the form.

The page will reload and the field values for `name`, `username` and `email` should be persisted.

forem-register-fields

## Added tests?

- [ ] Yes
- [x] No, and this is why: unmodified controller
- [ ] I need help with writing tests

## Added to documentation?

- [ ] Docs.forem.com
- [ ] README
- [x] No documentation needed

## Are there any post deployment tasks we need to perform?

Nope!

## What gif best describes this PR or how it makes you feel?

awesome

### CODE REVIEW

**Review by rhymes — COMMENTED** [review]
Hi @bntzio, it works well! I wonder if there's a way to add a system/regression test about this in https://github.com/forem/forem/blob/master/spec/system/authentication/user_logs_in_with_email_spec.rb

What do you think?

**Review by benhalpern — COMMENTED** [review]
This works well, and I agree with @rhymes that a regression test makes sense to cover our bases and ensure this functionality persists future changes.

(IMO a request spec that proves this is probably sufficient)

.... In terms of the code, would `form_for(@user` be better a little cleaner?

**Comment by bntzio** [comment]
@rhymes @benhalpern yeah agree, I'm on it, thanks!

**Comment by msarit** [comment]
@bntzio Hello! 👋🏾 

Thanks for your PR - could you please resolve the conflicts? 🙏🏾

**Comment by msarit** [comment]
@bntzio Hello! 👋🏾

Just checking to see if you are still working on this PR? Let us know please, thanks!

**Comment by bntzio** [comment]
> @bntzio Hello! 👋🏾
> 
> 
> 
> Just checking to see if you are still working on this PR? Let us know please, thanks!

Hey @msarit 👋

Sorry for the delay, will work on this today.

**Comment by bntzio** [comment]
@msarit I just rebased from master to resolve the conflicts.

Apart from that, I'm doing the regression test for this fix but for some reason I can't run RSpec, see #12600.

**Comment by msarit** [comment]
Hey @bntzio I'm assuming you're running the app on Docker?

**Comment by bntzio** [comment]
> Hey @bntzio I'm assuming you're running the app on Docker?

That's right.

**Comment by citizen428** [comment]
Hi @bntzio, would you mind pushing up the current spec you have so people can help you better debug this?

**Comment by msarit** [comment]
Hello @bntzio! 👋🏾 
Please push up the specs you added for this PR, so our engineers can test them locally (since you're having trouble running the specs on your Docker instance). 🙏🏾

**Comment by citizen428** [comment]
@bntzio Thanks for your contribution! Since this PR stalled I decided to tackle this myself, you can see an end-to-end test in https://github.com/forem/forem/pull/13614.

**Pull request closed without merging**
