### PR TITLE
Fix missing category in delete draft listing URL

### LINKED ISSUE #10800: Undefined in url for delete listing in listing dashboard
**Describe the bug**

Url for deleting listing in listing dashboard is `/listings/undefined/test-2fjm/delete_confirm`

**To Reproduce**

1. Go to https://dev.to/listings/dashboard
2. Create a draft listing
3. Hover over delete link of that listing it will have undefined in the url

**Expected behavior**

It should not have undefined in the url

**Screenshots**
undefined_link

**Desktop:**

OS, version: Ubuntu 20.04
Browser, version: Brave Version 1.12.112 Chromium: 84.0.4147.125 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by akshayymahajan**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
The JSON for listings on the listing dashboard page is missing the category key which causes an `undefined` in the delete listing URL. This PR adds the category key in the JSON.

## Related Tickets & Documents
Fixes #10800

## QA Instructions, Screenshots, Recordings

**Before**

Before

**After**

After

## Added tests?

- [x] yes
- [ ] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Review by rhymes — COMMENTED** [review]
Hi @akshayymahajan, great find! do you think you can add a test to make sure this doesn't regress in the future?

Controller specs are in https://github.com/forem/forem/blob/master/spec/requests/listings_spec.rb

thank you!

**Comment by akshayymahajan** [comment]
Thanks, @rhymes. I will add a test for that.

**Comment by akshayymahajan** [comment]
Hey @rhymes, I have added the test. Can you have a look?

**Review by rhymes — APPROVED** [review]
LGTM!

Thanks @akshayymahajan

**Review by benhalpern — APPROVED** [review]

**Pull request merged**
