### PR TITLE
Update readme in installation docs

### PR DESCRIPTION
**Pull request by reyesvicente**
fixed links on mac, windows, linux, containers and gitpod which returns 404

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation Update

## Description
Links on installation readme returns 404 on mac, linux, windows, containers, gitpod
## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [ ] no documentation needed

### CODE REVIEW

**Comment by rhymes** [comment]
Hi @reyesvicente, thanks for the PR! Are you sure they are broken? I just tried from https://docs.dev.to/installation/ and they work...

**Comment by reyesvicente** [comment]
> Hi @reyesvicente, thanks for the PR! Are you sure they are broken? I just tried from https://docs.dev.to/installation/ and they work...

Hi @rhymes , yes. It redirects to a 404 as shown here:
Screen Shot 2020-08-29 at 2 01 40 AM

**Comment by nickytonline** [comment]
@reyesvicente, all the links work for me as well. I am unable to reproduce this.

**Comment by rhymes** [comment]
@reyesvicente ah got it! the links are for the hosted version in https://docs.dev.to - not to be navigated through GitHub.

If you'll notice none of the links in docs folder files is has the `/docs` prefix

**Review by rhymes — CHANGES_REQUESTED** [review]
Ok I tested by running `yarn gitdocs serve` locally on this branch and now the links are broken in the live docs. So I don't think this is the right solution @reyesvicente 

To reproduce:

- go to the `docs` folder in your terminal
- run `yarn gitdocs serve`
- go to http://0.0.0.0:8000/installation/ 
- see that now the links are broken

**Comment by reyesvicente** [comment]
> @reyesvicente ah got it! the links are for the hosted version in https://docs.dev.to - not to be navigated through GitHub.
> 
> If you'll notice none of the links in docs folder files is has the `/docs` prefix.
> 
> We could technically add the prefix so that they'd work with GitHub as well though


> Ok I tested by running `yarn gitdocs serve` locally on this branch and now the links are broken in the live docs. So I don't think this is the right solution @reyesvicente
> 
> To reproduce:
> 
> * go to the `docs` folder in your terminal
> * run `yarn gitdocs serve`
> * go to http://0.0.0.0:8000/installation/
> * see that now the links are broken

Ok on it.

**Pull request closed without merging**
