### PR TITLE
Replace HEROKU_SLUG_COMMIT with custom footprint (naive)

### PR DESCRIPTION
**Pull request by benhalpern**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

We use `HEROKU_SLUG_COMMIT` to know when one release is later than another to bust caches and other duties.

This is a Heroku dependency we need to get rid of. This PR introduces a minute-precision timestamp which will be good enough right this moment, but it could be different on a process-by-process basis. For basic cache-busting and the such that is fine, but ideally we can computer a value here which will be more consistent.

If anybody has an idea for the most straightforward way to do that, feel free to drop an idea. Otherwise, I'd say we ship this as "good enough for right now".

### CODE REVIEW

**Comment by benhalpern** [comment]
@mstruve yeah something like that totally works for me.

Ideally I'd think we can do something with minimal moving pieces.

**Comment by mstruve** [comment]
@jdoss can we hook something like that up in our deploy process? Where we grab the SHA from the container and write it to a file before boot?

**Comment by jdoss** [comment]
@mstruve shouldn't be too hard. I'll look into it tomorrow.

**Comment by benhalpern** [comment]
Changed the code... @jdoss will add a `RELEASE_FOOTPRINT` to our Forem Cloud environment which will increment before boot.

**Comment by benhalpern** [comment]
Dealing with fixing the tests for new scenario.

**Pull request merged**
