### PR TITLE
Update format specifiers in readable_publish_date

### LINKED ISSUE #13612: Remove extra space from readable_publish_date
I am using the GET latest articles endpoint in [my project](https://github.com/hadiidbouk/DEV).

The `readable_publish_date` property added an extra space between the day and the month, this could be fixed on the front end, but if it's a readable publish date why not be better readable 😅

Screen Shot 2021-05-02 at 6 42 01 PM

### PR DESCRIPTION
**Pull request by Arun-kc**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Removed extra spaces from readable_publish_date by changing format specifiers

## Related Tickets & Documents
Fixes #13612
## QA Instructions, Screenshots, Recordings

I'm not sure about this since the only change done is updating format specifiers

### UI accessibility concerns?

N/A

## Added tests?

- [ ] Yes
- [x] No, and this is why: I guess old test will still work
- [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?
N/A
## [optional] What gif best describes this PR or how it makes you feel?

I'm nervous

### CODE REVIEW

**Review by gautamkrishnar — APPROVED** [review]

**Comment by rhymes** [comment]
Hi @Arun-kc! Great job! There's one failing test, you can run it locally with:

```
bundle exec rspec spec/requests/articles/video_player_show_spec.rb:29
```

Let us know if you need further help

**Comment by Arun-kc** [comment]
> Hi @Arun-kc! Great job! There's one failing test, you can run it locally with:
> 
> ```
> bundle exec rspec spec/requests/articles/video_player_show_spec.rb:29
> ```
> 
> Let us know if you need further help

Hi @rhymes I did this in windows since it was only format specifier updates. So I tried to do it in wsl Ubuntu 18.04. It's showing the following error. I tried to debug it on my own, but was not able to solve this. 

image

This is my first time forking forem and using it, so don't know if there are any mistakes I did while installation. I'm not able to run this command successfully. Could you please help me with this?

**Comment by rhymes** [comment]
Hi @Arun-kc, no problem! It looks like your local PostgreSQL requires a password but it's not receiving it.

By default Forem will try to connect to your DB using your current username and no password. If you have one setup, you need to edit the `.env` file to add a `DATABASE_URL`, something like:

```shell
export DATABASE_URL=postgres://USERNAME:PASSWORD@HOSTNAME/Forem_development
```

**Comment by Arun-kc** [comment]
> Hi @Arun-kc, no problem! It looks like your local PostgreSQL requires a password but it's not receiving it.
> 
> By default Forem will try to connect to your DB using your current username and no password. If you have one setup, you need to edit the `.env` file to add a `DATABASE_URL`, something like:
> 
> ```shell
> export DATABASE_URL=postgres://USERNAME:PASSWORD@HOSTNAME/Forem_development
> ```

Hi @rhymes, thanks for helping me like this. 
I did try using the username and password. But now it's showing the following error 

image

I tried restarting PostgreSQL, but still, this same error remains. 😅

**Comment by rhymes** [comment]
Hi @Arun-kc, you can type `createdb Forem_test`, you should also run `bin/setup` if you haven't yet!

**Comment by Arun-kc** [comment]
> Hi @Arun-kc, you can type `createdb Forem_test` in the command line, you should also run `bin/setup` if you haven't yet!

Hi @rhymes , I did try creating a db manually and yea did ran bin/setup. But I was getting this error when I created the db manually. I tried running the commands `rake db:migrate` and `rake db:reset`, but that didn't help.

image

Sorry for pinging you a lot like this, I'm pretty new to open sourcing and ruby, so need help in solving this issue 😅
Thank you!

**Comment by rhymes** [comment]
No worries @Arun-kc! Can you try:

`RAILS_ENV=test bundle exec rails db:test:prepare`

and then:

`bundle exec rspec spec/requests/articles/video_player_show_spec.rb:29`

?

**Comment by Arun-kc** [comment]
> No worries @Arun-kc! Can you try:
> 
> `RAILS_ENV=test bundle exec rails db:test:prepare`
> 
> and then:
> 
> `bundle exec rspec spec/requests/articles/video_player_show_spec.rb:29`
> 
> ?

Ok @rhymes 

image

But still failing the test

image

**Comment by rhymes** [comment]
Yes, as I mentioned, the test is failing :)

I think it's because `local_date` wasn't changed: 

https://github.com/forem/forem/blob/d7f9a18199a2fdbff7c4c54ce6f1922a38373506/app/helpers/date_helper.rb#L6

**Comment by Arun-kc** [comment]
> Yes the test is failing :)
> 
> I think it's because `local_date` wasn't changed:
> 
> https://github.com/forem/forem/blob/d7f9a18199a2fdbff7c4c54ce6f1922a38373506/app/helpers/date_helper.rb#L6

Ok @rhymes. So I should change the format specifier here too, right?

**Review by rhymes — APPROVED** [review]
Great job @Arun-kc!

**Comment by Arun-kc** [comment]
> Great job @Arun-kc!

Thanks a lot for the help @rhymes I really appreciate it 😇

**Pull request merged**
