### PR TITLE
Add text to "Follow podcast" button in Podcast liquid tag

### LINKED ISSUE #13667: "Follow" text missing from Podcast Liquid tag display.
**Describe the bug**

When using the podcast liquid tag in an article the button that should have "Follow" no longer displays the text. I tested this with several podcasts and none of them display the "Follow" text. 

**To Reproduce**
1. Navigate to the editor to create a new post. 
2. Use the podcast liquid tag to render any of the podcasts on DEV `{% podcast url-for-episode-here %}` 
3. click preview to preview the liquid tag
4. Scroll down to the rendered podcast liquid tag; it will be displayed with an empty button that should contain "Follow" 

**Expected behavior**
Follow text inside of the empty button

**Screenshots**
Screen Shot 2021-05-05 at 9 30 24 AM
Screen Shot 2021-05-05 at 9 30 57 AM
Screen Shot 2021-05-05 at 9 31 35 AM

Here you can see the text is not rendered at all in the HTML
Screen Shot 2021-05-05 at 9 33 59 AM

### PR DESCRIPTION
**Pull request by snyntakk**
## What type of PR is this? (check all applicable)
 - [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
## Description
There was a bug where there was no follow text on the follow button in a podcast liquid tag.
## Related Tickets & Documents
Closes #13667 
## Added tests?
No I don't think so
## [Forem core team only] How will this change be communicated?

Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it.

### CODE REVIEW

**Comment by nickytonline** [comment]
This works when a post is saved or published, but not when in Preview mode in the editor. I wonder if there is a reason the button text is `&nbsp;` instead of an explicit `Follow` text. The `Follow` text appears to be added dynamically`.

image

I'm just digging into the codebase as to why this may be.

**Comment by nickytonline** [comment]
I remember why it's `&nbsp;`. We do the same thing with follow buttons for users. It's because the page is cached, so we dynamically add `'Follow` or `Following` once the page is loaded.

I think in the case of this bug, we'd need to add the `Follow` text when in preview mode as it behaves fine in other scenarios.

**Comment by snyntakk** [comment]
> I remember why it's `&nbsp;`. We do the same thing with follow buttons for users. It's because the page is cached, so we dynamically add `'Follow` or `Following` once the page is loaded.
> 
> I think in the case of this bug, we'd need to add the `Follow` text when in preview mode as it behaves fine in other scenarios.

I will try to add this to the PR. Thank you for your input

**Comment by snyntakk** [comment]
I think I fixed it @nickytonline

**Review by rhymes — COMMENTED** [review]
Hi @snyntakk!

Thank you for this! The feature is working. I was wondering: how comfortable would you feel to be adding tests to the PR?

Precisely I think we should add a Cypress end to end test.

Unfortunately we don't podcast episodes in the seeded database, so it would require a bit of Ruby as well. 

The plan would be the following:

1. Add a podcast to https://github.com/forem/forem/blob/main/spec/support/seeds/seeds_e2e.rb - I recommend adding https://github.com/forem/forem/blob/7b05bd81fe082aaf8ecaeb7ecb3dc9651599ea21/db/seeds.rb#L254-L266 as it only has a few episodes

2. Import episodes from such podcast, which means that we'd need to slightly alter what we do in `seeds.rb` - From

https://github.com/forem/forem/blob/7b05bd81fe082aaf8ecaeb7ecb3dc9651599ea21/db/seeds.rb#L283-L286

to

```ruby
  podcast_objects.each do |attributes|
    podcast = Podcast.create!(attributes)
    # importing only one episode, instead of all
    Podcasts::GetEpisodesWorker.new.perform(podcast_id: podcast.id, limit: 1)
  end
```

3. Add a Cypress test, you can find them in https://github.com/forem/forem/tree/main/cypress/integration, to
  - create an article with the podcast liquid tag
  - click the preview button
  - assert that the text is there

Let us know if you need help or if you have questions! :-)

**Comment by citizen428** [comment]
Hi @snyntakk, thanks for your contribution! I just wanted to check in and see if you're planning to finish this PR and if you need any further help from us?

**Comment by citizen428** [comment]
Hi @snyntakk 👋 It's me again. Not meaning to rush you but are you planning on adding the tests @rhymes requested above or should one of our team members take over this P? Thanks for your contribution!

**Comment by aitchiss** [comment]
Just a heads up @snyntakk that we now have a podcast seeded in our end to end tests, which you would now be able to use (and avoid having to complete steps 1 and 2  mentioned above). You can see an example of where we use this seeded podcast in [this test for the podcast episode page](https://github.com/forem/forem/blob/19db4b028793b69516021760d0405c722ff38b1d/cypress/integration/seededFlows/podcastFlows/followPodcast.spec.js).

If you don't have time, just let us know and someone from the team can help push this over the finish line, as we'd love to have your fix in the codebase!

**Comment by citizen428** [comment]
I resolved the merge conflicts here now. Are you going to add tests to this PR @snyntakk or should someone from our team take over? 😃

**Comment by aitchiss** [comment]
Just to let you know @snyntakk (also @citizen428), we recently reviewed the podcast functionality as a whole, and took the decision to ultimately remove this follow button. Your fix made this a lot better, but there were deeper issues with the functionality of the podcast liquid tag, and we decided this would be best in the end.

Thank you for all of your work on this PR - it's much appreciated, but given the button has now been removed, I'm going to close this PR.

I hope you will consider contributing to the codebase again in future ✨

**Pull request closed without merging**
