### PR TITLE
Remove docs from repo ✂✂✂

### PR DESCRIPTION
**Pull request by Zhao-Andy**
## What type of PR is this? (check all applicable)

- [x] Documentation Update

## Description
We've moved to https://developers.forem.com under a separate repo at https://github.com/forem/forem-docs! This PR removes all references to the docs, GitDocs (previous doc generator). We've also decided to remove the YARD Ruby documentation since it wasn't being used.

As a checklist:
- [x] Remove `docs/` folder
- [x] Remove references to `docs/`
- [x] Remove `.gitdocs` references and file
- [x] Remove `gitdocs` package(s)
- [x] Update PR templates and this repo's markdown files that reference docs.forem.com
- [x] Update contributing guidelines for forem/forem-docs repo
- [ ] ...anything else?

## Related Tickets & Documents
https://github.com/forem/forem-docs

## QA Instructions, Screenshots, Recordings
Biggest concern
## [Forem core team only] How will this change be communicated?

- [x] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post

## [optional] Are there any post deployment tasks we need to perform?
Delete 

## [optional] What gif best describes this PR or how it makes you feel?

"On to bigger and better things"

### CODE REVIEW

**Review by jgaskins — APPROVED** [review]
12,000 line diff

I ain't reading all that. I'm happy for you, though. Or sorry that happened.

Seriously, though, this is good to pull out of the repo. Thanks for your effort here!

**Review by juliannatetreault — APPROVED** [review]
✂️ ✂️ ✂️

**Review by nickytonline — APPROVED** [review]
✂️✂️✂️✂️ Let's gooo! ⛴⛴⛴⛴

**Comment by mohammedgad** [comment]
Hi @Zhao-Andy ,
I am new here, and I wanted to contribute, so I went to read the contributing guide, and I found some broken links I am not sure if I should open a new issue or just post it here, as the links are changed through this PR which merged hour ago, 
links examples:  (I think that's all)
https://developers.forem.com/installation/
https://developers.forem.com/contributing/forem/
https://developers.forem.com/technical-overview/

Thank you.
I hope i didn't post it on the wrong place

**Comment by Zhao-Andy** [comment]
Hey @mohammedgad, thanks for the heads up! This is a fine place to let us know, although in the future an issue in the new repo would be great. :)

I'll update those broken links in a new PR.

**Pull request merged**
