### PR TITLE
fix: issue - modal 'flag user' is not openning [#20188]

### PR DESCRIPTION
**Pull request by Lucasm4sco**
checking if the modal is being rendered inside the iframe, if true it will look for the modal inside the iframe

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Related Tickets & Documents

- Related Issue #20188
- Closes #

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [axe DevTools](https://www.deque.com/axe/) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

_For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [ ] Yes
- [x] No, and this is why: I received a problem with my local tools when I tried ran tests (It had no relation to the repository I believe), so I didn't create one for this bug.
- [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?

Check if opening the modal causes any unwanted behavior.

## [optional] What gif best describes this PR or how it makes you feel?

funny cat

### CODE REVIEW

**Review by klardotsh — APPROVED** [review]
Well that's nifty. I'll enable CI for your PR which hopefully, maybe, might catch regressions here, and otherwise another reviewer with more relevant frontend chops than my own should be able to know whether this is suitable for integration.

Looks like a great and very impactful first-time contribution to the project, thank you so much!

**Comment by lightalloy** [comment]
I have created [a pr](https://github.com/forem/forem/pull/20213) which will fix the spec failing in this build.

**Comment by Lucasm4sco** [comment]
> Well that's nifty. I'll enable CI for your PR which hopefully, maybe, might catch regressions here, and otherwise another reviewer with more relevant frontend chops than my own should be able to know whether this is suitable for integration.
> 
> Looks like a great and very impactful first-time contribution to the project, thank you so much!

That's nice to hear, thanks. In fact, it's even one of my first contributions on GitHub, and btw if anyone thinks there are any improvements to be made or changes needed, I'd like to hear about and try to implement them. (I thought I mentioned this before, but it seems I didn't)

Thanks again for the words ;)

**Review by maestromac — APPROVED** [review]
Thank you for this fix. LGTM!

**Pull request merged**
