### PR TITLE
Remove language settings

### PR DESCRIPTION
**Pull request by citizen428**
## What type of PR is this? (check all applicable)

- [X] Refactor

## Description

While doing research for an RFC, I found some unused/unfinished code and we decided to clean that up. 

This PR does the following:

1. Remove `language_settings` and all related code.  Even though this was marked as "beta", it seems a bit too unfinished to provide any real benefit. The list of 7 languages seems very arbitrary: for example, we included only 4 out of the 10 most spoken languages, with Japanese being the only non-European one. If we revisit this future we probably also want to design the data model a bit better and have a separate table for this, not a JSONB column on `users`.
2. Usage of the `language` column on `Article`. It seems it was primary based on scoring an article's language against the user's preferred language(s), so with this feature gone it doesn't make sense to keep around. 

This whole topic can and probably should be revisited in the future, but with a proper RFC.

There will also be follow-up PRs to ignore and remove the two relevant columns.

Questions:

* [ ] @mstruve I removed the relevant attributes from ES indexing, but IIRC we can't remove them from the mapping, is that correct? 

## Related Tickets & Documents

https://github.com/forem/forem/issues/12356

## QA Instructions, Screenshots, Recordings

While this is a big change, it should primarily be covered by existing specs. 

For manual QA you can visit `settings/customization` and browse some articles and the feed to ensure everything is still working.

### UI accessibility concerns?

None

## Added tests?

- [X] Yes, updated/removed existing ones

## Added to documentation?

- [X] Update [Developer Docs](https://docs.forem.com)

### CODE REVIEW

**Comment by citizen428** [comment]
@vaidehijoshi I explicitly requested your review here to make 100% sure that removing this is ok from a product perspective.

**Review by rhymes — COMMENTED** [review]
Love it!

Should we add `language` to `Article.ignored_columns` ?

**Comment by citizen428** [comment]
> Should we add language to Article.ignored_columns ?

We can't really ignore it as long as code that potentially uses it is still in the app, that would lead to a `NoMethodError`. 

```ruby
Article.ignored_columns << "language"
Article.first.language
# NoMethodError: undefined method `language' for #<Article:0x0000560f946f6dd8>
```

So to play it safe in regards to AR column caching I wanted to first remove all the code interacting with this, before ignoring the column. See original PR description:

> There will also be follow-up PRs to ignore and remove the two relevant columns.

**Review by rhymes — APPROVED** [review]
Let's do this

**Review by jacobherrington — APPROVED** [review]
This makes sense to me, and we can ignore the column as a next step if that feels safe.

I think we need @vaidehijoshi to :+1: this change before we merge, but FWIW I think we should remove it.

**Comment by mstruve** [comment]
> @mstruve I removed the relevant attributes from ES indexing, but IIRC we can't remove them from the mapping, is that correct?

That is correct. You can actually remove the field from our .json file if you want but it will still exist in the mapping on Elasticsearch. In this case since we dont have much data its not a huge deal to have an unused field. If we had a bunch of them and lots of data then we might consider reindexing to a new index.

**Comment by vaidehijoshi** [comment]
I let this marinate in my mind all day today, and went back and forth on whether removing this was the right call or not. While the `language_settings` concept is certainly half-baked, it wasn't immediately obvious to me from a _product_ sense whether we needed to actually remove it or not right now.

As a thought exercise with @lisasy, I asked myself the following: _"If we were starting with a brand new forem tomorrow, would this feature be immediately useful?"_*

If we were starting with a brand new Forem that was just spun up, I don't think that the language settings feature is one that would be a big sell or be used. The more that I think about it, the more apparent it is that this is a feature that is useful to Forem instances with:
1) a significant _amount_ of content
2) content in more than _one_ language

I would say that this doesn't apply to the _majority_ of Forems right now ("right now" being very key words here). An out-of-the-box Forem would likely not need a "filter content based on selected language" feature. However, I could definitely see this being something we'd need to provide as Forems become more robust, with more users from around the world, who speak + write content in different languages. But before that, a Forem Creator would likely be concerned with _growing_ that community and _getting_ that content to begin with.

So, my answer to that original thought exercise was _"No"_. In fact, at the moment, this feels like a very DEV-specific feature, as DEV is an example of a Forem that fulfills requirements 1) and 2).

I would be okay with us coming back to a "language preference filtering" feature like this one when the time is right -- and with all Forems in mind. That moment would be the right one to re-evaluate the data model, and consider which languages are _actually_ in demand across the Forem ecosystem. I lean towards us removing this feature for now, and circling back to it when the time is right (when we have a demand for it across our Forems, meaning that we have Forems that have grown enough to the point where we can see enough variety of content, in different languages).

_Two relevant pieces of information I pulled while letting this marinate:_
1) Total number of [articles](https://dev.to/admin/blazer/queries/154-article-language-totals) on DEV with languages set.
2) Total number of [users)(https://dev.to/admin/blazer/queries/109-preferred-languages-totals) on DEV with preferred languages set.

To this end, I think it's important that we think about how making this change will impact the product experience. I'd like us to write a forem.dev post if we deprecate this feature with some reasoning as to why we decided to remove this (admittedly, the current state of this feature isn't useful, and I think that's a good thing to note), and our hope to revisit it in the future. Given the number of users who have a language setting _other_ than English, I think we owe it to them to explain why we're deprecating this feature after having it in beta for so long.

_*Obviously, we can't ask ourselves _only_ this question when making all product decisions, but it seemed like the right question given our current goals._

**Comment by citizen428** [comment]
> it wasn't immediately obvious to me from a product sense whether we needed to actually remove it or not right now.

I have a potential one: the list of available languages is extremely arbitrary and heavily skewed towards European languages. The only one that's not is Japanese, which is less spoken than e.g. Mandarin, Hindi, or Indonesian. So for every person we make happy with this feature, we potentially disgruntle many more.

> Total number of articles on DEV with languages set.

The top 2 are "en" and "null". If we exclude these two there are 30,033 articles that have a language set, out of 475,073.  That's about 6.3%, a very low number for a Forem instance that already fulfills both your criteria. Though I'd wager that this number could be significantly higher if we had a better implementation and supported more than 7 seemingly arbitrarily chosen languages. That's why I propose starting over from scratch with an actual RFC.

> Total number of users on DEV with preferred languages set.

For non-English that's 12,675 out of 561,408 or 2.25% percent. Same comment as above, I believe this number could be much higher with a better implementation.

**Comment by citizen428** [comment]
In the meantime, I'm setting this PR back to draft to prevent accidental merges until the above product discussion is resolved.

**Comment by citizen428** [comment]
> I would suggest removing it from the mapping

@mstruve ✅

**Comment by rhymes** [comment]
> Two relevant pieces of information I pulled while letting this marinate:

>    Total number of articles on DEV with languages set.

I took the liberty to fork that query to only view published articles https://dev.to/admin/blazer/queries/318-published-article-language-totals

**Comment by vaidehijoshi** [comment]
> I have a potential one: the list of available languages is extremely arbitrary and heavily skewed towards European languages. The only one that's not is Japanese, which is less spoken than e.g. Mandarin, Hindi, or Indonesian. So for every person we make happy with this feature, we potentially disgruntle many more.

Yes, I totally see this point. I definitely am not asserting that the languages that we originally chose for this feature are fully inclusive, by any means. 😓 

> The top 2 are "en" and "null". If we exclude these two there are 30,033 articles that have a language set, out of 475,073. That's about 6.3%, a very low number for a Forem instance that already fulfills both your criteria. Though I'd wager that this number could be significantly higher if we had a better implementation and supported more than 7 seemingly arbitrarily chosen languages. That's why I propose starting over from scratch with an actual RFC.

> For non-English that's 12,675 out of 561,408 or 2.25% percent. Same comment as above, I believe this number could be much higher with a better implementation.

Yep, I realize the overall percentages here are low. And I fully acknowledge that the feature is not widely used (probably because it is half-baked 🙃).

But I do think it means _something_ that even 2 percent had a language set. Perhaps some of those users were power users who joined in the early days and were excited by us rolling out beta features for language support. I know the feature is half-baked, but we _did_ release it at some point, and there were some folks who have a language set, so it is a feature that a small percentage of users expect to "do something", even _if_ it is a small percentage.

To be clear, the reason I wrote up my previous comment with my thought process was _not_ because I disagreed with what this PR does. 😃 From a technical perspective, it makes total sense. But, I also wanted to consider what it would feel like for those 2% of users who might notice that we suddenly dropped multiple-language settings without any explanation. As our team is predominantly English-speaking/anglocentric, I worried that dropping this feature without at least acknowledging the reasoning behind it (and the intent to return to it) would send a message of, _"Oh, we don't care about this anymore!"_, which I know is not the case. Hence, my suggestion to write a forem.dev post on this change.

>> I'd like us to write a forem.dev post if we deprecate this feature with some reasoning as to why we decided to remove this

> Who is "us" here, me or you? 😃

I'm happy to whip up a draft so as not to block you on this any longer :)

**Review by vaidehijoshi — APPROVED** [review]
This beta feature deprecation has [been shared with the greater community](https://forem.dev/vaidehijoshi/sunsetting-forem-s-current-language-settings-beta-4pk6), so I think we're go to go! 🚀

**Comment by citizen428** [comment]
Thanks for the context @vaidehijoshi, makes perfect sense. And also thanks for writing this draft post!

**Pull request merged**
