### PR TITLE
Update Analytics Dashboard time navigation to tabs

### LINKED ISSUE #13214: Contrast for analytics time windows is very low with the "night" theme
The tabs to select the time frame on the analytics page look like with the dark theme on DEV has very low contrast (black on very dark blue):

**To Reproduce**

1. Set the "Night" theme
   image
2. Visit [the analytics page](https://dev.to/dashboard/analytics)

**Expected behavior**

I can see all the options for the time frames to select

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: macOS 11.2.3
- Browser, version: Safari 14.0.3 & Firefox 86.0.1

### PR DESCRIPTION
**Pull request by Link2Twenty**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Move the time navigation to the more modern crayon layout, this will mean the theming stuff will work out the box.

## Related Tickets & Documents
Closes #13214

## QA Instructions, Screenshots, Recordings
image

### UI accessibility concerns?
This should fix the UI accessibility issue mentioned in the original ticket

## Added tests?

- [ ] Yes
- [x] No, and this is why: old tests should still work
- [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?
N/A

## [optional] What gif best describes this PR or how it makes you feel?

upgrades

### CODE REVIEW

**Review by rhymes — APPROVED** [review]
Works really well @Link2Twenty, great job!

ps. does this close the issue as a whole? I noticed you haven't specified it in the description

**Comment by Link2Twenty** [comment]
> does this close the issue as a whole? I noticed you haven't specified it in the description

It does, I've updated the original post 😅

**Review by aitchiss — APPROVED** [review]
Looking good! Thanks for this.

I think there is more work to do at a later time to make this more accessible as a [tab panel](https://www.w3.org/TR/wai-aria-practices-1.2/#tabpanel), but we already have an over-arching issue to look at usage of tab groups in the app generally (#11853) 👍

**Comment by Link2Twenty** [comment]
> I think there is more work to do at a later time to make this more accessible as a [tab panel](https://www.w3.org/TR/wai-aria-practices-1.2/#tabpanel).

I think in this specific instance of tabs the tab list stuff should be super easy to add, would you like me to do a follow up PR?

**Comment by aitchiss** [comment]
> > I think there is more work to do at a later time to make this more accessible as a [tab panel](https://www.w3.org/TR/wai-aria-practices-1.2/#tabpanel).
> 
> I think in this specific instance of tabs the tab list stuff should be super easy to add, would you like me to do a follow up PR?

Definitely happy if you'd like to have a look at it! I think it might be a significant piece of work though - it requires dynamic manipulation of the tabindex properties on the tab buttons, and also would need a bit of a refactor of how we present the tab panel content itself. At the moment, the HTML is only rendered in the DOM when the given tab is selected, but to follow the [tab panel](https://www.w3.org/TR/wai-aria-practices-1.2/#tabpanel) pattern we'd need it to be present in the DOM but hidden (so that we can add the appropriate `aria-controls` attributes)

**Pull request merged**
