### PR TITLE
Replace main tag inside another main tag with div

### LINKED ISSUE #14879: Notifications page has a <main> inside of a <main>
**Describe the bug**

On a user's notification page we can see an error in the axe devtools report, due to a `<main>` element being nested inside of another `<main>` element.

**To Reproduce**

- Log in to the app
- Visit `/notifications`
- Run the axe browser extension (Chrome or Firefox) and observe the error in the console

**Expected behavior**

- These errors shouldn't be present
- There should only be one main landmark on the page
- Visually there should be no change to the layout

**Screenshots**

screenshot of the notifications page, with axe dev tools report errors highlighted

### PR DESCRIPTION
**Pull request by luhova**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Replace main tag inside another main tag with div inside the notifcations page.
## Related Tickets & Documents
Fixes #14879
## QA Instructions, Screenshots, Recordings

- visit `/notifications`
- run axe
- tested on Chrome
Screenshot from 2021-10-02 12-32-10

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: it is a minor HTML change
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Review by aitchiss — APPROVED** [review]
Nice one - one small fix, 3 accessibility errors squashed 🎉

**Review by nickytonline — APPROVED** [review]
Accessibilitypalooza! Thanks @metamoni! 🚢

**Comment by metamoni** [comment]
> Accessibilitypalooza! Thanks @metamoni! 🚢

I'm afraid this one wasn't me, but great job @luhova! 🥳

**Comment by nickytonline** [comment]
Oops! You showed up in the autocomplete first. My bad. 🙃 Thanks so much @luhova!

**Pull request merged**
