### PR TITLE
Generator updates

### PR DESCRIPTION
**Pull request by ludwiczakpawel**
## What type of PR is this? (check all applicable)

- [x] Feature

## Description

Trying to pull out as much as possible [from another PR](https://github.com/forem/forem/pull/16174) and this felt like something tiny and good to isolate :)

## Related Tickets & Documents

- https://github.com/forem/forem/pull/16174

## QA Instructions, Screenshots, Recordings

Just review the code.

### UI accessibility concerns?

No.

## Added/updated tests?

No.

## [Forem core team only] How will this change be communicated?

It won't.

### CODE REVIEW

**Review by nickytonline — APPROVED** [review]

**Comment by nickytonline** [comment]
I restarted the failing test build node. Should be green shortly.

**Comment by ludwiczakpawel** [comment]
Turned out build had a good reason to fail... Apparently our Mod Tools are JS & CSS mess with lots of hacky solutions :sigh:. I had to make few extra changes to make it work - `!important` caused some changes with visibility of elements.  My changes haven't really changed anything visually though. I updated whatever was needed to be updated including tests...

**Comment by nickytonline** [comment]
> Turned out build had a good reason to fail... Apparently our Mod Tools are JS & CSS mess with lots of hacky solutions :sigh:. I had to make few extra changes to make it work - `!important` caused some changes with visibility of elements. My changes haven't really changed anything visually though. I updated whatever was needed to be updated including tests...

I'm glad to see that E2E tests caught this. Yay for tests.

**Comment by ludwiczakpawel** [comment]
> I'm glad to see that E2E tests caught this. Yay for tests.

Not really :D It was broken on production (one of the forms was always visible in mod tools and should be only visible after certain action) but no one ever noticed that and tests did not catch it. For some reason, after adding `!important` here and there (likely related to `hidden` class) tests started working...

Well... nevermind 🤷  :D

**Pull request merged**
