### PR TITLE
A data update script to remove unused ahoy events data

### PR DESCRIPTION
**Pull request by lightalloy**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description
Removing data after removing tracking "comment section viewable" in #19354

## Related Tickets & Documents
- Related Issue https://github.com/forem/forem-internal-eng/issues/523

## Added/updated tests?
- [x] Yes

### CODE REVIEW

**Comment by mirie** [comment]
Yay! So excited to see a PR for this~! 🎉

**Review by klardotsh — APPROVED** [review]
For my own learning's sake: what's our process for running these scripts? Do we make one-off `heroku run` dynos (or in Forem Cloud's case, shell through to the boxes with `ansible`?), or something else?

**Comment by maestromac** [comment]
@klardotsh it gets run as part of the startup rake task on all environments https://github.com/forem/forem/blob/main/lib/tasks/app_initializer.rake#L12

**Review by maestromac — APPROVED** [review]
LGTM! but I am going to mark as draft to avoid accidental merge

**Comment by maestromac** [comment]
@lightalloy we didn't realize how much data we were removing. We are going to close this off and run the script manuall via the console.

**Pull request closed without merging**
