### PR TITLE
[WIP] Fix milestone notification logic.

### PR DESCRIPTION
**Pull request by benhalpern**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Users are seeing more milestone notifications then they should—to the point of it being really annoying.

I think I have a handle for some of the issues with milestone notification mishaps, and why we're seeing them. This is a WIP PR, but I'm going to open another PR which temporarily removes the functionality.

Here is the other PR with the HOTFIX: https://github.com/thepracticaldev/dev.to/issues/4398

closes https://github.com/thepracticaldev/dev.to/issues/4398 (This is an old bug, exacerbated by new behavior)

### CODE REVIEW

**Comment by mstruve** [comment]
@benhalpern this has been updated and errors fixed. Feel free to remove the WIP if we still want this otherwise we should close it

**Comment by mstruve** [comment]
Good catch @rhymes, pretty sure those were removed in the original commit, the merge to update with master was a doozy and they probably accidentally got added back.

**Comment by Zhao-Andy** [comment]
So this PR was closed and I don't think we turned back on sending milestone notifications. Should I make a new PR with basically this code? Don't have the context as to why this PR was closed unfortunately :(

**Comment by mstruve** [comment]
Yay for Slack helping fill in context. 
Screen Shot 2021-03-31 at 12 37 52 PM

I think this might be something we want to bring up with to product since we would be bringing back a decent size feature.

**Pull request closed without merging**
