### PR TITLE
Fix code blocks get breaks added between each line

### PR DESCRIPTION
**Pull request by redencion**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Related Tickets & Documents

Closes https://github.com/forem/forem/issues/1446

## QA Instructions, Screenshots, Recordings

<a href="https://imgur.com/OJq3WNo"></a>

## Added tests?

- [ ] yes
- [ ] no, because they aren't needed
- [x] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

Wow It is my first time making pull request, It gives me confidence to try another case!

alt_text

### CODE REVIEW

**Comment by redencion** [comment]
> Hi @redencion, could you add a test for this?
> 
> You also need to sign the CLA before it.
> 
> Tests are legitimaly failing as you changed how the markdown parser works.
> 
> I'm turning this back as a draft, please mark it as ready for review when you're done. Let us know if you need further help (don't forget to fill out the PR template)

Thanks for supporting me!
Hi @redencion, could you add a test for this?
- no,  I get notice errors when running the command bin/spring rspec of the whole app before coding, I don't know what I need. But It works if I run ./bin/startup.

**Comment by rhymes** [comment]
@redencion what kind of errors? 

My suggestion is to run the tests for the files you modified at least, so in this case: https://github.com/forem/forem/blob/master/spec/labor/markdown_parser_spec.rb

**Comment by redencion** [comment]
> @redencion what kind of errors?
> 
> My suggestion is to run the tests for the files you modified at least, so in this case: https://github.com/forem/forem/blob/master/spec/labor/markdown_parser_spec.rb

I did, but It notices failed and doesn't know why! from branch master, there is no coding yet.

**Comment by rhymes** [comment]
@redencion can you report what are those errors? we can't help you otherwise. Thanks!

**Comment by redencion** [comment]
command
Screenshot 2020-08-12 14:23:25
result
Screenshot 2020-08-12 14:21:41

**Comment by rhymes** [comment]
@redencion try `bundle exec rspec spec/labor/markdown_parser_spec.rb`

**Comment by redencion** [comment]
> bundle exec rspec spec/labor/markdown_parser_spec.rb

It works! thanks

**Comment by redencion** [comment]
without errors bundle exec rspec spec/labor/markdown_parser_spec.rb

**Comment by redencion** [comment]
Hi, I've been checking out the bugs and I found out Class markdown.parser builds the whole article such as preview,  and view Html, with the method finalize,  then the first markdown.render  it adds tag <br> if we put on editor header below, however if I remove this line the goal is complete,  but the TDD not passing. Anybody would tell me a hint?  thank you very much

**Comment by rhymes** [comment]
@redencion I force pushed to re-trigger Travis and to see if we can get a consistent state of these failures.

Regarding how to proceed with the business logic I'm not 100% sure. 

cc. @maestromac and @Zhao-Andy

**Comment by redencion** [comment]
I think I have to build the first test and then continue,  if I don't I couldn't reach the goal.

**Review by maestromac — COMMENTED** [review]
Thank you for this PR @redencion . I believe the failing spec is a flaky spec so you don't have to worry about that.

I saw you initially added a method that would remove all linebreak from code block which might break some code block if there's an intentional linebreak in place. Regarding your current implementation of adding `html_edit` option, ignoring `#escape_liquid_tags_in_codeblock` is not a good idea as that's our main way to make sure liquid tags are properly ignored in the code block. Can you tell me what plan you have in mind?

Please also keep in mine that Issue #1446 only happens when using triple tilde(~) instead of triple grave accent (`)

**Comment by redencion** [comment]
@maestromac  thanks for supporting me.  I'm going to check again the method finalize into markdown_parser, maybe there is something hidden. It's weir because renderer = Redcarpet::Render::HTMLRouge.new(options) has hard_wrap: true and html = markdown.render(escaped_content) not, and if I add this line boom the code with the test. 
1.- I'm going to check the method finalize again into markdown_parse.
2.- Verify the algorithm to build code blocks.
For now, It would my task. Do you have anything else? I appreciate that.

**Comment by msarit** [comment]
Hi @redencion! :wave:
I'm checking in to see if you're still working on this PR? Please let us know if you have any questions or need some help. Thanks!

**Comment by redencion** [comment]
@msarit Sorry ,  I'm working not with this issue, if you want to change another no problem.

**Comment by citizen428** [comment]
Since the original author is no longer working on this and the PR is quite out of date now (see screenshot) I'll close this. Thanks again for your efforts @redencion!

image

**Pull request closed without merging**
