### PR TITLE
Explicitly adds the unique jobs middleware

### PR DESCRIPTION
**Pull request by fdoxyz**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

When in OSS Rotation we merged the `sidekiq-unique-jobs` [bump to 7.x](https://github.com/forem/forem/pull/12361) version but we missed [this note](https://github.com/mhenrixon/sidekiq-unique-jobs#add-the-middleware) that mentions we need to manually add the middleware in order for it to work properly (it wasn't this way before).

I realized the locks weren't being enforeced while working on [this spike PR](https://github.com/forem/forem/pull/12419)

## Related Tickets & Documents

#12361

## QA Instructions, Screenshots, Recordings

Add this dummy worker:

```ruby
class UniqueJobsWorker
  include Sidekiq::Worker

  sidekiq_options queue: :low_priority,
                  retry: 10,
                  lock: :until_executed,
                  on_conflict: :replace

  def perform
    puts "SiteConfig.app_domain: #{SiteConfig.app_domain}"
  end
end
```

Boot the app locally with `bin/startup` and in a separate console run this:

```ruby
3.times { UniqueJobsWorker.perform_in(3.seconds.from_now) }

# or in order to see the logs in the console run the following one liner:

UniqueJobsWorker.perform_in(3.seconds.from_now); UniqueJobsWorker.perform_in(3.seconds.from_now); UniqueJobsWorker.perform_in(3.seconds.from_now);
```

Due to the locks in place **the job should only run once**

### UI accessibility concerns?

None

## Added tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [x] I need help with writing tests

I tried adding tests to cover this situation but I haven't been able to make them work properly. If anyone has ideas on how to do this I'd be open to adding tests to add coverage to this situation. 

This is something that I tried (but didn't work):

```ruby
require "rails_helper"

class UniqueWorker
  include Sidekiq::Worker

  sidekiq_options queue: :low_priority,
                  retry: 10,
                  lock: :until_executed,
                  on_conflict: :replace

  def perform
    puts "SiteConfig.app_domain: #{SiteConfig.app_domain}"
  end
end

RSpec.describe UniqueWorker, type: :woker do
  describe "sidekiq-unique-jobs locks" do
    it "replaces previous jobs in the queue based on its lock + strategy" do
      allow(SiteConfig).to receive(:app_domain).and_return('STUB')

      UniqueWorker.perform_in(3.seconds.from_now)
      UniqueWorker.perform_in(3.seconds.from_now)

      sidekiq_perform_enqueued_jobs

      expect(SiteConfig).to have_received(:app_domain).once
    end
  end
end
```

## Added to documentation?

- [ ] [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/)
- [ ] README
- [x] No documentation needed

## [optional] Are there any post deployment tasks we need to perform?

None

## [optional] What gif best describes this PR or how it makes you feel?

did i do that

### CODE REVIEW

**Review by maestromac — APPROVED** [review]
Thanks for spotting this! LGTM!

**Review by mstruve — APPROVED** [review]
LGTM!

**Review by atsmith813 — APPROVED** [review]
🚀 

I wonder if the challenge of testing this is because the uniqueness is powered by Redis and we weren't stubbing that in the specs 🤔 

https://github.com/mhenrixon/sidekiq-unique-jobs/pull/25

But I believe the Sidekiq gem(s) has specs to test this functionality so maybe we're okay here?

**Review by citizen428 — APPROVED** [review]
@fdoxyz I'd be happy to trust the gem's specs and not re-test its functionality.

**Review by rhymes — APPROVED** [review]
Great catch @fdoxyz!

(I removed the label down here to wait for the US team to be online)

**Comment by fdoxyz** [comment]
Thanks everyone! I agree with the feedback about not having to test this, specially as it's a tricky one to do

Merging now 🚢

**Pull request merged**
