### PR TITLE
Fixing broken jest test

### PR DESCRIPTION
**Pull request by Rafi993**
## What type of PR is this?

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

It fixes broken test due to 24hr time format

## Related Tickets & Documents

closes https://github.com/forem/forem/issues/10141

## QA Instructions, Screenshots, Recordings
1. Run ```yarn test``` with 12hr time format in your system
1. Run ```yarn test``` again with 24hr time format in your system

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by rhymes** [comment]
@Rafi993 if you change your description to "Closes #10141" in the "Related tickets" section, it will close automatically the issue when merged 😊

**Comment by Rafi993** [comment]
> @Rafi993 if you change your description to "Closes #10141" in the "Related tickets" section, it will close automatically the issue when merged

oops sorry I forgot to add that.

**Comment by Rafi993** [comment]
> Thanks for this PR @Rafi993 
> 
> I'm not sure I'm reviewing your PR correctly, so I wanted to share what I'm doing.
> 
> I changed my Mac's time format to 24-hour, then set my DateTime to an evening hour. Running `date` in my Terminal showed that my system time was `22:46:11` (my actual time is `10:46AM`).
> 
> Then I ran the jest test you modified on `master` branch, and it is passing.
> 
> Could you perhaps include more detailed instructions for how to reproduce the failing spec? Thanks!

This what is happening for me

time_string

I'm not sure about mac though (since I use ubuntu)

**Comment by Rafi993** [comment]
since the snapshot test uses the function ```toLocaleTimeString``` it was failing

**Comment by Rafi993** [comment]
I found some reference here https://stackoverflow.com/questions/5471508/javascript-on-mac-safari-tolocaletimestring-oddities  (I think ideally it is better to mock that method in test)

**Review by vaidehijoshi — APPROVED** [review]
Thanks for this, @Rafi993 !

**Pull request merged**
