### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bilal1718**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x]  Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
 **Fixing "Back to Top" Anchor:**

This pull request addresses an issue where the "Back to Top" anchor link was not functioning as expected due to a casing mismatch between the anchor link and the id attribute of the corresponding anchor tag. 
The anchor link was using uppercase casing (#Table-of-contents), while the id attribute was in lowercase casing (#table-of-contents).

## QA Instructions, Screenshots, Recordings
https://github.com/bilal1718/forem/commit/06fa0c234192d0ea911b51acdae42d52103c819f

### CODE REVIEW

**Comment by rt4914** [comment]
@bilal1718 Thanks a lot for this nice fix. 
Before we approve this, can you please sign the CLA first. You can find details in this comment: https://github.com/forem/forem/pull/19962#issuecomment-1684922321

**Comment by bilal1718** [comment]
> @bilal1718 Thanks a lot for this nice fix. Before we approve this, can you please sign the CLA first. You can find details in this comment: [#19962 (comment)](https://github.com/forem/forem/pull/19962#issuecomment-1684922321)

Yeah Sure ! I will be waiting for approval.

**Review by dukegreene — APPROVED** [review]
Thanks for this!

**Review by benhalpern — APPROVED** [review]

**Review by klardotsh — APPROVED** [review]
Thanks! (and congrats on the first contribution to the repo)

**Comment by bilal1718** [comment]
> Thanks! (and congrats on the first contribution to the repo)

Thank you so much klardotsh ! Looking to contribute more

**Pull request merged**
