### PR TITLE
Remove code link style so it uses the default link color

### LINKED ISSUE #9603: Extra CSS style for <code><a href= links
Consider this:

```html
<code><a href="https://www.php.net/manual/en/function.set-time-limit.php">set_time_limit(10 * 60);</a></code>
```

or this code in editor:

```html
<a href="https://www.php.net/manual/en/function.system.php"><code>system()</code></a>
```

In output it shows a regular code chunk, without any indication it's actually a link, no underline, no hover effect. Consider adding some sort of indication it's a link (maybe dotted underline with some other background color for the ```<code>``` element?

### PR DESCRIPTION
**Pull request by Coteh**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Currently, the link color for the `code` element within articles is very similar to the color for normal `code` elements, making it hard to distinguish what is a link and what isn't. My solution is to remove the style that defines `code` links, so that it falls back to default color for links.

## Related Tickets & Documents

Fixes #9603

### Screenshots (changes outlined in red box)

**Before**
Screen Shot 2020-10-04 at 2 46 33 PM

**After**
Screen Shot 2020-10-04 at 2 43 40 PM

### Steps

Make an article with the following content:

```
<a href="https://www.php.net/manual/en/function.system.php"><code>system()</code></a>

<code>system()</code>

[`My Example`](https://example.com/)
```

First and third elements should have the blue link color (or whatever `--link-brand-color` var is set to)
The second element should be black color (assuming `--color-body-color` was not changed by the tester)

**edit:** Additional test case:

putting this in an article:
```
`My Example`
```
should still render default black color for `code` elements.

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Review by ludwiczakpawel — APPROVED** [review]
👍

**Review by rhymes — APPROVED** [review]
Thanks @Coteh!

**Comment by rhymes** [comment]
@Coteh please sign the above CLA so we can go ahead and merge your first contribution ;-) 🎉

**Comment by Coteh** [comment]
@rhymes Whoops did not realize I had to sign. Just signed. 👍

**Pull request merged**
