### PR TITLE
Remove navigation links from footer

### PR DESCRIPTION
**Pull request by citizen428**
## What type of PR is this? (check all applicable)

- [X] Refactor

## Description

Very recently we removed the navigation links from the site's footer for all private Forems. During the discussion for [RFC #238](https://github.com/forem/rfcs/pull/237#issuecomment-865236305) it was decided that we will completely remove them for all Forems, which this PR implements.

## Related Tickets & Documents

https://github.com/forem/rfcs/pull/237

## QA Instructions, Screenshots, Recordings

There should be no navigation links at the footer of the page.

**Before (on public Forem instances):**

image

**After (on public & private Forem instances):**

image

### UI accessibility concerns?

None

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

- [X] I will share this change internally with the appropriate teams

### CODE REVIEW

**Comment by citizen428** [comment]
I have a Cypress spec that now fails consistently on this branch both locally and on Travis. I'm a bit confused as it's supposed to the the links in the left sidebar, not the footer.

**Comment by rhymes** [comment]
@citizen428 I think `cy.findAllByText('Home').last().click();` is the culprit, maybe you can scope it down like with:

https://github.com/forem/forem/blob/a9e7bc4361d24eeb19ff1601996778852ec5472b/cypress/integration/navigationFlows/homePageLeftSidebar.spec.js#L11

**Comment by citizen428** [comment]
@rhymes That doesn't seem to change anything :-/ What really surprises me is that when I run the test locally at a certain step I end up on the Contact page with no sidebar menu:

image

**Comment by rhymes** [comment]
@aitchiss maybe you know what's happening here: https://github.com/forem/forem/pull/14041#issuecomment-865656722

😭

**Comment by aitchiss** [comment]
> Ok, this is not surprising after all, all nav links point to /contact which is a page that doesn't render a sidebar. I guess I just need to figure out why reloading the home page doesn't work, i.e. this part:

```
    cy.intercept('/?i=i').as('homepage');
    cy.findAllByText('Home').last().click();
    cy.wait('@homepage');
```

The Cypress log tells me:

`Timed out retrying after 4050ms: cy.click() failed because this element is not visible:`

Which is fair enough because the element isn't visible 😄  The test failure on surface level doesn't seem related to the changes in this PR, but I had a look at what link it was trying to click, and it was indeed targeting a footer link:

screenshot of the cypress output showing the Home link in the footer being clicked

A fun fact though is that `cy.findByRole...` only returns elements which are exposed in the accessibility tree, which means they are available to be interacted with. If we change that `findAllByText` line to:

```
cy.findAllByRole('link', { name: 'DEV(local) Home' }).first().click();
```

It will target the DEV logo in the top left corner, and click it successfully.

**Comment by citizen428** [comment]
Thanks @aitchiss!

**Review by rhymes — APPROVED** [review]
LGTM!!

**Review by aitchiss — APPROVED** [review]
looks good 👍

**Pull request merged**
