### PR TITLE
fix lazy-loaded multiple reaction icons joined by commas

### PR DESCRIPTION
**Pull request by yheuhtozr**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Reaction icons in lazy-loaded feed items are unexpectedly joined by commas, which makes the row of icons visibly bloat compared with server-rendered ones.

## Related Tickets & Documents

- Related Issue #19202
- Closes #

## QA Instructions, Screenshots, Recordings

Server-rendered reaction icon train:
server-rendered icons container: width = 87.5

Lazy-loaded reaction icon train:
JS-rendered icons container: width = 99.5

The latter has commas between spans:
inspector DOM panel, commas between spans

## Added/updated tests?

- [ ] Yes
- [X] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Review by jaw6 — APPROVED** [review]
@yheuhtozr Thanks for opening this PR! The change makes sense, but I'm having some difficulty replicating the bug and wonder if this is a browser issue? (So far, I have checked Firefox 110 and Chrome 111, and I am not seeing commas on either of those.)

**Review by rt4914 — CHANGES_REQUESTED** [review]
@yheuhtozr Agreeing with what @jaw6 said, I am unable to reproduce any visual change locally + there are no `,` between spans in current implementation too.

Can you please provide following details for more detailed review:
- Browser + its version
- Page on which you are testing it like http://localhost:3000/ or http://localhost:3000/username

@yheuhtozr Really appreciate you taking time and fixing this issue, we just want to to be sure where exactly is the issue. Thanks :-)

**Comment by yheuhtozr** [comment]
@jaw6 @rt4914 Hmm... that's interesting. The commas are inserted _only when_ you are logged in to the app.

1. log yourself in to https://dev.to
2. go to https://dev.to/ben
3. scroll down until lazy loading kicks in
4. inspect any multi-reactioned item

I'm browsing with Firefox 111 now, if this is of any help.

**Comment by jaw6** [comment]
Ah, yep, I see it now — this is in the "infinite scrolling" part of the front-end. @benhalpern is actually a good user to see it, the users I was testing with yesterday did not have posts on their "page 2" with multiple reactions, so it just wasn't visible.

Thanks again @yheuhtozr 🎉

**Review by rt4914 — APPROVED** [review]
@yheuhtozr  Really appreciate your work on this very-edge case bug.
Thanks a lot of the detailed steps for testing.
Screenshot 2023-04-04 at 10 32 49 PM

**Pull request merged**
