### PR TITLE
Tag Page partial UI updates

### LINKED ISSUE #19675: Hide tag weights and change negative weight tags to "Hidden tags"
## Is this feature related to a problem? Please describe.

- As a feed-consuming user, I want a simple means of hiding content I do not want to see in the feed. For example, if I am uninterested in javascript content, I can hide the `#javascript` tag.

## Describe the solution you’d like

This work targets two overall goals:

- Increase feed engagement and perceived feed quality by giving more control to users over what appears in their feed
- Improve the UX of the "Following tags" area in the user's dashboard by removing tag weights.

To reduce the complexity of this work, we will **continue to use the existing tag weights under the hood** and use the existing impact of negative tag weights on the feed (and nowhere new in the product, for the time being). In the future, we may split this work into its own logic and may apply it to other areas (e.g., notifications).

Feed modifications (using the existing feed variant mechanism) will happen in parallel with this work **but are NOT part of this issue**. It is imagined that the feed will now only interact with tag weights in a binary fashion (positive or negative) as opposed to using the tag-weighted value.

**This issue should not touch the feed algorithm or alter any feed math/calculations as this work should only touch the UI. QA may result in changing the tag weight to a <-1.** 

### Designs

Here is  the [Figma link](https://www.figma.com/file/nj32OuyDOR430frESjcOCM/Tag-Interaction?type=design&node-id=1637-1693&mode=design&t=1a924zsOXwQZJNSN-4) and below are small interactions to Hide/Unhide tag

Tag page

Following tags page 

## Definition of Done

- [x] Add a new section, "Hidden tags," to the Dashboard:
  - [x] All Tags that the user follows with a tag weight < 0 (i.e., negative) will now only appear within the "Hidden Tags" section.
  - [x] Within the "Hidden tags" section, each tag will be displayed with an "Unhide" button, which will remove the tag from the user's tag follows entirely.
  - [x] No feed weights will be displayed on Tags in the "Hidden tags" section.
- [x] Additionally, only Tags with Tag Weights >= 0 (i.e., 0 and positive) will appear in the "Following tags" section.
  - [x] Within the "Following tags" section, each tag will be displayed with an "Unfollow" button, which users can press to stop following the tag.
  - [x] Additionally, each tag will have a "Hide" option hidden beneath a meatball/three-dot button, which, when pressed, will set a tag weight of -1 on the tag (and consequently move the tag to the "Hidden tags" section).
  - [x] No feed weights will be displayed on Tags in the "Following tags" section. Existing tag weights will remain in the database in case we want to roll back this change for any reason.
- [x] On the Tags page (`/tags`), each Tag will show an additional "Hide" toggle, which will "follow" the tag for the user and set the tag weight to -1 on the tag. This will show for both "Top Tags" and the tag search results.
  - [x] The tags page will have a slight re-design to update the existing view and better support the new functionality
  - [x] On the Tags page, a tag can either be:
    - [x] Default, unfollowed and unhidden, in which both a "Follow" and "Hide" button will show
    - [x] Followed, in which a "Following" toggle button will show, which, when pressed, will unfollow the tag.
    - [x] Hidden, in which an "Unhide" toggle button will show, which, when pressed, will unhide the tag.

### PR DESCRIPTION
**Pull request by Ridhwana**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
In this PR we've updated the tags page UI partially. We've done the following: 
- Removed the color strip at the top in favour of the # being colored. 
- Have the buttons always be at the bottom of the card
- Remove the rotation of the badge and allow it to be inline with the button. As a result also reduce the size of the badge. 
- Change the Title from Top Tags to Tags 
- Add a formatted published count
- Move the post count to the top right and remove the word published. 

**_Things that have not been implemented in this PR:_**
**_- I've not made all the changes to the buttons (i.e. their style and color), especially the secondary button as this is a bigger change that comes with some gotchas that I will outline in the issue._** 

## Related Tickets & Documents

- Related Issue #https://github.com/forem/forem/issues/19675
- Closes

## QA Instructions, Screenshots, Recordings

Load up the /tags page and ensure that the UI changes look fine. 

Before:
Screenshot 2023-07-31 at 11 23 04

After: (On prod these tags will have descriptions!)
 
Screenshot 2023-08-04 at 13 50 30

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [axe DevTools](https://www.deque.com/axe/) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

_For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: UI changes
- [ ] I need help with writing tests

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by Ridhwana** [comment]
Closed and re-opened to see if it will help the PR to deploy to successfully deploy to  Uffizi.

**Comment by Ridhwana** [comment]
Waiting for the [strong_migrations revert](https://github.com/forem/forem/pull/19870) to fix Uffizi deploys for Qa

**Comment by Ridhwana** [comment]
I did something a bit wonky with my commits, but it should be okay because we squash and merge.

**Comment by dukegreene** [comment]
I'm getting a decoding error when I try visiting /tags on Uffizzi...
Screenshot 2023-08-02 at 10 15 53 AM

**Comment by Ridhwana** [comment]
Yes sorry! @anujbhavsar96 brought this up earlier, I'm going to move it into draft until I figure out whats happening with Uffizi! Thnaks @dukegreene

**Comment by Ridhwana** [comment]
OK @anujbhavsar96 and @dukegreene I fixed the error on Uffizi, sorry about that!

**Comment by anujbhavsar96** [comment]
@Ridhwana This looks great overall ✨. Just a few small changes,

1. Follow/Following button has more height _(48px instead of 40px)_ in the case when there is an image on the right side.
2. If we can have 4 column layout, that would be great for tags visibility since we will be able to accommodate more tags in one view
3. We can change the order of the Search input field and the `Following tags` link. We can keep the Search field on the rightmost side.

One last good to have if possible - Can we have one space between `#` and `Tag name` - E.g. `# design` instead of `#design`

**Comment by Ridhwana** [comment]
Thanks @anujbhavsar96, apologies that I missed these. 

- [x] 1. Follow/Following button has more height _(48px instead of 40px)_ in the case when there is an image on the right side.
- [x] 2. If we can have 4 column layout, that would be great for tags visibility since we will be able to accommodate more tags in one view
- [x] 3. We can change the order of the Search input field and the `Following tags` link. We can keep the Search field on the rightmost side.


As per our discussion on Slack: I
- I did not implement the space between `#` and `Tag name` because the helper is being used everywhere. 
- [x] We need to keep the card height fixed. There can be 4 scenarios based on the description.
- [x] Also 14px font size for description

**Review by anujbhavsar96 — APPROVED** [review]
LGTM 🚀

**Review by dukegreene — APPROVED** [review]
Looks great! super classy ✨mobile views lining up nice too

**Review by maestromac — APPROVED** [review]
Nice, tested on Uffizi. LGTM!

**Pull request merged**
