### PR TITLE
Cleanup unused DataUpdateScripts

### PR DESCRIPTION
**Pull request by atsmith813**
## What type of PR is this? (check all applicable)
- [x] Refactor

## Description
[In the removal of Elasticsearch](https://github.com/forem/forem/pull/13606), we basically rendered several DataUpdateScripts useless. We do not have a way to cleanly remove the files. This PR removes the files and includes a `DataUpdateScript` of its own to delete the existing and now unused `DataUpdateScript` records.

We can't delete the file by themselves because then the file tree (the source of truth for DataUpdateScripts) falls out of sync with the database on each instance of Forem.

In the `DataUpdateScript` code, we compare the number of files to the DB on the instance as a core piece of logic in how the scripts work:

https://github.com/forem/forem/blob/73529e71ebd443e2e876ecbfe18fb97d47acc2f1/app/models/data_update_script.rb#L23

The "ideal" solution probably involves updating the logic on `DataUpdateScript` to handle the case of unused scripts. I originally started to remove only the scripts related to Elasticsearch. Then I found a handful of unrelated, but also unused scripts so I figured I'd clean them all up in one swoop.

Technically, the script introduced in this PR will also become useless after it runs...I figured 1 useless script is easier to clean up later with a `DataUpdateScript` refactor vs 34 useless scripts (which this PR removes). I wanted to do this now while all the Elasticsearch context is fresh. It also seems some folks feel pretty strongly about these useless scripts hanging around in the codebase.

## Related Tickets & Documents
https://github.com/forem/forem/pull/13606
https://github.com/orgs/forem/projects/29#card-60117098 (see the last bullet)

## QA Instructions, Screenshots, Recordings
1. Run `rails data_updates:run` locally and make sure there are no errors 🎉  

## Added tests?
- [x] Yes

## [Forem core team only] How will this change be communicated?
- [x] I will share this change internally with the appropriate teams

## [optional] Are there any post deployment tasks we need to perform?
Check the Forem instances to ensure the scripts were deleted from the DB

finger_scissors

### CODE REVIEW

**Comment by djuber** [comment]
It's funny that we only perform the `scripts_to_run?`  "count script files, db scripts, and see if there are pending scripts to run" check in dev - I think the DataUpdateWorker is used in prod post-deploy just calls `scripts_to_run` which inserts/enqueues and then processes the pending scripts rather than warning and requiring manual action. 

Is the reasoning ~that starting the app via the Procfile starts both sidekiq and the puma/rails-server processes, and it's not feasible to have the update scripts only run on one of the two (right now the check is performed in the environment file)~ (edit: no, we only perform this check for console, server, and db consoles, sidekiq is not affected), or that the surprise delay in dev after a fetch/checkout would be a problem? I don't know what the overhead of always enumerating the files is - I feel like I personally don't start the rails _that_ much but fully sympathize with either a desire to make "you will be changing your database with the next command" an explicit action by a human, or a desire to keep the startup time minimal.  

It sounds like we maybe already had a problem around switching branches with the existing method- since the script table wasn't getting branch-local update scripts purged when you switched back (or checked out an earlier version) and the file count and script table count could have differed because you moved backward in time rather than forward? The blind spot would appear when you were simultaneously working in dev (same table) on two branches with two scripts - running the updates on the first branch would hide the existence of the update from the second branch.

Assuming "lets make different checks at startup" is not in the cards - this is a totally reasonable cleanup.

**Review by djuber — APPROVED** [review]

**Review by citizen428 — APPROVED** [review]
👋 Give this man an award!

**Review by rhymes — APPROVED** [review]
Awesome idea!

**Comment by atsmith813** [comment]
@djuber your thinking is spot on! If I understand correctly and if I recall correctly (arguably some BIG ifs 😅 ) a lot of the inspiration for this setup was Rails migrations. One idea to update how these scripts work to better handle this case is to create a sort of "schema" file that will be a source of truth. If you delete a script, it gets deleted from the schema, and we use that for the logic.

Changing branches and such was definitely one of the cases that prompted this setup. And like migrations, I think it was decided that a "harsh" prompt for user action was "safer" than "automatically" modifying local data.

**Comment by citizen428** [comment]
@atsmith813 While this was inspired by Rails migrations we did add the check around the number of script files, which migrations don't have. A schema may be hard, as that's there's no underlying structure to the sort of data a DUS may manipulate.  This discussion gave me a fun idea though: https://github.com/forem/forem/pull/13653

**Pull request merged**
