### PR TITLE
Update Bootstrap from 4.4.1 to 4.5.3

### LINKED ISSUE #17204: Use latest version of jQuery
### Describe the task

Use latest version of jQuery 3.6.0.

### PR DESCRIPTION
**Pull request by tnir**
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>

## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Optimization

## Description
Updates Bootstrap from 4.4.1 to 4.5.3 on `/admin` to update jQuery from 3.4.1 to 3.5.1.

## Related Tickets & Documents

- Bootstrap 4.5 docs: https://getbootstrap.com/docs/4.5/getting-started/introduction/
- jquery@3.4.1 vulnerabilities (snyk): https://snyk.io/vuln/npm:jquery@3.4.1
- Related Issue #17337
- Closes #17204

## QA Instructions, Screenshots, Recordings

Access to `/admin` on a test instance to confirm if there is no regression.

### UI accessibility concerns?

No regression should be confirmed.

## Added/updated tests?

- [x] No, and this is why: dependency update

### CODE REVIEW

**Comment by jeremyf** [comment]
@tnir I think you'll need to merge main into your branch.  PR #17390 addresses the breaking build

**Comment by tnir** [comment]
@jeremyf Thanks, I just did it.

**Review by aitchiss — APPROVED** [review]
TBH we're in the process of weeding out Bootstrap from the app, so we haven't really been looking to update it.

In saying that though, I don't see any problem with this upgrade in the meantime 🙂

**Comment by tnir** [comment]
> [...] we're in the process of weeding out Bootstrap from the app [...]

I noticed it while creating this PR etc. (from https://github.com/forem/forem/blob/92030f47988c5fa48b26a81b914fe3f102a061d5/app/assets/stylesheets/config/_import.scss#L163 (added in #16339)), but I was not able to see `https://forem-team.slack.com/archives/C01K9U7UATV/p1642687819005100`, so merging this PR would be much faster to address the 2 following vulnerabilities:

- https://security.snyk.io/vuln/SNYK-JS-JQUERY-567880
- https://security.snyk.io/vuln/SNYK-JS-JQUERY-565129

**Review by jeremyf — APPROVED** [review]

**Pull request merged**
