### PR TITLE
Opt in settings for Ahoy Tracking

### PR DESCRIPTION
**Pull request by fdocr**
## What type of PR is this? (check all applicable)

- [x] Optimization

## Description

Allows for admins to opt-in Ahoy Tracking

## Related Tickets & Documents

- Closes https://github.com/forem/forem-internal-eng/issues/524

## QA Instructions, Screenshots, Recordings

1. As an Admin visit `/admin/customization/config` and ensure Ahoy Tracking is disabled by default
2. Check in rails console the current amount of Ahoy events with `Ahoy::Event.count`
3. In an incognito window
   - Open the main feed
   - Click on any "Create Account" link
   - Check `Ahoy::Event.count` and it should've increased (we currently track this action)
4. Go back to the settings and disable Ahoy tracking
5. Restart the local server & open an incognito window again
   - Open the main feed
   - Click on any "Create Account" link
   - Check `Ahoy::Event.count` and it should remain the same (tracking was disabled)
6. You may want to enable tracking, restarting the server and trying again to ensure it works again if toggled back on

### UI accessibility concerns?

None: Using the same UI building blocks already implemented in the admin section

## Added/updated tests?

- [x] Yes

## [Forem core team only] How will this change be communicated?

- [x] I will share this change internally with the appropriate teams

## [optional] Are there any post deployment tasks we need to perform?

Enable this config in DEV & possibly in Codenewbie forem too

## [optional] What gif best describes this PR or how it makes you feel?

Geico gecko sailing

### CODE REVIEW

**Review by jaw6 — APPROVED** [review]

**Review by maestromac — APPROVED** [review]
LGTM!

**Comment by maestromac** [comment]
I marked this as draft to prevent accidental merges are we need to update config on DEV.

**Comment by mirie** [comment]
@maestromac what are the next steps (and who does it) for completing this work? (For example can @fdocr do the config updates?)

**Comment by fdocr** [comment]
Merging now @mirie, knowing that we should have admins online today in order to enable the configuration (compared to Friday afternoon).

> For example can @fdocr do the config updates?

I won't be able to make any of these changes. They can be done via console (admin Heroku access) or any Admin on the site itself (`/admin/customization/config`)

**Pull request merged**
