### PR TITLE
Fix "Unable to load Comment Subscription component"

### LINKED ISSUE #12545: "Unable to load Comment Subscription component"
**Describe the bug**

image

It's been happening quite often recently for me but I can't really tell how exactly this should be reproduced. It does work after refreshing the page, but then when I go to another post it's broken again.

Also, this is what's happening in the console:

image

**To Reproduce**

See above.

**Expected behavior**

Fo this component to work properly :)

**Screenshots**

See above. 

**Desktop (please complete the following information):**

n/a

**Smartphone (please complete the following information):**

n/a

### PR DESCRIPTION
**Pull request by javila35**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
This PR fixes the console error described in [the issue](https://github.com/forem/forem/issues/12545) by changing the `const` declaration to `var`. I was unable to replicate the UI bug without repro steps. 

The `changePage` function in `base.js.erb` sending over the `user_subscription_tag` when it's called, and declaring the `subscribeBtn` as a const was causing the error. I'm not familiar with liquid tags, but it seems that the other liquid tags that use JS declare variables with `var` instead of ES6.

## Related Tickets & Documents
Resolves #12545 

## Added tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [x] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Review by rhymes — APPROVED** [review]
Hi @javila35, I think your reasoning make sense!

This script is injected in 

https://github.com/forem/forem/blob/66c05db0daac4dcb599988d62c43c7e73ad0491a/app/views/articles/show.html.erb#L251

**Comment by rhymes** [comment]
@nickytonline I'm cc @atsmith813 who might know how we're using it. That said I don't think there's any reason to have multiple instances of that liquid tag inside a post. We might want to add a validation to limit it to one max. 

I would move ahead with this PR in the meantime

**Comment by atsmith813** [comment]
@rhymes @nickytonline oof, this is going back to open quite the can of worms. Some of what I'm about to mention doesn't necessarily have to apply to this PR, but I'm including it for posterity's sake. There are a few things going on here...

**1. If we are going to update the script, we may want to consider busting the cache for articles that have this liquid tag using a data update script. If we don't mind this fix taking time, we can let the caches take care of themselves over time.**
2. It's not ideal that we load all custom liquid tag scripts on every article, regardless of if the liquid tag is used or not. This is something we hope to change at some point.
3. IIRC, we did intend to allow multiple uses of user subscription liquid tags in the same article. I'm not opposed to updating that and putting validation to restrict to only one use per article.
4. I don't think this will entirely solve all issues since we use `getElementById`. If there were multiple liquid tag instances in an article, this wouldn't work as expected even switching to `var`.
5. The unique dom element ID issue as @nickytonline mentioned I believe is an issue for multiple liquid tags - I don't think we have a standard in liquid tags to deal with this.
6. The user subscription liquid tag is restricted to certain roles. It was originally designed for use in CodeLand and isn't used much otherwise.

**Comment by javila35** [comment]
Hey, it's been about a week and I wanted to check in on this. Seems like there is a conclusion of accepting this request, and examining liquid tags at a higher level.

**Comment by nickytonline** [comment]
Thanks for chiming in @atsmith813 and @rhymes! Given that there is some more work to be done for this but in a separate PR most likely, are we OK with going with this fix for now?

Also, for busting the cache, I imagine we could do that in a separate PR or did you mean doing it as a post deployment step @atsmith813?

**Comment by atsmith813** [comment]
> What are some deal-breaking characteristics you look for in a new hire?

Sounds good to me!

> Also, for busting the cache, I imagine we could do that in a separate PR or did you mean doing it as a post deployment step @atsmith813?

@nickytonline it may need to be a data update script with this PR. Those scripts are loaded on _every_ article 😭 . I don't quite recall how the caching of the scripts themselves works now since the removal of service workers. I remember those gave us many issues with loading stale scripts. I suspect we may want to bust the cache for every article that uses this tag so that they render the new script included in this PR.

That said, I'm not sure this "issue" is a "big deal". We could probably just deploy at is, understanding the fix may not show right away because of caching, but it will eventually once the caches expire.

cc: @jgaskins

**Comment by rhymes** [comment]
@nickytonline I vote for going ahead with this and dealing with the rest separately as it'd require a much bigger refactoring

**Review by nickytonline — APPROVED** [review]
Thanks for the fix! 🛳

**Comment by nickytonline** [comment]
> > What are some deal-breaking characteristics you look for in a new hire?
> 
> 
> 
> Sounds good to me!
> 
> 
> 
> > Also, for busting the cache, I imagine we could do that in a separate PR or did you mean doing it as a post deployment step @atsmith813?
> 
> 
> 
> @nickytonline it may need to be a data update script with this PR. Those scripts are loaded on _every_ article 😭 . I don't quite recall how the caching of the scripts themselves works now since the removal of service workers. I remember those gave us many issues with loading stale scripts. I suspect we may want to bust the cache for every article that uses this tag so that they render the new script included in this PR.
> 
> 
> 
> That said, I'm not sure this "issue" is a "big deal". We could probably just deploy at is, understanding the fix may not show right away because of caching, but it will eventually once the caches expire.
> 
> 
> 
> cc: @jgaskins 
> 
> 

I think as @rhymes mentioned, we can go ahead with the fix and address the cache busting among other things in a separate PR(s).

As you mentioned @atsmith813, this tag probably isn't used in a lot of posts.

**Pull request merged**
