### PR TITLE
fix scroll when popstate from a full screen code block

### LINKED ISSUE #19662: Can't scroll after return to contents page from Enter full screen mode
**Describe the bug**

Can't scroll after return to contents page from Enter full screen mode

**To Reproduce**

1. Go to any content inside that have code
2. Enter fullscreen mode
3. Go back to content (press back in your browser)
4. Booom. Can't scroll. also go back two steps.(technically one step but user can feel like two step)

**Expected behavior**

**Screenshots**

https://github.com/forem/forem/assets/85778639/506346c2-8a69-4cf3-ae3c-0d233bf94df3

**Desktop (please complete the following information):**

- OS, version: macOS Monterey, 12.6.5
- Browser, version: Chrome, 114

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

### PR DESCRIPTION
**Pull request by zhangted**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Going back from full screen code block leads to inability to scroll 

## Related Tickets & Documents

- Related Issue #19662 
- Closes #19662 

## QA Instructions, Screenshots, Recordings

https://github.com/forem/forem/assets/24551335/8ff57bb3-8040-4a5e-8ec6-617dee6b12c9

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [axe DevTools](https://www.deque.com/axe/) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

_For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: none captured on[ original MR](https://github.com/forem/forem/pull/10784/files#diff-61242fe8a8d5914cb2fc6d1adcfe57a30d556ca1544a1853f2f3c2d70c7c49eb)
- [ ] I need help with writing tests

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by PhilipHow** [comment]
@zhangted can you comment on https://github.com/forem/forem/issues/19662 so I can assign you?

**Review by rt4914 — COMMENTED** [review]
@zhangted Thanks a lot for the contribution.
For this functionality, you will need to add few tests. You can do that by creating a new file under `app/javascript/utilities/__tests__/` folder.

Let us know if you need any help.

**Comment by zhangted** [comment]
@rt4914 Sure, gave it a go and added some tests

**Review by rt4914 — APPROVED** [review]
Overall looks good to me. Thanks.

**Review by filleduchaos — APPROVED** [review]
Thank you for your PR 🎉 I'm approving this but looking at the bug & your implementation, I think we might be solving for the wrong thing. I think the back button _shouldn't_ take you out of the article in the first place - it was certainly confusing for me (outside of the scroll bug) that swiping back didn't just dismiss the fullscreen code popup like hitting the `Esc` key does.

@PhilipHow do we actually want to exit the article when a user "goes back" in fullscreen mode? If not, we could merge this anyway as a start and/or if @zhangted feels up for it they could pick up that fix as well

**Comment by PhilipHow** [comment]
> Thank you for your PR 🎉 I'm approving this but looking at the bug & your implementation, I think we might be solving for the wrong thing. I think the back button _shouldn't_ take you out of the article in the first place - it was certainly confusing for me (outside of the scroll bug) that swiping back didn't just dismiss the fullscreen code popup like hitting the `Esc` key does.
> 
> @PhilipHow do we actually want to exit the article when a user "goes back" in fullscreen mode? If not, we could merge this anyway as a start and/or if @zhangted feels up for it they could pick up that fix as well

@filleduchaos I *think* I'm happy with this - in my mind, you're still "on" the page, and anything else is overriding the default back button behavior. This is also how a full-screen YouTube video works.

**Pull request merged**
