### PR TITLE
Fixes forem-docs #127: References to rtx are out-of-date

### PR DESCRIPTION
**Pull request by medwards1771**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation Update

## Description
This PR
- renames the config file `.rtx.toml` to `.mise.toml`
- updates references to `rtx` to `mise`

## Related Tickets & Documents

- Related Issue: https://github.com/forem/forem-docs/issues/127

## QA Instructions, Screenshots, Recordings

Verify this change works as expected by running `mise install` or `mise doctor` from this branch.

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [ ] Yes
- [x] No, and this is why: documentation update
- [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?
I didn't find a script that runs `rtx install` for deployment, so I don't believe so.

### CODE REVIEW

**Review by benhalpern — APPROVED** [review]
Thank you!

**Comment by medwards1771** [comment]
@benhalpern is there a way for me to retry the failing cypress CI steps? if not, do you mind re-running them?
i wonder if the `error: getaddrinfo ENOTFOUND api-disabled-for-fork.knapsackpro.com` can be resolved with a simple retry.

**Review by maestromac — APPROVED** [review]
Thank you for this! LGTM

**Comment by maestromac** [comment]
@medwards1771 let me retry it for you.

**Pull request merged**
