### PR TITLE
Placeholder assets

### PR DESCRIPTION
**Pull request by ludwiczakpawel**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

This PR introduces placeholder images for:

- mascot user,
- social media image
- icon (PWA etc)

## Related Tickets & Documents

- https://github.com/forem/InternalProjectPlanning/issues/94
- https://github.com/forem/InternalProjectPlanning/issues/92
- https://github.com/forem/InternalProjectPlanning/issues/93

## QA Instructions, Screenshots, Recordings

**Mascot user:**

mascot

**Social media image:**

social-media-cover

**Icon:**

icon

## Added tests?

- [ ] yes
- [x]  no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by lisasy** [comment]
@ludwiczakpawel Looks good to me!

Random little workflow hack in the "Related Tickets & Documents" section of this PR:

I believe that if you add the word "Close" before each related ticket, it will link **_this_** PR to **_that_** issue and automatically move the issue to "Done" board once this is merged.

It would look like this:

- Closes https://github.com/forem/InternalProjectPlanning/issues/94
- Closes https://github.com/forem/InternalProjectPlanning/issues/92
- Closes https://github.com/forem/InternalProjectPlanning/issues/93

**Review by lisasy — APPROVED** [review]
LGTM

**Review by Zhao-Andy — APPROVED** [review]
LGTM! I'm guessing a follow up PR will use these files?

**Comment by ludwiczakpawel** [comment]
@lisasy correct, im aware of _closes_ keyword but i haven't used it intentionally since these PRs will be handed over to dev stage after my part is done - so not really "closed" :D 

@Zhao-Andy correct, sir.

**Review by vaidehijoshi — COMMENTED** [review]
@ludwiczakpawel have these images been run through an optimizer? I suggest using https://tinypng.com :)

**Comment by ludwiczakpawel** [comment]
@vaidehijoshi Yeap, I've run them through [ImageOptim](https://imageoptim.com/). I did a test out of curiosity:

File | Original | TinyPNG | ImageOptim
------|------|------|------
Icon | 14kb | 6kb | **4kb**
Mascot | 18kb | **8kb** | 11kb
Cover | 34kb | **12kb**  | 13kb
Overall | 66kb | **26kb** | 28kb

TinyPNG performed slightly better so I'll be using this one from now on :) Since this PR has been already merged (and the gain is actually minimal) I will probably never get back to reoptimizing these 3 assets :D

**Pull request merged**
