### PR TITLE
Modify codepen_tag to parse public and private Pen urls

### PR DESCRIPTION
**Pull request by quezo**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
CodePen has public and private Pen URLs but the `codepen_tag` class only parses public URLs. This PR allows the `codepen_tag` class to parse private URLs as well. This PR updates the `URL_REGEXP` used to parse public and private URLs. I added tests with real private URLs to prove the change works.

## QA Instructions, Screenshots, Recordings

Run rspec tests for `spec/liquid_tags/codepen_tag_spec.rb` unit test added in this PR.

### UI accessibility concerns?

None

## Added tests?

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [x] This change does not need to be communicated, and this is why not: The post editor already parses CodePen URLs. A write would expect both private and public URLs to be parsed. At the moment the post editor raises an error. This should resolve that error.

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Review by rhymes — COMMENTED** [review]
Hi @quezo!

I don't think this can work. 

Codepen private URLs can't be accessed from the outside, so the DEV/Forem server can't fetch them.

If I open either of these two URLs from my computer I get a 404:

- https://codepen.io/team/codepen/pen/fb02c34281cb08966ec44b4e1ae22bi7
- https://codepen.io/quezo/pen/e10ca45c611b2cf3c98a1011dpdc1471

Screenshot 2021-04-23 at 10 14 15 AM

and I guess you would too if you navigated in incognito mode.

Sorry @quezo! I'm going to close this PR but thanks for your contribution! If you would like to keep contributing we have a [few open bugs](https://github.com/forem/forem/issues?q=is%3Aopen+is%3Aissue+label%3A%22ready+for+dev%22) and some even related to [liquid tags](https://github.com/forem/forem/issues?q=is%3Aopen+is%3Aissue+label%3A%22ready+for+dev%22+label%3A%22area%3A+liquid+tags%22), [one is about CodePen itself](https://github.com/forem/forem/issues/12130).

**Comment by shshaw** [comment]
I think the included links are actual 404s. 

Here's are two example Private Pens that works, tested in Incognito Mode

https://codepen.io/team/codepen/pen/91719bd6e4845219735d7bfd53f614ab
https://codepen.io/shshaw/pen/17ecdb8563a4295d9d6521f88270d919

**Comment by rhymes** [comment]
Oh, thanks @shshaw, I thought "private" meant... private :)

**Comment by shshaw** [comment]
Yeah; Privacy on CodePen means:
1. Not publicly listed or search indexed
2. Obfuscated URL

If you share the URL with someone or embed that URL, it can still be viewed.

https://blog.codepen.io/documentation/private-items/#can-i-still-share-my-private-work-6

Thanks @rhymes!

**Comment by quezo** [comment]
Hey @rhymes I pushed real URLs to real Pens. Thanks for the review on this PR. I think it's ready to merge. 

I'll take a look at this [CodePen bug itself](https://github.com/forem/forem/issues/12130).

**Review by djuber — APPROVED** [review]
Thanks for this, @quezo

Makes sense, test coverage looks like what we had for public links, and I spot checked the private links in the examples were valid, to verify the format.

**Review by aitchiss — APPROVED** [review]
Tested this locally and it worked great 🎉

**Comment by aitchiss** [comment]
Thanks for the contribution @quezo!

**Pull request merged**
