### PR TITLE
Fix: Broken links after username change

### LINKED ISSUE #13663: Dashboard: article links break after username update
**Describe the bug**

When we change our username. links of old article break in dashboard. For example if you change your username from abc to xyz, links of old article change from dev.to/abc/hiii-devs(Working) to dev.to/xyz/hiii-devs(Not Working) in dashboard.

**To Reproduce**

To Reproduce
1. write some articles
2. change your username
3. Now if you go in dashboard and try to open or edit article it will show you an 404 error.

**Expected behavior**
Article link remain same and edit link update after username change.

Can you assign this to me?

### PR DESCRIPTION
**Pull request by NV404**
Solving issue #13663
Article links break after username update.

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Fixes #13663. Changed links to work after username update.

## Related Tickets & Documents

#13663

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://docs.forem.com/frontend/accessibility)._

## Added tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Review by rhymes — COMMENTED** [review]
Hi @NV404 thanks for the PR! I don't think this is the correct fix though for two reasons:

- if the article belongs to an organization, `current_state_path` will point to the wrong URL

https://github.com/forem/forem/blob/47908d7a876f938d39a664c02227e54a597236be/app/models/article.rb#L370-L372

- I think the actual fix is figuring out why `article.path` isn't correctly saved when the username changes

This is where the article "recomputes" its path:

https://github.com/forem/forem/blob/47908d7a876f938d39a664c02227e54a597236be/app/models/article.rb#L512

which is called from 

https://github.com/forem/forem/blob/47908d7a876f938d39a664c02227e54a597236be/app/models/article.rb#L97

So (a guess), maybe what's happening here is that changing the username is not re-saving the articles correctly, so that they can store the correct path.

This is probably a place to start the investigation: 

https://github.com/forem/forem/blob/47908d7a876f938d39a664c02227e54a597236be/app/models/user.rb#L624

Thank you!

**Comment by aitchiss** [comment]
Hi @NV404 👋  just checking to see if you are still working on this PR, and if we can offer any more assistance?

**Comment by citizen428** [comment]
Hi @NV404 and thanks for your contribution. I just wanted to check-in to see if you are still working on this PR, and if you need any help from us?

**Comment by aitchiss** [comment]
Hi @NV404 👋  I'm going to go ahead and close this PR for the time being, as we're not sure if it's still being worked on. We'd really love to have your contribution, and if you would like to continue work on this based on the feedback above please do go ahead and re-open the PR 😄 

We understand you might be too busy at the moment, and that's absolutely fine too. We look forward to any future contribution you make and thanks again for your efforts here ✨

**Pull request closed without merging**
