### PR TITLE
homepageFeed: Add null checks in cases where there's no featured story present

### PR DESCRIPTION
**Pull request by kirananto**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

During the initial setup, if there are no featuredArticles, the UI breaks. so to avoid this particular scenario I'm adding null checks at appropriate places.

## Related Tickets & Documents

N/A

## QA Instructions, Screenshots, Recordings

Try setting up a brand new dev environment without any featured article, to reproduce this particular bug

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## Are there any post deployment tasks we need to perform?

N/A

##  What gif best describes this PR or how it makes you feel?

Undefined error

### CODE REVIEW

**Comment by citizen428** [comment]
> no, because they aren't needed

For bug fixes I'd very much like to see a regression spec.

**Comment by kirananto** [comment]
I'm still new to the codebase, It'd be nice if you could direct me to where the spec files are for the homepageFeed.jsx
I couldn't find one for the homepage, Frontend part.

**Comment by citizen428** [comment]
Tbh, I'm not overly familiar with the JS part of the app myself, it was more a general comment. @nickytonline should know better, or maybe not even want a spec for this.

**Comment by nickytonline** [comment]
There is supposed to always be a featured article. Even with the seed data we always end up with one. I'm trying to remember the criteria in the backend for this though. @joshpuetz would know.

**Comment by joshpuetz** [comment]
That's right: we also set the featured story to SOMETHING on the backend:

https://github.com/forem/forem/blob/master/app/services/articles/feed.rb#L22

I'm certainly not opposed to checks on the client though: I'm curious if a missing featured story is a hypothetical situation, or something you're seeing running locally @kirananto ?

**Comment by kirananto** [comment]
@joshpuetz  Nope, it is definitely something that I see on my local, There was no seed data on initial setup, So I manually created a post, but then it was not showing up due to this breaking... 

I suggest you have this check just to make sure UI doesn't break at any point. I usually try to make clients as fail-proof as possible, and in such cases where you expect it to be there and it doesn't we can always push an analytics/sentry data to inform the concerned team right? So that we can handle it better next time 👍

**Pull request merged**
