### PR TITLE
Check github actions weekly with dependabot

### PR DESCRIPTION
**Pull request by jlosito**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This allows dependabot to check github actions which this project uses and submit PRs with version bumps.

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-actions-up-to-date-with-dependabot

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how accessibility is impacted and tested. For more info, check out the [Forem Accessibility Docs](https://docs.forem.com/frontend/accessibility)._

## Added tests?

- [ ] Yes
- [x] No, and this is why: This does not necessarily add or remove any *code* which would require tests.
- [ ] I need help with writing tests

## Added to documentation?

- [ ] [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/)
- [ ] README
- [x] No documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Review by rhymes — COMMENTED** [review]
Hi @jlosito, thanks for your contribution, I'm down to test this new dependabot functionality:


Could you add a comment to it explaining what it does? 

Something like:

```yaml
# Set update schedule for GitHub Actions
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-actions-up-to-date-with-dependabot

... the rest of the file ...
```

thank you!

**Comment by jlosito** [comment]
Dependabot will check weekly all of the github actions which this project uses and submit PRs if there's a version bump to any of them. This could also be expanded for the ruby gems of this project with a bundler package-ecosystem block.

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem

This project uses the checkout github action linked below as well as other github actions. The linked action already looks to be the [latest](https://github.com/marketplace/actions/checkout?version=v2.3.4) so it will simply be overlooked.

https://github.com/forem/forem/blob/master/.github/workflows/codeql-analysis.yml#L28

Let's pretend that this action was not not up-to-date, v1.x.x, dependabot would have submitted a PR like the following.

https://github.com/dependabot/dependabot-core/pull/2818

Note that I believe depedabot will already submit PRs for packages it finds to have security vulnerabilities. This is usually turned on by default. In other words,  I believe dependabot will already submit PRs for package bumps which have security vulnerabilities without this change. This change causes dependabot to submit PRs with version bumps regardless of security vulnerabilities but rather as soon as a new version of a github action is released.

**Comment by rhymes** [comment]
Thanks for the explanation! Please add the comment to the file, it'll help people in the future knowing what that action is for :)

**Review by rhymes — APPROVED** [review]

**Comment by rhymes** [comment]
Thank you @jlosito!

**Review by benhalpern — APPROVED** [review]
Nice PR

**Pull request merged**
