### PR TITLE
Make listing details modal close on internally-triggered navigation

### LINKED ISSUE #14459: Listing details modal doesn't close on navigation event triggered from it
**Describe the bug**

⚠️ _This might be a feature not a bug, though it's quite confusing so I'm reporting it anyway to figure out if the described behavior expected or not_

When a user goes to the Listings page and opens a modal for one of the available listings, they can click a category link at the bottom to navigate to the corresponding listing category (filter the list out in fact). This action should close the modal to actually communicate that the navigation event has happened, but the modal stays open and the navigation (including the URL change) happens on the background which is hardly distinguishable. 

**To Reproduce**

1. On the main page (dev.to) click `See all` in the Listings block to navigate to the Listings page
Screenshot 2021-08-10 at 16 29 37

2. Click on the title of some of the displayed listings to open the details modal
Screenshot 2021-08-10 at 16 30 10

3. Click on the category link at the bottom of the modal 
Screenshot 2021-08-10 at 16 30 56

4. Navigation happens, URL changes (correctly), **_modal stays open_**

**Expected behavior**

_Modal window should close on the navigation event and user should be navigated to the route they expected to get to (the clicked listing category)._

**Desktop (please complete the following information):**

- OS, version: macOS 10.15.7
- Browser, version: (browser-independent) Brave, Chrome, Safari, Firefox

**Smartphone (please complete the following information):**

- Device: iPhone
- OS, version: iOS 14.7.1
- Browser, version: (browser-independent) Brave, Safari

**Additional context**

When user has the modal opened and navigates using browser controls (back/forward) the URL change doesn't follow the actual route/page change. So this issue probably requires some additional attention in terms of router behaviour.

_The issue is especially blocking on mobile devices - as the modal is full-screen there, clicking the category link doesn't lead to anything visually distinguishable at all._

Also, talking about the mobile behaviour, for some reason I needed to click a listing title twice to navigate to the corresponding listing (probably this needs to be reported separately though).

### PR DESCRIPTION
**Pull request by fyodorio**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
The detailed description is [here](https://github.com/forem/forem/issues/14459) but in general, when you (1) go to the listings page and (2) open one of the listings by clicking its title, and then (3) try to navigate from it to the specific category this listing belongs to (by clicking category name in the listing modal footer), (4) navigation happens on the background but (5) modal window doesn't close (though it should).

The solution is simple - we can check if a modal is open in `selectCategory()` handler in `listings.jsx` and if it **is** - close the modal.

Ideally it would probably be better to hook up on navigation event inside the Modal component itself, but that's not how it works now everywhere else in the code so I would suggest to stick with this (more specific) solution.

## Related Tickets & Documents
CLOSES #14459 

## QA Instructions, Screenshots, Recordings

_Steps to reproduce are described in the issue details_ 👆

## Added/updated tests?

- [x] Yes
- [ ] No, and this is why
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://admin.forem.com/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Review by rhymes — APPROVED** [review]
Works perfectly, thank you @fyodorio!

**Comment by rhymes** [comment]
@fyodorio for some reason Travis was stuck, so I added an empty commit to unstuck it :D

**Comment by msarit** [comment]
@nickytonline @aitchiss Hey Nick and Suzanne, could you weigh in on the addition of a test for this PR? The contributor had this to say:

>  I'd tried to create a test file using `app/javascript/listings/__tests__/ListingDashboard.test.jsx` as an example to write some kind of an integration test for the scenario, but wasn't able to compile the container correctly. I suppose I'm doing something wrong with regards to the component being server-rendered (as far as I understand). I would be happy to add the test (if necessary) if someone would be able to help me with scaffolding the suite for it.

**Comment by aitchiss** [comment]
I think this change would be a great fit for a Cypress integration test - you can[ check this section in our docs for full details of how we use Cypress](https://docs.forem.com/tests/e2e-tests/) & some best practice tips.

This could be a new file in the directory `cypress/integration/seededFlows/listingFlows/`, and you can see an example of a Cypress test opening up a mocked listing in `cypress/integration/seededFlows/listingFlows/viewListing.spec.js`:

https://github.com/forem/forem/blob/4858b75bb58b130f3257689d480bed734231c06b/cypress/integration/seededFlows/listingFlows/viewListing.spec.js#L23-L44

I'm thinking your test could be very similar the one above, but instead of closing the open modal, selecting a link from inside it and then checking the modal is no longer visible.

Let me know how you get on and if you have any difficulties 👍

**Comment by fyodorio** [comment]
@aitchiss thanks for the guidance Suzanne, sounds good, will write the test and update the PR 👌

**Comment by fyodorio** [comment]
@aitchiss @rhymes @msarit @Ridhwana I have just added the e2e test case, please take a look

**Comment by cmgorton** [comment]
@fyodorio thanks again for working on this bug. We are wrapping up the bug smash event and I wanted to encourage you to write a post about your experience if you have time.
You can use this template.
https://dev.to/new/devbugsmash

**Comment by fyodorio** [comment]
> @fyodorio thanks again for working on this bug. We are wrapping up the bug smash event and I wanted to encourage you to write a post about your experience if you have time.
> You can use this template.
> https://dev.to/new/devbugsmash

[Done](https://dev.to/fyodorio/i-smashed-a-bug-and-i-liked-it-134m), @cmgorton, sorry that it's quite late, busy September 😅

**Pull request merged**
