### PR TITLE
Move conditional to render dots only on published articles

### LINKED ISSUE #19305: Mod Icon and 3 dots at the left showing on a draft article
**Describe the bug**
The mod icon and 3 dots at the left is showing on a draft post

**To Reproduce**
Create a new article and save it as draft. Next, edit the draft article and it will show you the mod icon and the 3 dots at the left

**Expected behavior**
No mod icon and 3 dots at the left of the draft article

**Screenshots**
Screenshot from 2023-04-07 18-50-33

**Desktop (please complete the following information):**

- OS, version: Linux Ubuntu 22.04
- Browser, version: [Version 1.50.114 Chromium: 112.0.5615.49 (Official Build) (64-bit)](https://brave.com/latest/)

### PR DESCRIPTION
**Pull request by divagueame**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Related Tickets & Documents

- Closes #19305
## QA Instructions, Screenshots, Recordings

-Go to http://localhost:3000/new
-Add a title
-Press on save draft
-Mod icon and dots should not be visible
-Click on edit
-Click on publish
-Mod  icon, dots should be visible

Before changes published articles have the dots and ui icons on the left:
before-published

After changes, published articles still have them:
after-published

Before changes, not published articles/draft articles also have these ui icons on the let:
before-not-published

After changes, not published articles/draft articles do not display these icons anymore:
after-not-published

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [x ] I need help with writing tests: Running on the project on docker, when I run yarn e2e I get the following message.
-  [1/6] Validating package.json...
error dev.to@1.0.0: The engine "yarn" is incompatible with this module. Expected version "1.22.18". Got "1.22.17"
error Found incompatible module.

### CODE REVIEW

**Review by rt4914 — APPROVED** [review]
Thanks @divagueame for this contribution. 🥳 🎉

**Comment by rt4914** [comment]
@divagueame Some tests are failing because of these changes so you might need to update them. Let us know if you need any help in that. Thanks :-)

**Comment by maestromac** [comment]
Light ping @divagueame . Some of the fail specs will require attention. Let us know if you need help with that or if you would like us to take over this PR.

**Comment by mirie** [comment]
I have updated this PR to be in draft to indicate that it needs some additional work before being merged / reviewed again.

**Comment by Ridhwana** [comment]
Hi @divagueame thanks for starting to work on the issue, do you still have capacity to work on the requested updates? If not, we could try to re-assign the issue. Let us know.

**Pull request closed without merging**
