### PR TITLE
Input grows with content

### LINKED ISSUE #8842: Connect input should grow with content
We changed the input in `/connect` from multiple lines by default to one, but when text spans more than one line the content gets hidden.

Expected behavior: Content grows, similar to how it does in the `Title` component (where we use `preact-textarea-autosize`

From that file:

```jsx
import Textarea from 'preact-textarea-autosize';

export const Title = ({ onChange, defaultValue, switchHelpContext }) => {
  return (
    <div data-testid="article-form__title" className="crayons-article-form__title">
      <Textarea
        className="crayons-textfield crayons-textfield--ghost fs-3xl s:fs-4xl l:fs-5xl fw-bold s:fw-heavy lh-tight"
        type="text"
```

### PR DESCRIPTION
**Pull request by adfaris**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This PR closes #8842  

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by benhalpern** [comment]
Hmmm this doesn't seem to work properly for me

**Comment by ludwiczakpawel** [comment]
It does not work for me either.

**Comment by nickytonline** [comment]
Hmm, it does not seem to work for me either.

**Comment by adfaris** [comment]
@nickytonline @benhalpern @ludwiczakpawel 

Please re-review the revised solution when you get a chance.

**Comment by ludwiczakpawel** [comment]
It still doesn't seem to be growing for me.

**Comment by narender2031** [comment]
@adfaris any updates on this PR.

**Comment by narender2031** [comment]
This issue is resolved in #10378

**Comment by citizen428** [comment]
Hi @adfaris, thanks a lot for giving this a shot, we appreciate the time and effort you put into this. However since another PR addressing the same issue has been merged in the meantime, I'll be closing this PR now. Thanks again and I'm looking forward to your future contributions!

**Pull request closed without merging**
