### PR TITLE
Fix search bar disappears on mobile

### LINKED ISSUE #16998: Search bar is sometimes disappears from the UI
**Describe the bug**

When clicking on the top nav search icon a few times the bar hides or gets removed and never reappears.

**To Reproduce**

1. Open dev.to in a mobile browser (not mobile app)
2. Click on the search icon from the top nav
3. repeat previous step a few times

**Expected behavior**

The search bar shouldn't disappear

**Screenshots**

https://user-images.githubusercontent.com/6045239/159955496-5a580b06-7fb8-4318-b967-66f50887b97c.mov

**Smartphone (please complete the following information):**

- Device: iPhone 13
- OS, version: `iOS 15.3.1`
- Browser, version: Safari/Chrome (both webkit based)

**Additional context**

I wasn't able to reproduce it on the iOS mobile app but did happen to me on a mobile browser.

### PR DESCRIPTION
**Pull request by adxy**
## What type of PR is this? (check all applicable)

- [x] Bug Fix

## Description
The search bar no longer disappears when the search button on the header is clicked 2 times or more on a mobile browser.

## Related Tickets & Documents

- Closes #16998

## QA Instructions, Screenshots, Recordings

**To reproduce the current issue:**

1. Goto [https://dev.to](https://dev.to)
2. Open mobile view from the Dev Tools of your browser or use a mobile browser, not the app.
3. Click on the search icon 2 or more times
4. The search bar should disappear.

**This PR fixes the issue. Added comments in the code for the same**

### UI accessibility concerns?

None

## Added/updated tests?

- [x] Yes

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] Are there any post deployment tasks we need to perform?
None

## [optional] What gif best describes this PR or how it makes you feel?

Messi Gif

### CODE REVIEW

**Comment by adxy** [comment]
test -fail

@Ridhwana @lboogie04 
One of the tests failed, but it looks like the knapsack API was down rather than failing due to a bug. Please correct me if I am wrong & guide me on what went wrong.

**Comment by Ridhwana** [comment]
> test -fail
> 
> @Ridhwana @lboogie04 One of the tests failed, but it looks like the knapsack API was down rather than failing due to a bug. Please correct me if I am wrong & guide me on what went wrong.

@adxy I had to re-run the CI to get it to pass, it's all green now 🟢. The team will start reviewing your PR :) Thanks!

**Comment by adxy** [comment]
> > @Ridhwana @lboogie04 One of the tests failed, but it looks like the knapsack API was down rather than failing due to a bug. Please correct me if I am wrong & guide me on what went wrong.
> 
> @adxy I had to re-run the CI to get it to pass, it's all green now 🟢. The team will start reviewing your PR :) Thanks!

Great!! 🙌 Let me know if you have any questions on the PR.

**Review by Ridhwana — APPROVED** [review]
I did some testing and this works as expected. Thank you @adxy! ✨

**Comment by adxy** [comment]
Hey @Ridhwana @lboogie04 . I see that both reviews have been accepted. Would you like me to do anything else to get it merged or will you guys take care of this?

**Comment by Ridhwana** [comment]
> Hey @Ridhwana @lboogie04 . I see that both reviews have been accepted. Would you like me to do anything else to get it merged or will you guys take care of this?

Hi @adxy I'll merge this PR later today, thank you so much for your efforts ✨

**Pull request merged**
