### PR TITLE
Enable Forem (Passport) Auth

### PR DESCRIPTION
**Pull request by fdoxyz**
## What type of PR is this? (check all applicable)

- [x] Feature

## Description

The Forem (Passport) Authentication provider was created to help solve the problem we have in certain platforms (mobile apps) where our hands are tied and we are forced to provide a less than ideal UX for our users. Most notably on Apple devices. It's also meant as a tool to help users find new Forem instances and join with a simple SSO provider that doesn't track them or share their data, the way some existing providers likely do.

## Related Tickets & Documents

forem/rfcs#283

## QA Instructions, Screenshots, Recordings

Forem Auth should be visible from all contexts (including `ForemWebView`) regardless of SIWA status but everything else should continue to work the same way. For example, Twitter and GitHub auth shouldn't be visible if SIWA isn't enabled (in order to comply with Apple guidelines).

**Mobile (iOS) without SIWA enabled:**
forem_auth

**Desktop:**
Screen Shot 2021-10-20 at 08 33 49

_I should update my Chrome_ 🧐 

### UI accessibility concerns?

None - Same pattern (for HTML rendering) is used for the new auth provider

## Added/updated tests?

- [x] Yes

## [Forem core team only] How will this change be communicated?

- [x] This change does not need to be communicated, and this is why not: Given this is a new product/service release the communication aspect will be coordinated by the Marketing team

## [optional] What gif best describes this PR or how it makes you feel?

passport stamp

### CODE REVIEW

**Comment by fdoxyz** [comment]
The integration seems ready IMO. Any creator should be able to work with this auth provider ([docs PR here](https://github.com/forem/forem-docs/pull/32)).

We're not openly communicating this yet but making it available for early adopters while we continue to polish the rough edges 🙂

**Comment by thomasbnt** [comment]
Passport website are a little bit problem of responsive.

https://user-images.githubusercontent.com/14293805/140445078-8da4fdd4-09ca-4b87-bdb7-40960d52cebb.mp4

**Review by citizen428 — APPROVED** [review]

**Review by jgaskins — APPROVED** [review]
This looks great! Everything seems to work well.

**Comment by fdoxyz** [comment]
Thanks for noting this @thomasbnt!

I'll make sure that we include a way to reach out for bug reports, feature requests, etc. when this feature gets communicated publicly. We haven't fully finalized these details yet, but I think they're important, so thanks for asking. 

Feedback via email would definitely be a good option for now. We're monitoring `hello+passport@forem.com` so we'll definitely take a look at what comes through that 🙂 

We have an iOS release with support for this auth provider coming up soon as well, so I'll merge this either today or next week.

**Pull request merged**
