### PR TITLE
Fix search with quotes in users's names

### PR DESCRIPTION
**Pull request by rhymes**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

As we're not using the `pg_search` gem to search for users's names or usernames, we don't rely on the gem's autoquoting capabilities. This fixes a [bug](https://github.com/forem/forem/pull/13489#issuecomment-825792269) detected by @djuber (thank you!), which would break search for user's names containing single or double quotes.

## Related Tickets & Documents

#13474

## QA Instructions, Screenshots, Recordings

There are tests but you can activate the `:search_2_usernames` flag and type a name with a quote in it:

https://user-images.githubusercontent.com/146201/115965392-60ba5b00-a529-11eb-9629-09b352b740cb.mov

## Added tests?

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [x] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

### CODE REVIEW

**Review by citizen428 — APPROVED** [review]

**Review by mstruve — APPROVED** [review]
😂  oh edge cases

**Review by atsmith813 — APPROVED** [review]

**Review by jgaskins — APPROVED** [review]
I'm surprised this is needed

> As we're not using the `pg_search` gem to search for users's names or usernames, we don't rely on the gem's autoquoting capabilities

ActiveRecord should be escaping any quotes automatically — `pg_search` shouldn't have to do this. I'm approving but I'd like to understand this a bit more.

**Comment by rhymes** [comment]
@jgaskins `pg_search` uses `ARel` and filters out some chars, it also supports negation, you can start here: https://github.com/Casecommons/pg_search/blob/ea17b19309e8e489cb637309955c5c3117bdd612/lib/pg_search/features/tsearch.rb#L100

**Comment by jgaskins** [comment]
@rhymes Right, but ActiveRecord should be escaping the search term. We shouldn't need `pg_search` to do that. See how it does it here:

```ruby
[1] pry(main)> puts User.where(%{to_tsvector('simple', coalesce(name::text, '')) @@ to_tsquery('simple', ''' ' || unaccent('simple', ?) || ' ''' || ':*')}, "O'hara").to_sql
<snip> WHERE (to_tsvector('simple', coalesce(name::text, '')) @@ to_tsquery('simple', ''' ' || unaccent('simple', 'O''hara') || ' ''' || ':*'))
```

Notice that `O'hara` gets encoded as `O''hara`.

**Comment by jgaskins** [comment]
To be clear, I'm not concerned with what `pg_search` does. I'm concerned that ActiveRecord isn't behaving as expected here.

**Pull request merged**
