### PR TITLE
Fix broken Podcast liquid tag

### PR DESCRIPTION
**Pull request by maestromac**
## What type of PR is this? (check all applicable)
- [x] Refactor
- [x] Bug Fix for Forem.

## Description
the asset images in `app/views/podcast_episodes/_liquid.html.erb` were using the asset path without fingerprint, causing the tag to be broken Forem. This PR

1. Remove the redundant podcast bar component in `app/views/podcast_episodes/_liquid.html.erb` and instead, call `render the partial "podcast_episodes/podcast_bar"` directly.
2. Replace all uses of instant variables in podcast bar partial with locals variable for maintainability and reusability.

## Related Tickets & Documents
Resolves https://github.com/forem/forem/issues/11462

## QA Instructions, Screenshots, Recordings
0. Pull down this PR, make sure you have podcasts locally with background job running and caching enabled.
1. Start up the rails server
2. head to `/pod` and choose a podcast episode.
3. head to `/new` and use the liquid tag in this manner in the body, `{% podcast localhost:3000/your/podcast/link %}`
4. Click save. You should see all icons like play/pause rendered normally. When playing the podcast you should see the volume and mute button working normally.

## Added tests?
- [x] No, and this is why: existing test covers this.

## Added to documentation?
- [x] No documentation needed

## [optional] Are there any post deployment tasks we need to perform?
n/a

### CODE REVIEW

**Review by rhymes — COMMENTED** [review]
The code looks sound, do you know if automatic tests cover it?

I tried to download podcasts to do this manually but I couldn't. 

This is where I'm at:

```ruby
Podcast.published.count # this returns 4

# this runs and doesn't do anything
Podcast.published.select(:id).find_each do |podcast|
  Podcasts::GetEpisodesWorker.new.perform(podcast_id: podcast.id, limit: 5, force_update: true)
end

PodcastEpisode.count # this returns 0
```

any tips on how I can test this manually?

**Comment by maestromac** [comment]
@rhymes make sure you have development caching enabled with `bin/rails dev:cache`. You should see `Development mode is now being cached.`, if not run that command again. After that, try manually running your command via rails console (`Podcasts::GetEpisodesWorker...`) again. Please let me know if that helps

**Comment by rhymes** [comment]
@maestromac caching is correctly enabled but I don't seem to be able to download podcast episodes anymore. I remember distinctly I was able to the last time I tried a few months ago. I'll investigate a bit but the code seem sound, so we should probably go ahead with this!

**Comment by msarit** [comment]
Hey @maestromac! 👋🏾  Drawing your attention to this PR 😄

**Comment by maestromac** [comment]
Thank you for the ping @msarit . This fix and refactor is still applicable, it just needs more reviews.

**Review by Zhao-Andy — APPROVED** [review]
LGTM!

**Review by juliannatetreault — APPROVED** [review]
Works for me!

**Pull request merged**
