### PR TITLE
Fix Bug: Series index page showing series with 0 articles -#9658

### PR DESCRIPTION
**Pull request by cwray-tech**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
I added a join and distict method to the collections controller index method to only get collections that contain articles. 

## Related Tickets & Documents
Closes https://github.com/forem/forem/issues/9658

## QA Instructions, Screenshots, Recordings

To test this functionality, you can create an article, add a series to that article. Save the Series/article, and create another article and a new series. 

After saving the new series/ article, replace the second article series with the first series created.

There should now be one series without any articles. 

Go to the series index view, by clicking on the series of the article, then clicking the "back to all series" link. Here, you should only see the first series created with the two articles.

## Added tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [x] I need help with writing tests. I am not sure if a test is needed as there is already a test written for the index method. 

## Added to documentation?

- [ ] Docs.forem.com
- [ ] README
- [x] No documentation needed

## [optional] Are there any post deployment tasks we need to perform?
No

### CODE REVIEW

**Comment by cwray-tech** [comment]
@citizen428 Thank you SO much for your help with this. All credit goes your way. (:

**Review by rhymes — CHANGES_REQUESTED** [review]
Hi @cwray-tech - thanks for tackling this! I think we should add a test to make sure this doesn't "regress" in the future.

I think the simplest would be to alter https://github.com/forem/forem/blob/master/spec/system/collections/user_views_collections_spec.rb by creating a collection with no articles and making sure it's not visible.

Let us know if you need further help

**Comment by cwray-tech** [comment]
@rhymes thank you, yes will do! This is so good for me. Learning a lot. (: Sorry I was not able to run tests locally, so I didn't catch that. I think I am able to run tests now so will try to ensure they all pass before adding another commit.

**Comment by citizen428** [comment]
@cwray-tech No, thank you! This is not about credit but about building Forem together with our community, so thanks a lot for your contribution and tackling this issue, even if it was maybe a bit outside your comfort zone 💯

**Review by citizen428 — APPROVED** [review]

**Review by rhymes — APPROVED** [review]
Looks awesome! Thanks @cwray-tech

**Pull request merged**
