### PR TITLE
Adds SVG_PLACEHOLDER Constant to Site Config

### PR DESCRIPTION
**Pull request by juliannatetreault**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
This PR adds a constant, `SVG_PLACEHOLDER`, to `sitr_config.rb` in place of multiple strings. This standardizes the file a bit more and makes it easier for future contributors to change this value.

## Related Tickets & Documents
Relates to PR #10992 

## QA Instructions, Screenshots, Recordings
To QA this change, make sure that all of the checks pass and Travis builds green. 

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?
Nope!

## [optional] What gif best describes this PR or how it makes you feel?

SVG

### CODE REVIEW

**Review by Zhao-Andy — APPROVED** [review]

**Comment by juliannatetreault** [comment]
> Also love that this now sets the precedent for us to abstract more of this file into constants, too!

@vaidehijoshi DONE! 😄

**Review by Ridhwana — COMMENTED** [review]
💚 these useful changes

**Review by jacobherrington — APPROVED** [review]
:brain:

I think there is a lot of room for cleaning up SiteConfig down the road. Good idea to grab this quick one now :+1:

**Review by vaidehijoshi — APPROVED** [review]
YESSSSSS!!! thanks for being proactive here, @juliannatetreault! glad we started this trend in https://github.com/forem/forem/pull/10992

**Pull request merged**
