### PR TITLE
Add admin shortcut to tag page

### PR DESCRIPTION
**Pull request by benhalpern**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

The problem that this is solving is that setting any admin-only functionality lacks intuitive ergonomics for admins. If they recognize that a tag needs to be adjusted or elevated, it's a pain to get to the proper admin dashboard. This adds an admin button alongside mod buttons. Also made a style adjustment.

Old:

Screen Shot 2020-10-26 at 11 59 40 AM

New:

Screen Shot 2020-10-26 at 11 53 18 AM

This creates a button a shortcut to admin, alongside moderation to allow admins to more easily modify admin-level tag decisions.

### CODE REVIEW

**Comment by lisasy** [comment]
I like this and this LGTM. Curious @ludwiczakpawel's thoughts around using `ff-monospace` as a variant of the button text style.

**Comment by benhalpern** [comment]
Yeah, @lisasy I think the monospace is just inherited from the container, which is legacy style.

I'd be down to give this a bit of a more thorough quick crayons pass similar to the tags page, or just ship this as a minor improvement and circle back next time for more.

**Comment by ludwiczakpawel** [comment]
Yeap, since the monospace is inherited, lets ship it as is and circle back later on.

**Review by ludwiczakpawel — APPROVED** [review]

**Review by Zhao-Andy — APPROVED** [review]
LGTM. One thing I noticed is that if the user is not an admin or mod, the last button won't be rounded:
Screen Shot 2020-10-27 at 9 43 39 AM

Pretty sure this is because the admin button exists in the HTML, but is hidden visually. This can probably be adjusted via CSS and checking for `display:none` or something, but probably not a huge deal.

**Pull request merged**
