### PR TITLE
Enqueue Ruby 3.2.0 base image builds in GHCR

### PR DESCRIPTION
**Pull request by heliocola**
## What type of PR is this? (check all applicable)
- [x] Upgrade

## Description
Get started on ruby 3.2 upgrade

## Related Tickets & Documents

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings

None

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
Not applicable

_For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._
- [x] No, and this is why: the goal is to build ruby-3.2.0 image to be used for the next upgrade

### CODE REVIEW

**Comment by heliocola** [comment]
@klardotsh : hi there!
Is this how the ruby upgrade is meant to be?
I only updated .ruby-version-next

BTW: the PR is still in draft to avoid notification broadcast across the board!

**Comment by klardotsh** [comment]
Hello again @heliocola and thanks! This is correct for general flow yeah :) I'm gonna mark this as ready for review so that I can provide a formal approval, and so that it'll tag folks for review.

Once merged, this will generate (after an hour or two...) `ghcr.io/forem/ruby:3.2.0`, which you can then use as a base for modifications to `Containerfile`. You'll need the SHA sums that the GHCR web UI will provide once the image is built. Bump `.ruby-version`, and then with that fully-qualified image path you can build new app containers and test the app.

---

Forem reviewers note: if this for some reason goes sideways and we need to skip 3.2.0 (or decide to never take it, or whatever), reverting this PR harms nothing on the Docker side of things. This PR also will change nothing about our currently-deployed infrastructure, as it does not, alone, change our Ruby version. This file is only an indicator to our CI system as to which *base images* to build and store in GHCR for future use; see further commentary from #19889

**Review by klardotsh — APPROVED** [review]

**Comment by heliocola** [comment]
Thank you @klardotsh !
BTW: there are some interesting CI failures (that I got on my fork repo).
So this PR will just prepare the image.

**Comment by heliocola** [comment]
BTW/FYI: all but 1 failed tests got fixed by updating rspec* gems.

**Review by benhalpern — APPROVED** [review]

**Comment by klardotsh** [comment]
Thanks @heliocola! Good luck with your continued upgrade work in your fork!

**Pull request merged**
