### PR TITLE
Feature/new liquid tag for Observablehq notebooks

### PR DESCRIPTION
**Pull request by radames**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This PR implements a liquid tag supporting [Observablehq Notebooks](https://observablehq.com/explore). Since they're now supporting a simple iframe specification [Introduction to Embedding](https://observablehq.com/@observablehq/introduction-to-embedding)

## QA Instructions, Screenshots, Recordings

video

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added tests?

- [X] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## Added to documentation?

- [X] Docs.forem.com
- [ ] README
- [ ] No documentation needed

### CODE REVIEW

**Comment by radames** [comment]
hi @jacobherrington sorry I didn't submit any draft for this PR, is there anything I should have done? thanks

**Comment by rhymes** [comment]
Hi @radames, first and foremost, thanks for the contribution and sorry for the delay! 

Unfortunately at the moment we don't plan to integrate this liquid tag in the codebase. I encourage you to open an issue for discussion in the future, ahead of submitting a PR, especially if it's about new functionality over bug fixes.

You can also take a look at the existing [feature requests labeled "ready for dev"](https://github.com/forem/forem/issues?q=is%3Aopen+is%3Aissue+label%3A%22ready+for+dev%22+label%3A%22type%3A+feature+request%22) and [our contributing guide](https://docs.forem.com/contributing/forem/).

Thanks again for your help!

**Comment by radames** [comment]
hi @rhymes thanks for your response. I was interested in write about Observablehq notebooks and their iframe embeds are pretty cool! works like codepen embeds. Do you think it worth to start a discussion issue and see if more people are interested? otherwise I'll drop this. Another related open issue is on the oEmbed feature  https://github.com/forem/forem/issues/6369, it will make this PR unnecessary as Observablehq support it. Thanks

**Comment by mootari** [comment]
Note that they [changed their process](https://github.com/forem/forem/issues/6369#issuecomment-765690718) earlier this year. Feature requests now have to be submitted to [forem.dev](https://forem.dev/).

**Pull request closed without merging**
