### PR TITLE
Rename comment-mentioned-user class added by Html::Parser

### PR DESCRIPTION
**Pull request by vaidehijoshi**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Renames the `.comment-mentioned-user` CSS class added by `Html::Parser#user_link_if_exists` in preparation for [RFC #22](https://github.com/forem/rfcs/pull/22).

This class name soon will make no sense and could actually cause some confusion as we allow mention functionality to work for _both_ Articles and Comments!

This [came up in another PR](
https://github.com/forem/forem/pull/13259#discussion_r607392547), and I had planned to do it anyways, so I decided to keep it as a separate PR to reduce the code's surface area 😅 

## Related Tickets & Documents

A small, encapsulated PR in service of https://github.com/forem/rfcs/pull/22.

Came up [originally in PR #13259](https://github.com/forem/forem/pull/13259#discussion_r607392547).

## QA Instructions, Screenshots, Recordings

Tests should pass, and everything that relies on the `Html::Parser` class should work smooth like butter 🙃 

### UI accessibility concerns?

_None, just a CSS class change!_

## Added tests?

- [ ] Yes
- [x] No, and this is why: _I updated pre-existing specs for the parser!_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

- [x] This change does not need to be communicated, and this is why not: _this is an internal change that doesn't impact how anyone interacts with the platform or the code_

## Are there any post deployment tasks we need to perform?

Nope!

### CODE REVIEW

**Review by citizen428 — APPROVED** [review]

**Review by rhymes — COMMENTED** [review]
One step at a time! Cool

Doesn't this require re-saving articles and messages? Otherwise I think existing rows will have `.comment-mentioned-user` and `.comment-mentioned-all` in their HTML columns and when this is deployed, the CSS will not match them.

**Comment by vaidehijoshi** [comment]
> Doesn't this require re-saving articles and messages? Otherwise I think existing rows will have `.comment-mentioned-user` and `.comment-mentioned-all` in their HTML columns and when this is deployed, the CSS will not match them.

@rhymes Ughhhhh I definitely didn't think of that (nor did the code make that clear to me lol). 🙈

I wonder if the best solution here is a DataUpdateScript to parse all articles and comments to edit the body markdown to have the new CSS rather than the old one? And I suppose that would have to be a part of this PR itself (I guess it's good that I kept this a separate PR!)

Can you think of a better solution or idea? And is there anything else I'm missing or not thinking of here? 🤔

**Comment by rhymes** [comment]
@vaidehijoshi yes, I think a data update script that resaves all those models is the best.

Something like `Article.published.find_each(&:save)` and similar for `Message`

It should be part of this PR, otherwise the new CSS will break old articles

**Comment by mstruve** [comment]
One thing to keep in mind is that saving all of the articles for DEV will take a very long time and there is a good chance another deploy will kill the job before it has a chance to complete. For this reason we may need to run the update for DEV in a console. Whoever is on-call should be able to help with this if it becomes the case.

**Comment by vaidehijoshi** [comment]
@rhymes + @mstruve 

The [latest commit](https://github.com/forem/forem/pull/13263/commits/a2d102c31ac448a4c7f43683e064b133d1b4589d) adds three separate data update scripts to re-save every model that takes the `.comment-mentioned-user` class into account via the `Html::Parser`, namely `Article`, `Comment`, and `Message`.

While addressing these comments, I initially had this all in a single DataUpdateScript, but then realized that touching every instance of these 3 models might be a lot for a single script -- and if it failed, we wouldn't easily be able to know if any of these models had been partially updated or not. For that reason, I split these out into 3 different scripts, which should make it easier for us to see if every part of this has succeeded on a Forem (aka if the script was successful). However, I can easily squeeze it all into a single script if folks feel that this is necessary!

It seemed a bit heavyweight to write a test for these scripts, which just calls `save` on a model. But, I did confirm that this works by checking out `master`, and creating a new article and inspecting its `processed_html` _before_ running the script:
```ruby
[1] pry(main)> a = Article.last
  Article Load (1.0ms)  SELECT "articles".* FROM "articles" ORDER BY "articles"."id" DESC LIMIT $1  [["LIMIT", 1]]
=> #<Article:0x00007fcd032087a8 ...>
[2] pry(main)> a.processed_html
=> "<p>wherein i mention <a class=\"comment-mentioned-user\" href=\"http://localhost:3000/admin_mcadmin\">@admin_mcadmin</a>\n !!</p>\n\n"
```

_(Note that the `processed_html` includes the `.comment-mentioned-user` class!)_


Then, I ran the script locally:
```bash
➜  forem git:(vaidehijoshi/generalize-comment-mentioned-user-class) ✗ rails data_updates:run
```

And then checked out the article again and inspected its `processed_html` after re-saving it:
```ruby
[3] pry(main)> a = Article.last
  Article Load (1.7ms)  SELECT "articles".* FROM "articles" ORDER BY "articles"."id" DESC LIMIT $1  [["LIMIT", 1]]
=> #<Article:0x00007fcd016c6468 ...>
[4] pry(main)> a.processed_html
=> "<p>wherein i mention <a class=\"mentioned-user\" href=\"http://localhost:3000/admin_mcadmin\">@admin_mcadmin</a>\n !!</p>\n\n"
```

_(Note that the `processed_html` now includes a `.mentioned-user` class rather than the previous `.comment-mentioned-user` class!)_

**Review by rhymes — APPROVED** [review]
Agreed that the data update script specs aren't necessary in this case.

LGTM @vaidehijoshi!

**Comment by vaidehijoshi** [comment]
@maestromac [The latest commit](https://github.com/forem/forem/pull/13263/commits/0c0b17be923c2b7f3e72a3b1ffbdb8cc8e2c9670) reorders _which_ models we will update, per your suggestion! The new order will be: `Message`, `Comment`, `Article`, with the "highest-touch" model being last 😃 

Screen Shot 2021-04-13 at 1 25 31 PM

Hopefully this sets us up in a better position to deploy this to DEV 👍🏽

**Review by maestromac — APPROVED** [review]

**Pull request merged**
