### PR TITLE
[15 min fix] Upgraded to Cypress 7.7.0

### PR DESCRIPTION
**Pull request by nickytonline**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [x] Dependency update

## Description

There's a bunch of bugs fixes/improvements and testing this to see if it helps with any of the flakiness.

## Related Tickets & Documents

#14078

## QA Instructions, Screenshots, Recordings

N/A

### UI accessibility concerns?

N/A
## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: This is testing infrastructure
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://admin.forem.com/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [x] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

Level up

### CODE REVIEW

**Review by Zhao-Andy — APPROVED** [review]
It passed CI! Looks like you have merge conflicts now with `package.json` :(

**Review by mstruve — APPROVED** [review]
🤞🏻 🤞🏻 🤞🏻

**Review by djuber — APPROVED** [review]
The package.json conflict is related to the cypress-failed-log line (immediately after the cypress 7.4.0 in the main branch) so looks like it's trivial to fix.

Passed CI and containers build, looks good to me.

**Comment by aitchiss** [comment]
It's worth keeping an eye on retry attempts in the E2E tests - I noticed that although it passed CI, 3 specs needed retry attempts (and not for 500 errors). Not to say we shouldn't merge, but just let's keep an eye on it 👀

**Pull request merged**
