### PR TITLE
Removed unused brand color field from Profile

### LINKED ISSUE #17686: Remove unused brand color field
# Background
We have 2 brand color fields in `/settings/profile` but we are using only one which is causing confusion. See discussion in https://github.com/forem/forem/discussions/17163
image

# Definition of done
There should be only one brand color left. Our backend should use that color for the background color of the upper section of a user's profile. Such as the screenshot shown here:
image

# To do 

- [ ] 1. Remove `Brand color 2` 
- [ ] 2. Rename `Brand color 1` to `Brand color`

### PR DESCRIPTION
**Pull request by rt4914**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

This PR removes `Brand Color 2` as well renames `Brand Color 1` to `Brand Color`.

**NOTE**: This change has been done only for profile and not for organization.

## Related Tickets & Documents

- Related Issue #17686 
- Closes 

## QA Instructions, Screenshots, Recordings

https://user-images.githubusercontent.com/9396084/183352871-0449a903-49f9-4228-8b10-c8da17d47730.mov

### UI accessibility concerns?

None

## Added/updated tests?

- [x] Yes
- [ ] No
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [x] This change does not need to be communicated, and this is why not: this is a very minor change

## [optional] Are there any post deployment tasks we need to perform?

No

### CODE REVIEW

**Comment by rt4914** [comment]
This PR has been created just as a reference for https://github.com/forem/forem/pull/18282 with minimal code changes so that CI checks can be fixed for this code first and then move ahead.

**Comment by rt4914** [comment]
@jaw6 @fdocr Feel free to review it whenever possible. Thanks.

**Comment by rt4914** [comment]
@maestromac I have made the changes correctly and closed the [previous PR](https://github.com/forem/forem/pull/18282) where changes were incorrect. 
In this will we need DB migration?

**Comment by maestromac** [comment]
@rt4914 DB migration would be a stand-alone final PR you create after you remove all the feature code. Having a migration-only PR is a way to allow us to roll back safely if something were to go wrong.

**Review by maestromac — APPROVED** [review]
LGTM!

**Review by jaw6 — APPROVED** [review]

**Pull request merged**
