### PR TITLE
change Dev_favicon to Forem_favicon

### PR DESCRIPTION
**Pull request by arbazkhan56**
I am replacing the generic favicon with a Forem favicon

Closes https://github.com/forem/forem/issues/12494

### CODE REVIEW

**Comment by arbazkhan56** [comment]
I am solving this issue. If you have any changes then tell me and Merge the pull request as soon as possible.
Thank you

**Review by rhymes — CHANGES_REQUESTED** [review]
Hi @arbazkhan56, thanks for the PR! I added the link to the issue in your description, please try to follow the PR template the next time :) 

The proposed solution isn't going to work as it links to a generic web server, I think we should replace the default favicon.

We already have a default favicon - https://github.com/forem/forem/blob/main/app/assets/images/favicon.ico - the issue is that it's not the same as the one in `public` - https://github.com/forem/forem/blob/main/public/favicon.ico

I think we should replace the second one with the first one. 

Thank you!

**Comment by arbazkhan56** [comment]
Ok, next time I will try to follow the PR template. I change the favicon with the default favicon, now check it and let me know if there are any changes in it.

**Comment by rhymes** [comment]
@arbazkhan56 sorry I wasn't clear, the file in `assets` has to be copied over to `public`, no other change should be necessary, as the 404 page will pick up the new favicon

**Comment by rhymes** [comment]
@arbazkhan56 It would be best to leave it as is - an icon of 48x48. This way we don't change the quality by transforming it. Thank you!

**Comment by arbazkhan56** [comment]
Ok, I have to change it according to you. If there any more changes then let me know.
If there are no changes then we send again pull request?

**Comment by rhymes** [comment]
@arbazkhan56 no additional changes: you can copy `app/assets/images/favicon.ico` in `public` and replace `public/favicon.ico` and remove the `<link>` tag in `public/404.html` or keep it and have it point to the correct file.

You can do it on this PR, I don't think it's necessary to create a new one!

**Review by rhymes — APPROVED** [review]
Thank you @arbazkhan56 and welcome to Forem!

**Comment by cmgorton** [comment]
> Check it and respond to me ASAP.
> Thank You for your guidance and suggestion. This teaches me a lot more things.

If this is for Bug Smash don't stress. I am watching the PRs and see you are working on it. I'll work to make sure you get credit for it even if you don't get the PR in today :) You will just need to write a post once your PR is merged https://dev.to/new/devbugsmash

**Comment by cmgorton** [comment]
@arbazkhan56 actually I just saw you already wrote the post 😄 https://dev.to/arbazkhan56/solve-problem-of-favicon-28ng

**Comment by arbazkhan56** [comment]
yeah, I am very Excited to Share with my Friends  🙈

**Review by Ridhwana — APPROVED** [review]

**Comment by aitchiss** [comment]
I'm re-running the Travis CI job as the failure looked unrelated - possibly a flaky Cypress test

**Review by jacobherrington — APPROVED** [review]

**Pull request merged**
