### PR TITLE
Replace uses of toBeDefined with toExist 

### PR DESCRIPTION
**Pull request by rt4914**
## What type of PR is this? (check all applicable)

- [x] Optimization

## Description

In this PR the we are replaceing `toBeDefined` with `toExist` and makes sure all tests pass.
After which there are 10 instances which are still pending:
Screenshot 2023-07-20 at 3 00 48 PM

These will be handled separately.
I will update the original issue description once the PR looks like merge ready.

## Related Tickets & Documents

- Related to #19452

## QA Instructions, Screenshots, Recordings

All tests should pass locally and on this PR

### UI accessibility checklist

Not a UI PR.

## Added/updated tests?

- [x] Yes

### CODE REVIEW

**Comment by rt4914** [comment]
Hi @filleduchaos @Ridhwana 
I am assigning you this PR first to get your opinion on the description and changes. Once I get nod from your side, I will make it available for full review. Thanks.

**Comment by rt4914** [comment]
Hi @Ridhwana @filleduchaos 
Please provide initial feedback on this PR whenever possible.

**Comment by Ridhwana** [comment]
Apologies for the delay @rt4914, I looked through the changes and they look good to me.

**Review by Ridhwana — APPROVED** [review]

**Review by filleduchaos — APPROVED** [review]
Got a chance to go over the tests and they all seem correct ✨

**Comment by rt4914** [comment]
Thanks @Ridhwana @filleduchaos 

I will now update the original issue to contain a list of tasks in which the first one (which is this PR) will be done and other s will be individual task for every file where we need to replace `toBeDefined` with some correction of code.

**Pull request merged**
