### PR TITLE
Mod tools trigger

### LINKED ISSUE #14062: Mobile experience for smaller screens
**Describe the bug**

When I am creating a comment on my mobile phone quite often I can't see what I am typing because the cursor is below the heart/unicorn/read later icons or underneath the moderator button. Now, my phone is relatively old, so it might be that newer phones with higher resolution screens don't suffer from this, so this might be a niche issue. 

**To Reproduce**

Write a comment that is a few paragraphs long. 

**Expected behavior**

I expect the editing box to not be hidden by anything 

**Screenshots**

**Smartphone (please complete the following information):**

- Device: Sony Xperia XZ 
- OS, version: android 8.0.0
- Browser, version: Firefox 89.1.1

**Additional context**

### PR DESCRIPTION
**Pull request by ludwiczakpawel**
## What type of PR is this? (check all applicable)

- [x] Feature

## Description

This PR moves "mod" button from bottom right corner to the actions bar.

## Related Tickets & Documents

- https://forem-team.slack.com/archives/C01MK34RE6P/p1635229212019100
- https://forem-team.slack.com/archives/C01MK34RE6P/p1635370983032100
- Closes #14062

## QA Instructions, Screenshots, Recordings

**Before:**

Zrzut ekranu 2021-11-17 o 10 44 40

Zrzut ekranu 2021-11-17 o 10 45 12

**After:**

Zrzut ekranu 2021-11-17 o 10 45 52

Zrzut ekranu 2021-11-17 o 10 46 28

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [x] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

### CODE REVIEW

**Comment by ludwiczakpawel** [comment]
cc @michael-tharrington

**Review by aitchiss — APPROVED** [review]
Looks good to me 👍

**Comment by nickytonline** [comment]
I guess this is safe to do now that there is no longer a connect button? I remember in the past we had to move it out because of spacing issues.

**Review by nickytonline — APPROVED** [review]
Looks great! 🚀

**Review by msarit — APPROVED** [review]
Love it!

**Pull request merged**
