### PR TITLE
Test PR for CI

### PR DESCRIPTION
**Pull request by jgaskins**
We've been having some segfaults on Travis CI. My current theory is that it's a gem with a busted C extension. I've run `bundle update` and this gem set is the result. This PR is being used only to kick off CI builds.

If we don't get segfaults on this branch, then one of the gems that this PR updates is probably the culprit and we can narrow it down there.

If we _do_ still get segfaults with this branch, these gems are likely not the problem and we'll have to comb through the dependabot PRs.

### CODE REVIEW

**Comment by jgaskins** [comment]
List of gems with native extensions, in reverse order of last updated in `Gemfile.lock`:

| Gem | Version | Last updated|
|-|-|-|
| pry-byebug | (3.8.0) | 2021-03-18 |
| oj | (3.11.3) | 2021-03-18 |
| nokogiri | (1.11.2-x86_64-linux) | 2021-03-18 |
| nio4r | (2.5.7) | 2021-03-18 |
| http-parser | (1.2.3) | 2021-03-18 |
| ffi | (1.15.0) | 2021-03-18 |
| debug_inspector | (1.0.0) | 2021-03-18 |
| hiredis | (0.6.3) | 2021-03-12 |
| puma | (5.2.2) | 2021-03-03 |
| ruby-prof | (1.4.3) | 2021-02-17 |
| bootsnap | (1.7.2) | 2021-02-09 |
| msgpack | (1.4.2) | 2021-02-02 |
| racc | (1.5.2) | 2021-01-06 |
| binding_of_caller | (0.8.0) | 2021-01-06 |
| eventmachine | (1.2.7) | 2021-01-04 |
| redcarpet | (3.5.1) | 2020-12-16 |
| stackprof | (0.2.16) | 2020-10-26 |
| bcrypt | (3.1.16) | 2020-09-28 |
| websocket-driver | (0.7.3) | 2020-09-09 |
| multi_json | (1.15.0) | 2020-08-02 |
| sassc | (2.4.0) | 2020-07-05 |
| unf_ext | (0.0.7.7) | 2020-05-07 |
| patron | (0.13.3) | 2020-04-10 |
| bindex | (0.8.1) | 2020-03-23 |
| pg | (1.2.3) | 2020-03-19 |
| html_tokenizer | (0.0.7) | 2019-01-29 |
| yajl-ruby | (1.4.1) | 2019-01-09 |
| http_parser.rb | (0.6.0) | 2018-02-28 |


<details>
<summary>Taken from this `bundle` output</summary>

```
➜  forem git:(test-builds-for-updated-gems) ✗ gem i bundler && b12
Fetching bundler-2.2.14.gem
Successfully installed bundler-2.2.14
Parsing documentation for bundler-2.2.14
Installing ri documentation for bundler-2.2.14
Done installing documentation for bundler after 1 seconds
1 gem installed
Fetching source index from https://rubygems.org/
Installing rake 13.0.3
Installing concurrent-ruby 1.1.8
Installing zeitwerk 2.4.2
Installing erubi 1.10.0
Installing crass 1.0.6
Installing minitest 5.14.4
Installing builder 3.2.4
Installing mini_portile2 2.5.0
Installing racc 1.5.2 with native extensions
Installing rack 2.2.3
Installing websocket-extensions 0.1.5
Installing thread_safe 0.3.6
Installing nio4r 2.5.7 with native extensions
Installing mimemagic 0.3.5
Installing mini_mime 1.0.2
Installing public_suffix 4.0.6
Installing errbase 0.2.1
Installing device_detector 1.0.5
Installing geocoder 1.6.6
Installing amazing_print 1.3.0
Installing ruby-next-core 0.12.0
Installing thor 1.1.0
Installing ast 2.4.2
Installing aws-eventstream 1.1.1
Installing aws_cf_signer 0.1.3
Installing ice_nine 0.11.2
Installing benchmark-ips 2.8.4
Installing bcrypt 3.1.16 with native extensions
Installing smart_properties 1.15.0
Installing coderay 1.1.3
Installing method_source 1.0.0
Installing html_tokenizer 0.0.7 with native extensions
Installing debug_inspector 1.0.0 with native extensions
Installing chartkick 3.4.2
Installing brakeman 5.0.0
Installing bindex 0.8.1 with native extensions
Installing msgpack 1.4.2 with native extensions
Installing browser 5.3.1
Installing redis 4.2.5
Using bundler 2.2.14
Installing environs 1.1.0
Installing multipart-post 2.1.1
Installing faraday-net_http 1.0.1
Installing ruby2_keywords 0.0.4
Installing multi_json 1.15.0
Installing hashie 4.1.0
Installing uniform_notifier 1.14.1
Installing byebug 11.1.3 with native extensions
Installing buftok 0.2.0
Installing yajl-ruby 1.4.1 with native extensions
Installing ssrf_filter 1.0.7
Installing mini_magick 4.11.0
Installing ffi 1.15.0 with native extensions
Installing fastimage 2.2.3
Installing regexp_parser 2.1.1
Installing childprocess 3.0.0
Installing http-accept 1.7.0
Installing unf_ext 0.0.7.7 with native extensions
Installing mime-types-data 3.2021.0225
Installing netrc 0.11.0
Installing coffee-script-source 1.12.2
Installing execjs 2.7.0
Installing connection_pool 2.2.3
Installing rexml 3.2.4
Installing dante 0.2.0
Installing database_cleaner-core 2.0.1
Installing dead_end 1.1.6
Installing memory_profiler 1.0.0
Installing orm_adapter 0.5.0
Installing mini_histogram 0.3.1
Installing ruby-statistics 2.1.3
Installing distribution 0.8.0
Installing diff-lcs 1.4.4
Installing docile 1.3.5
Installing dogstatsd-ruby 4.8.3
Installing dotenv 2.7.6
Installing eventmachine 1.2.7 with native extensions
Installing emoji_regex 3.2.2
Installing equalizer 0.0.11
Installing parallel 1.20.1
Installing rainbow 3.0.0
Installing http_parser.rb 0.6.0 with native extensions
Installing ruby-progressbar 1.11.0
Installing excon 0.79.0
Installing exifr 1.3.9
Installing unicode-display_width 2.0.0
Installing fastly 3.0.1
Installing sax-machine 1.3.2
Installing flipper 0.20.4
Installing formatador 0.2.5
Installing ipaddress 0.8.3
Installing front_matter_parser 1.0.0
Installing raabro 1.4.0
Installing gemoji 4.0.0.rc2
Installing rb-fsevent 0.10.4
Installing lumberjack 1.2.8
Installing nenv 0.3.0
Installing shellany 0.0.1
Installing guard-compat 1.2.1
Installing rspec-support 3.10.2
Installing hashdiff 1.0.1
Installing hiredis 0.6.3 with native extensions
Installing hkdf 0.3.0
Installing honeybadger 4.7.3
Installing http-form_data 2.3.0
Installing htmlentities 4.3.4
Installing http-2 0.11.0
Installing multi_xml 0.6.0
Installing httpclient 2.8.3
Installing json 2.5.1 with native extensions
Installing kaminari-core 1.2.1
Installing jwt 2.2.2
Installing knapsack_pro 2.11.0
Installing liquid 5.0.0
Installing nakayoshi_fork 0.0.4
Installing naught 1.1.0
Installing oauth 0.5.5
Installing oj 3.11.3 with native extensions
Installing patron 0.13.3 with native extensions
Installing redcarpet 3.5.1 with native extensions
Installing pg 1.2.3 with native extensions
Installing rack-timeout 0.6.0
Installing pusher-signature 0.1.8
Installing rolify 5.3.0
Installing rouge 3.26.0
Installing ruby-prof 1.4.3 with native extensions
Installing rubyzip 2.3.0
Installing tilt 2.0.10
Installing semantic_range 3.0.0
Installing simple_oauth 0.3.1
Installing simplecov-html 0.12.3
Installing simplecov_json_formatter 0.1.2
Installing slack-notifier 2.3.2
Installing spring 2.1.1
Installing staccato 0.5.3
Installing stripe 5.30.0
Installing ulid 1.3.0
Installing test-prof 1.0.2
Installing stackprof 0.2.16 with native extensions
Installing timecop 0.9.4
Installing vcr 6.0.0
Installing wcag_color_contrast 0.1.0
Installing yard 0.9.26
Installing zonebie 0.6.1
Installing websocket-driver 0.7.3 with native extensions
Installing sitemap_generator 6.1.2
Installing mail 2.7.1
Installing safely_block 0.3.0
Installing tzinfo 1.2.9
Installing descendants_tracker 0.0.4
Installing memoizable 0.4.2
Installing rack-test 1.1.0
Installing marcel 0.3.3
Installing warden 1.2.9
Installing rack-protection 2.1.0
Installing rack-proxy 0.6.5
Installing rack-cors 1.1.1
Installing addressable 2.7.0
Installing rack-attack 6.5.0
Installing rack-host-redirect 1.3.0
Installing request_store 1.5.0
Installing anyway_config 2.1.0
Installing i18n 1.8.9
Installing sprockets 4.0.2
Installing parser 3.0.0.0
Installing puma 5.2.2 with native extensions
Installing aws-sigv4 1.2.3
Installing heapy 0.2.0
Installing nokogiri 1.11.2 with native extensions
Installing better_errors 2.9.1
Installing pry 0.14.0
Installing binding_of_caller 0.8.0 with native extensions
Installing brpoplpush-redis_script 0.1.1
Installing redis-store 1.9.0
Installing bundler-audit 0.8.0
Installing faraday 1.3.0
Installing bootsnap 1.7.2 with native extensions
Installing ddtrace 0.46.0
Installing elasticsearch-api 7.11.2
Installing mime-types 3.3.1
Installing net-http-persistent 4.0.1
Installing crack 0.4.5
Installing katex 0.6.1
Installing unf 0.1.4
Installing sidekiq 6.1.3
Installing coffee-script 2.4.1
Installing uglifier 4.2.0
Installing ruby-vips 2.1.0
Installing ffi-compiler 1.0.1
Installing sassc 2.4.0 with native extensions
Installing webpush 1.1.0
Installing rspec-core 3.10.1
Installing rb-inotify 0.10.1
Installing get_process_mem 0.2.7
Installing rspec-expectations 3.10.1
Installing rspec-mocks 3.10.2
Installing notiffany 0.1.3
Installing pusher 1.4.3
Installing net-http2 0.18.4
Installing em-websocket 0.5.2
Installing selenium-webdriver 3.142.7
Installing simplecov 0.21.2
Installing recaptcha 5.7.0
Installing spring-commands-rspec 1.0.4
Installing et-orbi 1.2.4
Installing stripe-ruby-mock 3.0.1
Installing yard-activerecord 0.0.16
Installing yard-activesupport-concern 0.0.1
Installing axiom-types 0.1.1
Installing coercible 1.0.0
Installing flipper-ui 0.20.4
Installing omniauth 2.0.3
Installing launchy 2.5.0
Installing vault 0.15.0
Installing imgproxy 2.0.0
Installing activesupport 6.0.3.5
Installing faker 2.17.0
Installing redis-rack 2.0.6
Installing rubocop-ast 1.4.1
Installing faraday_middleware 1.0.0
Installing elasticsearch-transport 7.11.2
Installing gibbon 3.4.0
Installing oauth2 1.4.4
Installing sawyer 0.8.2
Installing pry-byebug 3.8.0
Installing pry-rails 0.3.9
Installing fog-core 2.2.3
Installing httparty 0.18.1
Installing webmock 3.12.1
Installing domain_name 0.5.20190701
Installing sidekiq-unique-jobs 7.0.4
Installing loofah 2.9.0
Installing twilio-ruby 5.48.0
Installing reverse_markdown 2.0.0
Installing xpath 3.2.0
Installing approvals 0.0.11
Installing image_processing 1.12.1
Installing html_truncator 0.4.2
Installing http-parser 1.2.3 with native extensions
Installing sass-listen 4.0.0
Installing listen 3.4.1
Installing derailed_benchmarks 2.0.1
Installing fugit 1.4.2
Installing rspec 3.10.0
Installing rspec-retry 0.6.2
Installing buffer 0.1.3
Installing omniauth-oauth 1.2.0
Installing webdrivers 4.6.0
Installing virtus 1.0.5
Installing octokit 4.20.0
Installing rubocop 1.11.0
Installing elasticsearch 7.11.2
Installing omniauth-oauth2 1.7.1
Installing http-cookie 1.0.3
Installing fog-json 1.2.0
Installing fog-xml 0.1.3
Installing rails-dom-testing 2.0.3
Installing globalid 0.4.2
Installing activemodel 6.0.3.5
Installing ahoy_matey 3.2.0
Installing bullet 6.1.4
Installing caze 0.2.2
Installing factory_bot 6.1.0
Installing inline_svg 1.7.2
Installing jbuilder 2.11.2
Installing jsonapi-serializer 2.2.0
Installing pundit 2.1.0
Installing redis-activesupport 5.2.0
Installing shoulda-matchers 4.5.1
Installing capybara 3.35.3
Installing rails-html-sanitizer 1.3.0
Installing feedjira 3.1.2
Installing guard 2.16.2
Installing sass 3.7.4
Installing omniauth-twitter 1.4.0
Installing sidekiq-cron 1.2.0
Installing omniauth-apple 1.0.1
Installing omniauth-facebook 8.0.0
Installing omniauth-github 2.0.0
Installing rest-client 2.1.0
Installing http 4.4.1
Installing activejob 6.0.3.5
Installing fog-aws 3.9.0
Installing activerecord 6.0.3.5
Installing carrierwave 2.2.0
Installing email_validator 2.2.2
Installing modis 3.3.0
Installing validate_url 1.0.13
Installing actionview 6.0.3.5
Installing guard-livereload 2.5.2
Installing guard-rspec 4.7.3
Installing cloudinary 1.19.0
Installing pusher-push-notifications 1.3.0
Installing carrierwave-bombshelter 0.2.2
Installing libhoney 1.18.0
Installing twitter 7.0.0
Installing rpush-redis 1.1.0
Installing honeycomb-beeline 2.4.0
Installing actionpack 6.0.3.5
Installing better_html 1.0.16
Installing kaminari-actionview 1.2.1
Using acts_as_follower 0.2.1 from https://github.com/forem/acts_as_follower.git (at /Users/jamiegaskins/Code/forem/vendor/cache/acts_as_follower-06393d3693a1@06393d3)
Installing flipper-active_record 0.20.4
Installing active_record_union 1.3.0
Installing acts-as-taggable-on 7.0.0
Installing ancestry 3.2.1
Installing hypershield 0.2.2
Installing kaminari-activerecord 1.2.1
Installing database_cleaner-active_record 2.0.0
Installing counter_culture 2.7.0
Installing pg_search 2.3.5
Installing ransack 2.4.2
Installing store_attribute 0.8.1
Installing storext 3.3.0
Installing strong_migrations 0.7.6
Installing actioncable 6.0.3.5
Installing activestorage 6.0.3.5
Installing actionmailer 6.0.3.5
Installing railties 6.0.3.5
Installing omniauth-rails_csrf_protection 1.0.0
Installing sprockets-rails 3.2.2
Installing redis-actionpack 5.1.0
Installing ahoy_email 1.1.1
Installing kaminari 1.2.1
Installing redis-rails 5.0.2
Installing actiontext 6.0.3.5
Installing actionmailbox 6.0.3.5
Using erb_lint 0.0.35 from https://github.com/thepracticaldev/erb-lint.git (at /Users/jamiegaskins/Code/forem/vendor/cache/erb-lint-05596ea189ee@05596ea)
Installing rubocop-rails 2.9.1
Installing rubocop-rspec 2.2.0
Installing rubocop-performance 1.10.1
Installing dotenv-rails 2.7.6
Installing cypress-rails 0.4.2
Installing responders 3.0.1
Installing factory_bot_rails 6.1.0
Installing field_test 0.4.1
Installing jquery-rails 4.4.0
Installing coffee-rails 5.0.0
Installing blazer 2.4.2
Installing doorkeeper 5.5.0
Installing rspec-rails 4.1.2
Installing jquery-fileupload-rails 0.4.7
Installing rails 6.0.3.5
Installing rpush 5.4.0
Installing sassc-rails 2.1.2
Installing web-console 4.1.0
Installing webpacker 5.2.1
Installing rails-settings-cached 2.5.2
Using devise 4.7.3 from https://github.com/heartcombo/devise.git (at /Users/jamiegaskins/Code/forem/vendor/cache/devise-0cd72a56f984@0cd72a5)
Installing devise_invitable 2.0.3
Installing sass-rails 6.0.0
Installing pundit-matchers 1.6.0
Installing s3_direct_upload 0.1.7
Updating files in vendor/cache
Bundle complete! 155 Gemfile dependencies, 353 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from acts-as-taggable-on:
When upgrading

Re-run the migrations generator

    rake acts_as_taggable_on_engine:install:migrations

This will create any new migrations and skip existing ones
Version 3.5.0 has a migration for mysql adapter
Post-install message from ancestry:
Thank you for installing Ancestry. You can visit http://github.com/stefankroes/ancestry to read the documentation.
Post-install message from doorkeeper:
Starting from 5.5.0 RC1 Doorkeeper requires client authentication for Resource Owner Password Grant
as stated in the OAuth RFC. You have to create a new OAuth client (Doorkeeper::Application) if you didn't
have it before and use client credentials in HTTP Basic auth if you previously used this grant flow without
client authentication.

To opt out of this you could set the "skip_client_authentication_for_password_grant" configuration option
to "true", but note that this is in violation of the OAuth spec and represents a security risk.

Read https://github.com/doorkeeper-gem/doorkeeper/issues/561#issuecomment-612857163 for more details.
Post-install message from httparty:
When you HTTParty, you must party hard!
Post-install message from sass:

Ruby Sass has reached end-of-life and should no longer be used.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  https://sass-lang.com/blog/posts/7828841

Post-install message from patron:

Thank you for installing Patron. On OSX, make sure you are using libCURL with OpenSSL.
SecureTransport-based builds might cause crashes in forking environment.

For more info see https://github.com/curl/curl/issues/788
Post-install message from rpush:
When upgrading, don't forget to run `bundle exec rpush init` to get all the latest migrations.

For details on this specific release, refer to the CHANGELOG.md file.
https://github.com/rpush/rpush/blob/master/CHANGELOG.md
Post-install message from sidekiq-unique-jobs:
IMPORTANT!

Automatic configuration of the sidekiq middelware is no longer done.
Please see: https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/README.md#add-the-middleware

This version deprecated the following sidekiq_options

  - sidekiq_options lock_args: :method_name

It is now configured with:

  - sidekiq_options lock_args_method: :method_name

This is also true for `Sidekiq.default_worker_options`

We also deprecated the global configuration options:
  - default_lock_ttl
  - default_lock_ttl=
  - default_lock_timeout
  - default_lock_timeout=

The new methods to use are:
  - lock_ttl
  - lock_ttl=
  - lock_timeout
  - lock_timeout=
Post-install message from ulid:

ulid gem needs to install sysrandom gem if you use Ruby 2.4 or older.
Execute `gem install sysrandom` or add `gem "sysrandom"` to Gemfile.
```

To print out the table of gems, pipe that through this Unix pipeline:

```
pbpaste | ruby -ne 'if /native extensions/; gem = $_.split[1]; blame = `git blame Gemfile.lock| grep "#{gem} (\\d"`.split; puts "| #{blame[-2]} | #{blame[-1]} | #{blame[-6]} |"; end' | sort -rk6
```

</details>

**Comment by jgaskins** [comment]
Actually, that table was from this branch. Here is the one from `master`:

| Gem | Version | Last Updated |
|-|-|-|
| nokogiri | (1.11.2-x86_64-linux) | 2021-03-16 |
| hiredis | (0.6.3) | 2021-03-12 |
| puma | (5.2.2) | 2021-03-03 |
| ruby-prof | (1.4.3) | 2021-02-17 |
| bootsnap | (1.7.2) | 2021-02-09 |
| nio4r | (2.5.5) | 2021-02-08 |
| msgpack | (1.4.2) | 2021-02-02 |
| oj | (3.11.2) | 2021-01-28 |
| racc | (1.5.2) | 2021-01-06 |
| debug_inspector | (0.0.3) | 2021-01-06 |
| binding_of_caller | (0.8.0) | 2021-01-06 |
| http-parser | (1.2.2) | 2021-01-04 |
| eventmachine | (1.2.7) | 2021-01-04 |
| ffi | (1.14.2) | 2020-12-29 |
| redcarpet | (3.5.1) | 2020-12-16 |
| stackprof | (0.2.16) | 2020-10-26 |
| bcrypt | (3.1.16) | 2020-09-28 |
| websocket-driver | (0.7.3) | 2020-09-09 |
| multi_json | (1.15.0) | 2020-08-02 |
| sassc | (2.4.0) | 2020-07-05 |
| unf_ext | (0.0.7.7) | 2020-05-07 |
| patron | (0.13.3) | 2020-04-10 |
| pry-byebug | (3.9.0) | 2020-03-23 |
| bindex | (0.8.1) | 2020-03-23 |
| pg | (1.2.3) | 2020-03-19 |
| html_tokenizer | (0.0.7) | 2019-01-29 |
| yajl-ruby | (1.4.1) | 2019-01-09 |
| http_parser.rb | (0.6.0) | 2018-02-28 |
| approvals | (0.0.24) | 2018-02-28 |

**Comment by citizen428** [comment]
👋 @jgaskins Do we still need this PR?

**Comment by aitchiss** [comment]
@jgaskins just having a look at any PRs we can tidy up - is this one still needed or can we close?

**Comment by jgaskins** [comment]
Ah, nope. I'll go ahead and close.

**Pull request closed without merging**
