### PR TITLE
Update to NodeJS 14.14.x to match with Fedora 33's installed version.

### PR DESCRIPTION
**Pull request by jdoss**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This updates us to NodeJS 14.14 which is the version installed by Fedora 33.

## Related Tickets & Documents

#10594

### CODE REVIEW

**Review by nickytonline — APPROVED** [review]
I'm good with this as long as everything is building fine. Better to be on the latest LTS.

Just give the team a grasp is all.

**Review by maestromac — APPROVED** [review]
:+1:

**Review by citizen428 — APPROVED** [review]

**Review by citizen428 — CHANGES_REQUESTED** [review]
Oops, accidentally hit "Approve". There's at least one more place where the Node version is hardcoded,`.gitpod.dockerfile`.

**Comment by citizen428** [comment]
> Better to be on the latest LTS.

@nickytonline Isn't 14.15 the newest LTS?

Screen Shot 2020-11-10 at 09 20 49

**Comment by citizen428** [comment]
@jdoss Hope you don't mind, I just updated the remaining file myself.

**Review by citizen428 — APPROVED** [review]

**Review by rhymes — APPROVED** [review]

**Review by benhalpern — APPROVED** [review]

**Pull request merged**
