### PR TITLE
Remove Vaidehi from Forem Core Team

### PR DESCRIPTION
**Pull request by vaidehijoshi**
❤️

### CODE REVIEW

**Review by juliannatetreault — APPROVED** [review]
💔

**Review by andygeorge — APPROVED** [review]
💔

**Review by rhymes — APPROVED** [review]
I'll tag you in a commit when you'll least expect it 💔 🤣

**Review by jgaskins — CHANGES_REQUESTED** [review]
nope :trollface:

**Comment by djuber** [comment]
changes requested
:cry:

**Review by jgaskins — APPROVED** [review]
j/k But for real you've been a huge part of Forem's story, since even before you joined the company. Feels like we set up an "alumni" or "special thanks" section.

**Review by fdoxyz — APPROVED** [review]

**Comment by vaidehijoshi** [comment]
> Feels like we set up an "alumni" or "special thanks" section.

@jgaskins Aw, that would be so cute! [Tilde](https://www.tilde.io/about-us) does this for alumns, I've always thought it's a nice touch 💕 

> I'll tag you in a commit when you'll least expect it 💔 🤣 

@rhymes After all the times I've accidentally tagged you and made your notification life _hell_, it's only fair 😅 😂

**Pull request merged**
