### PR TITLE
Use yarn in npm scripts

### PR DESCRIPTION
**Pull request by abenettt**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [X] Optimization
- [ ] Documentation Update

## Description
In accordance to https://github.com/forem/forem-browser-extension/pull/35#discussion_r480300587 the `package.json` has been updated to use `yarn` instead of `npm` for it's scripts. This has been done to improve consistency as we are already using yarn for our dependencies. 
## Related Tickets & Documents
https://github.com/forem/forem-browser-extension/pull/35#discussion_r480300587
## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added tests?

- [ ] yes
- [X] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [X] no documentation needed

### CODE REVIEW

**Review by rhymes — APPROVED** [review]
Thank you @abenettt !

**Comment by abenettt** [comment]
Hmm, for some reason netifly doesn't install `yarn` even tho a `yarn.lock` file is present as specified in the [docs](https://docs.netlify.com/configure-builds/manage-dependencies/#yarn).

**Comment by abenettt** [comment]
Ah, for some reason netlify directly mounts into the `/app/javascript` directory so it can't find the `yarn.lock` file to install `yarn`. This might be because of the `/app/javascript/netlify.toml` configuration file but I am not sure if that is true. I have not found any other netlify configuration in the repository so I guess it is either that or some configuration outside the repository. I am reluctant to just commit 10 different configurations and hope that one of them works so I'm hoping that someone with more knowledge of netlify can say something.

**Comment by nickytonline** [comment]
@Zhao-Andy, if it doesn't work on Netlify, this would be problematic no? Storybook deploys to Netlify and I can see the build for it fails.

**Comment by msarit** [comment]
@abenettt Hey, thanks for this PR! 🙏🏾  Would you please fix the merge conflicts?

**Review by rhymes — CHANGES_REQUESTED** [review]
As @nickytonline mentioned, the Netflify build breaks here https://app.netlify.com/sites/storybookdevto/deploys/5f4f9d9b6b1ffa0007befe64 since `yarn` is not installed. According to https://docs.netlify.com/configure-builds/manage-dependencies/#yarn, yarn needs to be explicitly installed, as the base directory is `docs/` (the one that contains the `netlify.toml` file)

cc @abenettt

**Comment by abenettt** [comment]
I seem to have deleted my fork at one time, but I could open another PR that would then be up to date @rhymes.

**Comment by rhymes** [comment]
@abenettt that would be nice, thank you!

**Comment by abenettt** [comment]
@rhymes OK, I have created a new PR in #12096

**Comment by rhymes** [comment]
Ok thanks @abenettt, closing this

**Pull request closed without merging**
