### PR TITLE
Normalize I18n in precommit

### PR DESCRIPTION
**Pull request by citizen428**
## What type of PR is this? (check all applicable)

- [X] Developer experience

## Description

This PR adds normalization for I18n files to our pre-commit hook.

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by yheuhtozr** [comment]
Ruby's default YAML parser seems to sanitize all characters above U+FFFF (that means, most emoji) into Unicode escape sequences, which I'm not sure we want.

**Comment by yheuhtozr** [comment]
@citizen428 It doesn't involve any error, so not wrong in any way, but I just thought most people today might expect emoji written as they are in the text.

https://github.com/forem/forem/blob/56ee3c571f5dbfa41dc29ac241cd4a6af51dbda8/config/locales/views/misc/fr.yml#L48

https://github.com/forem/forem/blob/53e8bf0919deb32741b441e48d72d1e169d32814/config/locales/fr.yml#L158

**Comment by yheuhtozr** [comment]
Oh it does look like a nasty problem. I'd still like to see this implemented because I don't think many people have a skill to mentally decode code point to emoji.

**Comment by citizen428** [comment]
@yheuhtozr I do see your point. I'm not sure it's much of a problem though because for new strings people can just enter emoji directly and normalize will convert them whereas for existing strings that are newly translated one can just ignore the Unicode sequences. I know it's not ideal and I'd like to see a better fix too but it's not a showstopper as far as I'm concerned.

**Pull request closed without merging**
