### PR TITLE
Render pagination widget to search result

### LINKED ISSUE #16297: Search results are not rendering pagination
**Describe the bug**

Our search results do not appear to render a pagination widget.

**To Reproduce**

On a local machine, you may want to update the search params to have a small page size:

```ruby
# ./app/controllers/search_controller.rb
# Amend the feed_params
def feed_params
  params.permit(FEED_PARAMS).tap { |fp| fp[:per_page] = 2 }
end
```

1. Go to the homepage
2. Search for a word with a lot of instances (e.g. "the")
3. The search results page should render the per_page limit but there will be no indicator of pagination.

**Expected behavior**

1. Go to the homepage
2. Search for a word with a lot of instances (e.g. "the")
3. The search results page should render a pagination widget.

### PR DESCRIPTION
**Pull request by jhonatan-kmt**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Render a pagination widget to search result

## Related Tickets & Documents

- Related Issue #16297
- Closes #16297

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by Link2Twenty** [comment]
This would also close #18206

**Review by joshpuetz — COMMENTED** [review]
Thank you so much for this PR @jhonatan-kmt! Apologies on it taking us so long to review it!

I've pulled the PR down locally, and I'm running into an issue where the first and last pages don't work/highlight correctly. See the attached gif (note that I'm using a modification locally to return only 5 results per page as mentioned [here](https://github.com/forem/forem/issues/16297#issue-1113915635)...could that be impacting it?

CleanShot 2022-08-19 at 15 04 38

**Comment by jhonatan-kmt** [comment]
Hi @joshpuetz, this is not the expected behavior, I will review it and upload the respective changes.

**Comment by Ridhwana** [comment]
Closing and re-opening to trigger the CI-status-report

**Comment by Ridhwana** [comment]
HI @jhonatan-kmt, my sincere apologies that this has not been reviewed again once your changes were made. Are you able to still resolve the conflicts and then we can review?

**Comment by rt4914** [comment]
Hi @jhonatan-kmt 

Thank you so much for the PR and for taking the leap and contributing to DEV! We are super happy to have your help 😄

With that said, we are in the process of going through and cleaning up some of our PR history to help us better prioritize what we need to be focusing on. Since this PR has not been active for a while I am going to go ahead and close it for now.

If you would still like to get this merged please feel free to update your branch with master and get the code ready to merge and then open the PR back up. We would be more than happy to help you push this through if you would like! Also remove the WIP tag once the PR is ready so we know to review it.

Thanks again for contributing! Ping us anytime if you have questions!

**Pull request closed without merging**
