### PR TITLE
Fix typo in migration class name to match filename

### PR DESCRIPTION
**Pull request by jgaskins**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

From the Heroku deployment log:

```
+ [[ '' = \b\l\o\c\k\e\d ]]
+ STATEMENT_TIMEOUT=4500000
+ bundle exec rails app_initializer:setup
== Preparing Elasticsearch ==
== Preparing database ==
rails aborted!
NameError: uninitialized constant AddTsvectorIndexOnSearchableColumnsToListings
Did you mean?  AddTsvectorIndexOnSearchableColumnnsToListings
```

## Added tests?

- [ ] Yes
- [x] No, and this is why: Fixing a typo in a migration
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [x] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] Are there any post deployment tasks we need to perform?

Watch the deployment go live and drink beer

### CODE REVIEW

**Review by rhymes — APPROVED** [review]
Thank you 😭

**Comment by jgaskins** [comment]
@juliannatetreault I'm sorry you got tagged for this automatically. I promise I tried not to tag you on yet another PR. :joy:

**Review by vaidehijoshi — APPROVED** [review]
🙊

**Review by juliannatetreault — APPROVED** [review]
🚀 !!!

**Pull request merged**
