### PR TITLE
Fixing date in listing modal

### PR DESCRIPTION
**Pull request by Rafi993**
##  What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

When listing modal is refreshed the date does not appear this PR fixes that.

## Related Tickets & Documents

Closes https://github.com/forem/forem/issues/11261

## QA Instructions, Screenshots, Recordings

1. Go to /listings
2. Click on a listing with date. It will open up a modal and it will show the date
3. Now refresh the page
4. The modal will show up but with date

## Added tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [x] I need help with writing tests

## Added to documentation?

- [ ] Docs.forem.com
- [ ] README
- [x] No documentation needed

### CODE REVIEW

**Review by citizen428 — APPROVED** [review]

**Review by rhymes — APPROVED** [review]
Thanks a lot @Rafi993!

**Comment by rhymes** [comment]
@Rafi993 I wonder if we can seal this with a test to avoid regression

**Comment by Rafi993** [comment]
> @Rafi993 I wonder if we can seal this with a test to avoid regression

Yes it would be awesome too. Is there any similar test that I can use for reference ?

**Comment by rhymes** [comment]
@Rafi993 I think we can add a test entry to https://github.com/forem/forem/blob/8d08191e9a455225438869e027f989cbd07e1e5c/spec/requests/listings_spec.rb#L31 similar to https://github.com/forem/forem/blob/8d08191e9a455225438869e027f989cbd07e1e5c/spec/requests/api/v0/articles_spec.rb#L24-L36

does it make sense?

**Comment by Rafi993** [comment]
> @Rafi993 I think we can add a test entry to
> 
> https://github.com/forem/forem/blob/8d08191e9a455225438869e027f989cbd07e1e5c/spec/requests/listings_spec.rb#L31
> 
> similar to
> https://github.com/forem/forem/blob/8d08191e9a455225438869e027f989cbd07e1e5c/spec/requests/api/v0/articles_spec.rb#L24-L36
> 
> does it make sense?

There is one issue though. Unlike the above sample it does not return json but rather returns rendered response as html (after passing it to views). Should I check the selectors in the rendered html is that ok?

**Comment by Rafi993** [comment]
> @Rafi993 I think we can add a test entry to
> 
> https://github.com/forem/forem/blob/8d08191e9a455225438869e027f989cbd07e1e5c/spec/requests/listings_spec.rb#L31
> 
> similar to
> https://github.com/forem/forem/blob/8d08191e9a455225438869e027f989cbd07e1e5c/spec/requests/api/v0/articles_spec.rb#L24-L36
> 
> does it make sense?

There is one issue here. **/listings** returns html (unlike json in the sample).  But luckily the data was stored in **data-listings** attribute.  so I tried the following

```ryby
    it "has correct keys in the response" do
      get "/listings"

      parsed_response = Nokogiri.HTML(response.body)
      listings = parsed_response.xpath("//*[@id='listings-index-container']")["data-displayedlisting"]

      index_keys = %w[
        title processed_html tag_list category id user_id slug contact_via_connect location bumped_at
        originally_published_at
      ]

      expect(listings.first.keys).to match_array index_keys
    end
```

**data-displayedlisting** is empty in the test while it has value when viewing the actual dom let me fix that too so that the test can pass.

**Review by rhymes — APPROVED** [review]
Thanks for adding the test! :-)

**Pull request merged**
