### PR TITLE
Excluded gists from InstantClick

### LINKED ISSUE #14428: Embedded GitHub Gists change their order in an unpredictable way
## Problem

Sometimes, when I open one of my [tutorials](https://dev.to/luvejo/how-to-build-a-carousel-from-scratch-using-vue-js-4ki0), I find the embedded [gists](https://gist.github.com/luvejo/0936b7c33a07592d1706818e89abda04) have changed their order. For example, if I specify `snippet-1.js`, `snippet-5.js` gets rendered instead, and so on. They change their order in an unpredictable way.

Needless to say what this means for readers. Specially in a long tutorial.

## Steps to reproduce

It happens sometimes, even if I open the post in incognito mode and no browser extensions. I just can't tell when.

**Desktop:**

- Browser: Google Chrome 92.0.4515.131
- Browser: Firefox 90.0.2 (64 bit)
- OS: Ubuntu 21.04

**Smartphone:**

- OS: Android
- Browser: Google Chrome 92.0.4515.131

By the way, I haven't found another way to show sample code with line numbers. I tried to upload screenshots of my snippets, but tall images are scaled because of their `max-height` rule. That's why I opened this [feature request](https://forem.dev/luvejo/code-blocks-with-line-numbers-3ae0).

### PR DESCRIPTION
**Pull request by natepelzel**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

It looks like this issue is caused by [postscribe](https://github.com/forem/forem/blob/def5de6d28b0621d51b669fd71425254aa5ab29f/app/javascript/utilities/gist.js#L34) conflicting with [InstantClick's script re-evaluation](https://github.com/forem/forem/blob/eae8557cf10e8e8911428b4f7e0aa8036735a94c/app/assets/javascripts/base.js.erb#L421-L444).  This explains why it doesn't happen on a refresh or initial load, but only when clicked from the home page or the author's page.

Since postscribe overrides `document.write`, when InstantClick re-evaluates the gist scripts, it triggers the postscribe callbacks.  (gist scripts make calls to `document.write`).

## Related Tickets & Documents

- Closes #14428

## QA Instructions, Screenshots, Recordings

1. Create an article with multiple different embedded gists and publish it.  I had the best luck with 5 or more gists.
2. Click on a link to that article from either your profile or the home feed. 
3. Before these changes, ~90% of the time, the gists would render out of order.  With these changes, you'll see they always render correctly

### UI accessibility concerns?

No UI changes

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: Not sure my methods are acceptable yet
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

crushing it

### CODE REVIEW

**Comment by natepelzel** [comment]
The simplest solution I found was to exclude those gist scripts from InstantClick's script re-evaluation, but I wanted to get some feedback from someone more involved in this project before submitting the PR.  The questions and alternatives I'm considering are:

* It seems like InstantClick was copied in from a 3rd party library or something, is that right?  If so, how often is that code updated? Is there a chance these changes could get overwritten easily?  If so, I could experiment with maybe delaying postcribe's call until InstantClick is done evaluating scripts, but that seemed more complex

* If this is something that could be an issue other places, maybe implementing a custom attribute for InstantClick to filter by would be a better choice.  Something like `<script src="..." noreevaluate></script>`

Once I know I'm on the right track, I can work on writing tests.  Just wanted to make sure this all seemed acceptable before putting in the extra work.

**Comment by natepelzel** [comment]
I suppose this is still somewhat a WIP, but I wasn't sure how to best get a core team member's eyes on it.  If it needs to be converted back to a draft, let me know.

**Comment by Ridhwana** [comment]
Hey @natepelzel thank you so much for outlining a solution and getting something in Draft. I'll be taking this back to the team and we'll get back to you. ✨

**Review by maestromac — APPROVED** [review]
great solution! tested locally. LGTM!

**Review by joshpuetz — APPROVED** [review]
Tested locally (in Chrome: strangely I can't reproduce this bug in Safari), and it's working! Thanks so much!

**Comment by maestromac** [comment]
re-opening to kick start the build

**Pull request merged**
