### PR TITLE
Update cypress from 8.7.0 to 9.5.4

### PR DESCRIPTION
**Pull request by tnir**
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>

## What type of PR is this? (check all applicable)
- [x] Refactor

## Description
Updates cypress from 8.7.0 to 9.5.4 (latest).

## Related Tickets & Documents
- Related Issue #17338

## QA Instructions, Screenshots, Recordings
See logs on CI.

### UI accessibility concerns?
n/a

## Added/updated tests?

- [x] No, and this is why: CI suite is updated.

### CODE REVIEW

**Comment by tnir** [comment]
Looping in @jeremyf

**Comment by djuber** [comment]
I had a look at https://applitools.com/blog/whats-new-cypress-9/ and https://docs.cypress.io/guides/references/changelog#9-0-0 and didn't see anything immediately problematic. I don't believe we're using contains() in a way that expected to check styles/scripts (it's counter to most of the existing e2e test design to look for that type of content).

Tests ran green (which is a good sign), my local testing had issues, but it also does on main with version 8.7.0, I assume it's not related to the major version upgrade.

**Review by djuber — APPROVED** [review]
This development/test only dependency upgrade, and easy to revert if we need to, no expected risk to production environments.

**Review by jeremyf — APPROVED** [review]

**Comment by aitchiss** [comment]
Great to see this updated! I'm wondering though why we didn't get this update via dependabot 🤔

**Comment by tnir** [comment]
Yes, I wonder why dependabot did not work on creation of this PR 😭

**Pull request merged**
