### PR TITLE
Add CSS for upload button

### LINKED ISSUE #18151: Bring Crayons to file upload
**Describe the request**
I noticed the button in the file uploaded is still the standard HTML button, it would be nice to crayonify this.

**To Reproduce**
1. go to [settings](https://dev.to/settings)
2. scroll down to user
3. see upload option

**Expected behaviour**
It would be nice to have a blue forem-esc button.

**Screenshots**
**Current**
current upload button

**New**
updated upload button

**Additional context**
I've included a [jsfiddle](https://jsfiddle.net/link2twenty/ysh2mcde/) mock up. Styles don't have to go this exact route but I thought I'd get the ball rolling.

### PR DESCRIPTION
**Pull request by lboogie04**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x ] Bug Fix
- [x ] Optimization
- [ ] Documentation Update

## Description
Updates the File Upload button in Settings to make use of Crayon styling.
Screenshot 2022-12-19 at 2 51 34 PM

## Related Tickets & Documents

- Related Issue #
- Closes #18151 

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by anujbhavsar96** [comment]
Is there an outline for the button background? @lboogie04 

Secondary button should look similar to what we have on [tags page](https://dev.to/tags)

**Comment by mirie** [comment]
@Ridhwana I switched up the reviewers list and tagged you for this one

**Comment by Ridhwana** [comment]
@lboogie04 is there potential to re-use our styles from the Secondary button component for this element?

**Comment by Ridhwana** [comment]
> @Ridhwana Yes possibly. Are there currently set styles for the Secondary button somewhere?

@lboogie04 yeah you can find the buttons related styles in this file https://github.com/forem/forem/blob/a350e220201a33539e5eb0e2a2b544d05810a6bd/app/assets/stylesheets/components/buttons.scss#L149-L155

**Review by maestromac — APPROVED** [review]
LGTM!

**Review by fdocr — APPROVED** [review]
🚀

**Comment by Ridhwana** [comment]
Whooop this is awesome 🎉, thanks for the change @lboogie04!

**Review by anujbhavsar96 — APPROVED** [review]

**Pull request merged**
