### PR TITLE
Add logic that does not miss new episodes when RSS is ordered oldest to newest

### PR DESCRIPTION
**Pull request by Miguel-Enrique13**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Added logic to the `Podcasts::Feed` class that checks whether the RSS is ordered newest to oldest or oldest to newest. Depending on the way it's ordered we'll check the first or last five elements of the RSS feed. 

## Related Tickets & Documents
resolves issue #3580 

## Added tests?

- [ ] Yes
- [ ] No, and this is why:
- [x] I need help with writing tests: Since the `Podcasts::Feed` is initialized with a `Podcast` that has a `feed_url` and the `feed_url` is what is used in the `get_episodes` method, I'm not sure how to create a fake `feed_url` that has an RSS feed sorted oldest to newest.  

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

### CODE REVIEW

**Comment by msarit** [comment]
@forem/backend Hey Team BackEnd 👋🏾  Could we get some eyes on this PR please? 🙏🏾

**Comment by joshpuetz** [comment]
> @forem/backend Hey Team BackEnd 👋🏾 Could we get some eyes on this PR please? 🙏🏾

Is this ready to go? @Miguel-Enrique13 still has it as a draft!

**Comment by msarit** [comment]
> Is this ready to go? @Miguel-Enrique13 still has it as a draft!

oops sorry, my last message was without context. The PR owner asked for help re: tests 😄

**Review by djuber — COMMENTED** [review]
regarding testing, I checked the reporting feed from http://techjr.dev/rss.xml and it's now listing in most recent first (so that's no longer representative of the issue as reported, they've worked around our shortcomings)

I'm tempted to edit the xml payload in the se_daily_rss_feed vcr cassette to change the order so that this issue surfaces (I think moving just the oldest item to the front, rather than expecting them to be sorted, is sufficient.) It could be sufficient in a stand alone test to stub the response instead of recording a new cassette or editing this one.

If we had this setup (first item is oldest, other items are newest first) we should be able to change the canned rss response without needing to update any tests (we would still expect that the limit(2) in the spec would get the two most recent examples, in this case from 2017-10-27 and 2017-10-26, and exclude the oldest episode, from 2017-06-12).

```
[2] pry(#<Podcasts::Feed>)> feed.items.map(&:pubDate).take(10)
=> [2017-06-12 09:00:58 +0000,                                
 2017-10-27 09:00:57 +0000,
 2017-10-26 09:00:30 +0000,
 2017-10-25 09:00:10 +0000,
 2017-10-24 09:00:39 +0000,
 2017-10-23 09:00:16 +0000,
 2017-10-20 09:00:43 +0000,
 2017-10-19 09:00:11 +0000,
 2017-10-18 09:00:52 +0000,
 2017-10-17 09:00:03 +0000]
```

I can push up a branch with the example edited file,   https://github.com/forem/forem/commit/3a9dbf0fec8418b511a4f6b4bbb9a360eb0328d2 (again, because of the base64 encoding the diff is highly unlikely to be informative, but a breakpoint in get_episodes as above shows what was done).

**Comment by citizen428** [comment]
@Miguel-Enrique13 Thanks for your contribution! Do you still plan to work on this PR or should we close it?

**Comment by Zhao-Andy** [comment]
Removing myself for now to clear out my reviews -- feel free to request me for review if this gets picked up again!

**Comment by citizen428** [comment]
Hi @Miguel-Enrique13, no rush, but if you could let us know if you still plan to finish this PR it would be much appreciated, thank you!

**Comment by citizen428** [comment]
@Miguel-Enrique13 Since this PR has been dormant for almost 5 months now I'll close it. Please feel free to reopen it if you start working on it again!

**Pull request closed without merging**
