### PR TITLE
Ensure all elements are contained by landmarks in mod center

### PR DESCRIPTION
**Pull request by jacobherrington**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

All elements should be contained by a [landmark element](https://dequeuniversity.com/rules/axe/3.5/region).

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by rhymes** [comment]
I was wondering if you had any idea of how we could work towards having regression tests for these changes?

**Comment by nickytonline** [comment]
> I was wondering if you had any idea of how we could work towards having regression tests for these changes?

Not really sure how we'd test for this regression aside from running an a11y tool during CI.

**Comment by rhymes** [comment]
@nickytonline yeah, that's what I was thinking. There was an effort back then to run Lightouse-CI which has a11y checks but I don't even know if it would catch stuff like this. Maybe aXe or WAVE have github actions?

**Comment by nickytonline** [comment]
> @nickytonline yeah, that's what I was thinking. There was an effort back then to run Lightouse-CI which has a11y checks but I don't even know if it would catch stuff like this. Maybe aXe or WAVE have github actions?

Definitely worth looking in to.

**Comment by rhymes** [comment]
This is the old issue about adding Lighthouse https://github.com/forem/forem/issues/2370 - I also found this https://github.com/marketplace/axe-linter

I'm going to add a card to our Team's backlog project

**Pull request merged**
