### PR TITLE
Run `yarn upgrade`

### PR DESCRIPTION
**Pull request by maestromac**
## What type of PR is this? (check all applicable)
Dependencies

## Description
Did some `yarn audit && yarn upgrade`

```
# Before 
82 vulnerabilities found - Packages audited: 3450
Severity: 32 Moderate | 50 High
Done in 2.71s.

# After
46 vulnerabilities found - Packages audited: 3293
Severity: 34 Moderate | 12 High
Done in 2.49s.
```
## Added tests?
- no, because they aren't needed

## Added to documentation?
- no documentation needed

## [optional] Are there any post deployment tasks we need to perform?
n/a

### CODE REVIEW

**Review by nickytonline — APPROVED** [review]
Going ahead to approve, but just curious why we're not letting dependabot handle this, or does our dependabot configuration not handle security updates?

**Comment by citizen428** [comment]
> does our dependabot configuration not handle security updates

Maybe not for transitive dependencies? We only have `prismjs` listed as a `resolution` but not a `dependency`.

**Review by rhymes — APPROVED** [review]

**Comment by maestromac** [comment]
@nickytonline I only do this when dependabot doesn't immediately patch GitHub vulnerability alerts

**Comment by aitchiss** [comment]
I didn't see anything odd in the checks for this PR, but I think it's killed our buildkite builds with our old friend:

```
error jest-regex-util@27.0.6: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0". Got "14.14.0"
```

**Pull request merged**
