### PR TITLE
remove unique validation article 19894

### LINKED ISSUE #19894: Remove unique body markdown validation
## Is this feature related to a problem? Please describe.

As a post-author, who writes a lot of ritual content, I would like to write the same body content for every edition of the ritual content, so I can efficiently produce ritual content for the platform.

## Describe the solution you’d like

- We currently validate unique combinations of post `body_markdown` and `title`, ensuring repeated content is not published.
- This is a rudimentary validation and doesn't prevent any real-world spam usage (where modifications are trivial to a determined spammer but more friction to genuine users creating ritual content).
- This validation should be removed.

## Definition of Done

- [ ] Remove the unique constraint/validation against post `body_markdown` and `title`.

## Additional Context

- I believe this is set [here](https://github.com/forem/forem/blob/2689da34e7699d389a66858c26d32b5d7a21d3b1/app/models/article.rb#L152C46-L152C46)
- [More context](https://forem-team.slack.com/archives/CAA200SH5/p1689972136032719) (Forem Team Only)

### PR DESCRIPTION
**Pull request by narender2031**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
As a post-author, who writes a lot of ritual content, I would like to write the same body content for every edition of the ritual content, so I can efficiently produce ritual content for the platform.
- remove the article validation as well as scope validation index
```
  validates :body_markdown, uniqueness: { scope: %i[user_id title] }
```

## Related Tickets & Documents

- Closes #19894 

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [axe DevTools](https://www.deque.com/axe/) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

_For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [optional] What gif best describes this PR or how it makes you feel?
Screenshot 2023-09-01 at 3 27 07 PM

### CODE REVIEW

**Review by dukegreene — APPROVED** [review]
Thank you for suggesting this change! The code and mechanics of it look good to me in my local environment - I appreciate you taking care to thoroughly comment the context behind the `down` migration.

"Zooming out" a bit, I am not sure whether the upside of being able to create ritual content more effortlessly outweighs the possible downside of users "spamming" the same non-ritual content at different times of the day in search of engagement. 

I'm not sure if @maestromac  or @PhilipHow have opinions on the tradeoff here, but to me it seems safe enough to ship, provided we stay sensitive to feedback from the Community team in the event users end up abusing the lack of a body markdown uniqueness validation.

**Comment by maestromac** [comment]
Thank you for this PR @narender2031 , we'll have to discuss this internally first and get back to you.

**Comment by mirie** [comment]
@narender2031 thank you for your patience! We discussed internally and aligned on this feature request. I'm moving this out of draft state. I'm sorry that it has taken us a bit to discuss and that has made a schema conflict appear. Do you mind resolving the conflict? 🙏 Thank you so much for your contributions!

**Comment by narender2031** [comment]
Thanks @mirie, I will resolve the conflicts.

**Comment by narender2031** [comment]
it's done  @mirie

**Review by maestromac — APPROVED** [review]
Approved but we're going to schedule a time to release this

**Pull request merged**
