### PR TITLE
Fix commentpreview instantclick issue

### PR DESCRIPTION
**Pull request by benhalpern**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This is some additional functionality that is not working properly with InstantClick relating to this issue: https://github.com/forem/forem/issues/19337

## Related Tickets & Documents

- Related Issue https://github.com/forem/forem/issues/19337

### CODE REVIEW

**Comment by jaw6** [comment]
:link: #19379

**Review by jaw6 — APPROVED** [review]
That explains it :+1:

**Review by filleduchaos — APPROVED** [review]
This does fix it 😅 I forgot about InstantClick

**Comment by yheuhtozr** [comment]
@benhalpern Does this fix for the preview button in "reply" too? It does not seem so in dev.to and I haven't successfully fixed that in #19290.

**Pull request merged**
