### PR TITLE
fix: 🐛 Abort fetch call when user types comma/space

### LINKED ISSUE #16966: Tag autocomplete sometimes shows previous entry under 'top tags'
**Describe the bug**

When you create a post, and click into the "Tags" field, some "top tags" are suggested. After making a selection, the remaining top tags are shown once again.

I noticed that sometimes, when we reset the UI and show "Top tags" again, the list of tags isn't actually the top tags, but the suggestions for the previously entered text. For example:

https://user-images.githubusercontent.com/20773163/159502949-f499c07f-150b-4e7a-bfb1-6b9787c6c8d5.mp4

It seems to be most reproducible if you select tags by using the comma or spacebar keys (rather than clicking an option or using up/down arrows + Enter), which makes me think it's the speed of entry/selection that's causing an issue. My current suspicion is that the last search results are coming back _after_ we've reset the internal state (cleared the input, shown the 'top tags' heading), in which case, we need a mechanism to ignore the late-returning search results - this is purely a hunch at the moment though and the first step will be to observe internally what's causing this disconnect in UI.

**To Reproduce**

1. Go to `/new` as a logged in user
2. Focus the tags field
3. Quickly type and select a tag by typing a word followed by either a space or a comma
4. Eventually you'll see the "top tags" header but with search results for your previous text input. The text input itself will be empty

**Expected behavior**

- When a user selects an option (by any means, including spacebar/comma), the input clears, and the top tags are shown

### PR DESCRIPTION
**Pull request by miguelnietoa**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
The reason why the issues happens is because the asynchronous operation that fetch the search was pending yet when the user types comma/space, so in this PR I try to abort the previous requests in this scenario.

Abort fetch call when user types comma/space

## Related Tickets & Documents

- Closes #16966 

## QA Instructions, Screenshots, Recordings

- **Before:**
https://app.birdeatsbug.com/sessions/82c60DQYwRsw9McrJr2V1LI3r_vgV_XKCUHmMKD9cn9s

- **After:**
https://app.birdeatsbug.com/sessions/vSWh2bvpRogwCtOpZ59LR0YtexjogGI_TxVSrNzEK7F3

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: _no needed, current ones already cover this_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by miguelnietoa** [comment]
Hi there @aitchiss, may you review this, please?

**Review by aitchiss — COMMENTED** [review]
Unfortunately, I can still reproduce the bug, even with this change 🙁  It seems like it's not enough to cancel the network request (although initially the approach made sense to me!).

https://user-images.githubusercontent.com/20773163/162966258-d561a501-7578-4cb5-b33c-97c4933e7c19.mp4

I haven't had time to investigate this bug further, so I'm curious if you have any thoughts on alternatives we could try here?

**Comment by miguelnietoa** [comment]
Oh, sad! 
I can't think of an alternative to solve this. Let me know if you got one or if anyone else has any ideas they can contribute to solving this issue 👍🏻

**Comment by aitchiss** [comment]
> I can't think of an alternative to solve this. Let me know if you got one or if anyone else has any ideas they can contribute to solving this issue 👍🏻

Ah, no worries! I'll put my thinking cap on 🤔  My initial thought is that we have a disconnect between the static suggestions ("top tags") state and the "suggesting" state - perhaps we can work around the issue by clearing up that distinction.

What I mean is that when the bug happens we are showing the "Top tags" heading, but not rendering the top tags. So it feels like the _heading_ knows that we are in the 'static suggestions' state, but the suggestions list doesn't 🙃

**Comment by aitchiss** [comment]
Hey @miguelnietoa! I was thinking about this earlier and I think I've been able to come up with a fairly straightforward fix, so I'm going to close this PR in favour of https://github.com/forem/forem/pull/17419

Thanks again for your work on this one - as much as it didn't fully solve the bug, I think it was necessary and valuable work to help us see a path forward

**Pull request closed without merging**
