### PR TITLE
Ghost textarea fixes

### LINKED ISSUE #12711: Comment composer padding disappears on hover/focus
**Describe the bug**

**To Reproduce**

1. Go to a DEV post
2. Hover over comment composer/focus on it

**Expected behavior**

Padding should remain constant

**Screenshots**

https://user-images.githubusercontent.com/3102842/108140484-25666080-7090-11eb-88a2-e6333567e202.mov

**Desktop (please complete the following information):**

- OS, version: Mac OS 11.1
- Browser, version: 88.0.4324.150

### PR DESCRIPTION
**Pull request by ludwiczakpawel**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This PR fixes two issues:

1. Inconsistent padding on commenting textarea
2. Wrong font on `/new` view textarea.

Both were caused by the same optimization I've introduced the other day (unfortunately sometimes little issues like this are hard to catch).

## Related Tickets & Documents

- Closes #12711

## QA Instructions, Screenshots, Recordings

If you can't reproduce behavior reported in #12711 then it probably works 👍  :D 

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://docs.forem.com/frontend/accessibility)._

## Added tests?

- [ ] Yes
- [x] No, and this is why: not needed
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [x] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

### CODE REVIEW

**Review by nickytonline — APPROVED** [review]
Tested locally. Looks good! 🚀

**Review by aitchiss — COMMENTED** [review]
I'm still seeing this behaviour on Chrome (but Firefox and Safari are both fine)

gif showing the original bug with padding changing on hover

**Comment by ludwiczakpawel** [comment]
> I'm still seeing this behaviour on Chrome (but Firefox and Safari are both fine)
> 
> gif showing the original bug with padding changing on hover

Cache maybe?

**Review by rhymes — APPROVED** [review]
I can't reproduce it neither on Edge nor on Chrome

**Comment by aitchiss** [comment]
> Cache maybe?

100% @ludwiczakpawel - woops! sorry, all looks good 🙂

**Pull request merged**
