### PR TITLE
removed envied docs

### PR DESCRIPTION
**Pull request by yihyang**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation Update

## Description

Since ENVied Gem has been replaced by "dotenv" gem in the recent PR: https://github.com/forem/forem/pull/9767, the documentation should be update too.

## Related Tickets & Documents
Related PRs: https://github.com/forem/forem/pull/9767

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added tests?

- [ ] Yes
- [x] No, and this is why: _this is a documentation update_
- [ ] I need help with writing tests

## Added to documentation?

- [x] Docs.forem.com
- [ ] README
- [ ] No documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Review by rhymes — COMMENTED** [review]
Hi @yihyang, great catch! could you do the same for `windows.md` and `linux.md` and `docs/getting-started/config-env.md` ? thank you!

**Comment by yihyang** [comment]
Hi @rhymes I have updated https://github.com/forem/forem/pull/11160/commits/5ab01c008b7742457ca9f6fab4c556d2660e1402

the `docs/getting-started/config-env.md ` seems to be pointing to the correct URL: https://github.com/forem/forem/blame/master/docs/getting-started/config-env.md#L39

**Review by benhalpern — APPROVED** [review]

**Comment by rhymes** [comment]
Thanks for the update @yihyang! I meant line 40 which points to envied :D https://github.com/forem/forem/blame/master/docs/getting-started/config-env.md#L40

**Comment by yihyang** [comment]
No worries @rhymes ! I think I removed in https://github.com/forem/forem/pull/11160/files#diff-bf09359bfc0d17184b7af3a60fe146c0e6e06949126ea2f38551510f25b3da5fL40
Can help me verify it? Thanks

**Review by rhymes — APPROVED** [review]
Great, sorry I didn't notice @yihyang, LGTM!

**Pull request merged**
