### PR TITLE
Migrate ProfileImage to Images::Profile

### PR DESCRIPTION
**Pull request by maestromac**
## What type of PR is this? (check all applicable)

- [x] Refactor

## Description
Prefer Module over Class and update the name from "profile image" to "avatar".

## Related Tickets & Documents
n/a
## QA Instructions, Screenshots, Recordings
Spec should've caught all the issues.

1. Boot up the server locally.
2. You should be able to browse all pages normally.

## Added tests?

- [x] yes, updated existing tests. I broke so many test 😩 

## Added to documentation?
- [x] no documentation needed

## [optional] Are there any post deployment tasks we need to perform?
n/a

### CODE REVIEW

**Comment by maestromac** [comment]
@mstruve it's shorter and seeing the word `image` being repeated twice in `Images::ProfileImage` feels a bit off, and `Images::Profile` is straight up confusing. 

I'm not married to it though. if @benhalpern thinks there's a better word or we should revert please let me know.

**Comment by mstruve** [comment]
Works for me, I was just curious, to me ProfileImage seemed very clear but I do see how the redundancy could be annoying

**Comment by maestromac** [comment]
After looking around the codebase, my change here might add more confusion than I initially thought. I'd rather be consistent so I'm no longer going with Avatar.

**Comment by rhymes** [comment]
@maestromac what about `Images::Profile.call()` ? The suffix in `ProfileImage` might be redundant

**Pull request merged**
