### PR TITLE
Freeze CodeClimate test reporter to 0.7.0

### PR DESCRIPTION
**Pull request by rhymes**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Builds like this one - https://travis-ci.com/github/forem/forem/jobs/463471583#L1301-L1304 - are currently broken because CodeClimate's test reporter latest release, 0.9.0, has accidentally pushed the macOS binary in lieu of the Linux binary to the `-latest-` URL.

We temporarily hardcoded to the previous release until this gets fixed

## Related Tickets & Documents

https://github.com/codeclimate/test-reporter/issues/449

## QA Instructions, Screenshots, Recordings

Wait for the build to be successful or:

1. download the binary with: `curl -LO https://codeclimate.com/downloads/test-reporter/test-reporter-0.7.0-linux-amd64`
2. issue `file test-reporter-0.7.0-linux-amd64`
3. ensure the result is something like `ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked`

### CODE REVIEW

**Review by nickytonline — APPROVED** [review]
Nice find @rhymes!

**Review by citizen428 — APPROVED** [review]

**Comment by nickytonline** [comment]
I had to add this fix to #11958. Chicken or the egg? 😄

**Comment by rhymes** [comment]
@nickytonline I'm going to close this one, let's merge the other one :D

**Comment by rhymes** [comment]
Superseded by https://github.com/forem/forem/pull/11993

**Pull request closed without merging**
