### PR TITLE
Issue #9077 has already been resolved, added specs

### PR DESCRIPTION
**Pull request by lsparlin**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description
I looked into the issue and tested it locally. I also added a couple new specs that show my findings. This issue seems to have already been resolved. 

## Related Tickets & Documents
#9077

## QA Instructions, Screenshots, Recordings

- Mention a user on an article inside a code block or inside a snippet
- That use should not  have any new notifications and no new Mentions should be created

## Added/updated tests?

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

### CODE REVIEW

**Comment by fdoxyz** [comment]
Thanks for the contribution @lsparlin! Adding test coverage on that case seems very helpful to me

The report from rhymes in that issue linked to a liquid tag though. To test this I added `@admin_mcadmin` to the description of [this dummy PR](https://github.com/fdoxyz/forem/pull/166) and then submitted the github liquid tag to my local environment.

Screen Shot 2021-11-10 at 06 58 20

The @ mention indeed doesn't trigger within a codeblock, but it does seem to still happen within liquid tags. I'm not very familiar with the area of the code where we add the exception for the codeblock, but maybe we need to include something to also avoid liquid tags triggering this.

I'm very unsure how tricky this might be, but it if possible we could maybe use these generated classes to do something similar to what codeblocks are doing to avoid triggering the mention.

Screen Shot 2021-11-10 at 07 03 47

**Comment by lsparlin** [comment]
@fdoxyz oh I see the comment from rhymes now. I was looking at the original description. I'll dig deeper and see if I can resolve the liquid rendered html having mention syntax

**Review by benhalpern — APPROVED** [review]

**Comment by benhalpern** [comment]
I came across this and approved, but may have been pre-emptive. Removed my approval.

**Comment by lsparlin** [comment]
Apologies for the delay in addressing this, it was a busy week. I believe this PR solves this - if my assumption is correct that there shouldn't be mentions inferred from _any_ html embedded by liquid tags, which seems to be the case

**Review by fdoxyz — APPROVED** [review]
Awesome, I gave this a try locally and the mention no longer trigger notifications within the liquid tag.

Thanks for this @lsparlin!

**Review by Ridhwana — APPROVED** [review]

**Pull request merged**
