### PR TITLE
Add VCL snippet for client geo header

### LINKED ISSUE #19792: Update Fastly config to include client country and region as a header
## Is this feature related to a problem? Please describe.

As a billboard creator, I’d like to restrict billboard displays to a particular country or region where they are most relevant. And as a platform, we want to offer this service without tracking or storing users' personally-identifying information.

## Describe the solution you’d like

Fastly, our edge network, has a built-in geolocation service that can be used to determine the country and region that a request originates from (based only on its IP address, which is information we require anyway to even serve the site to them). IP geolocation accuracy varies based on the visitor's ISP and how up-to-date the geolocation service's tables are, but in general is fairly accurate (95%+ at identifying the country, and ~80% at identifying the region).

## Definition of Done

- [ ] Incoming web requests have a header (`HTTP_CLIENT_GEO`) attached with the (fairly) accurate ISO 3166-2 country and region code of the requester (e.g. `"US-NY"` for the state of New York).

## Additional Context

[Fastly resource on geolocation at the edge](https://developer.fastly.com/learning/concepts/geolocation/)

### PR DESCRIPTION
**Pull request by filleduchaos**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This will get Fastly to send us clients' geolocation as a header, as an important step in targeting billboards by location.

We'll have to do further VCL updates in the future to support geofencing at the edge, but as that requires backend support beyond a Fastly config, I think it's best to hold off on that until #19790 

## Related Tickets & Documents

- Related Issue #19792
- Closes #19792

## QA Instructions, Screenshots, Recordings

N/A - see post-deploy

## Added/updated tests?

- [x] No, and this is why: this doesn't seem to need internal tests?

## [optional] Are there any post deployment tasks we need to perform?

From what I can tell, someone will need to deploy the new config to Fastly. Then I am not sure how we could check that the headers are being attached to requests before forwarding to our servers?

## [optional] What gif best describes this PR or how it makes you feel?

Cat driving a car fast

### CODE REVIEW

**Comment by Ridhwana** [comment]
@filleduchaos and @klardotsh I wanted to make sure that this PR is aware of the PR for [fastly_config: Soft-deprecate FastlyConfig service used only for DEV](https://github.com/forem/forem/pull/19837/files) in this PR.

Maybe this part is relevant: 

```
As such, if VCL snippets are added to the snippets directory, a Forem employee
# should replicate them in the appropriate infrastructure repository and roll
# them out to other non-DEV Forems.
``

**Comment by klardotsh** [comment]
Yep, the corollary merged as https://github.com/forem/infra/pull/575. This is still fine to submit, just go ahead and replicate it over in the infra repo as well if you don't mind (a literal on-disk copy of the VCL snippet file, and a "fill in the entry in the dictionary seen in the file", should be all that's necessary; I can handle the deploy side).

**Review by klardotsh — APPROVED** [review]

**Review by maestromac — APPROVED** [review]
Nice incode comment!

We have a release task that will run and automatically deploy this change. Should we stest this out on staging that has fastly-enabled first?

**Review by Ridhwana — APPROVED** [review]
✨

**Comment by filleduchaos** [comment]
@maestromac I think it's fine to deploy, but post-deploy we might want to look at something (request logs maybe?) to see if we are getting the header

**Pull request merged**
