### PR TITLE
(Really) Enable multiple reactions on #index

### LINKED ISSUE #19135: Update posts on index page to display the multiple reactions
This is a followup (post-launch) issue for Multiple reactions to address the following inconsistency:

### Problem

On index pages, there was an inconsistency on how reactions are displayed on the list of Posts. This was first noticed https://github.com/forem/forem/issues/19064#issuecomment-1421240035 and https://github.com/forem/forem/issues/19064#issuecomment-1424891619.

The following [issue](https://github.com/forem/forem/issues/19134) made a change so that the previous/old heart icon + reaction count displayed on Posts on index pages.

### Requirement
This issue is focused on resolving the display discrepancy so that we can show the selected multiple reactions, like this:

Image

Other notes: 
Please also see this comment on a closed issue: https://github.com/forem/forem/issues/19064#issuecomment-1434294365

### LINKED ISSUE #19144: Multiple reactions missing on profile index page
Multi-reactions are visible on the profile page article card and not visible on the index page. 

For consistency, we should remove it from the profile page and release it when it’s ready for both pages.

### PR DESCRIPTION
**Pull request by jaw6**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

From #19169: 
> For a variety of reasons, prior to turning on the feature flag for `multiple_reactions`, [we removed the "stack" display](https://github.com/forem/forem/issues/19134) from `articles#index` views. Some of these reasons include:
> 
> * We don't have feature-flag support in the front-end, so front-end rendered views were still using "simple reactions"
> * We render the home page server-side for _logged-out_ users, but client-side for _logged-in_ users — so, logged-out users would see the "multiple reactions stack" but logged-in users would not
> * We have some `#index` views (`/t/<tag>` for example) that use hybrid rendering (first page renders server-side, later pages are rendered client-side), so these pages would have seen a mix of "simple" and "multiple" reactions counts
> 
> In this PR, we're turning the `multiple_reactions` on across `#index` views, both server-rendered and client-rendered.

In #19197, we reverted, because there were issues with the new reaction icons not being visible in production-like environments.

Screen Shot 2023-03-01 at 16 55 29

Rails asset pipeline tries to make complex image URLs "easy" by way of helpers, but we don't have access to these helpers in the front-end.

In _this_ PR, I'm introducing a new, server-rendered `div` that contains all the (public visible) reaction categories, which the client-side code can then reference to build the reaction badges. In this way, the client-side rendered views gain access to Rails-generated image paths.

## Related Tickets & Documents

- Related Issue #19197 #19169
- Closes #19135 
- Closes #19144 

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: front-end visual change
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [x] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by jaw6** [comment]
`cc` @maestromac

**Comment by jaw6** [comment]
Thanks to @maestromac deploying this to `canary1`, it looks like this works now:

Screen Shot 2023-03-07 at 16 11 04

**Review by Ridhwana — COMMENTED** [review]
@jaw6 I have not reviewed the code as yet, just did a quick testing on the interface at first. I noticed some issues on the logged out view and then an issue when clicking on the reactions on the index page.  

https://www.loom.com/share/c623ba9d2a784edb9c63a9ab4488fe59

Hopefully there wasn't something that I needed to enable etc. before testing this?

**Comment by jaw6** [comment]
@Ridhwana 

> just did a quick testing on the interface at first. I noticed some issues on the logged out view and then an issue when clicking on the reactions on the index page.

Fantastic finds!

* `missing translation en.core.search` was a bit of a red-herring: the `bullet` gem inserts its warnings in a way that breaks the page, so the `locale` JS utility couldn't find the translations
* `bullet` was right, though: I had missed (at least one) eager-loading opportunity
* And the click problem was a React syntax problem (I am still getting up to speed on React)

**Review by Ridhwana — APPROVED** [review]
LGTM!

**Comment by mirie** [comment]
@jaw6 Can you catch me up to speed on the next steps for this PR? 🙏

**Pull request merged**
