### PR TITLE
Added a skip link for the admin area

### LINKED ISSUE #15339: Add a skip link to the admin area
**Describe the bug**

Like the client-facing portion of a Forem instance, the admin area requires a skip link as well to make the admin experience more accessible.

**To Reproduce**

1. Navigate to any page in the admin section, e.g. http://localhost:3000/admin
2. Use the TAB key to navigate the site
3. No skip link appears and an admin is forced to navigate through the entire sidebar menu.

**Expected behavior**

A skip link should be included so an admin can access the main region of a page in the admin section.

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

### PR DESCRIPTION
**Pull request by nickytonline**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Adds a skip link to admin pages

## Related Tickets & Documents

Closes #15339

## QA Instructions, Screenshots, Recordings

1. Navigate to http://localhost:3000/admin
2. Use the tab key to navigate the page
3. The first focusable element will be the skip link
4. Press ENTER
5. continue to tab. Notice the next thing that has focus is the first focusable element in the `<main />` tag.

https://user-images.githubusercontent.com/833231/141027695-0d0fe4d6-34c2-44ed-b3c1-ef59461c7a5d.mp4

### UI accessibility concerns?

Makes the page more accessible by allowing an admin to jump right to the main content of the page.

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: I'm not sure if it's worth the overhead of a test. Also, from what I remember, this is not something we can test in Cypress @aitchiss? We have some skip link tests in the client-facing portion of a Forem instance but it's related to search and not so much testing of a skiplink. We could maybe introduce cypress-axe, but that's bigger discussion and we also need to be mindful of tests times.
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [x] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

Jordan Peele in a skit saying Noice!

### CODE REVIEW

**Review by jeremyf — APPROVED** [review]
Looks like Travis failed on a PG timeout…which I can't imagine this PR would've introduced that error.

**Review by Ridhwana — APPROVED** [review]

**Comment by aitchiss** [comment]
@nickytonline For some reason this skip to content link never becomes visible for me (I've tried Firefox and Chrome) - if I press tab and then Enter, I can see that it's working, but I just never manage to see it 🙃  I suspect the styles aren't always getting pulled in...

I'm going to look at it in a PR for https://github.com/forem/forem/issues/15006

**Comment by nickytonline** [comment]
Weird as it was working when his got merged. 🤔

**Comment by aitchiss** [comment]
> Weird as it was working when his got merged. 🤔

Yeah it's very strange... I think it's probably a perfect storm of where those styles get loaded in, and because we only import the 'focus-visible' package in `Search.jsx` (the styles rely on the class it adds). Pulling both explicitly into the admin code seems to fix it for me.

**Pull request merged**
