### PR TITLE
Add PGHero for more insights into the DB

### PR DESCRIPTION
**Pull request by jgaskins**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

PGHero is a Ruby gem that provides insights and recommendations for Postgres databases. It checks for things like duplicate/unused indexes (including suggested ActiveRecord migration commands to remove them), recommended indexes to add, and lets you inspect and terminate long-running queries through the UI. It's kinda like the Sidekiq management UI but for Postgres.

Screenshot of the PG Hero user interface

*NOTE:* The recommendations PGHero provides are not meant to be used as the sole reason to add/remove indexes! Determining what we should do with indexes is more complicated than that and these recommendations are often based on a binary used/unused check. There are other tools that can give better insight but are a lot more invasive than this and we might not even be able to use them since they typically require installing new extensions — not just `CREATE EXTENSION`, but actually installing a `.so` file on the DB server, which is not something we can do for DEV and other AWS RDS instances.

## QA Instructions, Screenshots, Recordings

- Visit `/admin/pghero`
- Admire the sights

### UI accessibility concerns?

Not gonna lie, I have not looked into the a11y of the UI for this gem.

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: The only application code is a scheduled worker that calls a PGHero command if the environment variable is set.
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [x] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

### CODE REVIEW

**Comment by fdoxyz** [comment]
Yes, that's in there too:

```
Caused by:
LoadError: dlopen(/Users/fdoxyz/.rvm/gems/ruby-3.0.2/gems/google-protobuf-3.18.1-universal-darwin/lib/google/3.0/protobuf_c.bundle, 9): no suitable image found.  Did find:
	/Users/fdoxyz/.rvm/gems/ruby-3.0.2/gems/google-protobuf-3.18.1-universal-darwin/lib/google/3.0/protobuf_c.bundle: mach-o, but wrong architecture
	/Users/fdoxyz/.rvm/gems/ruby-3.0.2/gems/google-protobuf-3.18.1-universal-darwin/lib/google/3.0/protobuf_c.bundle: mach-o, but wrong architecture - /Users/fdoxyz/.rvm/gems/ruby-3.0.2/gems/google-protobuf-3.18.1-universal-darwin/lib/google/3.0/protobuf_c.bundle
/Users/fdoxyz/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/fdoxyz/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/fdoxyz/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/fdoxyz/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/fdoxyz/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/fdoxyz/.rvm/gems/ruby-3.0.2/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'

...
```

**Comment by citizen428** [comment]
@jgaskins / @fdoxyz Did either of you make any progress debugging this? 😃

**Comment by jgaskins** [comment]
@citizen428 Ooh, thanks for the reminder. I got distracted while messing with it before.

Yes, actually. It seems to be something going on between Bundler and the universal compiled package. Protobuf provides only a single [combined Intel/ARM-compiled C extension](https://github.com/forem/forem/blob/4606d364823d3d6f0636c6547ccc471bfdd4e834/Gemfile.lock#L331) whereas libraries like Nokogiri provide [one for each architecture](https://github.com/forem/forem/blob/4606d364823d3d6f0636c6547ccc471bfdd4e834/Gemfile.lock#L485-L487). So we didn't have to do anything special for Nokogiri because it chose the `.so` file for the current architecture.

The solution here seems to be on setting `bundle config set force_ruby_platform true`. The `BUNDLE_FORCE_RUBY_PLATFORM=true` env var does the same thing, but it looks like we were doing that only for bundling and not for running it. Apparently it needs to be set globally.

Oddly, I couldn't use this setting before (I actually had to _unset_ it) because it caused problems with Nokogiri. I don't remember what they were, unfortunately — it was a while before I posted this PR. But I think that I installed both gems at different times under different configurations was the reason it worked for me before and why reinstalling everything reproduced the issue @fdoxyz was seeing.

### Solution

Due to recent changes, the Bundler setting `force_ruby_platform` seems to work. Enable it globally with this command:

```ruby
gem install bundler -v '2.2.30' # The version I tested against, the latest as of this writing
bundle config set force_ruby_platform true
```

Then you should be able to install the gems load the application:

```ruby
bundle install && rails db:migrate data_updates:run && rails runner 'puts "It works!"'
```

I've been able to do this several times reliably even after running `rvm gemset empty` to remove all installed gems. @fdoxyz Can you confirm?

**Comment by jgaskins** [comment]
(to clarify, I'll add this to the docs if this works for more than just me)

**Review by fdoxyz — APPROVED** [review]
> @fdoxyz Can you confirm?

Thanks @jgaskins! I can confirm it worked on my machine now 🙌  the steps I followed were:

```ruby
rvm gemset empty
gem install bundler -v '2.2.30'
bundle config set force_ruby_platform true
bin/setup && bin/startup
```

**Comment by jgaskins** [comment]
Docs are updated with this info. Merging this in.

**Pull request merged**
