### PR TITLE
Make the footer links dynamic

### PR DESCRIPTION
**Pull request by Ridhwana**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
In [another PR](https://github.com/forem/forem/pull/10754) we added a NavigationLinks Table and made all the links on the sidebar dynamic, such that an admin can configure what links they want to show on http://localhost:3000/admin/navigation_links and it will appear on the sidebar. 

We now applying that same workflow to the footer and rendering the items from the NavigationLinks Table instead of hardcoding them. 

_Note: I've had to amend use grids more dynamically and make the template render in a dynamic way. This means that we were not able to group the links in the same manner_

## Related Tickets & Documents
https://github.com/forem/InternalProjectPlanning/projects/5#card-47436154

## QA Instructions, Screenshots, Recordings
**Hardcoded Links:** 
Screenshot 2020-10-19 at 11 22 08

**Dynamic Links:**
Screenshot 2020-10-19 at 14 14 02

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by Ridhwana** [comment]
@ludwiczakpawel we're working on a bunch of priority issues for a launch, and making the footer dynamic is one of them. In order to make it dynamic, I had to amend the styling. Please can you review :)

**Comment by ludwiczakpawel** [comment]
I do understand the reasoning but I don't think it's the right solution. 

image

Except the things that seem to be broken (see screenshot above) there are some design/product things I'm not sold on, for example - if we make this whole thing dynamic in that way, we will likely introduce some confusion around order of the links. Previously, links were more or less logically grouped together into columns... 

```
Link 1       Link 4       Link 7
Link 2       Link 5       Link 8
Link 3       Link 6     
```

And now it's no longer grouped in that way, instead we have this:

```
Link 1       Link 2       Link 3
Link 4       Link 5       Link 6
Link 7       Link 8     
```

The groups/columns I’ve mentioned were supposed to be:
1. Main information architecture: home, reading list, listings, podcasts, …
2. Less important pages, mostly content pages: CoC, FAQ, About, …
3. „Other stuff” like Sponsors, DEV Shop

With new solution it will be all kinda mixed together and not very logical therefore the columns-like UI here doesn’t make much sense.

**Comment by Link2Twenty** [comment]
It feels like the backend needs a column field too.

link name
link location
link column
link position

**Comment by Ridhwana** [comment]
Some discussions regarding this issue: 

> Previously, links were more or less logically grouped together into columns...
The Links should definitely run per column and not per row, that was my mistake and I'll fix that up now. 

>The groups/columns I’ve mentioned were supposed to be:
>Main information architecture: home, reading list, listings, podcasts, …
>Less important pages, mostly content pages: CoC, FAQ, About, …
>„Other stuff” like Sponsors, DEV Shop

These groupings will become difficult to form/maintain as the links are now dynamic and the user can create _any number of links and any type of links_, - these links may not confirm to these groupings. One "potential grouping" may also have many more links than another grouping which would have an impact on the UI. Hence I guess we could possibly maintain these groupings on the admin as well as per @Link2Twenty's suggestion of adding a `column name/grouping`, although I do feel like we should give this more thought before implementing - taking into consideration the dynamic nature of the links and how it will impact these groupings. Also maybe we should discuss do we limit the number of links that a user can create? 

However an interim solution I'd like to propose is that we match up the order of the sidebar and the footer. I think that if we want sponsors and DEV Shop to show up together on the footer, we should have them after each other on the sidebar as well. I can't think of a reason why the logical order on the sidebar and footer should be different. Having these reflect each other would at least provide a good order (but would not sort out the groupings issue). We could for now maintain 6 items in per column. 

It won't be an exact match to what we currently have on DEV and we'd need to figure out what the next step is to get this in a better shape. In the future these issues should be discussed with product/design beforehand.

**Comment by Ridhwana** [comment]
Update: I've amended the flow to be column based instead of row based.

**Comment by Ridhwana** [comment]
**_Updated Note:_**

screencapture-localhost-3000-admin-navigation-links-2020-10-19-14_20_06

If we amended our order of our navigation links on the sidebar to be logically inline with our groupings we could accomplish the following:

_Hardcoded Links:_
Screenshot 2020-10-19 at 14 20 38


_Dynamic Links:_
Screenshot 2020-10-19 at 14 20 23


However, keep in mind this will alter the order of the sidebar as well, which I don't think is a bad thing as it will be more logical:
Screenshot 2020-10-19 at 14 23 17

Thoughts?

**Review by pkfrank — APPROVED** [review]
This looks good to me from a functionality perspective.  That said, I'm not capable of "approving" the technical implementation so defer to others there.

**Review by benhalpern — APPROVED** [review]
This looks good to me right now. It's also a fairly small change we can build on later with further customization, but serves our needs very well now.

**Pull request merged**
