### PR TITLE
Returns an error code when validation fails

### LINKED ISSUE #19587: Creating an article with a title too long for example returns a 200 on the post
**Describe the bug**

Creating an article with a title too long for example returns a 200 on the post.
It's the same for anything that is wrong in the front matter too.

EDIT: It's the same if we're trying to update (PUT)

**To Reproduce**

1. Open dev.to
2. Create a new article with a really long title
3. Press save as draft
4. Notice that you get an error displayed

image

5. Look into the network dev tool, you'll see that even though it was returning an error, the returned status is 200 like everything was fine

image

**Expected behavior**

Should return an error code

### PR DESCRIPTION
**Pull request by dhurba87**
## What type of PR is this? (check all applicable)
- [x] Bug Fix

## Description
Returns error status code when updating fails

## Related Tickets & Documents
- Closes #19587

## QA Instructions, Screenshots, Recordings
Screenshot 2023-07-11 at 22 23 29
Screenshot 2023-07-11 at 22 22 49

## Added/updated tests?
- [ ] Yes
- [x] No, and this is why: Not needed
      have not been included_
- [ ] I need help with writing tests

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
@dhurba87 Thanks a lot for the PR. 
There are couple of suggestions.
1. Don't force-push commits on PRs. It tampers the commit history and can make PR review difficult in longer PRs.
2. Have a look at https://github.com/forem/forem/pull/19734/files it looks like there are multiple non-required changes. These can be reverted (This is optional and not mandatory)
3. Finally, for this PR you will need to add tests to make sure that the `code-coverage` passes for this PR. Let us know if you need help with tests.

**Review by rt4914 — COMMENTED** [review]
Screenshot 2023-07-15 at 1 03 47 AM

So if you look at this screenshot you can actually put the `render json:` part outside and that way you can simply add `status` at the end of current code resulting less changes on PR. 

Anyways, this is not a mandatory change, just a suggestion.

**Comment by rt4914** [comment]
@dhurba87 Have a look at my above suggestion. Thanks :-)

**Review by dukegreene — APPROVED** [review]
I agree that Rajat's suggestion above would probably get the code coverage bot to stop complaining about the coverage percentage. And it would definitely be simplest.

A more complicated way to address it with less lingering "tech debt" (not created by you! thanks for uncovering it with this helpful change) would be from the opposite direction: by testing the line 194 `else` case explicitly. 

There are specs for controller responses with various edge cases considered in [the articles update request specs](https://github.com/forem/forem/blob/main/spec/requests/articles/articles_update_spec.rb), but I didn't see any in there that specifically try to update an Article with invalid data and check for that "sad path" response.

In the spirit of leaving things a little better for the next coder, you could try a test like

```
it "returns an unprocessable status with invalid params" do
    put "/articles/#{article.id}", params: {
      article: { title: nil, body_markdown: nil }
    }
    expect(response.status).to eq(422)
  end
  ```
 I haven't attempted to run it, I'm just copypasting from the first spec in the linked file and changing some things. 
 
If you attempt the simpler fix and it doesn't work for some reason, that test is a strategy I'd recommend. If simple does work, we can fold sad path tests for article create/edit into our existing issues backlog and refine/prioritize them in our regular workflow.
 
 Thanks again for your contribution!

**Review by rt4914 — APPROVED** [review]
Thanks for continuous work on this PR. Really appreciate your efforts @dhurba87 . 🥳

**Pull request merged**
