### PR TITLE
Sort Options have more clickable area and appropriate style on hover

### PR DESCRIPTION
**Pull request by vishaldeepak**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Related Tickets & Documents

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by aitchiss** [comment]
Hi @vishaldeepak 👋  Just checking in to see if you're still working on this one?

**Comment by vishaldeepak** [comment]
I think I might have just forgotten to make some final changes, will get back to you @aitchiss in a couple of days

**Comment by vishaldeepak** [comment]
@aitchiss Looks like the sort options for comments were reverted, so this PR makes no sense any more

**Comment by aitchiss** [comment]
Hey @vishaldeepak I think the sort options for comments were reverted due to the UI issues we identified (including this clickable area work). We'd still very much value this feature/contribution if you're keen to continue working on it? It would involve re-opening your original PR, and including this larger click area with it.

**Comment by vishaldeepak** [comment]
@aitchiss That would actually be great. But I would need some help, as to figure out what exactly went wrong

**Comment by aitchiss** [comment]
Yes of course! Sorry @vishaldeepak I can see that the issues were not very well communicated, and I can see some are already resolved. I'm putting this on my todo list for today/tomorrow - I'll look through the old communications and update the main issue (https://github.com/forem/forem/issues/16133) with the full details.

I'm fairly confident that the only issues left are fairly small UI tweaks, so hopefully we can see your awesome work merged again soon enough ✨

**Pull request closed without merging**
