### PR TITLE
Improve keyboard accessibility of comment rate limit and error modals

### LINKED ISSUE #10610: a11y: improve keyboard access on modals
# Problem

When I'm looking at a modal and tab through with a keyboard, it goes through everything behind the modal overlay first, making it a really frustrating user experience. 

# Proposed solution

When a modal is open and a user tabs through with their keyboard, have them navigate through the modal first, not what is behind the modal.

Video here: https://share.getcloudapp.com/6quPkxyr

### PR DESCRIPTION
**Pull request by aitchiss**
## What type of PR is this? (check all applicable)

- [X] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Updates the error and rate limit modals triggered in for comments so that they're keyboard accessible. I've also refactored slightly to add the 'showModal' code in `base.jsx` to the `window.Forem` name space, like the mention autocomplete methods.

## Related Tickets & Documents

Closes #10610

## QA Instructions, Screenshots, Recordings

**For both modals:**

- The close button should be immediately focused. Press `Enter` as soon as the modal appears and check that it closes the modal
- Focus should be returned to the 'Submit' button when the modal closes. Press `Enter` again to check that the modal re-opens as expected
- Focus should be trapped within the modal - press the Tab key a number of times and check that focus cycles between the 'Close' button and the 'Got it'/'OK' button
- The 'Got it' button should close the modal and again return focus to the submit button
- When the modal is open, pressing `Escape` should close it and return focus to the submit button
- Experiment a bit with different methods of closing using keyboard or mouse and check it continues to handle focus as per the above

**To trigger the rate limit modal:**

- Logged in as an admin user, go to Config > Rate limits and anti-spam and reduce the number of comments a user can make in 30 seconds (e.g. to 0). Save and confirm the changes
- Go to an article, and add multiple comments within 30 seconds (if you set it to 0 in the last step, the modal should trigger on comment 2)
- When you have exceeded the rate limit, the modal should appear

https://user-images.githubusercontent.com/20773163/116249786-0f96ab00-a765-11eb-8b1f-bbb0fbb43a7d.mp4

**To trigger the error modal:**

- There are lots of ways to do this, but the easiest I found was on a given article, add a comment
- Try to submit the exact same comment text again and an error modal should appear

https://user-images.githubusercontent.com/20773163/116251670-c8a9b500-a766-11eb-8537-8af6fd453a60.mp4

### UI accessibility concerns?

This change is an accessibility enhancement - without the focus trap, a keyboard user is not able to navigate/dismiss these modals

## Added tests?

- [X] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [X] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

wiggly eared dog

### CODE REVIEW

**Comment by ludwiczakpawel** [comment]
I don't think I have enough JS experience to review this one :P sorry!

**Comment by rhymes** [comment]
I manually tested on Firefox but I had some troubles, I was even able to trigger the upload image button while using the modal. When you see the cursor disappear, that's me trying to press the `Enter` button:


https://user-images.githubusercontent.com/146201/116435508-b8b7d100-a84b-11eb-85a1-0c15bcbd9eb2.mov

The second time I'm just using the keyboard and `Command-Enter` to post the article

**Comment by aitchiss** [comment]
> I manually tested on Firefox but I had some troubles, I was even able to trigger the upload image button while using the modal. When you see the cursor disappear, that's me trying to press the `Enter` button:
> 
>  Untitled.mov 
> The second time I'm just using the keyboard and `Command-Enter` to post the comment

oh wow this definitely not right! I'll take a look into it and try reproducing 👍

**Comment by aitchiss** [comment]
There was a problem with the element the focus trap was targeting if you were logged in as a "Trusted user" (which is why it was initially working for me locally) - updated this now 🙂  Sorry about that @rhymes - glad you spotted it!

**Review by rhymes — APPROVED** [review]
Tested both manually! 

Thanks for the fix @aitchiss!

**Review by citizen428 — APPROVED** [review]

**Pull request merged**
