### PR TITLE
Revert "Use the tag_list method, rather than the cached_tag_list attribute"

### PR DESCRIPTION
**Pull request by djuber**
Reverts forem/forem#15638

Non-critical - but the performance did decrease more than my limited local testing suggested it would.

https://ui.honeycomb.io/thepracticaldev/datasets/rails/result/5v8bxRJqoBy

Screenshot from 2021-12-03 16-55-09

Comparison with the day before versus after 15638 deployed:
Screenshot from 2021-12-03 17-00-07

This job (Follows::UpdatePointsWorker) is now taking between 0.5-2.0 seconds - we run it about 7000 times a day (averaging to about every 10 seconds), so it's not a *huge* problem, but it's a bigger regression in performance than we should accept uncritically

### CODE REVIEW

**Comment by citizen428** [comment]
This is what I was afraid of :-( Can we easily revert this or will this bring back a problem that the previous PR will revert? Also, is this performance regression something critical or can we live with it?

**Comment by djuber** [comment]
Ah - this is 
1) something we can live with (the performance regression is acceptable for how often the job runs
2) something we can safely revert - the issue may have been test only and resolved separately

**Review by citizen428 — APPROVED** [review]

**Comment by maestromac** [comment]
image
my gut feeling based on this 14 days heatmap is it's a tolerable performance loss. The performance loss is not very noticeable.

**Comment by jgaskins** [comment]
Agreed with @maestromac. There are a few outliers but they're acceptable. Also, those outliers started a full day after that PR was merged, with thousands of reactions created in that time.

**Pull request closed without merging**
