### PR TITLE
Upgrade to SimpleCov 0.20

### PR DESCRIPTION
**Pull request by rhymes**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

SimpleCov 0.20 has been released with support for the latest CodeClimate reporter.
Let's see if that works.

## Related Tickets & Documents

- https://github.com/codeclimate/test-reporter/issues/413#issuecomment-749505649
- https://github.com/codeclimate/test-reporter/issues/449

### CODE REVIEW

**Comment by rhymes** [comment]
Checked both the builds and CodeClimate and it seems to be all working well :)

**Review by maestromac — APPROVED** [review]
just a heads-up the coverage hasn't been working since we started using knapsack and the plan was to move onto something else but this is LGTM!

**Review by nickytonline — APPROVED** [review]
LGTM, just @maestromac's comment.

**Comment by rhymes** [comment]
@maestromac thanks for the update! We can say bye bye to CodeClimate in a separate time yeah

**Pull request merged**
