### PR TITLE
Add scroll back to the top to README

### PR DESCRIPTION
**Pull request by AswinBarath**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x ] Documentation Update

## Description
Added a "Scroll Back To Top" link at the end of the README.md file.
## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://docs.forem.com/frontend/accessibility)._

## Added tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## Added to documentation?

- [ ] [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/)
- [ ] README
- [ ] No documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by benhalpern** [comment]
Looks good to me! Can you go aheead and sign the CLA?

**Comment by AswinBarath** [comment]
> Looks good to me! Can you go ahead and sign the CLA?

@benhalpern I have signed the CLA

**Review by rhymes — APPROVED** [review]

**Comment by rhymes** [comment]
Thanks @AswinBarath

**Review by Ridhwana — APPROVED** [review]
Thanks @AswinBarath 🎉 Nice one!

**Comment by AswinBarath** [comment]
> Thanks @AswinBarath 🎉 Nice one!

You're welcome.
And I hope to even contribute to the code one day after going through the codebase carefully.
:)

**Comment by AswinBarath** [comment]
> Thanks @AswinBarath!

You're welcome.
And I hope to even contribute to the code one day after going through the codebase carefully.
:)

**Pull request merged**
