### PR TITLE
Tweet overflow

### PR DESCRIPTION
**Pull request by Hanaffi**
## What type of PR is this? (check all applicable)
- [X] Bug Fix

## Related Tickets & Documents
Closes https://github.com/forem/forem/issues/12519

### CODE REVIEW

**Review by rhymes — APPROVED** [review]
Hi @Hanaffi, welcome to the Forem project and thank you for this contribution :-) I tested it manually and it works well!

Would you mind signing the CLA [here above](https://github.com/forem/forem/pull/12682#issuecomment-778520874) ? This way we can merge the code in when the reviewers are done.

**Review by ludwiczakpawel — APPROVED** [review]

**Comment by aitchiss** [comment]
Hi @Hanaffi!

Just checking in with you to see if you have a chance to sign [the CLA in this comment above](https://github.com/forem/forem/pull/12682#issuecomment-778520874)? We'd love to get your changes merged into the codebase, and this is the final task needing ticked off ✅

Let me know if you have any questions about it!

**Comment by Hanaffi** [comment]
Hello @aitchiss  ,
I read it multiple times but I dont understand what is it and why do we need it.
If you can explain, I'd appreciate that :)

**Comment by aitchiss** [comment]
Hi @Hanaffi - yes of course!

The Contributor License Agreement (CLA) is a legal document in which you state that you are entitled to contribute your code to the Forem codebase, and are willing to have it used in distributions and derivative work. The CLA helps provide confidence to future users that they will be allowed to use the Forem codebase without fear that a contributor will try to withdraw permissions at a later date.

Essentially, it says that Forem/DEV has license to use and distribute your contribution without further restriction.

Does that help at all?

**Comment by Hanaffi** [comment]
@aitchiss Thanks for your help.
Can you explain what are these rights?
`c. Other Rights Reserved. Each party reserves all rights not expressly granted in this Agreement. `

**Comment by cmgorton** [comment]
Hey @Hanaffi this is common contract terminology especially around copyright. You can read more about Reservation of rights here.

**Comment by Hanaffi** [comment]
@cmgorton @aitchiss Sorry If I ask a lot but Its my first time to encounter such document.
Will it now or in the future give the maintainers the rights to sue me for ANY REASON?
Do I have the right to break/cancel it in the future?

**Comment by cmgorton** [comment]
@Hanaffi It's ok to ask questions! I am going to let @pkfrank weigh in on this. He helped set up a lot of the CLA docs.

**Comment by benhalpern** [comment]
Hi @Hanaffi, the contributor license agreement exists in order to give our project maximum flexibility to modify this code in the future. We basically want contributors to make it explicitly clear that we don't have to reach back out to you if we were to, say, create a specially licensed version of the codebase for any reason.

It has nothing to do with rights to sue or anything like that (like what Facebook had in their old licensing of React), it's a pretty basic agreement that ensures there's no grey area in our ability to keep distributing the code under the appropriate open source license, even if it needs to change slightly, nothing further.

Don't take this as legal advice, of course, but you have our word that there is no further purpose to the CLA. And if you're not comfortable, it's totally okay for you to close the PR and we will be happy to re-implement the change in some way ourselves.

**Comment by citizen428** [comment]
@Hanaffi Has the question been answered to your satisfaction? If yes, could you please sign the agreement now so that we can merge this PR? 😃

**Comment by Hanaffi** [comment]
@citizen428 @benhalpern 
Yes, If I can ask one last question. (Sorry, But I dont want to spend my life in New York jails XD)
I agree with a and b.
But What do you mean by : `c. Other Rights Reserved. Each party reserves all rights not expressly granted in this Agreement. No additional licenses or rights whatsoever (including, without limitation, any implied licenses) are granted by implication, exhaustion, estoppel or otherwise.` thats very vague.

Also, Can you change the agreement terms without needing me to sign the new one? 

Why dont you just merge? I promise I will never complain about changing my code.
Do whatever you want with my submissions.

**Comment by citizen428** [comment]
@Hanaffi Let me sum it up as easily as I'm able to, with the caveat of not being a lawyer: the agreement is in place so we have full ownership of the code, despite developing it as FOSS. Without each contributor signing this agreement, that wouldn't be the case, as you would retain the rights to your own code. Unfortunately, promises aren't legally binding, so unless contributors sign the CLA we won't be able to merge their code in order to protect _ourselves_/the company. 

Many bigger/commercial FOSS projects have similar CLAs, see e.g. [this list](https://en.wikipedia.org/wiki/Contributor_License_Agreement#Users) from Wikipedia. 

No worries if you are still worried about signing it, we'll close this PR, and a team member will re-implement this fix.

**Comment by cmgorton** [comment]
@Hanaffi if you are uncomfortable signing the agreement (perfectly ok!) let us know. We have another contributor (@omkz ) who would like to work on this issue. Thanks again for your time and thoughtful questions here.

**Comment by Hanaffi** [comment]
@cmgorton Sorry, I dont feel comfortable for signing at the moment!
I want to thank you for being very patient and I hope that won't affect my future contribution to your porject!
Best wishes

**Comment by cmgorton** [comment]
> @cmgorton Sorry, I dont feel comfortable for signing at the moment!
> I want to thank you for being very patient and I hope that won't affect my future contribution to your porject!
> Best wishes

No problem @Hanaffi . We will go a head and close this PR and if in the future you feel more comfortable sighing the CLA we look forward to any other contributions. Thanks again for taking the time to talk through the CLA and ask questions.

**Pull request closed without merging**
