### PR TITLE
Update .env_sample

### PR DESCRIPTION
**Pull request by thekilluadev**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
fixes the error described in #11777 
## Related Tickets & Documents
#11777 
## QA Instructions, Screenshots, Recordings

image
first line is before and second line is after

## Added tests?

- [ ] Yes
- [x] No, and this is why: not needed.
- [ ] I need help with writing tests

## Added to documentation?

- [ ] [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/)
- [ ] README
- [x] No documentation needed

### CODE REVIEW

**Comment by rhymes** [comment]
Hi @ty-schnoor, I don't think this is the solution, `export` is needed because `.env_sample` has to be copied to `.env` and customized. See the installation guide https://docs.forem.com/installation/containers/#setting-up-forem

**Comment by ty-schnoor** [comment]
> Hi @ty-schnoor, I don't think this is the solution, `export` is needed because `.env_sample` has to be copied to `.env` and customized. See the installation guide https://docs.forem.com/installation/containers/#setting-up-forem

i'm confused, do you not create `.env` manually?

**Comment by rhymes** [comment]
Yes, by copying `.env_sample` to `.env`, this is what we mention in the [setup installation guide](https://docs.forem.com/installation/containers/#setting-up-forem)

```
Create .env by copying from the provided template.env_sample (i.e. with bash: cp .env_sample .env).
```

**Comment by citizen428** [comment]
@rhymes Tbh, I always was confused by this too, generally `.env` files don't contain `export` statements, unless you *also* want to source them from a shell.  As per `dotenv`'s documentation:

> You may also add `export` in front of each line so you can `source `the file in bash:

**Comment by rhymes** [comment]
@citizen428 maybe we can have this double checked from systems, I understand your point, I don't know if that was added on purpose or not

**Comment by citizen428** [comment]
@rhymes I'm checking with systems.

**Comment by nafaabout** [comment]
This is confusing, especially for a newcomer. I think the default should be the format without the `export`. This is because the purpose of copying the `.evn_sample` to `.env` is to run the `bin/container-setup` script or to load them with `dotenv` not to source them in a terminal.
Or, at least make it clear in the documentation that `export` statements are only needed if the file is sourced to a terminal and they need to be removed for `bin/container` to work properly.

**Comment by citizen428** [comment]
Looping in @jdoss

**Comment by jdoss** [comment]
I am unclear on what steps people are using to reproduce this problem. From the screenshot 

> image
> first line is before and second line is after

the command being run is `docker-compose run bin/contIner-setup` which is incorrect. The right command is just `bin/container-setup`. What are people running that produces this problem that this PR is trying to solve and what happens if people just run the right command?

**Comment by nafaabout** [comment]
> I am unclear on what steps people are using to reproduce this problem. From the screenshot
> 
> > image
> > first line is before and second line is after
> 
> the command being run is `docker-compose run bin/continer-setup` which is incorrect. The right command is just `bin/container-setup`. What are people running that produces this problem that this PR is trying to solve and what happens if people just run the right command?

I run the `bin/continer-setup` command. What I get is that `Error: in ./.env file ...` message. This is because `docker-compose` expects the `.env` file to be formatted as `VARIABLE=value`  not `export VARIABLE=value`. The latter is a valid format for sourcing the file directly into a `terminal` or for using it with `dotenv` gem. It's not valid for `docker-compose` which is run by `bin/container-setup` script.
The docs say `copy .env_sample to .env` then run `bin/container-setup`. It doesn't say anything about the `export` statements which are invalid for `docker-compose`. A developer who doesn't have good experience with `docker-compose` could get confused.

**Comment by msarit** [comment]
Hello @thekilluadev! 👋🏾 

Drawing your attention to this PR; still working on it? Looks like you got some feedback to address.

Let us know if you need help or have any questions. 🙏🏾

**Comment by jdoss** [comment]
I believe the dotenv gem got removed some time ago and this was never updated as it should have been. @thekilluadev can you fix the conflicts on your PR and we can get this merged.

**Comment by nickytonline** [comment]
Hi @thekilluadev, just following up on this. When you have a chance can you fix the merge conflicts? Thanks!

**Comment by citizen428** [comment]
> I believe the dotenv gem got removed some time ago

@jdoss `dotenv-rails` is still in current `master` for the `development` and `test` groups.

**Comment by jdoss** [comment]
Oh, I thought it got removed. Regardless, I don't use this for anything in systems and if it is causing issues with docker-compose, then we should change it.

**Comment by aitchiss** [comment]
Hi @thekilluadev 👋  Just checking in to see if you're still working on this and will be able to resolve the conflicts in `.env_sample`? If you no longer have time, or you need some help - please just let me know!

**Comment by citizen428** [comment]
Thanks for your work on this @thekilluadev! I resolved the conflicts now and removed some `export`s that had snuck back in,

**Review by citizen428 — APPROVED** [review]

**Review by rhymes — APPROVED** [review]
LGTM!

Thanks @thekilluadev!

**Pull request merged**
