### PR TITLE
fix: Update Twitter logo

### LINKED ISSUE #20356: Update name and logos from Twitter to X
**Describe the issue**

We've not yet updated the logos and copy across DEV to take into account Twitter's rebrand to X.

**Expected**

We should do an audit for all of the places that we mention Twitter in our app and all of the places that we include the bird logo, so we can appropriately update these.

**Screenshots**

Here are a few examples of places to consider:

Screen Shot 2023-11-14 at 5 02 58 PM

Screen Shot 2023-11-14 at 5 03 12 PM

Screen Shot 2023-11-14 at 5 03 25 PM

**Additional context**

Thanks to @fabriziobagala who called this out to me recently!

### PR DESCRIPTION
**Pull request by CBID2**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
This PR updates the name and logo of Twitter to X. **Note:** This is still a work-in-progress. Here's what I have done so far:

- [x] Find an SVG file of X's logo. Result: https://fontawesome.com/icons/x-twitter?f=brands&s=solid

### Next plan of action
- [ ] Adjust the measurements of the logo.
- [ ] Replace the button's text with "X". 

## Related Tickets & Documents
Closes #20356

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [axe DevTools](https://www.deque.com/axe/) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

_For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [x] I need help with writing tests

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by dambar08** [comment]
Do we need to need to keep twitter-icon.svg as the filename?

**Comment by CBID2** [comment]
> Do we need to need to keep twitter-icon.svg as the filename?

Hi @dambar08. I think using the current name would be best.

**Comment by dambar08** [comment]
Did you change the name?

**Comment by CBID2** [comment]
> Did you change the name?

Hi @dambar08. Sorry for the delay. I changed the file's name, but I just can't find the file where the Twitter icon is placed.

**Comment by Anmol-Baranwal** [comment]
@CBID2 
You can find it here :)
https://github.com/forem/forem/blob/main/app/assets/images/twitter-icon.svg

**Comment by CBID2** [comment]
> @CBID2 You can find it here :) https://github.com/forem/forem/blob/main/app/assets/images/twitter-icon.svg

To clarify @Anmol-Baranwal, I mean I can’t find the file that contains the code for the Log in section 
login

**Comment by fabriziobagala** [comment]
Hi @CBID2. Do you have any idea when you will finish this fix?

**Comment by CBID2** [comment]
> Hi @CBID2. Do you have any idea when you will finish this fix?

Soon @fabriziobagala

**Comment by CBID2** [comment]
> Hi @CBID2. Do you have any idea when you will finish this fix?

Hi @fabriziobagala. Can you show where the code for the sign-in form is located? I'm having trouble finding it.

**Comment by fabriziobagala** [comment]
> Hi @fabriziobagala. Can you show where the code for the sign-in form is located? I'm having trouble finding it.

@CBID2 unfortunately I do not know Ruby on Rails, however I found these files that I hope can help you:

- https://github.com/forem/forem/blob/main/app/services/authentication/providers/twitter.rb
- https://github.com/forem/forem/blob/main/app/views/shared/authentication/_providers_registration_form.html.erb

**Pull request closed without merging**
