### PR TITLE
Update ruby version to 3.0.6, latest in the 3.0 series.

### PR DESCRIPTION
**Pull request by heliocola**
## What type of PR is this? (check all applicable)

- [x] Update ruby to latest version of the 3.0 series

## Description
In preparation to try out Ruby 3.1.2 with YJIT, this PR udpate to latest version of the Ruby 3.0 series.
The main goal of this PR is to update to the latest 3.0 series and create an issue to discuss an strategy and benchmark for Ruby 3.1.2 with and without YJIT.

## Related Tickets & Documents
None

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings
No extra QA would be necessary, but let CI run would be ideal.

### UI accessibility concerns?
None

## Added/updated tests?
- [x] No, and this is why: no extra tests needed.

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by heliocola** [comment]
Hi there Forem team.
One of the CI failures is about `quay.io` not having Ruby 3.0.6.
Here is the summary from the build logs:
```
Dockerfile:1
--------------------
   1 | >>> FROM quay.io/forem/ruby:3.0.6 as base
   2 |     
   3 |     FROM base as builder
--------------------
ERROR: failed to solve: quay.io/forem/ruby:3.0.6: quay.io/forem/ruby:3.0.6: not found
Error: buildx failed with: ERROR: failed to solve: quay.io/forem/ruby:3.0.6: quay.io/forem/ruby:3.0.6: not found
```

I've taken the approach to update all places where I've found `3.0.2`, but please let me know if I should take a different strategy.

The other CI failures, for step `CI/CD / rspec (8, *)`, are all about knaosackpro and looks like `API disabled for forks`.
But there are some deprecation warnings for Rails 7.1 as well.

Here is the details from the build logs:
```
W, [2023-05-23T01:58:27.834580 #2487]  WARN -- : [knapsack_pro] POST https://api-disabled-for-fork.knapsackpro.com/v1/build_distributions/subset
W, [2023-05-23T01:58:27.834640 #2487]  WARN -- : [knapsack_pro] Request failed due to:
W, [2023-05-23T01:58:27.834677 #2487]  WARN -- : [knapsack_pro] #<SocketError: Failed to open TCP connection to api-disabled-for-fork.knapsackpro.com:443 (getaddrinfo: Name or service not known)>
```
Deprecation warnings:
```
DEPRECATION WARNING: minimal_admin? is deprecated and will be removed from Rails 7.1 (Deprecating ApplicationPolicy#minimal_admin?, use ApplicationPolicy#user_any_admin?) (called from block (3 levels) in <top (required)> at /home/runner/work/forem/forem/spec/policies/html_variant_policy_spec.rb:17)
```

IMO: It doesn't look like these failures are related to the chagnes in the PR.

**Comment by maestromac** [comment]
@heliocola thank you for your contribution. This is what I found
- I ran the test locally and there's a legitimate failure that 3.0.6 found.
- Our knapsack integration seemed to have clobbered up the rspec output. I will fix this.
- We will address the Quay.io issue.

**Comment by heliocola** [comment]
@maestromac : thank you for digging into it and find this broken spec.
I was able to replicate on my machine.
It does work on ruby 3.0.2 and it doesn't on 3.0.6!

I will spend some time digging into it.

**Comment by heliocola** [comment]
@maestromac : after some digging, I've found the settings that is breaking the test case.

There are basically 2 issues that needs to be addressed:
### 1. New versions of ruby needs CGI gem 0.3.6 to allow cookies domains starting with `.`: 
Ref: https://github.com/ruby/cgi/pull/29

The app is using cookies like this in all environments:
* Production: https://github.com/forem/forem/blob/main/app/lib/middlewares/set_cookie_domain.rb#L10
* Test: is `.localhost:3000` coming from .env.test APP_DOMAIN variable

So, just adding the line to the Gemfile and the cookie domain can stay the way it is.
> gem 'cgi', '~> 0.3.6' # Support for the Common Gateway Interface protocol.

### 2. If you use the new CGI gem, you can't have the cookie with `:3000` in it.
From ruby/CGI gem:
Cookies domain validation regexp: https://github.com/ruby/cgi/blob/master/lib/cgi/cookie.rb#L45
Method where exception is raised: https://github.com/ruby/cgi/blob/master/lib/cgi/cookie.rb#L126-L131

If you look at the regexp in the CGI gem: `DOMAIN_VALUE_RE = %r"\A\.?(?<label>(?!-)[-A-Za-z0-9]+(?<!-))(?:\.\g<label>)*\z"`, It allows `.localhost`, but it doesn't allow `.localhost:3000`.

### Changes to have the test passing
I was able to get the test running successfully with the following changes:
1. Add ruby/CGI 0.3.6 to the gem file: `gem 'cgi', '~> 0.3.6'`
2. Change APP_DOMAIN in .env.test (sym link to .env.sample) to `forem.test`.

I've noticed that APP_DOMAIN can also come from the DB table `site_configs`, so for the test environment we can seed some data, instead of changing .env file.

I will change this PR back to DRAFT and do some testing.

Let me know your thoughts or any preference of the direction to go.

**Comment by gareth** [comment]
Just posting here because I saw a link to this PR on https://github.com/ruby/cgi/pull/29 after you referenced it.

> New versions of ruby needs CGI gem 0.3.6 to allow cookies domains starting with .:

Cookie domains should **not** start with a `.` any more. The leading dot was originally _required_ in cookies based on [RFC 2965][rfc2965] (October 2000), but [RFC 6265][rfc6265] (April 2011) changed that behaviour, making a leading dot strictly _incorrect_. Since then, sending cookies to subdomains is the *default* behaviour. (Todays browsers aim to conform to RFC 6265 with respect to cookies)

The CGI PR you linked to was created so that headers generated by legacy servers could still be parsed by the gem, but this just to allow "error handling", it's not saying that the leading dot is correct.

I wrote more about this in https://github.com/rails/rails/pull/48036 where I wrote a patch to fix a similar leading dot behaviour in Rails.

[rfc2965]: https://www.rfc-editor.org/rfc/rfc2965#section-3.2
[rfc6265]: https://www.rfc-editor.org/rfc/rfc6265#section-4.1.1

**Comment by heliocola** [comment]
@gareth : thank you for looking into it. Great finding that this was being added by Rails and rejected by new versions of Ruby and CGI gem.
That appears to be a different problem that this PR helped uncover.

I reviewed the failed specs and I could not find any issue.
I will close this PR and open a fresh one (somehow I can't replicate the issue that required changing `APP_DOMAIN` to remove `:3000`).

Only cgi gem is still needed.

The guiding question for the new PR is: do you want to wait for a release of Rails removing the leading dot? Or can we add cgi gem and update Ruby to 3.0.6?

**Comment by heliocola** [comment]
Closing this PR in favor of #19603

**Comment by heliocola** [comment]
@gareth : thanks again for your comment about the leading dot, the RFC references, and the PR in Rails to change the default behavior.
Despite the change in behavior in the RFCs and Rails, Forem repo does add leading dot to the cookie.

I've opened a discussion to document (and request the changes), instead of a bug report, as it seems more appropriate: https://github.com/forem/forem/discussions/19604

I also want to separate that discussion from the ruby 3.0.6 upgrade.

**Pull request closed without merging**
