### PR TITLE
fix dropdown-menu not closing when click outside or click on a item on mobile

### LINKED ISSUE #12466: Profile navigation menu doesn't close on selection and focused link flickers
**Describe the bug**

The bug is particularly noticeable on mobile - I've added a recording below of the experience on Android.

When you click your profile image, a dropdown menu opens with navigation options. When you tap to make a selection, the new page loads and there is a very brief flicker where "Sign out" appears to be selected, then your original selection, then "Sign out" again. The menu doesn't close until the user taps their profile image again, which on mobile means a large portion of the screen is obscured. Tapping outside of the menu on mobile does not close the menu (but it does on desktop).

**To Reproduce**

- Open a forem instance on a mobile device
- Click the avatar in the top right
- Select 'Dashboard' from the dropdown
- Observe the flickering link focus and the menu still being visible
- Try to click away from the menu and note it doesn't dismiss

**Expected behavior**

I'm open to suggestions on the UX here but I would suggest either:

- When you make a selection from the menu, the dropdown closes (in terms of focus management, sending focus back to the avatar button that opened the menu)

or

- The menu stays open, but there's no strange flicker of focus on the "Sign out" link, and tapping outside of the menu on mobile closes the dropdown

**Screenshots**

gif showing the reproduce steps and bug described above

**Desktop (please complete the following information):**

N/A - on desktop the dropdown stays open but there's no strange flicker of focus and clicking outside of the dropdown closes it.

**Smartphone (please complete the following information):**

Observed on:

- Device: Pixel 5
- OS, version: Android 11
- Browser, version: Chrome 88

NB: I've observed the same behaviour both in the PWA and in Chrome browser

**Additional context**

I think this was introduced in #11509 - Header navigation dropdown accessibility

### PR DESCRIPTION
**Pull request by tuliocll**
## What type of PR is this? (check all applicable)

- [x] Bug Fix

## Description
On the dev.to (mobile or application) when we click on menu its dont close if we click outisde(like on desktop one) or on a menu link.

## Related Tickets & Documents

Closes  #12466

## QA Instructions, Screenshots, Recordings

- Pull down this branch and start up the rails server
- Login and open the dropdown menu on mobile view (maybe need a refresh after resize the window).

## Added tests?

- [x] No, and this is why: _please replace this line with details on why tests
      have not been included_

## Added to documentation?

- [x] No documentation needed

## [optional] Are there any post deployment tasks we need to perform?
no
## [optional] What gif best describes this PR or how it makes you feel?

Awesome!

### CODE REVIEW

**Review by katiedavis — APPROVED** [review]
Hey @tuliocll I tested this out and it's great. Way to take advantage of blurHeaderMenu. We'll just need you to sign the CLA!

**Review by aitchiss — APPROVED** [review]
LGTM! Thanks for this contribution - it makes the mobile experience so much better! 

Just a quick note that I'll amend the PR description very slightly - just because it actually closes #12466 and not #12067 🙂

Thanks again - don't forget to sign the CLA!

**Comment by nickytonline** [comment]
The Code Climate issue can be ignored.

**Comment by tuliocll** [comment]
hello guys, i just signed the CLA!

**Comment by cmgorton** [comment]
Thank you for this fix @tuliocll !

**Comment by tuliocll** [comment]
you are welcome! I loved making this contribution, I can't wait for the next one 😍

**Comment by aitchiss** [comment]
@tuliocll Just a heads up that we had to revert your commit for the time being - we totally missed this in review but on some iOS devices, the added event listener is firing immediately on opening the menu, causing it to close immediately.

These things happen - we've reopened the original issue and will iterate on your solution (which is working for android perfectly!). Thanks again for the contribution 🙂

**Comment by tuliocll** [comment]
> @tuliocll Just a heads up that we had to revert your commit for the time being - we totally missed this in review but on some iOS devices, the added event listener is firing immediately on opening the menu, causing it to close immediately.
> 
> These things happen - we've reopened the original issue and will iterate on your solution (which is working for android perfectly!). Thanks again for the contribution

sorry about it 😞 
i did some tests now with epiphany (web kit based browser for linux, i dont have ios) and a lot of user agents (safari 10, 11, 12, 13 and 14) but i cant reproduce the bug. do you know the ios version ? maybe i can fix it

**Comment by aitchiss** [comment]
> sorry about it 😞
i did some tests now with epiphany (web kit based browser for linux, i dont have ios) and a lot of user agents (safari 10, 11, 12, 13 and 14) but i cant reproduce the bug. do you know the ios version ? maybe i can fix it

Don't worry about it @tuliocll ! I think it is one of these things we can only trigger with the real device (difference between clicking vs tapping) - I totally missed it too as I'm also an android user 🙂  One of the Forem team is going to pick up where you left off and make sure any workaround is added for the iOS issue.

**Pull request merged**
