### PR TITLE
Adding admin link for admins

### PR DESCRIPTION
**Pull request by ludwiczakpawel**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This PR will add a link to admin section if user is an admin...

## Related Tickets & Documents

- Closes https://github.com/forem/InternalProjectPlanning/issues/173

## QA Instructions, Screenshots, Recordings

image

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Review by Zhao-Andy — APPROVED** [review]
I'm forgetting if `current_user` is able to be used here because of caching but _I think_ it should be okay since there's an `if user_signed_in?` above... cc @benhalpern

**Comment by ludwiczakpawel** [comment]
Additional context from @atsmith813 https://github.com/forem/InternalProjectPlanning/issues/173#issuecomment-712192200

**Comment by atsmith813** [comment]
This won't work as expected in production due to caching and service workers.

At this time, we can't modify the server-side views of the content cached by service workers to be user-specific. It's currently set up so that there's a "signed in" version and a "signed out" version. We can't introduce a user-specific specific version (i.e. users with role of admin) without changing a lot more.

An example of this is the profile image/avatar in the nav bar - a user-specific element. That is actually populated by some [async JS](https://github.com/forem/forem/blob/3ccecfbbb7fe2524f0c450274dbef9560d21d033/app/assets/javascripts/initializers/initializeBaseUserData.js#L112-L118). We can't render that server-side.

I suspect a "quick win" may be to do some similar JS to update this dropdown with an async script. I'm not sure where we could tell the client-side that the user is, in fact, an admin 🤔 . My knee-jerk reaction would be to add the info [to the  `user_data` used by many components on the front-end](https://github.com/forem/forem/blob/4e1e5a45624f9a9ade75f08b8605aa54ebf0a58d/app/controllers/async_info_controller.rb#L47-L72), but I'm hesitant to do that with roles/admin because that's sort of sensitive data.

**Review by benhalpern — CHANGES_REQUESTED** [review]
This will actually need to be inserted dynamically because we may cache this page....

Probably makes sense in the `setCurrentUserToNavBar` function....

Will need to add `admin: @user.any_admin?` to `/async_info/base_data` in order to fetch this information.

Let me know if you need more help with any of that.

**Comment by ludwiczakpawel** [comment]
Ok, I pushed an update. @benhalpern would you mind taking a look, I'm not sure if I'm approaching this correctly (this kind of work is pretty new for me).

**Review by benhalpern — APPROVED** [review]
Looks great to me

**Pull request merged**
