### PR TITLE
Fix onboarding_update persistence bug

### PR DESCRIPTION
**Pull request by benhalpern**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

We have have an issue where the fields set in `/onboarding_update` are not being preserved. We have had a hard time replicating this _locally_, but it is easy to see in prod. It seems to be affecting Forems of all sizes, so is not likely a scale problem.

When we update these same fields in `/settings`, which calls the `users#update` path, everything works fine. Since we're basically doing the same function in both places, I altered the code in `/onboarding_update` to similar to how it already works in `users#update`, which is the more "standard" way.

## Related Tickets & Documents

https://github.com/forem/forem/issues/12138

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added tests?

- [x] Yes: Adjusted test
 
## Added to documentation?

- [x] [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/)
- [ ] README
- [ ] No documentation needed

### CODE REVIEW

**Review by rhymes — APPROVED** [review]

**Review by Ridhwana — APPROVED** [review]

**Review by Ridhwana — APPROVED** [review]
Needs some test updates but I tested this locally and it seems to behave well.

**Review by mstruve — COMMENTED** [review]
I am really hesitant to change anything when we dont know what is happening. While the intention is good I think we could introduce other problems possibly which could make the debugging we have already done obsolete.

**Review by mstruve — CHANGES_REQUESTED** [review]
This wont fix it, it is rate limit issue

**Comment by mstruve** [comment]
Closing since this was solved with #12281

**Pull request closed without merging**
