### PR TITLE
Removed ambiguity when multiple profile fields and groups exist in test

### PR DESCRIPTION
**Pull request by fdoxyz**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

<details><summary>Flaky spec log</summary>
<p>

```ruby
Failures:
1551
1552
  1) Admin manages profile fields adds a profile field
1553
     Failure/Error: click_on "Add Field"
1554
1555
     Capybara::Ambiguous:
1556
       Ambiguous match, found 4 elements matching visible link or button "Add Field"
1557
1558
1559
1560
     # ./spec/system/admin/admin_manages_profile_fields_spec.rb:26:in `block (2 levels) in <top (required)>'
1561
     # ./spec/rails_helper.rb:135:in `block (3 levels) in <top (required)>'
1562
     # ./spec/rails_helper.rb:135:in `block (2 levels) in <top (required)>'
1563
1564
  2) Admin manages profile fields deletes a profile_field_group
1565
     Failure/Error: click_button "Delete Group"
1566
1567
     Capybara::Ambiguous:
1568
       Ambiguous match, found 4 elements matching visible button "Delete Group" that is not disabled
1569
1570
1571
1572
     # ./spec/system/admin/admin_manages_profile_fields_spec.rb:33:in `block (2 levels) in <top (required)>'
1573
     # ./spec/rails_helper.rb:135:in `block (3 levels) in <top (required)>'
1574
     # ./spec/rails_helper.rb:135:in `block (2 levels) in <top (required)>'
1575
1576
Finished in 8 minutes 32 seconds
1529
2309 examples, 2 failures, 2 pending
```

</p>
</details>

## Added tests?

- [ ] Yes
- [x] No, and this is why: It's a fix of an existing spec
- [ ] I need help with writing tests

## Added to documentation?

- [ ] [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/)
- [ ] README
- [x] No documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

i will try to fix you

### CODE REVIEW

**Comment by fdoxyz** [comment]
I'm not sure if this was a one-off flaky spec though... If it doesn't come up again I think we can just close this without merging

**Review by maestromac — APPROVED** [review]
LGTM!

**Review by benhalpern — APPROVED** [review]
LGTM but looks like there's now a conflict that needs to be resolved.

**Comment by fdoxyz** [comment]
> LGTM but looks like there's now a conflict that needs to be resolved.

I see the `within` clause should fix the ambiguity here, merged on another PR. I don't think this will be necessary anymore

**Pull request closed without merging**
