### PR TITLE
Fix database schema

### PR DESCRIPTION
**Pull request by AlbertoPdRF**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix (not quite though)
- [ ] Optimization
- [ ] Documentation Update

## Description

Whenever I run `bin/setup`, I get the committed diff. After investigating for a bit, I think this line was mistakenly commited [here](https://github.com/forem/forem/pull/9294/files#diff-1acd2e7e27a227829d5d14a91c863bb6R495), although I could just be missing something!

## Related Tickets & Documents

None.

## QA Instructions, Screenshots, Recordings

None.

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] Are there any post deployment tasks we need to perform?

None.

## [optional] What gif best describes this PR or how it makes you feel?

Detective GIF

### CODE REVIEW

**Comment by mstruve** [comment]
The link you are referencing is for a commit in a PR, the actual PR diff does not have that line added. If you go on master and reset your database it should match the schema. Let me know if it doesnt.

**Comment by AlbertoPdRF** [comment]
Hmmm, I do see that line being added on [the actual PR diff](https://github.com/forem/forem/pull/9294/files). And I get the diff I committed after doing:

```bash
git checkout master
git fetch upstream # this is a remote pointing to forem/forem
git reset --hard upstream/master
bin/setup
```

Is that what you meant to by resetting my database?

**Comment by rhymes** [comment]
@AlbertoPdRF no, to reset your DB you should run `bundle exec rails db:reset` and then `bin/setup` and you start from scratch

**Comment by maestromac** [comment]
@rhymes I did all the resetting and I too am seeing this diff 😕

**Comment by citizen428** [comment]
Hi @AlbertoPdRF, thanks for the PR, but as indicated by the comments this is something that should be resolved in your environment, not via a PR, so I'll close this now.

**Pull request closed without merging**
