### PR TITLE
Feature:Rake Task to Return Health Check Token

### PR DESCRIPTION
**Pull request by mstruve**
## What type of PR is this? (check all applicable)
- [x] Feature

## Description
Return health check token for @jdoss to use for Forem things.

### CODE REVIEW

**Comment by jdoss** [comment]
MRW @mstruve makes me new toys...

**Comment by mstruve** [comment]
@jdoss was also thinking, I could write this value to a file as well using this rake task if that would be easier to ingest for you. let me know :)

**Comment by jdoss** [comment]
> @jdoss was also thinking, I could write this value to a file as well using this rake task if that would be easier to ingest for you. let me know :)

Kicking it out to stdout is perfect for now. If I need to write it to a file I can on my end easily.

**Review by jdoss — APPROVED** [review]

**Review by jacobherrington — APPROVED** [review]
:+1:

**Pull request merged**
