### PR TITLE
Creator Settings: Removed SVG files as an option for logo upload

### PR DESCRIPTION
**Pull request by nickytonline**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This removes the option to upload an SVG file for a logo. The main reason is it's an XSS attack vector potentially.

## QA Instructions, Screenshots, Recordings

1. Ensure you're logged out from the Forem instance.
2. Set up the database to be in a state where you are about to create the Forem creator role

```ruby
# Enable the feature flag
FeatureFlag.enable(:creator_onboarding)

# Delete all users 
User.destroy_all

# Set `waiting_on_first_user` to be true
Settings::General.waiting_on_first_user = true

# If you've logged in before set the mascot id to nil
Settings::General.mascot_user_id = nil

# If you've logged in before set the logo SVG to nil
Settings::General.logo_svg = nil
```

3. Click on the login link. Since the feature flag is enabled, you'll be redirected to Creator Signup Form.
4. Fill in the necessary information and submit the form.
5. On the next page select an image for the logo.
    - Note that you should only be able to select a jpeg or png file. This PR removes the ability to upload an SVG, so try adding one.
6. Ensure both the Terms and Conditions and Code of Conduct checkboxes are checked off and submit the form.
7. Notice that the logo loads in the header.
8. You can redo this process with multiple image types.

### UI accessibility concerns?

N/A

## Added/updated tests?

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [x] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

n'sync singing Bye Bye Bye

### CODE REVIEW

**Comment by citizen428** [comment]
What about existing Forems with SVG logos, will be prompt them to move to something else?

**Review by citizen428 — APPROVED** [review]

**Review by Ridhwana — CHANGES_REQUESTED** [review]
@nickytonline we need to remove this in a couple of other places too: 

1. In the [description on the frontend](https://github.com/forem/forem/blob/main/app/views/admin/creator_settings/_form.html.erb#L14): 

    `<p id="logo-subtitle" class="crayons-field__description">Ideally SVG, but PNG or 
     JPEG will work, too.</p>`

    Maybe we can change it to: 
   `You may upload only upload a PNG, JPG or JPEG image`

2. We should remove the [`:not_svg` method ](https://github.com/forem/forem/blob/main/app/uploaders/logo_uploader.rb#L47-L49 )and the [unless statement calling this method](https://github.com/forem/forem/blob/8ff6fe0d237f0dcb6827b1c22b735c9aae4262ef/app/uploaders/logo_uploader.rb#L34) since we don't allow the upload of SVG's any longer, we no longer need to have this check in place in order to resize an image. 


3. We can also change [this statement `::Settings::General.resized_logo = logo_uploader.resized_logo.url || logo_uploader.url` ](https://github.com/forem/forem/blob/main/app/controllers/admin/creator_settings_controller.rb#L23-L24) to `::Settings::General.resized_logo = logo_uploader.resized_logo.url` because when we remove SVG uploads we will always be serving a resized image back to the browser.

**Comment by nickytonline** [comment]
> 1. You may upload only upload a PNG, JPG or JPEG image

@Ridhwana, I was thinking of something more terse. `PNG or JPEG image`. We don't need to worry about the JPEG extensions as we support the content type for JPEG too.

**Comment by Ridhwana** [comment]
> > 1. You may upload only upload a PNG, JPG or JPEG image
> 
> 
> 
> @Ridhwana, I was thinking of something more terse. `PNG or JPEG image`. We don't need to worry about the JPEG extensions as we support the content type for JPEG too.

I don't have a strong opinion on it. I thought most of our descriptions follow more of a sentence description that's why I suggested it :) but feel free to use your best judgement - if product thinks we should change it they'll let us know.

**Review by juliannatetreault — APPROVED** [review]
✂️ ✂️ ✂️

**Comment by nickytonline** [comment]
> > > 1. You may upload only upload a PNG, JPG or JPEG image
> > 
> > 
> > @Ridhwana, I was thinking of something more terse. `PNG or JPEG image`. We don't need to worry about the JPEG extensions as we support the content type for JPEG too.
> 
> I don't have a strong opinion on it. I thought most of our descriptions follow more of a sentence description that's why I suggested it :) but feel free to use your best judgement - if product thinks we should change it they'll let us know.

Actually, I'm looking at the other fields, so will probably go with a sentence to keep it consistent.

**Comment by nickytonline** [comment]
> What about existing Forems with SVG logos, will be prompt them to move to something else?

This feature is currently behind a feature flag. Having said that, we will need to communicate to Forem creators that we are removing the ability to have an SVG as a logo, including DEV and the CodeNewbie community. cc: @JennieOcken @emmmmmmmmmmmma

**Review by Ridhwana — APPROVED** [review]

**Review by Ridhwana — APPROVED** [review]

**Pull request merged**
