### PR TITLE
Add forem_owner_secret to params

### PR DESCRIPTION
**Pull request by atsmith813**
## What type of PR is this? (check all applicable)
- [x] Refactor
- [x] Feature

## Description
This PR adds functionality for creators configuring a new Forem instance to read the `forem_owner_secret` from the querystring parameters if provided.

This will be used soon. We'll be emailing creators a URL to their new Forem that includes the `forem_owner_secret` param so that they don't have to type it in. That will be something along the lines of:

```
Hey, Alex! Your new Forem is ready. Please click this link https://localhost:3000?forem_owner_secret=test to configure your new Forem.
```

## Related Tickets & Documents
N/A

## QA Instructions, Screenshots, Recordings
The original functionality still works if `?forem_owner_secret` is not present in the URL:
no_param

If the param is found, the form field is rendered as a hidden field with the value updated from the parameter automatically - rendering one less field that's required to be completed 🎉 .
with_param

1. Set your local app into "starter mode" by setting `ENV["MODE"] = "STARTER"` in your environment.
2. Set your `ENV["FOREM_OWNER_SECRET"]` to any value (i.e. `"test"`).
2. Reset your DB (`rails db:reset`) - **warning** this will erase your local data.
3. Fire up the app locally (`rails s`).
4. Visit the home page [localhost:3000](http://localhost:3000) - you should see the form as usual that includes a field to enter the secret token.
5. Visit the home page with the querystring param matching the value you set from step 2 - [localhost:3000?forem_owner_secret=test](http://localhost:3000?forem_owner_secret=test). You should no longer see the form field to enter a Forem secret token.
6. Open up your browser's inspector - you should be able to find the hidden form field containing the value of the token.
7. Submit the form 🎉 .

## Added tests?
- [x] yes

## Added to documentation?
- [x] no documentation needed

jimmy_fallon_ive_got_a_secret_gif

### CODE REVIEW

**Review by benhalpern — CHANGES_REQUESTED** [review]
Looks good to me.....

One small change.... Let's add this to the vcl safe params list. Even though it isn't needed here, at some point we could adopt something like that for Forem Cloud and may find ourselves copying from that folder to come up with the list, and we'd want this there.

**Comment by atsmith813** [comment]
@benhalpern great call - updated!

**Review by benhalpern — APPROVED** [review]
🥳

**Review by maestromac — APPROVED** [review]
> Name:
> Columbus, OH 
🤔 

LGTM!

**Comment by atsmith813** [comment]
@maestromac my auto-fill on localhost:3000 is super broken 😅 🙈

**Pull request merged**
