### PR TITLE
Save valid attributes with ignoring the invalid ones

### LINKED ISSUE #12284: All Profile Updates are Lost When 1 Field is Invalid
**Describe the bug**

When you go to update your profile you can fill in multiple fields at a time. If you fill in many of those fields and then submit form, if 1 field is invalid you will receive an error message and none of the fields will have been saved. This can be very frustrating if you spent a lot of time filling them all out and only 1 was wrong. 

Error:
Screen Shot 2021-01-14 at 2 22 23 PM

Fields I had previously all filled out:
Screen Shot 2021-01-14 at 2 25 34 PM

**To Reproduce**

1. Go to edit profile page
2. Fill in multiple fields but make the summary very long.
3. Click save profile information at the bottom
4. You should receive an error that your summary was too long but nothing else was saved.

**Expected behavior**

We should save what we can and only skip saving those fields that are invalid.

### PR DESCRIPTION
**Pull request by rna**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
This PR fixes the issue that all profile updates are lost when 1 field is invalid. Used the `restore_attributes` method from `ActiveModel::Dirty` to restore the previous state of invalid params and then save the valid data. 

## Related Tickets & Documents
Closes #12284

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://docs.forem.com/frontend/accessibility)._

## Added tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## Added to documentation?

- [ ] [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/)
- [ ] [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] README
- [x] No documentation needed

### CODE REVIEW

**Comment by rna** [comment]
Hi Team, // @mstruve 

This is the simplest solution I got for the mentioned issue. However, The `restore_attributes` method from `ActiveModel::Dirty` is not working as expected in the project codebase. I tried to debug the issue, but I can see the `restore_attributes` method not restoring the previous value where it supposed to. So, Can anyone please point me in the right direction why it's not behaving as expected?

Thanks
Ramesh

**Comment by citizen428** [comment]
@rna Thanks for looking into this issue. Your problem is that these are not simple attributes (i.e. not columns on a table), but a JSONB object persisted in the `data` column:

```ruby
profile.summary = "X" * 300
profile.valid?
#=> false
profile.errors.keys
#=> [:summary]
profile.changed
#=> ["data"]
```

As you can see the error key is on the `summary` store accessor, but the underlying changed attribute is `data`. `ActiveModel::Dirty` restores what was changed, and there is no change for a `summary` attribute on this model.

BUT, all of this inside, I find the behavior you attempted in this PR unexpected, as it doesn't follow Rails conventions. When trying to save a model either all changes get persisted or none do. Instead, the validation errors and current unpersisted data are used to re-render the form. By using a service object the calling controller doesn't get hold of an updated profile object, so it can't render back the changes.

Changing the existing code to follow the same pattern would look roughly like this:

1. Make sure we can get the `user` back out of the service, e.g. by adding a public `attr_reader` for it.
2. Update `ProfilesController` to behave more like a "classic" Rails controller: on success, display a success notice and redirect back, on error display an error flash and re-render the same page. What might get a bit tricky here is that the `edit` and `update` actions live in different controllers.

Please let me know if you plan on tackling these changes or if someone on our team should look into it.

**Comment by rna** [comment]
Thank you so much for the detailed feedback and suggestions. @citizen428
I would like to fix the changes for this.

**Comment by citizen428** [comment]
That's great, thanks @rna!

**Comment by citizen428** [comment]
Hi @rna, no rush, just wanted to check how things are going on your end? Did you have time to work on this?

**Comment by rna** [comment]
Hi @citizen428 , Sorry I have been busy lately. I will work on it this week. Hope that will be okay.

**Comment by citizen428** [comment]
No problem at all @rna, thanks for getting back to me!

**Comment by rna** [comment]
@citizen428 Please review and give me your feedback

**Comment by msarit** [comment]
@rna Thank you for your patience! 👋🏾  We'll get some eyes on your PR soon.

**Review by citizen428 — APPROVED** [review]

**Review by rhymes — CHANGES_REQUESTED** [review]
I don't think it's working correctly:


https://user-images.githubusercontent.com/146201/112281308-31909f80-8c86-11eb-9679-1525113af576.mov

I wrote something in my bio and added a lot of text in the summary, after I click on Save, I see the content of the summary in my bio...

Thank you for looking into this @rna!

**Comment by rna** [comment]
Thanks for reviewing the code @citizen428 @rhymes 

This issue has already existed beforehand. I thought it's expected behaviour since I saw no field name with **summary** in dev.to. So, I assumed the summary is deprecated and it's not worth raising a doubt here. 

However, Please confirm if you want me to fix that issue in this PR so that I'll look into it.

**Review by rhymes — APPROVED** [review]
@rna oh got it, so this is an existing bug. I thought it was a byproduct of you PR.

Given this, I'm going to accept this and merge it. If you'd like to explore the solution to that bug, could you start by opening an issue ticket? We can then assign it to you "formally"

Thanks a lot!

**Comment by rna** [comment]
Wow. That's great. Thank you. @rhymes 

I would like to work on that bug fix. Sure, I will raise an issue.

**Pull request merged**
