### PR TITLE
Refactoring questions asked of user

### PR DESCRIPTION
**Pull request by jeremyf**
## What type of PR is this? (check all applicable)

- [x] Refactor

## Description

In this pull request, I'm extracting and normalizing role-based
questions asked of the user.

Prior to this commit, our codebase has asked two very similar questions
of our user model:

- `user.has_role?(:admin)`
- `user.admin?`

In asking `has_role?(:admin)` we are relying on implementation details
of the rolify gem.  In addition, the `has_role?` question asked
throughout controllers or views means that it's harder to create
hieararchies of permissions.

In favoring `user.admin?` as our question, we can use that indirection
as an opportunity to discuss and decide "Should someone with the
`:super_admin` role be `user.admin? == true`?"

The details of this commit is to do three primary things:

1. Ask the `has_role?` questions in "one place" in the code (e.g. the
   `Authorizer` module)
2. Extract the role based questions that are on the `User` model and
   provde backwards compatable delegation.
3. Structure the code so that it's harder to accidentally call
   `user.has_role?` (e.g., make `User#has_role?` and `User#has_any_role?`
   private).

## Related Tickets & Documents

This is related to #15624 and the updates are informed by discussion in
PR #15691.  This commit supplants #15691.

## QA Instructions, Screenshots, Recordings

None...at the moment.

### UI accessibility concerns?

None...at the moment.

## Added/updated tests?

- [x] Yes

## [Forem core team only] How will this change be communicated?

- [x] I will share this change internally with the appropriate teams

### CODE REVIEW

**Review by citizen428 — APPROVED** [review]

**Comment by jeremyf** [comment]
Apologies for the force push, there were merge conflicts.

**Comment by jeremyf** [comment]
Again, pardon the force push, there was both a merge conflict and a flakey test.

**Review by msarit — APPROVED** [review]
SOLID refactor, @jeremyf! 🚀 

I think I missed where we're creating permissions around the use of certain Liquid Tags 😅

**Review by djuber — APPROVED** [review]
stellar documentation in the comments - thank you

**Pull request merged**
