### PR TITLE
Code snippet fullscreen icon - setting constraints for size.

### LINKED ISSUE #11747: Fullscreen button on article code block has huge svg icon path viewbox size
This issue only rises up when some of the scripts fail to load. Apparently one of those failed to load scripts include css which overrides this svg path viewbox size which is huge by default. Here's a screenshot (from my colleague) from Firefox which does not use any ad blockers. The screenshot is a little bit scaled down for the context, but as you can see the fullscreen icon is huge.

image

The size is 448 x 512 even though normally the icon is shown as 16 x 16:
```
<div class="highlight__panel-action js-fullscreen-code-action">
    <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 448 512" class="highlight-action highlight-action--fullscreen-on"><title>Enter fullscreen mode</title>
        <path fill="#fff" d="M0 180V56c0-13.3 10.7-24 24-24h124c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12H64v84c0 6.6-5.4 12-12 12H12c-6.6 0-12-5.4-12-12zM288 44v40c0 6.6 5.4 12 12 12h84v84c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12V56c0-13.3-10.7-24-24-24H300c-6.6 0-12 5.4-12 12zm148 276h-40c-6.6 0-12 5.4-12 12v84h-84c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h124c13.3 0 24-10.7 24-24V332c0-6.6-5.4-12-12-12zM160 468v-40c0-6.6-5.4-12-12-12H64v-84c0-6.6-5.4-12-12-12H12c-6.6 0-12 5.4-12 12v124c0 13.3 10.7 24 24 24h124c6.6 0 12-5.4 12-12z"></path>
    </svg>
</div>
``` 

And here are some console log from my colleague which probably points out the failed script which has the correct size of the fullscreen icon:
```
13:28:59.784 Loading failed for the <script> with source “https://practicaldev-herokuapp-com.freetls.fastly.net/packs/js/runtime~Search-5ec5f41eb3c09400436a.js”. my-first-date-with-tailwind-57d7:28:1
13:28:59.852 Loading failed for the <script> with source “https://practicaldev-herokuapp-com.freetls.fastly.net/assets/hello-dev-a33d069dda0cc1cfef81b71ac053adb1c4cfb617ad4140d02892b548b3081161.js”. my-first-date-with-tailwind-57d7:1591:1
13:28:59.921 Loading failed for the <script> with source “https://practicaldev-herokuapp-com.freetls.fastly.net/assets/base-7b4225a18255cd93f336b035a111a621d1f896f66fa18e26141c1958a7dbeabb.js”. my-first-date-with-tailwind-57d7:31:1
13:28:59.992 Loading failed for the <script> with source “https://practicaldev-herokuapp-com.freetls.fastly.net/packs/js/Search-5b0e630aa6f089abbc66.chunk.js”. my-first-date-with-tailwind-57d7:30:1
13:28:59.993 Loading failed for the <script> with source “https://practicaldev-herokuapp-com.freetls.fastly.net/packs/js/vendor-2db052da96e92ab3c700.chunk.js”. my-first-date-with-tailwind-57d7:29:1
13:29:00.004
Uncaught TypeError: window.InstantClick is undefined
    254 responseTemplates.js:3
    Webpack 4
responseTemplates.js:3
13:29:00.218
Request to access cookie or storage on “<URL>” was blocked because it came from a tracker and content blocking is enabled. 2
```

Anyway, this does not probably happen very often, and in his case this fixed by reload, but I think that the root cause, the huge svg viewbox size could be changed smaller, if there is no real reason to be that big.

### PR DESCRIPTION
**Pull request by ludwiczakpawel**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

This PR fixes #11747 - it may not fix it in existing posts but it will prevent future posts from having this issue. Reason: I believe actual markup for these icons is in actual database/markdown? So it's not being generated on the fly (which is bad and probably wrong.. I guess we would have to run some special task on all the existing posts to fix it there too).

## Related Tickets & Documents

- Closes #11747 

## QA Instructions, Screenshots, Recordings

1. Create a post with code snippet.
2. Try to disable CSS and/or JS. If "fullscreen" icon isn't HUGE, then we're good.

## Added tests?

- [ ] Yes
- [x] No, not needed.
- [ ] I need help with writing tests

## Added to documentation?

- [ ] [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/)
- [ ] README
- [x] No documentation needed

### CODE REVIEW

**Review by rhymes — APPROVED** [review]
LGTM!

**Review by msarit — APPROVED** [review]
Looks good, Pawel! 😄 

The failing specs have to do with a mismatch between received and expected files:
`/home/travis/build/forem/forem/spec/support/fixtures/approvals/user_preview_article_body.received.html`
`/home/travis/build/forem/forem/spec/support/fixtures/approvals/user_preview_article_body.approved.html`

@ludwiczakpawel

**Comment by rhymes** [comment]
@ludwiczakpawel to approve the change you need to run the failing test, check the diff and then issue `bundle exec approvals verify` to verify the change. Let us know if anything is unclear

**Comment by ludwiczakpawel** [comment]
@rhymes hmm i was able to fix one issue but not the other one so the build still fails.. would you mind taking a look when have a moment?

**Comment by rhymes** [comment]
@maestromac tagging you because this PR now contains a data update script that's going to run on all published articles to regenerate their markdown

**Comment by ludwiczakpawel** [comment]
@rhymes would you mind helping me out with this build failure?

**Comment by rhymes** [comment]
@ludwiczakpawel I merged master in ase `CodeBlockParser` doesn't exist anymore, let's see if it still fails. I'll keep an eye on it

**Pull request merged**
