### PR TITLE
15 minute fix: Remove `/partnerships` page ✂️

### PR DESCRIPTION
**Pull request by citizen428**
## What type of PR is this? (check all applicable)

- [X] Refactor

## Description

I really needed a break from the splitting `SiteConfig` work, so I quickly removed `/partnerships`.

## Related Tickets & Documents

Closes https://github.com/forem/forem/issues/13468

## QA Instructions, Screenshots, Recordings

Specs should pass,

### UI accessibility concerns?

None, only removing code.

## Added tests?

- [X] Yes

## [Forem core team only] How will this change be communicated?

- [X] I will share this change internally with the appropriate teams

### CODE REVIEW

**Comment by citizen428** [comment]
@mstruve There are a few more mentions of partners across the code base, but those were not included in the checklist. They are mainly small things on the sponsors page, let me know if we should remove them as part of this PR or later when we tackle sponsors.

**Review by rhymes — APPROVED** [review]
Found a tiny mention in 

https://github.com/forem/forem/blob/3a333ebbb12c280fb86f173de455f34a50ef682b/app/views/credits/new.html.erb#L50

but other than that, LGTM!

I don't remember the difference between "sponsorship" and "partnership" in our code though :D

**Comment by citizen428** [comment]
@rhymes There are several smaller mentions like this left, as indicated in my question above. I didn't change this copy yet, because we may still do partnerships as in run an event together, etc maybe? I'm not sure, the things I removed here are from the issue checklist.

**Review by mstruve — APPROVED** [review]
I think leaving that small email mention is fine. I noticed it's connected to the `business` email address which is another config [we are looking to remove for the starter pack](https://docs.google.com/document/d/1facy0-UXlUPrzpll8TAM-MNjZiwVbO1vepphuE6a-ek/edit) so I would not be surprised if it also gets 🔪  soon.

**Review by vaidehijoshi — APPROVED** [review]
snip snip snip ✂️ ✂️ ✂️

**Pull request merged**
