### PR TITLE
Do not set SiteConfig values in specs

### PR DESCRIPTION
**Pull request by jacobherrington**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

There are a few places that will probably require a closer look, but this gets rid of most of the places that we alter SiteConfig in the test suite.

## Added tests?

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## Added to documentation?

- [ ] Docs.forem.com
- [ ] README
- [x] No documentation needed

### CODE REVIEW

**Review by maestromac — APPROVED** [review]
Nice catch!

**Review by mstruve — APPROVED** [review]
😍

**Review by benhalpern — APPROVED** [review]
Fabulous improvement.

**Comment by rhymes** [comment]
Thank you 😭

**Pull request merged**
