### PR TITLE
Update FollowUsers.jsx

### LINKED ISSUE #19643: Change "Follow" button styling in `/onboarding` to others instances
> As a user, I always perceive highlighted/primary actions as important. 

>I always confuse "Following" with "Follow" because I would expect Follow button to be primary. But it's the opposite here, and I realize it once I click it.

> And anyway, since our default behavior is Followed state, the "Following" button should be secondary since it's unfollowing action. 

> image

> _Originally posted by @anujbhavsar96 in https://github.com/forem/forem/issues/19498#issuecomment-1608607846_

We should match the style of the Follow/Following buttons on the "Kickstart your community" step of `/onboarding` to match the behavior to instances shown in other areas of the main UI. Currently, the styles are reversed from the other main areas (e.g. see https://dev.to/ben).

The main change required here is to show a 'secondary' / 'outline'  button when the user/organization is followed and a 'primary' / 'filled' button when the user/organization is not followed.

There may be other changes to the styling required to keep them matching throughout the UI but fixing the above behavior satisfies the scope of this issue.

### PR DESCRIPTION
**Pull request by Kireeti-28**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
- As a user, I always perceive highlighted/primary actions as important.
- I always confuse "Following" with "Follow" because I would expect Follow button to be primary. But it's the opposite here, and I realize it once I click it.
- And anyway, since our default behavior is Followed state, the "Following" button should be secondary since it's unfollowing action.

ss
## Related Tickets & Documents

- Related Issue #
- Closes #19643

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [axe DevTools](https://www.deque.com/axe/) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

_For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: _This was just toggling of colors for Follow button on ```/onboarding```_
- [ ] I need help with writing tests

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by jaw6** [comment]
`cc` @anujbhavsar96 and #19498

**Review by anujbhavsar96 — APPROVED** [review]
Thank you @Kireeti-28 

Design-wise, this looks great 🚀

**Review by jaw6 — APPROVED** [review]
:tada:

**Comment by mirie** [comment]
@filleduchaos can you review this today please?

**Review by filleduchaos — APPROVED** [review]
🎉

**Comment by PhilipHow** [comment]
@Kireeti-28 thanks so much for getting this work to PR. Can you comment on the [Issue](https://github.com/forem/forem/issues/19643) so I can assign you?

**Pull request merged**
