### PR TITLE
Spelling db migrate

### PR DESCRIPTION
**Pull request by jsoref**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Fix spelling errors (db/migrate)

## Related Tickets & Documents

#15669 

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: I'm happy to provide the workflow, but I tend to offer it separately as it requires more buy-in than just fixing typos
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [x] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

### CODE REVIEW

**Comment by citizen428** [comment]
Class and file names need to match for migrations. Tbh it may be less effort to just live with the spelling mistakes. Technically there's no need to keep old migration files around at all, since the DB gets set up from `db/schema.rb`, so may eventually end up removing them.

We probably should keep the bugfix for `db/migrate/20210917023320_drop_connect_tables.rb` as that catches an actual typo yours truly introduced.

**Comment by jsoref** [comment]
Before posting this PR, I added the directory `db/migrate` directory to my `excludes.txt` file, so the spell checker won't comment going forward -- although it sounds like that's actually the wrong approach. Perhaps it'd be better to add a pattern of `class\s+\S+\s+< ActiveRecord::Migration`?

Am I right in understanding that, technically, if I renamed the files to match the fixed class names, things would be happy?

That said, it sounds like for now I should just drop all the class renames and leave just the one typo fix.

**Comment by citizen428** [comment]
> Am I right in understanding that, technically, if I renamed the files to match the fixed class names, things would be happy?

Yes. Though once a migration has run and its changes recorded in `db/schema.rb` there's no need for the files to stick around. There are even gems that e.g. automatically clean out/merge older migration files, etc.

**Comment by jsoref** [comment]
Well, I have tooling for that, it's pretty harmless. It's also trivial for me to drop the commits.

**Review by citizen428 — APPROVED** [review]
So to be sure I 

1. checked out this branch
2. dropped my local DB
3. recreated it and
4. ran all migrations.

Worked as expected, so this seems good to go.

**Review by jeremyf — APPROVED** [review]

**Comment by jeremyf** [comment]
LGTM.

**Pull request merged**
