### PR TITLE
Add creator to DisplayAd

### LINKED ISSUE #19122: Billboard/display_ad should track its creator
* [ ] Migration to add `creator_id` to display_ads
* [ ] Allow `creator_id` in API
* [ ] Append current-user as `creator` in Admin
* [ ] Make creator visible in Admin#show

If we'd had this field from the beginning, we'd have made it `required`, but we're bolting-it on after-the-fact. Since `forem-tools` is already sending ads over the API, we'll want it to be optional at first. Once `forem-tools` is sending `creator_id` reliably, we'll want to come back and make this field _required_.

### PR DESCRIPTION
**Pull request by jaw6**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

We're adding additional features to DisplayAds, including linking `community` ads to their `owner`. We also want to track who **created** these ads. This PR adds `creator` as an association on `display_ads`.

## Related Tickets & Documents

- Related Issue #https://github.com/forem/forem-internal-eng/issues/536
- Closes #19122

## QA Instructions, Screenshots, Recordings

Screen Shot 2023-02-16 at 14 39 50

Trying to keep this on the simpler side, I have added `Created by` as a non-editable field in the ad editor, rather than style this as plain text.

## Added/updated tests?

- [x] Yes - For now, this attribute is optional, but we'll eventually want it to be required (at least, in the API)
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [x] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] Are there any post deployment tasks we need to perform?

There is a migration. The `display_ads` table should be fairly small?

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by jaw6** [comment]
Closing & re-opening, hoping to trick CI into working properly.

**Comment by jaw6** [comment]
Going to close & re-open and see if I can surprise CI.

**Comment by rt4914** [comment]
Will review this PR tonight.

**Review by rt4914 — APPROVED** [review]
LGTM, Thanks.

**Comment by mirie** [comment]
@lightalloy can you take a look at this tomorrow please?

**Review by maestromac — APPROVED** [review]
LGTM!

**Pull request merged**
