### PR TITLE
Removing un-used email prop

### PR DESCRIPTION
**Pull request by Rafi993**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
It removes un-used email prop

## Related Tickets & Documents
closes https://github.com/forem/forem/issues/9826

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by Rafi993** [comment]
> [forem/app/javascript/chat/ChatChannelSettings/ModFaqSection.jsx](https://github.com/forem/forem/blob/4500fe6f2216219a944038f1edebd3e3781046bc/app/javascript/chat/ChatChannelSettings/ModFaqSection.jsx#L26-L29)

you are right it is being used but it is hard coded here. I'll remove the hard-coding instead

**Comment by Rafi993** [comment]
The email is avaiable via rails helper **email_link** I am having trouble accessing it in the Preact component  **app/javascript/chat/ChatChannelSettings/ChatChannelSettingsSection.jsx**

**Comment by Rafi993** [comment]
I should have create github issue for this PR. I'll do that now

**Comment by rhymes** [comment]
@Rafi993 sure! :-)

**Comment by Rafi993** [comment]
> @Rafi993 sure! :-) should we close this PR?

I guess so. The branch for this PR is named wrong (since the issue means something else different entirely now).

**Pull request closed without merging**
