### PR TITLE
Update verbiage around connect invitations

### PR DESCRIPTION
**Pull request by jacobherrington**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation Update (copy tweak)

## Description

The phrasing of this may reflect the code, but is a little confusing. A
user might not understand what a "joining request" is, so we should
probably just keep things simple for the time being.

## Added tests?

- [ ] Yes
- [x] No, and this is why: This is just a copy change.
- [ ] I need help with writing tests

## Added to documentation?

- [ ] [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/)
- [ ] README
- [x] No documentation needed

### CODE REVIEW

**Review by rhymes — APPROVED** [review]
❤️

**Review by vaidehijoshi — COMMENTED** [review]
Hm, there is a test that checks for this text but it has inexplicably _not_ failed with this change? 😬
 
https://github.com/forem/forem/blob/530e9270608219e02db7774bc8e939379f22d525/app/javascript/chat/__tests__/requestManager.test.jsx#L48-L50

**Comment by jacobherrington** [comment]
@vaidehijoshi :thinking: 

tenor

That can't be good. I'll look into it!

**Comment by jacobherrington** [comment]
@vaidehijoshi It seems that the test will pass no matter what I tell it to look for -- we should be okay to merge this and I'll follow up with a PR that fixes or removes the test today.

**Comment by katiedavis** [comment]
> Hm, there is a test that checks for this text but it has inexplicably _not_ failed with this change? 😬
> 
> https://github.com/forem/forem/blob/530e9270608219e02db7774bc8e939379f22d525/app/javascript/chat/__tests__/requestManager.test.jsx#L48-L50

I think queryByText finds the first match and not an explicit string match :/ Which I guess for this test makes sense because it's it's just asserting an element exists...but probably shouldn't be used for much else!

**Comment by jacobherrington** [comment]
@katiedavis My understanding of JS leaves a lot to be desired, but it **seems** like the test passes because the result is not `undefined`... It is `null`. :wink:

**Comment by jacobherrington** [comment]
https://github.com/forem/forem/pull/12561 fixes the test. We'll need to merge this first, or that test will fail! :upside_down_face:

**Comment by katiedavis** [comment]
> @katiedavis My understanding of JS leaves a lot to be desired, but it **seems** like the test passes because the result is not `undefined`... It is `null`. 😉

haha duh 🙃 goodbye...

**Review by vaidehijoshi — APPROVED** [review]

**Pull request merged**
