### PR TITLE
Remove redundant extension recommendations

### LINKED ISSUE #9549: Remove redundant vscode extension reccomendations
**Is your feature request related to a problem? Please describe.**
With the addition of the `nickytonline.dev-to-extension-pack` the same extensions must not be recommended again.  

**Describe the solution you'd like**
Remove recommended extension that are within the `nickytonline.dev-to-extension-pack`.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by abenettt**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [X] Optimization
- [ ] Documentation Update

## Description
Removes redundant extension reccommendations in vscode.
## Related Tickets & Documents
Closes #9549 
## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added tests?

- [ ] yes
- [X] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [X] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by citizen428** [comment]
I'll let @nickytonline clarify, but from his comment on the issue 

> Just having the separate extensions probably makes more sense if people do not want to install all of them.

I think he'd prefer keeping the individul recommendations instead of the pack.

**Comment by abenettt** [comment]
That's an argument, maybe turn it around and add the extensions by themselves and only mention the extension pack as an option in the documentation on how to setup the editor?

**Comment by nickytonline** [comment]
I'm a fan of extension packs, but the previous PR which I can't find started a discussion about what if they don't want to install all the extensions? So that's why, even though I created the extension pack, I think the individual extensions in the recommended extensions would make sense.

In regards to documentation, I'm fine with mentioning that the extension pack exists as an alternative.

**Comment by msarit** [comment]
@citizen428 @nickytonline Hey fellas! 👋🏾 
Seeing as the source repository is listed as `unknown repository`, I'm inclined to conclude that this PR has been abandoned. Thus, I'm closing it. Let me know if you have any thoughts.

**Pull request closed without merging**
