### PR TITLE
Navigation Link: fix regex to allow multiline SVG

### LINKED ISSUE #14334: Bad regex for detecting SVG on Navigation Links
The dreaded error:

Screen Shot 2021-07-26 at 8 57 12 AM

Code in question:

```rb
class NavigationLink < ApplicationRecord
  SVG_REGEXP = /<svg .*>/i.freeze
```

Testing with rubular
Screen Shot 2021-07-26 at 9 03 10 AM

So the problem is that the Regex expects svg text to be all on a single line:

Screen Shot 2021-07-26 at 9 06 04 AM

When exporting svg from illustrator it will sometimes insert a XML schema tag first.

Yep Single line formatting fixed it:

Screen Shot 2021-07-26 at 9 11 39 AM

### PR DESCRIPTION
**Pull request by SiddharthShyniben**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Allows the regex which is used to test SVG match multiline SVGs. Fixes #14334 

## Related Tickets & Documents

Closes #14334 

## QA Instructions, Screenshots, Recordings

NA

### UI accessibility concerns?

NA

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: Not sure if there are any tests for this
- [x] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://admin.forem.com/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] Are there any post deployment tasks we need to perform?

NA

## [optional] What gif best describes this PR or how it makes you feel?

Teeny Tiny one

### CODE REVIEW

**Review by citizen428 — COMMENTED** [review]
Thanks for the quick turnaround time on this @SiddharthShyniben! Could you please add a test case for this so we can verify the fix and avoid regressions?

**Comment by SiddharthShyniben** [comment]
Sure @citizen428

**Comment by SiddharthShyniben** [comment]
Could you tell me where the tests are? I'm kinda confused now

**Comment by SiddharthShyniben** [comment]
I'm having some trouble testing... Getting this error `database "Forem_test" does not exist`. Any help will be appreciated

**Comment by citizen428** [comment]
@SiddharthShyniben You should run our `bin/setup` script which will set up the database and everything.

**Comment by SiddharthShyniben** [comment]
@citizen428 I already ran that (twice).

FYI: I'm on GitPod

**Comment by citizen428** [comment]
Hmm, I haven't used Gitpod in a while. What happens if you manually run this:

```sh
RAILS_ENV=test rails db:create
RAILS_ENV=test rails db:test:prepare
```

**Comment by SiddharthShyniben** [comment]
@citizen428 Command rails not found. I'll try installing it

**Comment by SiddharthShyniben** [comment]
Tests done :D

**Review by citizen428 — APPROVED** [review]

**Comment by citizen428** [comment]
Thanks @SiddharthShyniben!

**Review by Ridhwana — APPROVED** [review]

**Comment by cmgorton** [comment]
Thanks for the help here @SiddharthShyniben ! 🎉

**Pull request merged**
