### PR TITLE
Fix: X (Twitter) icon not visible in dark mode

### LINKED ISSUE #20926: Social media icon not visible in dark mode on home page and settings page.
**Describe the bug**
detailed description of the issue 
followed by screenshots

The Twitter ( X ) icon is not visible in the dark mode on the dev.to home page. Its also not visible in the settings page ( in both dark and light modes )

Below are the screenshots of the issues.

**1.) Icon not visible in dark mode ( home page )**

image

**2.) Icon not visible in both ( dark and light  modes ) ( settings page )**

Dark Mode ->

image

Light Mode ->

image

**To Reproduce**

1.) Open dev.to site , on the left sidebar there will be social media icons.
2.) Open dev.to site, on the right side click on profile icon -> click on settings -> there will be 4 options to correct twitter being the last one ( 4th one )

**Expected behavior**

Expected behaviour is the clear visibility of the icon in both dark and light modes.

### LINKED ISSUE #21120: X logo (formerly Twitter) is not correctly visible in dark mode
**Describe the bug**

When using the dark theme within the website, the X icon within the settings is not visible.

**To Reproduce**

1. Go to '[settings](https://dev.to/settings)'
2. Go to 'Customization' section
3. Click on 'Dark Theme' radio button
4. Click on 'Save' button
5. Go back to the 'Profile' section

**Expected behavior**

[square-x-twitter](https://fontawesome.com/icons/square-x-twitter?f=brands&s=solid)

When the link opens, click on the `Nox! icon` to see the expected behavior.

**Screenshots**

immagine

**Desktop (please complete the following information):**

- OS, version: macOS Sonoma 14.5
- Browser, version: Firefox 126.0.1

**Smartphone (please complete the following information):**

- Device: iPhone 11 Pro
- OS, version: iOS 17.5.1
- Browser, version: Safari 17.5

**Additional context**

No additional information.

### PR DESCRIPTION
**Pull request by danielmbrasil**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
The X (Twitter) icon was not visible in dark theme, as reported in the linked issues. To resolve this, I replaced the X icon's SVG file with a version that has a transparent background, preventing conflicts with the CSS. Now, the icon is clearly visible in both light and dark themes.

## Related Tickets & Documents

- Related Issue #21120, #20926
- Closes #20926, closes #21120

## QA Instructions, Screenshots, Recordings
**X icon in dark mode**:
Screenshot from 2024-10-14 20-12-59

**X icon in light mode:**
Screenshot from 2024-10-14 20-13-09

**X icon in light mode (sign-in/sign-up forms):**
Screenshot from 2024-10-14 20-12-50

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [axe DevTools](https://www.deque.com/axe/) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

_For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Review by benhalpern — CHANGES_REQUESTED** [review]
Oops, I mean to select "Request changes" in my last comment instead of approved.

**Comment by danielmbrasil** [comment]
Hey @benhalpern, I’ve just pushed a commit with the requested changes. I removed the XML declaration and adjusted the width, height, and viewBox to match the other icons. The spacing issue should be fixed now.

**Comment by danielmbrasil** [comment]
Hey @benhalpern, could you take a look at this again when you get the chance?

**Review by benhalpern — APPROVED** [review]
Hey thank you for this.

There's still a small issue with the padding, but we can merge this and deal with that after. All in all it's better than the current state with the dark mode issue. Sorry for delay.

**Pull request merged**
