### PR TITLE
Multiple reactions - remove circle from active reactions

### PR DESCRIPTION
**Pull request by rt4914**
## What type of PR is this? (check all applicable)

- [x] Optimization

## Description

Multiple reactions - remove circle from active reactions
Simply see screenshots below

## Related Tickets & Documents

- Related Issue #19008

## QA Instructions, Screenshots, Recordings

https://www.loom.com/share/a2bfb69edd2143a38cc7116f43849952

| Before  | After |
| ------------- | ------------- |
| Screenshot 2023-01-31 at 7 03 40 PM | Screenshot 2023-01-31 at 7 03 01 PM |
| Screenshot 2023-01-31 at 7 04 15 PM | Screenshot 2023-01-31 at 7 04 35 PM |

### UI accessibility concerns?

NO

## Added/updated tests?

- [x] No

## [Forem core team only] How will this change be communicated?
- [x] This change does not need to be communicated

### CODE REVIEW

**Comment by rt4914** [comment]
@anujbhavsar96 @benhalpern Does this match your expectation?

**Review by benhalpern — APPROVED** [review]
LGTM — but double check with @anujbhavsar96 that this is exactly what we want. But cool with me.

**Comment by anujbhavsar96** [comment]
Looks perfect 🔥 @rt4914

**Review by jaw6 — COMMENTED** [review]
I _think_ we're still intending to keep the new feature behind the feature flag. The changes here remove the circle highlight everywhere, even when the feature flag is disabled. (But maybe I'm wrong and we're actually intending to remove the circles everywhere?)

**Comment by rt4914** [comment]
@anujbhavsar96 Need clarification regarding https://github.com/forem/forem/pull/19034#pullrequestreview-1278554258

We want to remove circle on reactions on multiple reactions + current users too or we only want to remove it for multiple-reactions?

**Comment by anujbhavsar96** [comment]
@rt4914 This can go with a Multi-reaction release. No need to make changes to the current one.

**Comment by rt4914** [comment]
@jaw6 Have a look at this output https://www.loom.com/share/a2bfb69edd2143a38cc7116f43849952

I have removed the outer circle with feature flag enabled.

**Pull request merged**
