### PR TITLE
Fix github readme liquid tag

### PR DESCRIPTION
**Pull request by omkz**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
The image and text are messed up.

## Related Tickets & Documents
#12772

## QA Instructions, Screenshots, Recordings

1. Visit a post with a github liquid tag.

### UI accessibility concerns?

Nope

## Added tests?

- [ ] Yes
- [x] No, and this is why: Update style only.
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [x] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by citizen428** [comment]
Thanks for a great first contribution @omkz. That said, it doesn't quite close #12772, as that also mentions Twitter liquid tags. Would you prefer to update the PR description or do you also want to work on that?

**Comment by omkz** [comment]
Thank you for the review @citizen428. I prefer to update the PR description to keep the PR small.

**Review by aitchiss — APPROVED** [review]
Thanks for this PR! I've checked the changes locally on Firefox/Chrome/Safari and it's looking much better 🙌

**Review by rhymes — APPROVED** [review]
Awesome!

**Pull request merged**
