### PR TITLE
Sidebar explore

### PR DESCRIPTION
**Pull request by ludwiczakpawel**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Long time ago, we've been discussing internally idea for having "explore" widget to be able to follow new tags and/or users. This PR brings frontend draft for this feature. Who want to build backend and JS for this?

This widget should randomly recommend you tags and/or people to follow based on your current interest. It should refresh (randomize) proposed tag/user once in a while (not sure how often exactly) OR after hitting the "Refresh" icon.

Would be cool to wire in some analytics to measure "success rate" for this.

## QA Instructions, Screenshots, Recordings

image

image

## Added tests?

- [ ] yes
- [ ] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [ ] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by benhalpern** [comment]
This looks great! I'll give some thought as to how the rest gets implemented.

Not to anyone thinking through this: We currently cache the sidebar, this will affect the implementation. Whatever choice we make here should complement future decisions.

**Comment by mstruve** [comment]
Hey @ludwiczakpawel, is this still something we want to pursue? I was going through old PRs and trying to tidy things up a bit and was wondering if this is something we want to close until we are ready to finish it off.

**Comment by ludwiczakpawel** [comment]
@mstruve yes, we do want to pursue this but it's waiting for backend to chime in :D I've been linking to this PR in many convos and comments on forem.team, forem.dev and Slack in last several months since problem(s) solved by this solution is commonly discussed in those places. So I'd really appreciate if we could keep it here even though I do understand code-wise it's probably a bit outdated (shouldn't be hard to make it up-to-date though).

**Comment by citizen428** [comment]
@ludwiczakpawel Your friendly OSS rotation check-in: now that we have a new RFC process, would it make sense to turn this PR into a stage 0 RFC and close it? Then we can get it approved by product and prioritize the remaining work properly,

**Comment by ludwiczakpawel** [comment]
Yea, I guess we can close it.

**Pull request closed without merging**
