### PR TITLE
StandardError to ApplicationError

### PR DESCRIPTION
**Pull request by ledestin**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

Try replacing `raise StandardError` with `raise ApplicationError` in a single class and rescue `ApplicationError` in controllers alongside with `StandardError`.

## Related Tickets & Documents

#8248

## Added tests?

- [x] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by ledestin** [comment]
@rhymes take a look at a possible gradual approach.

**Comment by joshpuetz** [comment]
Tagging @rhymes and the rest of @thepracticaldev/oss

**Comment by ledestin** [comment]
My plan was to introduce `ApplicationError`, so that it can be used later on, in liquid tags and elsewhere. At this point, it should be safe to replace `raise StandardError` in liquid tags with `raise ApplicationError`, since controllers catch it.

As @rhymes suggested, the issues, when liquid tags still raise `StandardError` due to code errors, should be resolved one by one.

**Comment by joshpuetz** [comment]
Re-pinging @forem/oss

**Comment by rhymes** [comment]
@joshpuetz thanks! we're having a sort of double conversation between the PR and the issue https://github.com/forem/forem/issues/8248#issuecomment-673404569

It's a bit confusing!

Basically I still think we should go the custom route of having `LiquidTagError < ApplicationError < StandardError` so the controller can distinguish from errors thrown by liquid tags and everything else

**Comment by rhymes** [comment]
Hi @ledestin, I'm sorry we dragged our decision on this but we're not sure we'd like to proceed as is and this PR has sat here for months due to such indecision. I still think you have a point there's valuable feedback in #8248 but we haven't had the chance of moving forward with this and we'd like to table this PR until we can make a team decision on the issue that this refers to.

So, in the meantime, I'm going to close this.

Thank you again!

**Pull request closed without merging**
