### PR TITLE
[15 Min. Fix] Update Default bg_color and text_color Hexes on Tag Edit Page

### PR DESCRIPTION
**Pull request by juliannatetreault**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
**The issue**:
> As a tag admin, I don't want to accidentally set my tag to using #000000 as the color hex for both text and background.

**The solution**:
This PR adds default hex colors to the `color_field_tag` to the `edit.html.erb` form for `/t/tag/edit`. The default `bg_color_hex` has been set to black, `#000000`, and the default `text_color_hex` has been set to white, `#ffffff` if a tag doesn't already have a `text_color_hex` or `bg_color_hex` set. If, however, a tag already has a `bg_color_hex` or `text_color_hex` set, the colors will default to whatever colors the tag already has set.

Additionally, this PR adds a system spec that tests that users with the correct permissions (admins or tag moderators) are able to successfully update the tags as expected.

## Related Tickets & Documents
Closes issue #11522 

## QA Instructions, Screenshots, Recordings
To QA this PR, first ensure that you have an admin role or tag moderator role (for the particular tag you create), and then please do the following:
- Create a new post with a new tag (one that didn't exist prior to you creating it) and navigate to the tag's edit page. Observe that the hex colors default to black and white:
Screen Shot 2021-02-22 at 11 01 49 AM

- Without updating anything, click "SAVE CHANGES" and observe that the tag updates to a readable default of black and white:

**(Before clicking "SAVE CHANGES")**
Screen Shot 2021-02-22 at 11 02 21 AM

**(After clicking "SAVE CHANGES")**
Screen Shot 2021-02-22 at 11 03 01 AM
- Next, update one or both of the tag's hex colors and click "SAVE CHANGES". Observe that the tag updates as expected and now defaults to the tag's current hex colors (whatever colors you updated the tag to), rather than black and white:
Screen Shot 2021-02-22 at 11 04 03 AM

- Try to break things! 🛠️ 

### UI accessibility concerns?
I don't believe that this should bring up any UI concerns.

## Added tests?

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [x] I'm not sure how best to communicate this change and need help
⚠️ Due to the nature of this bug, I'm not sure if this fix warrants any update other than communicating on the issue itself that the bug has been fixed.
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] Are there any post-deployment tasks we need to perform?
N/A

## [optional] What gif best describes this PR or how it makes you feel?

Bob Ross Painting

### CODE REVIEW

**Comment by juliannatetreault** [comment]
Pinging @lisasy and @vaidehijoshi for review on this fix so that I can get a set of product eyes on this quick bug fix, please and thank you so much in advance! ✨

**Review by atsmith813 — APPROVED** [review]
Tested this locally and it works as expected!

**suggestions (non-blocking)**
This may or may not be better explored in a separate PR...but when you edit tags from Admin instead of the tag edit page, the value of the field doesn't update when you click on a color in the color picker

Screen Shot 2021-02-22 at 1 39 11 PM

Also, when I clear the hex code value in the field and click save, I almost expected it to revert back to the default colors since I cleared the values, but instead, they just remained what they originally were. The concept of "what happens when you clear a `SiteConfig`" has come up a few times and I don't think we've landed on a single answer yet. Does it revert to default? Does it not change at all? etc.

**Comment by juliannatetreault** [comment]
> **suggestions (non-blocking)**
> This may or may not be better explored in a separate PR...but when you edit tags from Admin instead of the tag edit page, the value of the field doesn't update when you click on a color in the color picker
> 
> Screen Shot 2021-02-22 at 1 39 11 PM
> 
> Maybe we can update this at some point so that when a color is chosen in the color picker, the form value updates right away as well. To be clear, while the form value doesn't update in the UI, updating the colors on the color picker _does_ work!
> 
> Also, when I clear the hex code value in the field and click save, I almost expected it to revert back to the default colors since I cleared the values, but instead, they just remained what they originally were. The concept of "what happens when you clear a `SiteConfig`" has come up a few times and I don't think we've landed on a single answer yet. Does it revert to default? Does it not change at all? etc.

You bring up some great suggestions and questions, @atsmith813! I have been poking around at this a bit and haven't been able to figure out why this isn't updating as expected yet. 🤔   Maybe this issue and the fact that the cleared hex values do not default back to the default colors after clearing the values could be a potential RFC? I also wonder if, for consistency purposes, it would make sense to make both tag color pickers (the one on `/t/#{tag}/edit` and the one on `/admin/tags/:id/edit`) the same, since one (on `/t/#{tag}/edit`) is just a color picker and the other (on `/admin/tags/:id/edit`) is a form field _in addition to_ a color picker.

**Review by citizen428 — APPROVED** [review]

**Review by vaidehijoshi — APPROVED** [review]
Nice improvement!

**Pull request merged**
