### PR TITLE
Refactor admin settings view into partials

### PR DESCRIPTION
**Pull request by citizen428**
## What type of PR is this? (check all applicable)

- [X] Refactor

## Description

For the time being, this should be the last bigger PR [1] related to splitting `SiteConfig`: the `admin/settings/show.html.erb` view was becoming extremely unwieldy which is something that was brought up during previous PR reviews. This PR splits it into several partials. 

[1] I will probably still do minor cleanup work here or there but as 15-minute fixes or during cooldown weeks.

## Related Tickets & Documents

RFC #126

## QA Instructions, Screenshots, Recordings

* Specs should be green
* e2e tests should be green
* The settings page at `admin/customization/config` should work as expected

### UI accessibility concerns?

None, pure code refactoring

## Added tests?

- [X] No, and this is why: covered by existing tests

### CODE REVIEW

**Comment by rhymes** [comment]
There's a failing test, https://github.com/forem/forem/blob/1bf27b0331155a3b2d31b331f20d91c6a3052b3d/cypress/integration/adminFlows/config/authenticationSection.spec.js#L72 - I can reproduce it by repeating the steps Cypress does manually

I think Stimulus needs this https://github.com/forem/forem/blob/1bf27b0331155a3b2d31b331f20d91c6a3052b3d/app/views/admin/settings/show.html.erb#L1175

**Comment by citizen428** [comment]
Hah, I thought I ran all Cypress tests locally.

**Comment by citizen428** [comment]
I'll temporarily set this PR back to draft since I have started something else in the meantime that I'd like to wrap up. Debugging this will have to wait until tomorrow.

**Comment by citizen428** [comment]
Hmm, I'm a bit unsure why this is happening, could it be related to the controller being attached in the main view while the actions are in a partial? Because the `div` with the right attribute is definitely still there.

**Review by rhymes — APPROVED** [review]
Works great!

**Review by djuber — APPROVED** [review]
Github unhelpfully hid the show.html.erb diff since it was big - I kept looking for a wall of red to offset all the newly created partials.

**Pull request merged**
