### PR TITLE
Switch from rubocop to standardrb

### PR DESCRIPTION
**Pull request by jaw6**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Recently, while fixing a minor bug, [I ran into a problem](https://github.com/forem/forem/pull/18662/files#r1010315296) with rubocop. Briefly, there was a relatively new cop in the `rubocop-rspec` gem (`RSpec/NoExpectationExample`) that failed any spec that didn't have the words `expect_` in it. In my specific case, I had two spec files which had (long prior to my change) used `sidekiq_assert_enqueued_with`, thus failing the new cop. I think this is a "bad cop" -- I don't think the linter can or should shoulder this responsibility -- and my immediate inclination was to disable it, but I thought it might be time for a broader discussion about how we're using our linting tools.

In the context of that bug fix, bumping rubocop-rspec to a newer version brought in an upgrade to this cop that made it possible to configure it in a way that recognized `sidekiq_assert_enqueued_with` as a valid expectation, so the change I'm proposing here is nowhere near critical path, _however_ the specific case highlighted a problem I've seen many times over with rubocop: poorly considered cops are brought into the rubocop library, without sufficient consideration for their impact or suitability. 

The expectation of rubocop's developers seems to be that downstream consumers will make use of configuration options to opt-out (or otherwise adapt) new cops to fit their particular style. However, in practice -- broadly and most specifically in our project -- this is _rarely_ done in practice, and seems to conflict with the ostensible purpose of a linting/formatting/style tool. 

I would like to propose subbing in `standard` for our bespoke `rubocop` config. The [standard](https://github.com/testdouble/standard) project aims itself squarely at these concerns. Standard wraps rubocop, but they take a more community-oriented, deliberate pace when adopting new style changes. To highlight from the project's readme:

> The beauty of Ruby Standard Style is that it's simple. No one wants to maintain multiple hundred-line style configuration files for every module/project they work on. 
> **No configuration.** The easiest way to enforce consistent style in your project. Just drop it in.
> **Deliberate pace.** We strive to take the hassle of upgrading Rubocop out of each individual team's hands and shoulder it ourselves. We enable about ~20% of new cops and generally choose conservative configurations for them.

I believe the net impact would be:

* our ruby code would be _more_ inline with community expectations
* there would be less "care and feeding" of ruby styling tools overall

For this PR, I have configured rubocop to use standard's config (there is also a `standard` executable, but configuring things in this way, it's still possible to use the `rubocop` executable), so there would be minimal impact on our existing tools & workflow (:crossed_fingers: I'll see how CI goes soon) but I had to tweak some things to remove a hard-coded (and possibly unnecessary) dependence on `rubocop-rails`. 

I'm hoping for a discussion here, using this PR as a springboard. I'm still relatively new here and I don't know if we've previously considered standard and rejected it (if so, apologies for bringing it up again). Our setup only runs Standard/Rubocop on changing files, but I manually ran it against `spec/models/user_spec.rb` so this PR would have at least one example of how standard's config might differ from rubocop's.

(Note: there is also a [standard.js](https://github.com/standard/standard) project, with similar goals & spirit, but I am _not_ proposing it in this PR, as I am personally much less familiar with it and how it would impact our code.)

`cc` @fdocr @lboogie04@lightalloy @maestromac @Ridhwana @rt4914 

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [x] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

high standards

### CODE REVIEW

**Review by maestromac — APPROVED** [review]
I am completely for this. Any for more uniformity and less manual intervention.

**Comment by fdocr** [comment]
Without much personal experience with `standardrb` I'd be in favor of moving forward with this change based on the logic you mentioned (i.e. difference in how rubocop vs standardrb approach differs in new rules added over time).

> Our setup only runs Standard/Rubocop on changing files, but I manually ran it against spec/models/user_spec.rb so this PR would have at least one example of how standard's config might differ from rubocop's.

So to try and understand this, `standardrb` wasn't run against the entire codebase for this particular PR? I'm asking in order to know if we were to merge this PR, then we would have to progressively edit files in new PRs "as we go" to conform with `standardrb` rules? (because the pre-commit hooks run only against files that changed)

**Comment by jaw6** [comment]
> So to try and understand this, `standardrb` wasn't run against the entire codebase for this particular PR? 

That's correct -- I have **only** run the `specs/models/user_spec.rb` through the new linter config. I thought it would be useful to the discussion to have a concrete example of "what's changing", so I picked a file I'd changed recently.

I think "rolling forward" is a general consensus preference for linter adoption/change. For example, this is how the _current_ rubocop config deals with newly appearing cops, such as my encounter with `NoExpectationExample`. As far as I'm aware, the reasons for this preference are both trivial (changing many, many lines messes with blame, churn, and many other history/statistical tools) and not (lexical changes made by automated linting tools are _not_ guaranteed to be behaviorally inert; it's good to limit our QA risk by making Pandora's box as localized as we can).

To be clear, I think this point is up for discussion, I think I'm just sharing how I understand the preference for "forward rolling" linter changes came to be this way. Also, again just wanting to be clear, this is not without some downside risk: rollbacks can be harder as the linter won't "allow" reverting files to "bad" old styles (but again, we have also seen this with `rubocop`), and it can be annoying to deal with styles being a bit mismatched (although, again, this would also continue happening anyway, as new cops appear).

> if we were to merge this PR, then we would have to progressively edit files in new PRs "as we go" to conform with `standardrb` rules? (because the pre-commit hooks run only against files that changed)

That's mostly accurate, but some things to note:

* This isn't _significantly_ different than how things work currently with rubocop -- again, my recent experience with `NoExpectationExample`, new "surprise" cops will still pop up from time-to-time.
* `standard` should _generally_ be _more_ permissive than `rubocop` -- the conservative approach to rule adoption means that at any given moment `standard` generally has _fewer_ rules than `rubocop` does.
* `standard` also has a guideline that _most_ rules ought to be auto-correctable (rubocop does not have this guideline) -- of course, it's only a guideline and it is subject to change, but the folks running standard really strive for it to remain a _formatting_ tool.

My expectation would be that future commits _after_ standard would see less _manual_ intervention to satisfy style rules than we would see in an alternate timeline where we remain on rubocop (though we _might_, initially, see more noise in diffs, until the styles gradually converge).

Again, I think this is all still up for discussion -- if anyone is uncomfortable with this direction, it's easy enough to stay on with `rubocop`.

**Comment by Ridhwana** [comment]
@jaw6 thank you so much for putting together this thoughtful discussion with an example ✨. 

I'm not familiar with `standard`, so forgive me if these questions are noob-like 😅 The part that caught my attention was that you mentioned that standard is like rubucop but more permissive.

I find that sometimes a linter that is less permissive allows for better standardization and uniformity across the app, especially when the app is large and there's many developers with different styles of coding working on the app.

> Deliberate pace. We strive to take the hassle of upgrading Rubocop out of each individual team's hands and shoulder it ourselves. We enable about ~20% of new cops and generally choose conservative configurations for them.

I'm thinking out aloud if 20% of cops be sufficient or would it perhaps make our codebase too open to various linting styles and opinions such that its more difficult to focus on the code? In addition would it still be useful to new open source contributors to try and adhere to the styling that we have.

What are your thoughts on this? I'm not opposed to this change but I'm just thinking out loud some thoughts that come to mind.

**Comment by jaw6** [comment]
@Ridhwana 

> I'm thinking out aloud if 20% of cops be sufficient or would it perhaps make our codebase too open to various linting styles and opinions such that its more difficult to focus on the code? In addition would it still be useful to new open source contributors to try and adhere to the styling that we have.

> What are your thoughts on this?

It's a fair question and one that may be difficult to answer in a satisfying way. I'm not sure it's rewarding to do an exact, point-by-point comparison of which cops are included or excluded, but in the hand-ful of examples I've spot-checked, I don't find the changes to be significant. That is: often we were _already_ disabling the cop in question, or we were [frequently disabling it in-line](https://github.com/forem/forem/search?q=rubocop%3Adisable), or it was otherwise irrelevant. 

It's terribly imprecise, but my "gut feeling" is that we're not operating quite as strictly as `rubocop` would have us be -- but I can't guess how "close" we are to `standard`'s 20%. My sense is that we wouldn't see a change in consistency -- except that, we _might_ see fewer in-line cop exemptions?

I also think we might be less consistent with `rubocop` (maybe? depending on how much we've already drifted from the out-of-box config), but _more consistent_ with the actual broader `ruby` community?

Something I've been thinking about here is something like "who is responsible for our style preferences?" We currently give a lot of that responsibility to the `rubocop` team, but my sense is that they don't see their project as _being_ responsible for style -- rather, for being a tool that allows _us_ to be responsible for style. `rubocop`'s approach appears to be: let all the cops in and folks will opt-out, or configure, as needed.

In _practice_, though, I'm not sure we're terribly mindful of style. When a new cop, like `NoExpectationExample`, comes along, I think it's an easier path to adapt our style -- to assume that `rubocop` _must_ have a good reason for preferring that style -- than to interrogate the rules on any deeper level. 

That is: I think we're using `rubocop` less the way `rubocop` wants to be used, and more the way `standard` wants to be used.

Does that make any sense?

**Comment by Ridhwana** [comment]
@jaw6 thank you so much for your thoughtful response. I think it makes sense, and you've answered all my questions. I'm okay with proceeding with standard.

**Review by fdocr — APPROVED** [review]
Thanks for the thorough answers to the conversation here @jaw6. I have no objections to this either 👍🏼 

Eager to possibly see this merged next week if no other questions/objections come up 😄

**Comment by jaw6** [comment]
Sadly, after trying today to merge this, I am instead closing this without merging. 😥 

In short: I have now run this config on more of our code and now I am **much less confident** that standard would be friction-light.

In more detail: 

Because this PR has been open for a time, and because we have linting as a pre-commit hook, and because we have `erblint` setup to use `rubocop` (even with `standard`'s config), trying locally to merge `main` into this branch (to resolve merge conflicts) meant running this new style config against a wider (but still small-ish) cross-section of our code -- much more than just one test file.

Critically, `erblint` acts as a nexus of several issues:

* For a variety of technical reasons, `erblint` is _much more_ conservative about `autocorrect` than `rubocop` or `standard` are -- that is to say, many rules that _are_ autocorrectable on a `*.rb` file are _not_ autocorrectable in `*.erb` (or, maybe, not correctable _by_ `erblint`). In one case, I saw 1/11 lint failures were not-autocorrect-able by `erblint` that _would have been_ autocorrect-able by `standard` in an `.rb` context -- that suggests that potentially as much as 90% of the newly required style rules would require at least some manual rewriting in `.erb`. Even if the requested changes were trivial, this is a high fraction.
* There are some rules configured in `standard` that are a) noticably different than our `rubocop` defaults, b) of debatable validity, and c) seem significantly worse when applied to `erb`. One fairly clear example is [`Layout/ArgumentAlignment`](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/ArgumentAlignment), where `rubocop`'s default `with_first_argument` is significantly better in `erb` contexts than `standard`'s preference `with_fixed_indentation`. (I _might_ disagree with `standard` here, but I _really_ disagree with them for `erb`.) I don't know if this is deliberate on the part of `standard` -- that is, _maybe_ this is a situation where our preferences really are separate from `standard` -- I don't know if `standard` is aware of `erblint` at all, really.

Technically, it's possible to merge `main` and this branch without significant effort, however, it paints a clear picture that _future_ changes would not be as smooth as we (I) believed when I opened this PR. Whatever my/our individual/pre-existing preference(s), with the additional experience applying these style changes to a larger sample of our code, it is clear now that the proposed change to `standard` _likely would_ require more significantly more ongoing manual intervention than I had previously estimated, and more than I think I can defend as a worthwhile investment of our resources at this time. 

In particular, knowing that we are spinning up work internally to address code style as part of paying down technical debt, I now think additional effort necessary to converge on `standard` would be better spent in other ways.

**Pull request closed without merging**
