### PR TITLE
Remove input scroll from position

### LINKED ISSUE #13513: Long comments with @-mentions cause rendering issues
**Describe the bug**

The @-mention autocomplete component does not render in the correct location when typing a long comment and using an @-mention further "down" in the comment.

**To Reproduce**

1. Go to a Forem, and type a comment. Input enough text in the comment such that it is "long" enough to trigger the scroll bar on the side.
2. Towards the bottom of the comment's text, @-mention any user; in the process of typing the @-mention, you'll notice the the list of users renders significantly _below_ the comment's input box, and not near where your cursor is.

Some examples of this occurring:
*On DEV:*
Screen Shot 2021-04-26 at 9 23 42 AM

*On Forem.team:*
Screen Shot 2021-04-26 at 9 19 33 AM
Screen Shot 2021-04-26 at 9 21 40 AM

**Expected behavior**

The expected behavior would be that the layout/location of the @-mention list of suggested users appears directly below the cursor, just as it does for "short comments", like this:

Screen Shot 2021-04-26 at 9 28 40 AM

**Desktop (please complete the following information):**

- Browser, version: Chrome 90.0.4430.85

### PR DESCRIPTION
**Pull request by Link2Twenty**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
When an input has a scroll we remove its position from the overall position putting the mention popover in the right place

## Related Tickets & Documents
closes #13513

## QA Instructions, Screenshots, Recordings

comment
post

### UI accessibility concerns?
N/A

## Added tests?

- [ ] Yes
- [x] No, and this is why:  existing tests will still work
- [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?
N/A

## [optional] What gif best describes this PR or how it makes you feel?

Doctor who pops his head over a wall appearing all sweaty

As a side note I finally installed a local copy of forem rather than just winging it 😅

### CODE REVIEW

**Comment by Link2Twenty** [comment]
As another aside ddtrace 0.48.0 doesn't work, I had to force downgrade to 0.47.0 to get the forem setup to work

**Comment by rhymes** [comment]
@Link2Twenty sorry about that, we eventually reverted to 0.47 https://github.com/forem/forem/pull/13570

**Comment by Link2Twenty** [comment]
> @Link2Twenty sorry about that, we eventually reverted to 0.47 #13570

It's alright, most of my debugging time was spent trying to work out what I did wrong, once I realised it wasn't my fault it was an easy fix 😅

**Comment by Link2Twenty** [comment]
I don't think the Travis fail is me, can someone verify?

**Comment by rhymes** [comment]
@Link2Twenty re-ran Travis!

**Review by rhymes — APPROVED** [review]
LGTM!

**Review by aitchiss — APPROVED** [review]
Nice one! Thanks for taking this on - looks great to me ✨

**Comment by cmgorton** [comment]
Thanks for taking the time to work on this @Link2Twenty !

**Pull request merged**
