### PR TITLE
Revert "Remove mascot from JS template for modals (#11388)"

### PR DESCRIPTION
**Pull request by rhymes**
This reverts commit f8f3795b88436f67ca714d5088aee3a6969dd091.

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Me and @maestromac confirmed it was something "only on my machine" and we couldn't reproduce it, so this should go back to normal

### CODE REVIEW

**Review by maestromac — APPROVED** [review]
LGTM!

We would like more people to try to boot this up locally to verify that it is working without throwing any site_config related warnings.

**Comment by joshpuetz** [comment]
Works/boots just fine locally for me!

**Review by joshpuetz — APPROVED** [review]

**Review by juliannatetreault — APPROVED** [review]
Tested this out and the images loaded as expected -- works for me! 🚀

**Comment by atsmith813** [comment]
`bin/startup` doesn't work for me, but `rails s` works

**Comment by rhymes** [comment]
@atsmith813 what error do you get ? I tried with `/bin/startup` and it worked. Then I had an idea: calling clear cache on site config and booting it up again to see if maybe it was that's the reason it was working but still no issues anymore. Mmm

**Comment by joshpuetz** [comment]
I should clarify I ran locally with `overmind start -f Procfile.dev`

**Comment by atsmith813** [comment]
Screen Shot 2020-11-12 at 11 05 59 AM

cc: @rhymes

**Comment by maestromac** [comment]
I also used hivemind but I double checked with `bin/rails server`

**Comment by rhymes** [comment]
@atsmith813 mmm weird, can you run bin/setup and then bin/startup?

**Review by benhalpern — CHANGES_REQUESTED** [review]
This will, indeed, not work because for Forem Cloud, assets are compiled outside of the container so we can't use anything that relies on the database or even environment variables.

**Comment by vaidehijoshi** [comment]
> This will, indeed, not work because for Forem Cloud, assets are compiled outside of the container so we can't use anything that relies on the database or even environment variables.

Hm, if this is the case, then we need to rethink all of the "default" images that we are adding to `SiteConfig` then, potentially? If we access them through `SiteConfig`, then we're accessing the DB, and if we can't access them from SiteConfig, maybe it doesn't make sense to define the defaults in there.

**Comment by benhalpern** [comment]
@vaidehijoshi do any of those images need to be referenced within JavaScript files in a way that where they can't be passed in HTML via `data` params?

**Comment by vaidehijoshi** [comment]
> @vaidehijoshi do any of those images need to be referenced within JavaScript files in a way that where they can't be passed in HTML via `data` params?

Hm, I'm not immediately sure! It just seems annoying/a potential pain point down the road that we won't be able to use these image files that exist in our DB in any other way, so I just wanted to flag it as a downside of our "put default images in the SiteConfig" approach. I was just pondering if there was a better/another place to put those default assets......but I suppose fetching it from JS is ok given the constraint of where the assets are compiled 🤷

**Comment by rhymes** [comment]
I'm going to close this, I kept a record of what we could do and opened an issue in https://github.com/forem/forem/issues/11492

**Pull request closed without merging**
