### PR TITLE
Add `Edit Profile Image` option to Onboarding

### LINKED ISSUE #19497: Update profile image as part of onboarding
## Is this feature related to a problem? Please describe.

As a new user, I should be prompted to set my profile image as part of onboarding, so I can present part of my online identity to other users as soon as possible and be motivated to invest further in the community.

## Describe the solution you’d like

* Where the profile image can be obtained from the Authentication Provider, we set the user's image as part of their account.
* Within `/onboarding`, as part of the 'Build your profile' step, we should allow users to update and upload a new profile image separate from the one they've used with their Authentication Provider.
* ~We should make this step mandatory in the instances that (for whatever reason) we can't get the user's profile image from the Authentication Provider.~
* The fallback option to provide a default profile image for users is triggered before this onboarding step, so we know users will be given the option to update (and override) the stock image.

| Without edit option ❌ | With edit option ✅ |
| ------ | ------ |
| Before | Image uploaded |

Checkouy this **[Figma link](https://www.figma.com/file/u7VcNG4pjbn7K01V8JrFWo/Member-Onboarding-Process?type=design&node-id=2479-20052&t=XB2rYCXGZ4ATKxFR-4)**.

## Definition of Done

- [ ] Able to edit the profile image as part of the onboarding step, being able to upload a new image
- [ ] Sensible limits are set on the profile image upload control (formats and file sizes)

## Additional Context

* image
*Screenshot of the 'Build your profile' step in onboarding*

### PR DESCRIPTION
**Pull request by rt4914**
## What type of PR is this? (check all applicable)

- [x] Feature

## Description

Currently onboarding process does not have `Edit Profile Image` option. This PR introduces that option with current limtation.

## Related Tickets & Documents

- Closes #19497

## QA Instructions, Screenshots, Recordings

1. Visit `/onboarding` on localhost or Uffizzi. (http://localhost:3000/onboarding)
2. Follow the process and notice the `Edit Profile Image` option. Select image and update the profile image from here directly.

| Before | After |
| ------ | ------ |
| Before | Image uploaded |

**Output on mobile devices:**

https://github.com/forem/forem/assets/9396084/5146b690-072f-4e6c-b795-2d8fc2434d58

https://github.com/forem/forem/assets/9396084/da347be4-1e82-47f5-812e-42ea68f68773

**Light mode and Dark Mode**
| Light Mode  | Dark Mode |
| ------------- | ------------- |
| Screenshot 2023-06-14 at 12 36 56 PM | Screenshot 2023-06-14 at 12 36 39 PM |
| Screenshot 2023-06-14 at 12 37 07 PM | Screenshot 2023-06-14 at 12 36 30 PM |

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [x] Semantic HTML implemented? Yes
- [x] Keyboard operability supported? Yes
- [x] Checked with [axe DevTools](https://www.deque.com/axe/) and addressed `Critical` and `Serious` issues? Yes, 0 issues.
- [x] Color contrast tested? Yes

Screenshot 2023-06-14 at 9 24 45 PM

_For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [x] Yes

### CODE REVIEW

**Comment by rt4914** [comment]
@anujbhavsar96 I have kept the button design similar to what we are using in settings page but do let me know if I need to change it. And if so, please share the dark-mode design for that button too. Thanks. Otherwise this PR is ready for your review.

**Comment by anujbhavsar96** [comment]
@rt4914 We can use the same button style as we have for profile image in `/settings/profile`
Screenshot 2023-06-15 at 5 59 44 PM


And another small suggestion is to display an error message below the button. So it doesn't break layout.
Screenshot 2023-06-15 at 6 04 14 PM

**Comment by rt4914** [comment]
> @rt4914 I'm getting this in the console on that slide:
> 
> Screenshot 2023-06-22 at 10 45 18 AM

Thanks @benhalpern ! I have fixed these errors and added relevant tests too. I have added placeholder strings based on what we have in `/settings` page.

**Comment by rt4914** [comment]
@anujbhavsar96 I have applied the suggested changes. Thanks.

Screenshot 2023-06-22 at 5 18 47 PM

**Comment by klardotsh** [comment]
This seems like something I probably shouldn't be a reviewer of; untagged myself but please ping me if it's a false-negative and I really should be reviewing this (and if so, hint at how!)

**Comment by anujbhavsar96** [comment]
@rt4914 design looks good✨ but getting this error while changing the image

image

**Comment by rt4914** [comment]
> @rt4914 design looks good✨ but getting this error while changing the image
> 
> image

Discussed this with @anujbhavsar96 
Mostly some Uffizzi or previous build related issue. It is working correctly now on Uffizzi as well as locally.

**Review by anujbhavsar96 — APPROVED** [review]
🚀

**Review by jaw6 — APPROVED** [review]

**Comment by rt4914** [comment]
Thanks @jaw6 for additional review.

**Pull request merged**
