### PR TITLE
Setup pg_search

### PR DESCRIPTION
**Pull request by atsmith813**
## What type of PR is this? (check all applicable)
- [x] Feature

## Description
_Please do **not** merge this until @rhymes has had a chance to check this out and approve it. It helps our workflow to stay in sync right now :100:_

This PR does 2 things:
1. Adds the `pg_search` gem
2. Adds the necessary PostgreSQL Extensions

## Related Tickets & Documents
closes https://github.com/forem/forem/issues/12903
closes https://github.com/forem/forem/issues/12904
[RFC](https://github.com/forem/rfcs/pull/153)

## Added tests?
- [x] No, and this is why: N/A - we don't test for gems or PostgreSQL extensions

## [Forem core team only] How will this change be communicated?
- [x] This change does not need to be communicated, and this is why not: this is just adding some dependencies to set us up for more PRs to follow.

thats_the_plan_gif

### CODE REVIEW

**Review by Zhao-Andy — APPROVED** [review]
LGTM, bundled and migrated successfully 👍

**Review by maestromac — APPROVED** [review]
:+1: :+1:

**Review by jgaskins — COMMENTED** [review]
I haven't used this gem before and I'm admittedly wary of adding dependencies without understanding their benefits, so mainly I'm asking out of curiosity: what benefit does this gem offer over plain AR?

**Comment by atsmith813** [comment]
@jgaskins check out the [RFC](https://github.com/forem/rfcs/blob/5ebd5c84992bd595cb588dad9f6dc3056cc8aee0/text/0153-search-2.0.md) for more details. This gem is a more friendly interface to FTS using Postgres. We're dropping ElasticSearch in favor of PostgreSQL for search.

**Comment by jgaskins** [comment]
@atsmith813 To be clear, I did read the gem's documentation and I was aware of the move away from ElasticSearch 😃 The gem seems to offer a lot of flexibility in search, but do we _need_ that flexibility up front? Is there any reason this wouldn't work?

```ruby
module FullTextSearchable
  extend ActiveSupport::Concern

  module ClassMethods
    def full_text_search(text)
      where("to_tsquery(language, body) @@ to_tsvector(language, ?)", text)
    end
  end
end
```

**Comment by atsmith813** [comment]
@jgaskins Nope! I don't believe there's a reason that wouldn't work.

@rhymes and @citizen428 could probably explain in greater detail. I put it here because that's what we agreed on in the [spike](https://github.com/forem/forem/pull/11985) and the [RFC](https://github.com/forem/rfcs/blob/5ebd5c84992bd595cb588dad9f6dc3056cc8aee0/text/0153-search-2.0.md).

From what I understand, the gem makes the interface a little more readable and "easier" to understand. It also offers a few handy helpers like rebuilding search documents. It also lets us do things like this easily:

```ruby
# additional scopes and regular AR methods can be used
> Tag.search_by_name("ja").order(hotness_score: :desc).page(2).per(1)
```

**Comment by atsmith813** [comment]
@jgaskins also, I believe some of the thinking here was from the findings of the spike as well which is that we'll be pushing the limits of FTS so it would be nice to start with this flexibility since we've already found ourselves at the edge in some ways.

**Review by citizen428 — APPROVED** [review]

**Comment by rhymes** [comment]
Hi @jgaskins! Good observation. I think it's worth adding a gem in this case.

In addition to what @atsmith813 said, an advantage of using this gem over using `to_tsquery` manually is the ability to use both FTS and similarity searches.

The gem also constructs a simple declarative API for multi column FTS, to assign weights on those columns, to do prefix and negation searches, to use FTS dictionaries, to use normalization, highlighting, ranking, to use `tsvector` columns for faster search (in case we want to explore that with triggers) and more.

We can do all that manually with PostgreSQL but we'd eventually, essentially, rebuild the gem, so I think it's worth integrating it in this case. The gem's code's complexity also seems within our collective knowledge's reach: https://github.com/Casecommons/pg_search/blob/59529cd64592343bb3197e3a706fda90edc53543/lib/pg_search/features/tsearch.rb

For more information on features you can check: https://github.com/Casecommons/pg_search#pg_search_scope

**Review by rhymes — APPROVED** [review]

**Comment by jgaskins** [comment]
@rhymes @atsmith813 All fantastic points! Thanks! 👍🏼

**Pull request merged**
