### PR TITLE
Don't modify environment global in tests

### PR DESCRIPTION
**Pull request by djuber**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

The ENV constant is a process global variable. Modifying it during
example execution is something we can avoid, and prevents unwanted
interaction between test cases.

Pass 1 excludes the registrations controller (there are a number of
sequential modifications to the FOREM_OWNER_SECRET env var there, that warrant
creating a helper for this).

## QA Instructions, Screenshots, Recordings

Tests should pass (test only change).

### UI accessibility concerns?

None

## Added/updated tests?

- [x] Yes

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [x] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

### CODE REVIEW

**Comment by djuber** [comment]
oh hi!

Does anyone have a good idea about the right way to do this? 

I considered:

- example metadata that creates the before block with the right mappings and runs the example (I dislike this API in practice, but it works)

- an EnvironmentHelper module that provides a stub_env(var, value) method that adds the two allow lines (one to call original, one to specify this value)

- something like this (wrapping the existing environment with a provided var=>value mappings): `stub_const("ENV"), ENV.merge(**mappings))`

I'm leaning toward the latter stub_const pattern, unless we're asserting that ENV received `#[]`, as the cleanest.

**Comment by jeremyf** [comment]
Here's what I would hope to see:  a consistent mechanism to stub and ENV value and a clear nope behavior otherwise (as in we collectively agree to not do this OR we "freeze" ENV before suite).

So I could have `before { stub_ENV(key: value) }` and for our purposes that test would return that value.  I will add that this is one reason that I like using the Figaro gem.  It wraps ENV in a great way and from there on out you call `Figaro.env` (or something like that).

**Comment by djuber** [comment]
Thanks, @jeremyf for the hint about the shape of the api (and the social contract around only using that). Yes, I was looking for a `stub_ENV(mappings)`, and toying with the right way to do this so that it's _also_ safe if I nest it (between a surrounding context and a specific example, I think the `and_call_original` in the `allow to receive` pattern breaks that. 

Let me freeze ENV before suite and see what falls down (I know the requests/registrations is a bit tricky because we change things a number of times and we probably rely on ordering there, I expected I got the rest of these).

**Comment by djuber** [comment]
TIL

```
An error occurred in a `before(:suite)` hook.
Failure/Error: ENV.freeze

TypeError:
  cannot freeze ENV
# ./spec/rails_helper.rb:110:in `freeze'
# ./spec/rails_helper.rb:110:in `block (2 levels) in <top (required)>'
```

**Comment by djuber** [comment]
Marking ready for review at this point (it uses a common pattern, without having codified it).

**Review by maestromac — APPROVED** [review]

**Review by joshpuetz — APPROVED** [review]

**Pull request merged**
