### PR TITLE
Sidebar: social media icons + spacing

### PR DESCRIPTION
**Pull request by Ridhwana**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Remove extra space + add back social media icons.

## Related Tickets & Documents
https://github.com/forem/forem/issues/10980#issuecomment-713418826

## QA Instructions, Screenshots, Recordings

Screenshot 2020-10-21 at 11 03 18

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Review by rhymes — APPROVED** [review]

**Review by ludwiczakpawel — APPROVED** [review]

**Comment by ludwiczakpawel** [comment]
@Ridhwana  Oh I've just realized social icons won't be accessible if site has < 5 navigation links, right?

**Comment by Ridhwana** [comment]
Yes that is correct. Do you have a potential design solution to this?

**Comment by ludwiczakpawel** [comment]
@Ridhwana Not really 🤷‍♂️ Quick idea from top of my head (but that's likely not ideal either):

```
<% if NavigationLink.all.length > 5 %>
replace with
<% if NavigationLink.all.length > 5 ||  are_there_any_social_media_assigned? %>
```

**Comment by Ridhwana** [comment]
Seems like a solution would be:

If there is less than 5 items then just pop the social media icons below the items. 
If there is greater than 5 items pop the social media icons in the more section.

what do you think?

**Pull request merged**
