### PR TITLE
Remove API docs packages ✂️ ✂️ ✂️ 

### PR DESCRIPTION
**Pull request by rhymes**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

After https://github.com/forem/forem/pull/14579 was merged, some packages used to validate and build the HTTP and Ruby APIs were left behind

## Related Tickets & Documents

https://github.com/forem/forem/pull/14579

### CODE REVIEW

**Review by Zhao-Andy — APPROVED** [review]
Good catch, thanks!

**Review by nickytonline — APPROVED** [review]

**Comment by nickytonline** [comment]
✂️✂️✂️✂️✂️

**Comment by nickytonline** [comment]
Some yarn.lock file conflicts to sort out @rhymes and then this is good to go.

**Review by Ridhwana — APPROVED** [review]
✂️✂️✂️

**Pull request merged**
