### PR TITLE
Multiple Reactions icons stack fix

### LINKED ISSUE #19137: Leftmost icon should be on top when there are multiple, stacked reactions on Index page
In below image, the icons are in form of stack and the right most icon is on top but instead the leftmost icon should be on top and right most icon should be at bottom.

Image

^ This happens on index page view and is blocked by [#19135](https://github.com/forem/forem/issues/19135)

### PR DESCRIPTION
**Pull request by rt4914**
## What type of PR is this? (check all applicable)

- [x] Optimization

## Description
In below image, the icons are in form of stack and the right most icon is on top but instead the leftmost icon should be on top and right most icon should be at bottom.

Image

^ This happens on index page view and is blocked by [#19135](https://github.com/forem/forem/issues/19135)

## Related Tickets & Documents

- Closes #19137

## QA Instructions, Screenshots, Recordings

| Before  | After |
| ------------- | ------------- |
| Screenshot 2023-02-20 at 6 58 50 PM | Screenshot 2023-02-20 at 6 58 03 PM |
| Screenshot 2023-02-20 at 6 58 36 PM | Screenshot 2023-02-20 at 6 58 13 PM | 

### UI accessibility concerns?

No

## Added/updated tests?

- [x] No

## [Forem core team only] How will this change be communicated?

- [x] This change does not need to be communicated

### CODE REVIEW

**Review by jaw6 — APPROVED** [review]
We will want to be careful with this and #19142. Probably this should merge first, then I can update #19142 so that we can revert it cleanly in the future.

**Comment by jaw6** [comment]
For me, what I have prior to this PR (`main`):
Screen Shot 2023-02-20 at 16 37 57

With this branch:
Screen Shot 2023-02-20 at 16 43 13

**Comment by rt4914** [comment]
> For me, what I have prior to this PR (`main`): Screen Shot 2023-02-20 at 16 37 57
> 
> With this branch: Screen Shot 2023-02-20 at 16 43 13

@jaw6 I just tried on latest main again and I am issue able to see the issue. 
I am checking this on user's own profile like http://localhost:3000/admin_mcadmin

**Comment by mirie** [comment]
Discussed with @benhalpern and @pkfrank: this does NOT need to block launch, and can even go post-launch. 
Going to merge https://github.com/forem/forem/pull/19142 as this is approved and _IS needed for launch_.

**Comment by anujbhavsar96** [comment]
@rt4914 One minor thing I noticed here is that icons need to be center aligned to the bg circle. Approving this, but we can look into this later.

**Not center aligned**
image

**Center aligned**
image

**Review by anujbhavsar96 — APPROVED** [review]
🚀

**Comment by rt4914** [comment]
> @rt4914 One minor thing I noticed here is that icons need to be center aligned to the bg circle. Approving this, but we can look into this later.
> 
> **Not center aligned** image
> 
> **Center aligned** image

@anujbhavsar96 I have fixed it by adding a negative margin at top to shift the icon upwards.
Screenshot 2023-02-21 at 1 51 05 PM

**Pull request merged**
