### PR TITLE
fix: tool editor disappears when dragging words #20270

### LINKED ISSUE #20270: tool editor disappears when dragging words
**Describe the bug**

A small bug when trying to drag words from the editor but still remaining within the editor, the opacity of the tools will decrease and not return, a while ago I discovered this by doing the drag event unconsciously so I didn't understand why this happened, today I found it again and I think It can be annoying for other users too.

**To Reproduce**

1. Go to create new post;
2. Write something in the body of the article;
3. Drag the words anywhere within the body of the article.

**Expected behavior**

The tools editors appear again.

**Screenshots**

forem

**Desktop (please complete the following information):**

- OS, version: Manjaro 
- Browser, version: Brave

### PR DESCRIPTION
**Pull request by Lucasm4sco**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

just adding the ondragend event to the element

## Related Tickets & Documents

- Related Issue #20270
- Closes #20270

_For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## [optional] Are there any post deployment tasks we need to perform?

i believe it's not necessary

## Added/updated tests?

- [x] Yes
- [ ] No, and this is why: __
- [ ]  I need help with writing tests

## [optional] What gif best describes this PR or how it makes you feel?

a little shy

### CODE REVIEW

**Review by lightalloy — APPROVED** [review]
Thanks for the pr, looks good to me.

**Comment by Lucasm4sco** [comment]
lol, I'm not very familiar with testing, should I do anything?

**Comment by lightalloy** [comment]
@Lucasm4sco sorry for the delay, initially the failures themselves were not displayed on the CI, so it was not clear what's failing, and we were figuring out the details.

Displaying jest failures was fixed in #20281 , so currently they are visible on the CI.
There is a number of tests failing in `app/javascript/utilities/__tests__/dragAndDrop.test.js`
You can see the fails on CI [the build](https://github.com/forem/forem/actions/runs/6658875526/job/18096723289?pr=20271)  or locally by running 
```
yarn run jest app/javascript/utilities/__tests__/dragAndDrop.test.js
```
Could you adjust the tests or do you need help?

**Comment by Lucasm4sco** [comment]
OK, thanks for the answer @lightalloy :), I made the changes related to these tests and added them to a commit in this PR

**Pull request merged**
