### PR TITLE
Update the UI for Low-Quality-Comments Notice

### PR DESCRIPTION
**Pull request by msarit**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [X] UI Update

## Description
Updates the notice that appears above comments that have been flagged as `low-quality` by the forem's community. The updated UI is designed to clearly communicate the the forem's admins do not support such low-quality content, or allow its propagation through the forem. See [this diagram](https://user-images.githubusercontent.com/816402/108918129-b9cb4880-75e5-11eb-84aa-2688013496c6.jpg) for more context.

## Related Tickets & Documents
closes https://github.com/forem/forem/issues/12751

## QA Instructions, Screenshots, Recordings
1. Login to `localhost` as a `trusted` user. Navigate to an article's comment. Click on the three-dot icon in the top-right corner of the comment. Click on `Moderate`
2. Choose the `Flag To Admins` option in order to downgrade the comment's quality rating past the `-100` mark, to trigger the low-quality notice.
3. Go back to the article page and refresh. You should observe the following:
- The comment has moved lower in the comment list.
- There is a yellow `crayons-warning` notice with an explanation and a link to the Code of Conduct.
- The comment text has been slightly greyed out.

Please see a Loom video below demonstrating these steps 🙏🏾 
https://www.loom.com/share/1251ede2f8904939961d0cc712587072

### UI accessibility concerns?

This PR does not introduce any accessibility concerns; the notice's design leverages our Crayons design system, which has already been properly vetted.

## Added tests?

- [X] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [X] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] Are there any post deployment tasks we need to perform?
None

## [optional] What gif best describes this PR or how it makes you feel?

South Park GIF

### CODE REVIEW

**Review by aitchiss — COMMENTED** [review]
I tried following the testing steps but I'm not seeing the low quality UI - is there something I'm missing (I'm not super familiar with this part of the app so it's probably just me 😆 )? This is what I'm doing:

https://user-images.githubusercontent.com/20773163/110619464-c1672180-818f-11eb-8142-d3795c467e17.mp4

**Comment by msarit** [comment]
> I tried following the testing steps but I'm not seeing the low quality UI
Hmmmm @aitchiss that is strange indeed! 🤔  Let me circle back to you on this, thanks!

**Review by rhymes — COMMENTED** [review]
It didn't work for me either but I think it's not related to your PR per se, as your PR touches CSS and HTML templates.

I checked the score of the comment and it's not `-100`, so that's likely why it won't show the comment.

I'll investigate 🕵️ 

**update**

When "flag to admins" is invoked, I only see a vomit reaction created, but the score is untouched by https://github.com/forem/forem/blob/cc2b76f7e43f33e15f5cdf84d8d8665188a0c607/app/controllers/reactions_controller.rb#L54

I can see it if I force `comment.save!` in the console, but I can't see it after I flag it to admins. Following the thread, I can see the comment's score is updated in 

https://github.com/forem/forem/blob/cc2b76f7e43f33e15f5cdf84d8d8665188a0c607/app/models/comment.rb#L56

I can't find a place in the `ReactionsController` where we trigger `comment.update` or `.save`, thus I think that's why we can't see the yellow box. The comment's `calculate_score` callback invokes the job `Comments::CalculateScoreWorker` so I tried to find if we call that elsewhere and I couldn't.

So I'm left to wonder, is this feature actually working on in production? Again, the `ReactionsController` aside from creating reactions doesn't seem to invoke any method directly or indirectly on its `comment`.

I'll keep investigating

**Review by rhymes — COMMENTED** [review]
I am not totally sure how, but after restarting the app, the flag started working consistently and I can see the yellow box, in the article's page and in the comment index page.

When the article is deleted the page breaks though, with `You may not use current_user in this cached code path`

Any ideas?

cc @Zhao-Andy

**Comment by lisasy** [comment]
> I tried following the testing steps but I'm not seeing the low quality UI - is there something I'm missing (I'm not super familiar with this part of the app so it's probably just me 😆 )? This is what I'm doing:
> CleanShot.2021-03-10.at.10.56.26.mp4

I can also echo having a similar issue here; I can't see the yellow UI box either, yet :(

**Comment by msarit** [comment]
I'm still investigating the problems surfaced in the reviews of this PR [here](https://github.com/forem/forem/pull/12952#pullrequestreview-608583806) and [here](https://github.com/forem/forem/pull/12952#issuecomment-796029653).

**Review by rhymes — APPROVED** [review]
Ok I think I have some more clarity about how the moderation feature works.

I tested this on `master` as a baseline. It's a bit convoluted but:

- the "flag to admins" button is pressed
- a HTTP call is fired as `POST /reactions`

https://github.com/forem/forem/blob/c0ea4e58787a1142ddb952fdbe2709f177158ec0/app/javascript/actionsPanel/actionsPanel.js#L71-L74

- a new vomit reaction attached to the comment is created

https://github.com/forem/forem/blob/c0ea4e58787a1142ddb952fdbe2709f177158ec0/app/controllers/reactions_controller.rb#L79-L81

- this will trigger a callback in the `Reaction` model, called `updated_reactable`

https://github.com/forem/forem/blob/c0ea4e58787a1142ddb952fdbe2709f177158ec0/app/models/reaction.rb#L40

- this callback will fire off an async worker, `Reactions::UpdateRelevantScoresWorker`

https://github.com/forem/forem/blob/c0ea4e58787a1142ddb952fdbe2709f177158ec0/app/models/reaction.rb#L92-L94

- `Reactions::UpdateRelevantScoresWorker` (high priority) gets picked by the queue and calls `.touch_by_reaction` on the comment:

https://github.com/forem/forem/blob/c0ea4e58787a1142ddb952fdbe2709f177158ec0/app/workers/reactions/update_relevant_scores_worker.rb#L11

- `touch_by_reaction` is aliased to `save` for comments:

https://github.com/forem/forem/blob/c0ea4e58787a1142ddb952fdbe2709f177158ec0/app/models/comment.rb#L69

- calling `comment.save` will trigger the callback `:calculate_score`

https://github.com/forem/forem/blob/c0ea4e58787a1142ddb952fdbe2709f177158ec0/app/models/comment.rb#L60

- this will in turn call `Comments::CalculateScoreWorker`

https://github.com/forem/forem/blob/c0ea4e58787a1142ddb952fdbe2709f177158ec0/app/models/comment.rb#L198-L200

- `Comments::CalculateScoreWorker` (medium priority) uses an algorithm to recompute the score and save it in the column (bypassing the callbacks, otherwise it'd be an endless loop)

https://github.com/forem/forem/blob/c0ea4e58787a1142ddb952fdbe2709f177158ec0/app/workers/comments/calculate_score_worker.rb#L11-L14

I then chose a comment, pressed the "flag to admins" button, waited a bit and checked if the score was updated, as it was. 

I went from a score of `0` to a score of `-100`. I then refreshed the page of the comment and there the old notice was in all of its glory:

mod_master

I then tested again with this branch three times and it worked as expected by @msarit 

mod_branch

Given this branch is only presentational code, I am going to accept it as it is even if I'm not 100% sure why it wasn't working for me before and it is now (which also applied to master BTW)

For the other reviewers: please try on `master` also to see if you have the same issue.

cc @lisasy @aitchiss

**Review by aitchiss — APPROVED** [review]
Thanks for the detail on how this all works @rhymes! I got this working now and from what I can tell, each user I flagged a comment with resulted in a -50 drop in points rather than 100 (if I'm reading the logs correctly). So I was able to get this working by just logging in as a different user and flagging the same comments 😄 

Looking great @msarit 🚀

**Review by Zhao-Andy — COMMENTED** [review]
Hi, sorry I should have hopped in here earlier to clear the confusion -- as @rhymes pointed out, you'll need background jobs running to see the comment as low quality after vomiting on it. Looks like you all got it working though! 😁 

Not to nitpick but I think it does look a little different than the design @lisasy had in the issue: https://user-images.githubusercontent.com/816402/108918129-b9cb4880-75e5-11eb-84aa-2688013496c6.jpg

The current implementation is like so: 

Screen Shot 2021-03-12 at 9 47 46 AM

Namely, the yellow notice in the design is outside the comment box, whereas the implementation is inside. However I think with the proposed design it might get a bit confusing about which comment the `notice` is displaying the warning for. Here's an example of me playing around with how the design might look with multiple comments of varying depths (not inline because it's a long screenshot):
https://user-images.githubusercontent.com/17884966/110957668-d5d72580-8319-11eb-9dc0-e5c9a2a44b97.png

IMO something similar to @msarit's implementation is probably a bit easier to see which comment the notice is attached to. Any thoughts @lisasy?

**Comment by msarit** [comment]
> Not to nitpick but I think it does look a little different than the design @lisasy had in the issue: https://user-images.githubusercontent.com/816402/108918129-b9cb4880-75e5-11eb-84aa-2688013496c6.jpg

Hey @Zhao-Andy! I totally agree with your observations; I felt that, in the design, the notice seemed too removed from the associated comment. However, I realize that I made a product judgement-call that I probably should have checked in with @lisasy first 🙈 

So I'm checking in now 😄

**Comment by lisasy** [comment]
@msarit this looks pretty good to me — ship it!

**Review by lisasy — APPROVED** [review]
LGTM — ship it!

**Pull request merged**
