### PR TITLE
Remove cache headers from sidebars controller

### PR DESCRIPTION
**Pull request by benhalpern**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This removes edge cache headers from sidebars controller (which only is called for signed-in contexts) — we still have some fragment caching in place.

## Related Tickets & Documents

- Closes https://github.com/forem/forem/issues/20001

## QA Instructions, Screenshots, Recordings

This should be pretty straightforward.

_For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [x] Yes — small adjustment

### CODE REVIEW

**Comment by Ridhwana** [comment]
@benhalpern our of curiosity why are we removing the edge caching on the sidebar controlling?

**Comment by benhalpern** [comment]
@Ridhwana sorry I should have made that more clear in the issue.

The current sidebar is rendered async for signed in users, so edge caching is not _necessary_. Of course we still might want it to ensure the snappiest possible response, however it is limiting our capacity to make tweaks which might be much more straightforward without this caching.

I will provide some follow up issues relating to some tweaks to customize the experience, but I saw first starting with this tweak to how it's rendered as a simplifying first step to a few upcoming tweaks.

**Review by filleduchaos — COMMENTED** [review]
Thanks for the additional reasoning - that makes sense, and I think we could/should also remove `EdgeCache::BustSidebar` as part of this work (or maybe as a follow-up?)

**Comment by benhalpern** [comment]
@filleduchaos Oh yeah, good call. Added those changes to this PR.

**Review by filleduchaos — APPROVED** [review]
🎉

**Pull request merged**
