### PR TITLE
API: Remove Admin Config endpoint ✂️ ✂️ ✂️ ✂️ 

### PR DESCRIPTION
**Pull request by rhymes**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

The current `/api/admin/config` endpoint is broken due to how we changed how config/settings works. We've decided to remove it, see https://github.com/forem/forem/issues/13843#issuecomment-854313973 for further details

## Related Tickets & Documents

https://github.com/forem/forem/issues/13843#issuecomment-854313973

## Added tests?

- [ ] Yes
- [x] No, and this is why: just removing code
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [x] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

### CODE REVIEW

**Review by maestromac — APPROVED** [review]
:scissors:

**Review by jacobherrington — COMMENTED** [review]
This looks like an unrelated CI failure, so I'm restarting the job.

**Comment by rhymes** [comment]
@jacobherrington magic touch! it worked :D

**Review by jacobherrington — APPROVED** [review]
@rhymes :sparkles: Magic!

**Review by jgaskins — APPROVED** [review]

**Review by citizen428 — APPROVED** [review]

**Pull request merged**
