### PR TITLE
Fix nested sidebar active item highlight

### LINKED ISSUE #17240: Menu item isn't highlighted when on a tab
**Describe the bug**

When you first land on `/admin/advanced/tools`, the `Developer Tools` menu item to the left stays highlighted, so you get a sense of where you are in the application. 

However, if you move on to any of the tabs on top (`Vault Secrets`, `Data Update Scripts`, `Extensions`), the highlighted status on the menu item is gone, which causes confusion and disorientation. 

**To Reproduce**

1. Go to `/admin/advanced/tools`
2. Click on any of the tabs on top that you are not currently in (any of `Vault Secrets`, `Data Update Scripts`, `Extensions`)
3. You'll see that highlighted status on the menu button disappear

**Expected behavior**
The `Developer Tool` menu item should stay highlighted, no matter which tab you are on.

**Screenshots**

Screen Shot 2022-04-12 at 3 47 32 PM

Screen Shot 2022-04-12 at 3 46 17 PM

**Desktop (please complete the following information):**

- OS, version: macOS 12.3.1 
- Browser, version: Chrome Version 93.0.4577.63

**Additional context**

This inconsistency was originally discovered by @ellativity.

### LINKED ISSUE #18863: Developer Tools become inactive when clicked on Extensions
**Describe the bug**

Developer Tools become inactive when clicked on Extensions

**To Reproduce**

1. Sign in as admin locally
2. Visit `/admin/advanced/tools`
3. Notice how `Developer Tools` option on left-side-menu is highlighted/active.
4. Now click on `Extensions` tab
5. Notice that `Developer Tools` is not active anymore.

**Expected behavior**

If `Tools` or `Extensions` are selected the `Developer Tools` should remain highlighted.

**Screenshots**

Screenshot 2022-12-15 at 2 13 50 PM

### PR DESCRIPTION
**Pull request by dancristianb**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Related Tickets & Documents

- Related Issue #18863
- Related Issue #17240
- Closes #18863
- Closes #17240

## QA Instructions, Screenshots, Recordings

This PR targets fixing the admin sidebar nested items highlight. 

It was the `Developer Tools / Extensions` tab that originally surfaced the issue, but it looks like the `Content Manager / Badges / Achievements` tab is impacted as well. From what I've checked I think we should be able to use the already existing `AdminMenu#nested_menu_items` method to correctly determine the active menu item entry.

#### Before

Screenshot 2023-01-17 at 18 04 57
Screenshot 2023-01-17 at 18 03 14

#### After

Screenshot 2023-01-17 at 18 05 35
Screenshot 2023-01-17 at 18 04 11

### UI accessibility concerns?

~_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._~

## Added/updated tests?

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

~## [optional] Are there any post deployment tasks we need to perform?~

## [optional] What gif best describes this PR or how it makes you feel?

Alt text

### CODE REVIEW

**Review by rt4914 — COMMENTED** [review]
I have tested this locally and it does work fine. Thanks @dancristianb

**Comment by dancristianb** [comment]
> Also tested locally and works great. Thank you for this @dancristianb!

@fdocr thanks the review! 🙏 

> One request for change though: Would you mind applying the rubocop failure suggestions for consistency? You can find them [as inline comments](https://github.com/forem/forem/pull/18973/files)

Oooh missed that! Sure thing, I'll send out the updates!

**Comment by dancristianb** [comment]
Hmm I think the updates from this PR should also close #17240, right? 🤔

**Review by fdocr — APPROVED** [review]
Thanks @dancristianb! LGTM

Sorry, misclicked on "update branch" while approving CI run but that shouldn't have any effects.

> Hmm I think the updates from this PR should also close https://github.com/forem/forem/issues/17240, right? 🤔

I agree, that one will be closed with this PR too

**Review by Ridhwana — APPROVED** [review]

**Review by jaw6 — APPROVED** [review]
Looks good to me :+1:

**Pull request merged**
