### PR TITLE
Fix infinite redirect loop for articles

### PR DESCRIPTION
**Pull request by citizen428**
## What type of PR is this? (check all applicable)

- [X] Bug Fix

## Description

The original issue described a redirect loop and suspected that this is related to the interaction of `username`, `old_username`, and `old_old_username`. However, my investigation led me down a different path and I provided a detailed explanation in [this comment](https://github.com/forem/forem/issues/12444#issuecomment-777197399). I'll only share the tl;dr here:

> 1. This only seems to happen to articles that belong to organizations but are accessed via the author's slug.
> 2. I'm not yet sure if the best possible fix is the one regarding `old_username` and `old_old_username` described in the original issue or if we want to update the logic in `StoriesController#show` instead.

By making the article part of an organization I was able to reproduce the redirect loop.

After digging a bit deeper into the code I'm now convinced that this isn't really related to the usernames (as soon as we redirect correctly the `if` condition in `StoriesController#show` should take care of this), so instead I just rearranged the logic in the `handle_possible_redirect` method as follows:

1. Check for the existence of an organization first.
2. If an organization exists, permanently redirect to the article's `path`. This path takes organizations into account, thanks to `Article#calculated_path` (which gets used in the `set_caches` `before_save` action).

This resolved the redirect loop for me.

## Related Tickets & Documents

https://github.com/forem/forem/issues/12444

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

### UI accessibility concerns?

n/a

## Added tests?

- [X] No, and this is why: still struggling with a spec that fails on `master` but is green on this branch.

### CODE REVIEW

**Comment by citizen428** [comment]
Before I add specs for this, can reviewers please do a quick sanity check here?

**Comment by citizen428** [comment]
Re specs: I have a local replication that clearly works:

image

However, I haven't yet managed to turn this into a failing spec, the one I have is green both on `master` and this branch.

**Comment by citizen428** [comment]
I now added the spec that isn't super useful because it's green both on master and this branch. But maybe someone has an idea on what to improve, I may have thought myself into a corner there.

**Review by rhymes — APPROVED** [review]
The logic seems sound to me! 

We can test it in production with the cases in https://github.com/forem/forem/issues/12444#issuecomment-777197399

**Comment by citizen428** [comment]
Thanks, @rhymes, that's what I thought. What should I do with the spec? Since I can't seem to get it to fail, I feel it would be better to just remove it.

**Comment by rhymes** [comment]
@citizen428 would they make sense as regression testing? If somehow we "break" the feature?

**Comment by citizen428** [comment]
@rhymes I'm afraid not quite, which is why I'm asking. If I can't get it to fail now on `master` where things are not right, I don't see how it would guard us against a regression in the future 😢

**Review by benhalpern — APPROVED** [review]

**Comment by benhalpern** [comment]
Approving this as it fixes the issue I had brought up, and will stop the infinite redirect.

1. We look for an article by its path, if we can't find it we search for redirects.
2. By finding the new article _by path_ it should definitely succeed the next time.

... So this should probably get merged as a solution inherently. 

... But in looking more closely at the possible root of the problem, it looks like the problem is that the `path` is not properly being updated on these posts. Looks like the logic in `organization#check_for_slug_change` is not ultimately triggering the updates to effectively complete. So the above solution will just ensure it does go to the place that is, in fact, the current "path", but there is more to learn about the proper proper fix.

**Comment by citizen428** [comment]
@benhalpern Maybe I don't understand, but it seems the paths got updated correctly. They point to the org slug and the problem happens when trying to access the article via the user's slug. But maybe I'm missing something here, this was the first time I got exposed to this logic.

**Pull request merged**
