### PR TITLE
Uncomment import for enabling copying secret code to clipboard.

### LINKED ISSUE #13434: Organization secret code not copied to clipboard
**Describe the bug**

When copying the organization secret code with the special button, it says "Copied to clipboard!" but doesn't work in reality. 

**To Reproduce**

1. Go To Edit Profile 
2. Go to Organization
3. Create an org (or switch to an existing one)
4. Under Grow the team - Your secret code is: --> Copy Button 
image
5. It does not copy the secret code

**Expected behavior**

Clicking on the button just copy the secret code. Or select it if it's not possible to copy. 

**Screenshots**

image
*Not copied in reality

Desktop (please complete the following information):

OS, version: Microsoft, Windows 10
Browser, version: Chrome, latest (88.0.4324.190)

Smartphone (please complete the following information):

Not specific to smartphones.

**Additional context**

I add that we can copy the secret code, just the special button doesn't work.

### PR DESCRIPTION
**Pull request by rafaVls**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This enables copying an organization's secret code by uncommenting the clipboard-copy-element import. 

This fixes #13434. However, this same line was commented out in 2c54add / #6815. The reason given was that it was "causing problems in production"; so I'm not sure if this PR would reintroduce those problems.

## Related Tickets & Documents
#13434 

## Added tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [x] I need help with writing tests

## What gif best describes this PR or how it makes you feel?

Docker whale flying through space while pooping out a rainbow.

### CODE REVIEW

**Comment by nickytonline** [comment]
I don't remember why this was commented out and there isn't enough context in #6815. Do you remember what the issue was @benhalpern?

**Comment by benhalpern** [comment]
@nickytonline here is some context from Slack on that issue. Link: https://forem-team.slack.com/archives/C7GE84DEJ/p1585065230418100


Screen Shot 2021-06-21 at 9 49 15 AM
Screen Shot 2021-06-21 at 9 49 25 AM
Screen Shot 2021-06-21 at 9 49 34 AM

**Comment by rhymes** [comment]
@nickytonline what should we do about this? I don't remember the context either :(

**Comment by aitchiss** [comment]
For what it's worth, I tried following the original bug's test steps a bunch in different browsers and couldn't replicate it in this PR 🤷‍♀️  From the slack convo above, it looks like this was always very intermittent and hard to reproduce.

Instead of relying on this import which _might_ bring back these (impactful) problems, why don't we rework the copy to clipboard feature in this area to not rely on it? We have [a solid example of copy to clipboard functionality in the post share options dropdown](https://github.com/forem/forem/blob/c48e31731df5bf38df4fc508ab08306813dfd82a/app/assets/javascripts/initializers/initializeCommentDropdown.js#L41-L46)

**Comment by citizen428** [comment]
Hi @rafaVls 👋 Thanks for your contribution! I wanted to check in to see if you plan on changing this PR according to @aitchiss suggestion above or if we should close it?

**Comment by rafaVls** [comment]
> Hi @rafaVls 👋 Thanks for your contribution! I wanted to check in to see if you plan on changing this PR according to @aitchiss suggestion above or if we should close it?

Hi! I hadn't noticed the comments, sorry for the delay.

I'll look into it, should I push a new commit or rebase the current one?

**Comment by citizen428** [comment]
> I'll look into it, should I push a new commit or rebase the current one?

Whatever is easiest for you 😃

**Comment by rafaVls** [comment]
Hey @aitchiss !

I understand the functionality of using Runtime.copyToClipboard(), but I'm a bit confused as to where exactly could I implement this for this specific element (I've never worked with ruby before, apologies).

**Comment by aitchiss** [comment]
Hey @rafaVls no worries - it's not super straightforward 😅 

Our admin views use a framework called [StimulusJS](https://stimulus.hotwired.dev/handbook/introduction), this means that behind the view, we can use JS to power some of the interactivity via a controller. I think to hook up the input in the view with the "copy to clipboard" functionality from `Runtime`, we would need to introduce a new controller to do this.

A comparable piece of code that it might be good to look at is the [`image_upload_controller`](https://github.com/forem/forem/blob/0beacb19c954204b19cdca97557237bc11e228c0/app/javascript/admin/controllers/image_upload_controller.js) and how it's used in the [image upload view](https://github.com/forem/forem/blob/086939e7c16863d9fa9b6b8fa75fc3611be6e1c1/app/views/admin/shared/_image_uploader.html.erb).

I'll let you investigate those files for a feel for it, but I think the tasks involved would be:

- Create a new controller for copy to clipboard functionality (in the same folder as the image upload one)
- Add the `data-controller` attribute to the clipboard copy container element in `_org_admin.html.erb` (similar to how this is done in the image upload view linked above)
- Add a function in your new controller that handles the copy button click
- Hook this up to the button in the view with `<button data-action="click->controller-name#handleCopyClick">`

The bonus to this approach is that your new controller code will be able to be reused throughout the admin area as needed ✨ 

Let me know if you have any questions as you go through this - the Stimulus docs I linked above are pretty good, but I know it's not always intuitive!

**Comment by rafaVls** [comment]
Hey y'all! 

I've been having issues getting forem to start on my machine with Docker since I switched to Linux recently. Unfortunately, this means I can't really start the dev server or look at the website, so I'm really sorry but I think it's best if y'all close this PR.

Sorry if I've wasted your time, y'all have been really helpful and patient, and I hope that at least this PR can help someone else fix this issue in the future.

**Comment by aitchiss** [comment]
Hey @rafaVls - absolutely no problem, and thanks for letting us know!

We'd be delighted for you to be able to contribute to the codebase in future though - if this is something you'd still like to do, please do let us know what errors you're running into locally and the team will be able to help you get things unstuck 🙂  

I'll close this PR for now - thanks for your work on this and all the discussions here!

**Pull request closed without merging**
