### PR TITLE
Render op markers for coauthors

### PR DESCRIPTION
**Pull request by jacobherrington**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

We weren't rendering "OP markers" (author identifying flair) on coauthors. This change fixes that!

## Related Tickets & Documents

Closes https://github.com/forem/forem/issues/11128

## Added tests?

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## Added to documentation?

- [ ] Docs.forem.com
- [ ] README
- [x] No documentation needed

### CODE REVIEW

**Review by rhymes — APPROVED** [review]
Should the marker say co-author instead of author?

**QA note for the others**: to test this I had to pick an article, add a coauthor, then load the console, load the coauthor and then `ar.comments.create!(user: tt, body_markdown: "test comment")` where `ar` is the article I added the coauthor for

**Comment by jacobherrington** [comment]
@rhymes Maybe, but I think this is a somewhat urgent request for a community that wants to do a lot of AMAs, so maybe we can go with this for the moment. :smile:

**Review by benhalpern — APPROVED** [review]
lgtm

**Comment by benhalpern** [comment]
@rhymes I also believe the near-term design change will make this into an icon (maybe with a hover tooltip, where we could discuss this language?), cc: @ludwiczakpawel

**Review by juliannatetreault — APPROVED** [review]
Works as expected 👍 👍

**Pull request merged**
