### PR TITLE
Adding cypress retries to e2e

### PR DESCRIPTION
**Pull request by jeremyf**
## What type of PR is this? (check all applicable)

- [x] Optimization

## Description

I submit this for discussion.

In ./bin/e2e we use the `cypress.dev.json` configuration.  The
`cypress.json` configuration has `"retries": 3`.

We have retries for `:flakey` tests: https://github.com/forem/forem/blob/92c8c1a760cb8dc0b872f19efd77ef14d784eed6/spec/rails_helper.rb#L127-L129

Related to forem/forem#14241

## Related Tickets & Documents

None

## QA Instructions, Screenshots, Recordings

None

### UI accessibility concerns?

None

## Added/updated tests?

- [X] No

## [Forem core team only] How will this change be communicated?

- [x] I will share this change internally with the appropriate teams

### CODE REVIEW

**Comment by jeremyf** [comment]
In a twist of irony, it appears this retry doesn't help with flakey tests.

**Comment by djuber** [comment]
I might be misunderstanding the way this works - but this is the dev json config file for local testing?

I would rather we see the flakey tests fail locally rather than retrying automatically

In travis.yml we call bin/knapsack_pro_cypress (which I think uses the default config) - so this only should impact local testing

**Comment by aitchiss** [comment]
> I would rather we see the flakey tests fail locally rather than retrying automatically

Agreed - this is why we only added the retries in the config used by the CI. Locally, we want it to fail fast so we can detect it needs fixed

**Comment by jeremyf** [comment]
Thank you everyone for the context and feedback, I'm going to close this one.

**Pull request closed without merging**
