### PR TITLE
Multiple Reactions: opens drawer on single tap - mobile device

### LINKED ISSUE #19136: Open drawer when user single taps like reaction
On single tap along with like reaction, open the drawer too so that user can see feedback for their action (see https://github.com/forem/forem/issues/19115 for more detail)

### PR DESCRIPTION
**Pull request by rt4914**
## What type of PR is this? (check all applicable)

- [x] Optimization

## Description

Multiple Reactions: opens drawer on single tap - mobile device

This was suggested here: https://www.loom.com/share/da32ca317cf04b3ead07aadabfb161b7
## Related Tickets & Documents

- Closes #19136 #19115

## QA Instructions, Screenshots, Recordings

Have a look at this video to check the output: https://www.loom.com/share/36a11d6356674fcca99709c8b6a8c114

### UI accessibility concerns?

Improves user experience

## Added/updated tests?

- [x] No

## [Forem core team only] How will this change be communicated?

- [x] This change does not need to be communicated

### CODE REVIEW

**Comment by rt4914** [comment]
@anujbhavsar96 Need your suggestions on these? https://www.loom.com/share/e05d43b60ace4fd0bbe9a08f1550c6dd

Basically two questions:
1. If user has already liked the article and now when they single-tap on heart+ icon should this remove the like reaction and open the drawer?
2. User taps on heart+ icon which marks the like reaction and opens the drawer, now if user again taps on heart+ icon what should be the behaviour?

**Comment by anujbhavsar96** [comment]
> If user has already liked the article and now when they single-tap on heart+ icon should this remove the like reaction and open the drawer?

YES

> User taps on heart+ icon which marks the like reaction and opens the drawer, now if user again taps on heart+ icon what should be the behaviour?

It should remove the like reaction.

Consider clicking on the heart+ icon as a `Like` reaction - Only extra thing is, it opens the drawer as well on every click.

**Comment by rt4914** [comment]
@anujbhavsar96 Have a look at this output and let me know if you have any suggestions. https://www.loom.com/share/36a11d6356674fcca99709c8b6a8c114

**Comment by rt4914** [comment]
> For mobile, it looks perfect✨ @rt4914
> 
> Are we going to tackle the web _(heart+ icon click = default reaction)_ separately or with this issue only?

@anujbhavsar96 Actually I was not aware of that. I can make that change in this PR only. So the conclusion is that the drawer + heart+ icon will act same in web+mobile right?

**Comment by anujbhavsar96** [comment]
YES. So behavior stays consistent across all the devices @rt4914

**Review by jaw6 — APPROVED** [review]

**Comment by rt4914** [comment]
@anujbhavsar96 I have updated the link, can you confirm if this matches the expectation: https://www.loom.com/share/da32ca317cf04b3ead07aadabfb161b7

**Review by anujbhavsar96 — APPROVED** [review]
All the interactions are working as expected 🙌. Thank you!

**Pull request merged**
