### PR TITLE
Generate OpenAPI definitions with AppMap

### PR DESCRIPTION
**Pull request by petecheslock**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [X] Documentation Update

## Description
This PR includes OpenAPI definitions (see `openapi.yml`) of the Forem application APIs. The definitions are generated by [AppMap OpenAPI]([https://appmap.io/docs/openapi/](https://appmap.io/docs/openapi/index.html)) from recordings of test case execution. Recordings include the API routes, request methods, parameters, status codes, request and response payloads, headers, security, etc. From this data, AppMap can generate accurate OpenAPI definitions that include everything that is covered by a test case. Test cases do not need to be written in any particular format, they just need to be regular Rails tests written with minitest or rspec. “request”, and “system” tests generally provide good data.

OpenAPI definitions can be generated locally (e.g., using AppMap extensions for VSCode and JetBrains, or on the command line) and in CI. This information can be used to supplement manually written OpenAPI definitions, check their accuracy, identify discrepancies, add missing routes and status codes etc.

This PR also includes a bug fix, in which a `hash` method was defined (overriding the built-in `hash` method) to return a Hash object. `hash` should only be used to provide a hash code; to transform an object to a Hash, implement `to_h`. Similarly, `to_a` should be overridden to transform an object to an Array; rather than `list`.

The OpenAPI definitions generated by AppMap cover 23 more routes than the existing `swagger/v1/api_v1.json` for a total of 42 routes.  Some routes generated by AppMap that were missing are `/api/articles`, `/api/listings` and `/api/organizations`.

AppMap detects routes constructed dynamically by parameters. One example is `/api/articles/me(/{status})` which represents a route for the status values `all`, `published`, `unpublished`. Another example is detecting route access through locales by adding the prefix `(/locale/{locale}/)` to routes.

OpenAPI definitions can be processed further. `openapi.yml` can be read with a script to add or update definitions and it can complement the definitions in `swagger/v1/api_v1.json`. Routes that aren’t intended for public use or aren’t of interest can be removed. The YML file can be converted to JSON with other tools.

## Related Tickets & Documents
https://dev.to/devteam/documenting-the-forem-v1-api-15ck
https://github.com/forem/forem/milestone/10

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings

We’ve included 2 helper scripts that show how to generate the AppMaps for the API endpoints.
Running `./create_appmaps_for_api.sh` will run the API tests at `./spec/requests/api/v1` with AppMap enabled.

When that completes, running `./create_openapi_yml.sh` will run the command to generate a file called `openapi.yml` with the routes documented.  We’ve committed the version from this branch into `openapi.yml`

### UI accessibility concerns?

No

## Added/updated tests?

- [X] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] Are there any post deployment tasks we need to perform?

We recommend including this in the Forem CI process to auto generate AppMaps and OpenAPI documentation on each merge/release. In situations where manually written OpenAPI exists, this information can be merged with the generated OpenAPI to provide a more comprehensive and accurate result.

### CODE REVIEW

**Comment by kgilpin** [comment]
@Ridhwana this is the PR that adds generated OpenAPI definitions. Would love to hear your reaction to it!

**Comment by Ridhwana** [comment]
> @Ridhwana this is the PR that adds generated OpenAPI definitions. Would love to hear your reaction to it!

Hi @petecheslock, thank you for submitting this PR ✨, we're discussing the feature as a team and will feedback as soon as possible.

**Comment by maestromac** [comment]
Thank you for this contribution @petecheslo . The team has discussed it at great length and whilst AppMap looks promising, we unfortunately do not have the bandwidth to experiment with it at the moment. Should we decide to incorporate it in the future, we'll reach out to you. Again, thank you for the effort!

**Comment by kgilpin** [comment]
Can you briefly explain what your primary concerns are? This would help us with our development planning.

**Comment by kgilpin** [comment]
Also, you may want these two fixes for mis-implementations of `to_a` and `to_h`:

28d6914a49a8fc2ee2f61124b681351be51e84aa
a513f597b2eae8af1579dac628f8380ba89e5b06

**Pull request closed without merging**
