### PR TITLE
New Profile Header

### LINKED ISSUE #7117: Long name is breaking to multiple lines
**Describe the bug**
A user / organization with a long name will have it break onto multiple lines if it goes below a certain width.  This "problem" is more pronounced on smaller screens.

This might be a bit of an edge-cased based on the average length name and screen size, but I still think it's important to people and organizations with longer names.

**To Reproduce**
Press `CMD + minus` to zoom out on a profile with a longer name.  You will observe it spills over.  You can also view the included screenshot.

**Expected behavior**
Open to ideas.  Maybe the text could re-size before it spills over?

**Screenshots**
sample screenshot of long name spilling over

**Additional context**
I'm actually creating this issue on behalf of an organization that is having this problem / annoyance.

### LINKED ISSUE #8188: Scaling issue of .user-profile-header
**Describe the bug**

The sizing units used for the user profile header breaks the box as the window grows horizontally. At 1600xN and less it looks as I assume the design intends it to look, but as the window width grows, it becomes more and more broken, until it breaks in the middle of words (in this case, my surname).

Attaching a few different window widths below that illustrate the issue:

1. Make your browser window 2048xN or wider.
2. Go to any profile with a medium-length or long surname.
3. Make the window wider and narrower to see the difference.

**Expected behavior**

The profile box to look roughly the same at all widths, or at least not break words when there's plenty of room left. 

**Screenshots**

Screenshot 2020-05-30 at 19 18 11
Screenshot 2020-05-30 at 19 18 17
Screenshot 2020-05-30 at 19 18 24

The only difference in these three cases is the window width.

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version: 83.0.4103.61 (Official Build) (64-bit)

**Additional context**

This is somewhat similar to #7117, although in this case it's not about the name length, but rather how the media queries and floats affect the layout.

### LINKED ISSUE #9647: [Dev.to] - Profile header height too small for infobox
**Describe the bug**

On my dev.to profile (@zfett), my infobox on the right of my header has a vertical scroll due to the height. Using Firefox Version 79.0 64-bit. Tested in Edge with the same result.

**To Reproduce**

1. Fill out enough information in your infobox, try filling out your email, work, location, and education.
2. Visit your profile page
3. Height should overflow on Firefox.

**Expected behavior**

.user-profile-header should resize in height with .user-metadata-details to prevent vertical overflow on the default breakpoint.

**Screenshots**

screenshot

**Desktop (please complete the following information):**

- OS: Windows 10 Home, 10.0.18363 Build 18363
- Browser: Firefox
- Version: 79.0

**Additional context**

This only happens when the page width is at or above the 1216px breakpoint. The minute you resize it below that point and the content reflows, it no longer suffers from this issue.

### LINKED ISSUE #9723: Profile name field resizes incorrectly in large window widths.
When the browser window is very wide relative to the zoom level, the amount of text on each line _decreases_.

**To Reproduce**

1. Go to a dev.to profile page, e.g. https://dev.to/keithrbennett
2. Increase the width of the window to the screen width.

If you don't see the text lines break up into more lines, zoom out (e.g. Ctrl-- on Linux) until you do.

(See screenshot below.) 

**Expected behavior**

I would expect at least as much text to fit on a line as the window width increases.

**Desktop (please complete the following information):**

- OS: Linux, Mac OS
- Browser: Firefox, Brave, Vivaldi, Chrome
- Version:

dev-to-text-width-error

### PR DESCRIPTION
**Pull request by ludwiczakpawel**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Feature

## Description

This PR introduces new Crayons styling for User's profile top header. 
This PR **does NOT** bring this styling to Organization's profile top header. It will come afterwards.
Keep in mind, most of the files added to this PR are just new SVG icons.

## Related Tickets & Documents

- Closes #7117 
- Closes #8188 
- Closes #9647 
- Closes #9723 

### Desktop

image

image

image

### Mobile

image

image

## Added tests?

- [x] no, because I need help

## Added to documentation?

- [x] no documentation needed

### CODE REVIEW

**Review by rhymes — APPROVED** [review]
Looks great! I pushed the likely fix for the failing specs. A class had changed!

**Review by benhalpern — APPROVED** [review]
This looks fabulous!

Something we could deal with now or maybe as a follow-on PR, I think ideally we don't have any "jump" when we change the content of the follow button... So maybe a minimum width here? I think there are more shortcuts we can do to make this even less jumpy but ensuring no displacement would be a good start.

E.g. https://www.loom.com/share/6102395834de44bd848fb52c1501edd0

**Comment by ludwiczakpawel** [comment]
@benhalpern definitely. Although I'd prefer to solve it as a part of bigger "follow button cleanup" project - the code behind this functionality would appreciate some love and I've [alerted that in the past as a potential project](https://github.com/orgs/forem/projects/10#card-43405521).

**Comment by Link2Twenty** [comment]
It might be a good candidate to start the i18n process as it's only 3 phrases.

**Pull request merged**
