### PR TITLE
Bug fix #11402 - Very wide code blocks overflow in comment preview

### LINKED ISSUE #11402: bug: Very wide code blocks overflow in comment preview
**Describe the bug**

The comment preview with a code block that is very wide overflows.

**To Reproduce**

Example code block:
```js
function square(value) {
  if (value === 4) {
    return 4 + 4 + 4 + 4;
  }
  if (value === 16) {
    return 16 + 16 + 16 + 16 + 16 + 16 + 16 + 16 + 16 + 16 + 16 + 16 + 16 + 16 + 16 + 16;
  }
  if (value === 51) {
    return 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51;
  }
}
```

1. Go on an article
2. Copy in a comment the example code block above inside a markdown code block
3. Check out the comment preview
4. Notice it overflows

**Expected behavior**

It scrolls horizontally just like it does once the comment is posted.

**Screenshots**

demo

It also happens on the article page:

Screen Shot 2020-11-13 at 09 32 01

**Desktop (please complete the following information):**

- OS, version: macOS Catalina
- Browser, version: Chrome 86

### PR DESCRIPTION
**Pull request by yogeshktm**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Fixing the very wide code blocks in comments preview
## Related Tickets & Documents
References/Closes/Fixes/Resolves #11402 

## QA Instructions, Screenshots, Recordings

image

image

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://docs.forem.com/frontend/accessibility)._

## Added tests?

- [ ] Yes
- [x] No, Test not required
- [ ] I need help with writing tests

## Added to documentation?

- [ ] [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/)
- [ ] README
- [x] No documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Review by ludwiczakpawel — CHANGES_REQUESTED** [review]
The proposed solution will make the entire container scrollable and we only want to have it for the code block itself.

There's another fix we could do here - it's about adding `min-width: 0;` to some container. Yes, that's weird - I know :D But it's a fix for a browser's bug ¯\_(ツ)_/¯

We add this fix in [other places too](https://github.com/forem/forem/search?q=hack+preventing).

So as far as I can tell, we need that `min-width: 0;` for two more containers:

- [`.comment-form__inner`](https://github.com/forem/forem/blob/2ff7244c5563218b8f0613a1236f4e8f7e1635ff/app/assets/stylesheets/views/comments.scss#L28-L32)
- [`.comments-container`](https://github.com/forem/forem/blob/2ff7244c5563218b8f0613a1236f4e8f7e1635ff/app/views/comments/edit.html.erb#L3) - in this case we could probably just add another class to this container: `min-w-0` which would apply `min-width: 0;` property to this element.

**Comment by yogeshktm** [comment]
> The proposed solution will make the entire container scrollable and we only want to have it for the code block itself.
> 
> There's another fix we could do here - it's about adding `min-width: 0;` to some container. Yes, that's weird - I know :D But it's a fix for a browser's bug ¯_(ツ)_/¯
> 
> We add this fix in [other places too](https://github.com/forem/forem/search?q=hack+preventing).
> 
> So as far as I can tell, we need that `min-width: 0;` for two more containers:
> 
>     * [`.comment-form__inner`](https://github.com/forem/forem/blob/2ff7244c5563218b8f0613a1236f4e8f7e1635ff/app/assets/stylesheets/views/comments.scss#L28-L32)
> 
>     * [`.comments-container`](https://github.com/forem/forem/blob/2ff7244c5563218b8f0613a1236f4e8f7e1635ff/app/views/comments/edit.html.erb#L3) - in this case we could probably just add another class to this container: `min-w-0` which would apply `min-width: 0;` property to this element.

Thanks for your review @ludwiczakpawel .

i will go through the changes requested and come back with a PR.

**Review by yogeshktm — COMMENTED** [review]
@ludwiczakpawel 

i have commited the changes requested for PR #12166 . kindly review it. let me know in case any clarification required.

**Review by ludwiczakpawel — APPROVED** [review]
⛴

**Review by rhymes — APPROVED** [review]

**Comment by rhymes** [comment]
Hi @yogeshktm could you sign the CLA? According to https://github.com/forem/forem/pull/12166#issuecomment-755982779 I believe you used two different identities to commit so you have to sign the CLA from both :)

**Comment by yogeshktm** [comment]
> Hi @yogeshktm could you sign the CLA? According to [#12166 (comment)](https://github.com/forem/forem/pull/12166#issuecomment-755982779) I believe you used two different identities to commit so you have to sign the CLA from both :)

hi @rhymes . Yes i have wrongly committed with username like this one. since it is not configured in my local. is there any way to revert this ? 

thanks in advance.

**Comment by rhymes** [comment]
@yogeshktm mmm good question. You could try with `git rebase` by squashing all commits into one and then use `git push -f` to override the history. Something like `git rebase -i master`, then following the instructions to squash commits into one.

Another option might be to export the diff from master as a patch with `git format-patch`, reset the `HEAD` of your branch before of your first commit and then use `git am` to apply the patch, and then `git push -f` again

**Review by Ridhwana — APPROVED** [review]

**Pull request merged**
