### PR TITLE
Try multiple reactions external img

### PR DESCRIPTION
**Pull request by jaw6**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

After some Slack discussion, we would like to trial having the `multiple-reactions` SVGs use an `img` tag, instead of being rendered inline. This would remove the need for `UniqueSvgTransform`,  though we would still be using `crayons_icon` and `inline_svg` elsewhere (at least, for now).

## Related Tickets & Documents

- Related Issue #https://github.com/forem/forem/issues/19008
`cc` @benhalpern @anujbhavsar96 

## QA Instructions, Screenshots, Recordings

You'll need to have the `multiple_reactions` feature flag enabled, you can run this at a command prompt:

```
rails r "FeatureFlag.enable :multiple_reactions"
```

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: I'm actually removing a spec for a `transform` we don't need anymore
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [x] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by jaw6** [comment]
fwiw, I have been unable to replicate the glitchy behavior that originally lead me away from this implementation, I think maybe I had some mix of inline and external SVGs previously. (Or failed to restart a server, or something caching, or...)

**Review by Ridhwana — APPROVED** [review]

**Comment by benhalpern** [comment]
Looks good to me overall!

I believe this resulted in some small height/width/spacing differences:

Looks like a misalignment here between the reaction image and the number, causing a content layout shift problem on load:

https://share.getcloudapp.com/BluR8jqx

And then looks like the image here is in the top-left part of the circle instead of direct center:

Screen Shot 2023-02-07 at 9 54 02 AM

That's all I saw, seem like small issues.

This will be better for page load time, and _seems_ cleaner to me overall. 🙂

**Review by maestromac — APPROVED** [review]
Tested locally, LGTM

but I agree with but there's content jumping because of inconsistent height

**Comment by jaw6** [comment]
@benhalpern @maestromac the new design "bubbles" create padding/line-height complications, but it should be tracked in the [non-launch-blocker issue](https://github.com/forem/forem/issues/19064) (it should be in there already)

**Pull request merged**
