### PR TITLE
Updated replit url from repl.it to replit.com

### LINKED ISSUE #13665: Editor guide links to repl.it instead of replit.com
**Describe the bug**

[Editor guide](https://dev.to/p/editor_guide) mentions `repl.it` instead of `replit.com` [here](https://dev.to/p/editor_guide#repl-it-embed) (The url was changed some time ago). Trivial issue but still posting it.

**To Reproduce**

Go to [The repl.it part of the liquid tags guide in the editor guide](https://dev.to/p/editor_guide#repl-it-embed)

**Expected behavior**

URL is `replit.com` instead of `repl.it`.

**Screenshots**

repl it

**Desktop (please complete the following information):**

- OS, version: All
- Browser, version: All

**Smartphone (please complete the following information):**

- Device: All
- OS, version: All
- Browser, version: All

**Additional context**

The link is also wrong in the [new post editor](https://dev.to/new)

The related file is [/app/views/pages/_editor_liquid_help.html.erb](https://github.com/forem/forem/blob/355d510f8841029e69af3a03b04c6bd282629c80/app/views/pages/_editor_liquid_help.html.erb#L230)

```erb
<h3>repl.it Embed</h3>
<p>All you need is the URL after the domain name:</p>
<code>{% replit @WigWog/PositiveFineOpensource %}</code>
```

If this is there for the bug smash, Could you assign me?

### PR DESCRIPTION
**Pull request by SiddharthShyniben**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation Update

## Description

Updated replit url in the editor guide from repl.it to replit.com 

## Related Tickets & Documents

Fixes #13665 

## QA Instructions, Screenshots, Recordings

No tests written because this is a UI change.

This has been tested on Chrome 90.0.4430.93 on a MacBook Pro (13-inch, Early 2011) with macOS version 10.12.6

### UI accessibility concerns?

No concerns.

## Added tests?

- [ ] Yes
- [x] No, and this is why: This is a UI change
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

Teeny tiny change

### CODE REVIEW

**Comment by rhymes** [comment]
Hi @SiddharthShyniben, thanks for this! there a few other places that need the copy update:

https://github.com/forem/forem/blob/d59b8ba0eef6daaa6cd94549c00cf4b5e70773d6/app/views/pages/_editor_guide_text.html.erb#L346

https://github.com/forem/forem/blob/d59b8ba0eef6daaa6cd94549c00cf4b5e70773d6/app/liquid_tags/replit_tag.rb#L21

The one you've changed is fine, for these I think we should replace the URL with the product name: `Replit`

Thank you!

**Comment by SiddharthShyniben** [comment]
I'll add those as soon as I can

**Comment by SiddharthShyniben** [comment]
Sorry for the delays @rhymes 

Do you think I should update the URL of the embed code from repl.it to replit.com [here](https://github.com/forem/forem/blob/main/app/views/liquids/_replit.html.erb)? it may break in the future.

```erb
<iframe frameborder="0" height="550px" src="<%= "https://repl.it/#{id}?lite=true" %>" loading="lazy"></iframe>
```

<sup>PS: @rhymes How do you embed those code snippets like that?</sup>

**Comment by rhymes** [comment]
> Do you think I should update the URL of the embed code from repl.it to replit.com here? it may break in the future.

@SiddharthShyniben only if you want, it's technically outside the scope of this PR and you'd need to fix the related Ruby spec as well. Let me know!

> PS: @rhymes How do you embed those code snippets like that?

I open the files on GitHub, click on the three dots and then click on "Copy permalink"

Screenshot 2021-05-07 at 10 52 14 AM

**Comment by SiddharthShyniben** [comment]
@rhymes I guess someone else could take that for the bug smash. I'm not too good at ruby 😅 .

> I open the files on GitHub, click on the three dots and then click on "Copy permalink"

That's cool, I never knew URLs were converted like that

**Review by rhymes — APPROVED** [review]
LGTM!

**Review by Zhao-Andy — APPROVED** [review]
Nice catch! :)

**Pull request merged**
