### PR TITLE
Fixing id and class of non featured article

### PR DESCRIPTION
**Pull request by Rafi993**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Fixing id and class of non featured article. It was adding string false before

## Related Tickets & Documents
Closes https://github.com/forem/forem/issues/10246

### Before
class_and_id_false

### After
removing_false_id_and_class

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Review by nickytonline — APPROVED** [review]
Good catch! 🧤

**Review by nickytonline — APPROVED** [review]
Good catch! 🧤

**Comment by rhymes** [comment]
Looks like some of the failed tests are legit https://travis-ci.com/github/forem/forem/jobs/382385173#L1456

**Comment by Rafi993** [comment]
> Looks like some of the failed tests are legit https://travis-ci.com/github/forem/forem/jobs/382385173#L1456

Oh. I ran ```yarn test``` but I did not run rspec since I did not expect rspec to fail. I'll fix the test.

**Comment by nickytonline** [comment]
> > Looks like some of the failed tests are legit [travis-ci.com/github/forem/forem/jobs/382385173#L1456](https://travis-ci.com/github/forem/forem/jobs/382385173#L1456)
> 
> Oh. I ran `yarn test` but I did not run rspec since I did not expect rspec to fail. I'll fix the test. But was the class "false" intended to be there?

If rspec is expcting `'false'` for the CSS class name, that should be updated to reflect your bug fix.

**Review by nickytonline — APPROVED** [review]
🚀

**Review by benhalpern — APPROVED** [review]
Great fix!

**Pull request merged**
