### PR TITLE
Update the CSS of the badge page title

### LINKED ISSUE #13652: Badge title is unreadable when long
**Describe the bug**

The title of the badges is too small to read in some cases. In particular, the title of the DigitalOcean App Platform Hackathon on DEV Badge is unreadable on smaller screens.

**To Reproduce**

1. Go to the [Digital Ocean Hackathon badge page](https://dev.to/badge/participant-e2-80-94-digitalocean-app-platform-hackathon-on-dev)

**Expected behavior**

The title of all badges should be readable.

**Screenshots**

Screenshot of the DigitalOcean App Platform Hackathon on DEV Badge

**Desktop (please complete the following information):**

- OS, version: MacOS Catalina
- Browser, version: All browsers.

**Smartphone (please complete the following information):**

- Device: iPhone/Android
- OS, version: All
- Browser, version: All

**Additional context**

The size of the badge title is calculated dynamically based on a fixed value (`1.66vw`) and another value based on the badge title length:

https://github.com/forem/forem/blob/c842d1a0c6718f319f167e9ec13d4d7d5d6b6d39/app/views/badges/show.html.erb#L5

The badge-specific value for the DigitalOcean App Platform Hackathon on DEV Badge translates into a negative number:

1. "Participant — DigitalOcean App Platform Hackathon on DEV" = 56 characters
2. 56 / 1.1 = 50 (rounded down)
3. 34 - 50 = -16

And that causes the title to have a size of zero or lower for screens smaller than 964px (also, it isn't easy to read on larger screens).

One option would be to make the badge-title size fixed for all the badges instead of depending on their length... but that should be a design decision and not my call :)

### PR DESCRIPTION
**Pull request by SiddharthShyniben**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Update the CSS of the badge page title so that the title is still readable for long badges and small screens

## Related Tickets & Documents

Fixes #13652 

## QA Instructions, Screenshots, Recordings

No tests written because this is a UI change.

This has been tested on Chrome 90.0.4430.93 on a MacBook Pro (13-inch, Early 2011) with macOS version 10.12.6

Before fixes: 

before

After fixes: 

after

### UI accessibility concerns?

As far as I know, accessibility has not been impacted.

## Added tests?

- [ ] Yes
- [x] No, and this is why: This is a UI change
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

Teeny change

### CODE REVIEW

**Comment by alvaromontoro** [comment]
@SiddharthShyniben, out of curiosity, I noticed the padding changed. Did the new font size affect it somehow?

**Comment by SiddharthShyniben** [comment]
> @SiddharthShyniben, out of curiosity, I noticed the padding changed. Did the new font size affect it somehow?

Yes @alvaromontoro I just thought it looked a bit better for really long badge titles on certain screens

**Review by aitchiss — APPROVED** [review]
Tested this locally on a few browsers and it's looking good 👍  thanks for the change!

**Comment by nickytonline** [comment]
I'm good with the change, just want to make sure Product design is. Summoning @ludwiczakpawel and @lisasy.

**Comment by SiddharthShyniben** [comment]
Great 👍

**Review by ardianshine21 — APPROVED** [review]

**Review by rhymes — APPROVED** [review]

**Pull request merged**
