### PR TITLE
Add Visit dashboard buttons for admin

### PR DESCRIPTION
**Pull request by maestromac**
## What type of PR is this? (check all applicable)
- [x] UX

## Description
Add an button for UX improvement

## QA Instructions, Screenshots, Recordings
image

## Added tests?
- [x] no, because they aren't needed

## Added to documentation?
- [x] no documentation needed

## [optional] Are there any post deployment tasks we need to perform?
n/a

### CODE REVIEW

**Comment by anujbhavsar96** [comment]
It would be good if we add an icon instead of a button. Having multiple buttons at the top look confusing.

Shared the Dashboard icon SVG with you @maestromac

**Comment by jaw6** [comment]
Am I misunderstanding, or does this conflict with https://github.com/forem/forem/pull/19109 ? `cc` @lboogie04

**Comment by rt4914** [comment]
> Am I misunderstanding, or does this conflict with #19109 ? `cc` @lboogie04

+1

**Comment by maestromac** [comment]
Superseded by https://github.com/forem/forem/pull/19109/

**Pull request closed without merging**
