### PR TITLE
Try yarn instead over npm for storybook deploys

### LINKED ISSUE #12108: Netlify docsdevto build fails due to no content change
**Describe the bug**

[Netlify docsdevto](https://app.netlify.com/sites/docsdevto/deploys) is built on every [github.com/forem/forem](https://github.com/forem/forem) PR and fails if there is no content change.

```
10:54:33 AM: No changes detected in base directory. Returning early from build.
10:54:33 AM: Failed during stage 'checking build content for changes': Canceled build due to no content change
10:54:33 AM: Finished processing build request in 19.336942253s
```
_snippet from master@[e41c995](https://github.com/forem/forem/commit/e41c9954d6dfa887de78229b47e33c44822caa47) build_

**To Reproduce**

- List of Netlify builds: https://app.netlify.com/sites/docsdevto/deploys
- Log of master@[e41c995](https://github.com/forem/forem/commit/e41c9954d6dfa887de78229b47e33c44822caa47) build: https://app.netlify.com/sites/docsdevto/deploys/5ff2e5c4d7e5dc0007293c9a

**Expected behavior**

While this is not an real issue (Netlify builds do suceed when changes are pushed) I am just thinking if the build status influence other parts of the system (I first noticed the README [Netlify tag](https://api.netlify.com/api/v1/badges/e5dbe779-7bca-4390-80b9-6e678b4806a3/deploy-status)). 

Or open up a discussion about the possibilities of strategically building the docsdevto to reduce the no-content builds – or if it's worth the effort to change it.

### PR DESCRIPTION
**Pull request by Zhao-Andy**
## What type of PR is this? (check all applicable)
- [x] Bug Fix

## Description
Our Storybook deploys are broken, and partially the reason for the failed build status for the README Netlify badge.

## Related Tickets & Documents
Resolves #12108 

## QA Instructions, Screenshots, Recordings
N/A

### UI accessibility concerns?
N/A

## Added tests?
- [x] N/A

## Added to documentation?
- [x] No, but this is a future to-do item

### CODE REVIEW

**Review by nickytonline — APPROVED** [review]

**Review by katiedavis — APPROVED** [review]

**Comment by nickytonline** [comment]
@Zhao-Andy, the yarn.lock file is in the root of the source code not in the `app/javascript` folder. Does this block this?

**Comment by Zhao-Andy** [comment]
@nickytonline hmm figuring it out. I think we can use root as the base directory for Netlify, and then publish `app/javascript`. testing it now.

**Comment by Zhao-Andy** [comment]
@nickytonline sigh so here's the deal. I think what happened was we have a package or something now that runs `yarn something`. So the failure is happening because our previous command of `npm install && npm run build-storybook` fails at `npm install` since a package tries to run `yarn something`.

I never got `yarn` to work on the Netlify build because to do that, we need to set the base directory to be `root`. When `root` is the base, Netlify sees that the app is a Ruby project, and tries to run `bundle install` (which fails). So out of ideas here for now... 😓

**Comment by nickytonline** [comment]
> @nickytonline sigh so here's the deal. I think what happened was we have a package or something now that runs `yarn something`. So the failure is happening because our previous command of `npm install && npm run build-storybook` fails at `npm install` since a package tries to run `yarn something`.
> 
> I never got `yarn` to work on the Netlify build because to do that, we need to set the base directory to be `root`. When `root` is the base, Netlify sees that the app is a Ruby project, and tries to run `bundle install` (which fails). So out of ideas here for now... 😓

@Zhao-Andy, if that's the case, let's revert to `npm` for the commands calling `yarn` currently as it was working before that change..

**Review by Zhao-Andy — COMMENTED** [review]
It works!!! 😭 

https://app.netlify.com/sites/storybookdevto/deploys/603847346bfbeb0009123595

**Review by aitchiss — APPROVED** [review]

**Pull request merged**
