### PR TITLE
Fix: cannot unpin articles using checkbox

### LINKED ISSUE #14974: Cannot update article to unpinned intuitively
**Describe the bug**

In the /admin/content_manager/articles/## interface there appear to be two ways to unpin an article and one doesn't seem to work.

**To Reproduce**

1. Go to an articles admin page — '/admin/content_manager/articles/##'
2. Check "pinned" + click submit to pin the article
3. Refresh the page
4. Uncheck "pinned" + click submit to unpin the article
5. This doesn't appear to work
6. Click the "unpin post" button at the top of the article widget
7. This does work

**Expected behavior**

You should be able to uncheck "pinned" + click submit to unpin the article (the same action that you take to pin the article)

**Screenshots**

https://www.loom.com/share/4b49b2455518470f92d575d499820b7c

**Additional context**

It's not too urgent of a bug since there is a way to unpin articles. This just feels odd and likely should be fixed.

### PR DESCRIPTION
**Pull request by RehmatFalcon**
fixes #14974

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Cannot unpin article using the `pinned` checkbox present in the form.

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by RehmatFalcon** [comment]
@rhymes I have updated the codes as you requested. I could not run the cypress test as I am using gitpod for development and there seems to be some issue with that.

I did update the integration test at spec/request/admin/articles_spec.rb

**Comment by RehmatFalcon** [comment]
@rhymes I haven't used cypress much. But I am glad that my solution, which I scrapped as I was not sure if it worked or not, was very similar to yours. Feels nice 😁😁

**Comment by msarit** [comment]
Hello @RehmatFalcon 👋🏾 

Great work again on this PR! There are a few outstanding changes that need to be made, to ensure that the flow is accessible:

- The "Unpin Post" button is still technically a link; would you please change it to an actual button, like you did with the "Pin Post" button. I strongly recommend you make the action async, again just like with "Pin Post". After you complete this part, I will update the Cypress tests.

- To solve the problem of there being no accessible confirmation when pinning or unpinning a post, I suggest utilizing our `displaySnackbar` and `displayErrorAlert` messaging utilities. **Monday next week, I will write up a helpful guide for incorporating these utilities into your current work.** As always, the team is here to keep supporting you. Thank you for your patience, and for contributing to Forem! 💙

**Review by msarit — APPROVED** [review]

**Comment by nickytonline** [comment]
As discussed @msarit and @aitchiss, we're going to follow up with a subsequent PR to address the UX and remaining a11y issues.

**Pull request merged**
