### PR TITLE
Fix search bar disappears issue on mobile view

### PR DESCRIPTION
**Pull request by ubaidisaev**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Related Tickets & Documents

- Closes [Search bar is sometimes disappears from the UI ](https://github.com/forem/forem/issues/16998)

## QA Instructions, Screenshots, Recordings

Click multiple times top nav search icon on mobile view, the search form should not disappear

### UI accessibility concerns?

No significant frontend changes

## Added/updated tests?

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

### CODE REVIEW

**Review by aitchiss — COMMENTED** [review]
Hey @ubaidisaev - thank you for tackling this issue! 

It looks like the specs are failing with a legitimate error - I see this in the console:
Uncaught Error: Undefined parent passed to render(), this is the second argument.
Check if the element is available in the DOM/has the correct id.

It also looks like the sync between the mobile/desktop search forms is broken. The deleted code is intended to make sure that the following works:

1. I search for something while in 'desktop size' view
2. I narrow my viewport to trigger the 'mobile size' view
3. I should still see my search term in the search field

Point 3 is no longer happening 😞 

https://user-images.githubusercontent.com/20773163/165302252-8733059c-3b58-4675-9b9a-bd860390258a.mp4

Are you able to have a look into these issues? Let me know if you need any assistance at all! It's definitely a tricky bit of code.

**Comment by aitchiss** [comment]
Also, if you haven't checked this out already, please take a look at these notes from @MrFuku who has done some great investigation into the cause of this issue - https://github.com/forem/forem/issues/16998#issuecomment-1079977197

**Comment by ubaidisaev** [comment]
Thank for the feedback @[aitchiss](https://github.com/aitchiss). There was some tricky code for mobile search which i don't totally understand. Yeah i see that i loosed some functionality there.
I also have a question about search button in the header, what should happen when we clicking multiple times on it ?
image

**Comment by aitchiss** [comment]
> also have a question about search button in the header, what should happen when we clicking multiple times on it ?

That's a good question! So although it looks like a button, it's actually just a link to the search page - `/search`. So clicking on it any number of times should just cause the search page to load/reload 👍

**Comment by juliannatetreault** [comment]
> [CLA assistant check](https://cla-assistant.io/forem/forem?pullRequest=17429) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/forem/forem?pullRequest=17429) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/forem/forem?pullRequest=17429) it.

Also, when you get a moment, could you please sign the CLA, @ubaidisaev? Thank you so much in advance! 🌟

**Comment by msarit** [comment]
@ubaidisaev hello! 👋🏾  Thank you for working on this! I'm going to move this PR to draft status; let us know if you need some more support with the work. 🙏🏾

**Comment by aitchiss** [comment]
Hi @ubaidisaev 👋  Since we haven't heard back from you in a while, I'm going to go ahead and close this one for now. If you're still keen to continue work on it, please do re-open, and no worries if you just need some more time!

Either way, thank you for your contribution - we really appreciate you taking the time to work on this ❤️

**Pull request closed without merging**
