### PR TITLE
Revert "Add (updated) mention autocomplete to post comments (#13061)"

### PR DESCRIPTION
**Pull request by nickytonline**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [x] Feature Revert

## Description

The feature is working but it prevents navigation in the comment editor when using the up and down arrow keys. Further investigation is required to re-enable this feature.

image

## Related Tickets & Documents

#13061

## QA Instructions, Screenshots, Recordings

Ensure that comments still work in posts (including nested comments) as well as comments in the notifications area.

You can see the QA notes in #13061 on how to generate notifications.

### UI accessibility concerns?

N/A

## Added tests?

- [ ] Yes
- [x] No, and this is why: We're reverting to the old functionality which already (hopefully) had some tests.
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [x] This change does not need to be communicated, and this is why not: We're reverting a feature that has not been communicated to the community yet.

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Review by rhymes — APPROVED** [review]
😢

**Comment by nickytonline** [comment]
> 😢

Don't worry. We'll get this back in. 😎

**Review by Zhao-Andy — APPROVED** [review]
TBH I think we can wait too -- I'm not sure there's anything too urgent that needs to go out to Forem fleet but happy to get this merged and deploy fleet too.

**Comment by nickytonline** [comment]
> TBH I think we can wait too -- I'm not sure there's anything too urgent that needs to go out to Forem fleet but happy to get this merged and deploy fleet too. I'll put it back into draft mode for now then.

@Zhao-Andy, if you can wait great and we can try and get a fix in later today. @cmgorton, have any issues been opened up in regards to comments and arrow keys not working?

**Comment by cmgorton** [comment]
> @Zhao-Andy, if you can wait, great and we can try and get a fix in later today. @cmgorton, have any issues been opened up in regards to comments and arrow keys not working on dev.to?

Not sure if this is related @nickytonline but it was opened yesterday. 
https://github.com/forem/forem/issues/13097

**Comment by nickytonline** [comment]
> > @Zhao-Andy, if you can wait, great and we can try and get a fix in later today. @cmgorton, have any issues been opened up in regards to comments and arrow keys not working on dev.to?
> 
> Not sure if this is related @nickytonline but it was opened yesterday.
> #13097

Looks like that is related @cmgorton.

**Comment by nickytonline** [comment]
Just investigating this @aitchiss some more before reverting.

**Comment by Link2Twenty** [comment]
Just to add I also noticed this when I was writing something but just presumed it was my browser bugging out. I wouldn't surprise me if other people thought the same.

**Review by Zhao-Andy — APPROVED** [review]

**Pull request merged**
