### PR TITLE
Billboard style tweaks

### PR DESCRIPTION
**Pull request by benhalpern**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

These are some small tweaks as we refine how billboards are supposed to look in different locations.

We had to make a few general adjustments in https://github.com/forem/forem/pull/19106 and some past PRs, and this goes in and makes some follow-up tweaks to get things more where they should be.

Two changes: Adjusts padding on _below comments location_ so that the left lines up with the left part of the content in the above boxes, and the general padding is tweaked to achieve some kind of satisfying optical center.

This also adjusts the sidebar billboard to have proper fonts, it has been too big relative to our typical layout font size.

We may need to keep tweaking this, but I think this lands us in a better place than before.

## Related Tickets & Documents

- Related Issue https://github.com/forem/forem-internal-eng/issues/531

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: Only css tweaks
- [ ] I need help with writing tests
- [ ] 

### Before:

Screen Shot 2023-03-06 at 11 50 51 AM

### After:

Screen Shot 2023-03-06 at 11 44 34 AM

## [Forem core team only] How will this change be communicated?

- [x] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## What gif best describes this PR or how it makes you feel?

css

### CODE REVIEW

**Comment by anujbhavsar96** [comment]
@benhalpern IMO, the before version looks more consistent with other billboard units with side padding to 16px.

With these changes, Billboard authorship would have more spacing on the left while the dropdown icon would have 16px - That would look inconsistent.

**Comment by benhalpern** [comment]
@anujbhavsar96 are you sure about that being the right lens to look at this from? I feel like within the reading structure of this part of the site, left padding should be consistent, even if the top-right menu icon needs to be all the way to the right.

I feel like this is not a good experience:

Screen Shot 2023-03-07 at 8 29 13 AM

**Comment by anujbhavsar96** [comment]
@benhalpern, I got your point. But If we are changing the left side padding, we should also change the right side padding and make it consistent. Otherwise, it would look weird that content goes till the end of the card on the right side and have paddings on the left.

Something like the below with side paddings to 64px, and we can keep the dropdown icon on the top right corner. Since we are increasing side paddings, we can increase the top-bottom to 32px, the same as the sections around it.

Frame 2

**Comment by benhalpern** [comment]
Okay @anujbhavsar96 I made adjustments based on your feedback. 👍

**Comment by anujbhavsar96** [comment]
image


Not a CSS expert so I want to confirm if we use the same padding as surrounding cards.

`padding: var(--content-padding-y) var(--content-padding-x)` -> We can use this. And keep the dropdown icon floating on top right corner

**Comment by benhalpern** [comment]
Yeah @anujbhavsar96 I used `padding-left: var(--content-padding-x)` where I could, but because there are different inner-boxes which have their own padding within this container, I couldn't do this as cleanly as just _only_ using `padding-left: var(--content-padding-x)` — in order to get this close to the right visual state here, I had to use a combination of distances in different places for this particular case.

**Review by anujbhavsar96 — APPROVED** [review]
LGTM 🚀

**Review by Ridhwana — APPROVED** [review]
LGTM

**Review by jaw6 — APPROVED** [review]
Seems fine?

**Pull request merged**
